multiversx/mx-chain-go

process/block/metablock.go, process/block/shardblock.go, process/sync/baseSync.go, process/sync/shardblock_test.go
* Fixed bug in boostrap from storage when recreate trie fails
* Fixed bug in CreateBlockHeader when checkAndRequestIfShardHeadersMissing was not called in every situation and with wrong round
=> Recreate trie and request shard headers missing

core/trimmers.go, core/trimmers_test.go
on windows the "..." in filename are not ok
=> core: fix filename trimming

process/block/baseProcess.go, process/block/baseProcess_test.go, process/block/export_test.go, process/block/interceptors/metachainHeaderInterceptor.go, process/block/interceptors/metachainHeaderInterceptor_test.go, process/block/metablock.go, process/block/metablock_test.go, process/block/preprocess/transactions.go, process/block/shardblock.go, process/block/shardblock_test.go, process/constants.go, process/errors.go, process/interface.go, process/sync/basicForkDetector.go, process/sync/basicForkDetector_test.go, process/sync/shardblock.go
Fork choice detected (After more than 12 sec of latency in which one proposer tried to write on disk and then to broadcast the valid block with nonce n, the network already proposed another block with the same nonce n, and also the next proposer broadcast the block with nonce n + 1. Before the rest of the network to sync this block with nonce n + 1, they also received the block with nonce n from the slow proposer. Because they didn't sync yet the block with nonce n + 1 and the final block is still n - 1 (as k finality is 1) they will start a fork choice on the block with nonce n (as they have now two block with nonce n but with different round inside). As the rule is that when two VALID blocks have the same nonce, the one with the lower round will be selected, they will try to request the …
=> Fixed bugs with fork choice and notarized meta blocks

dataRetriever/resolvers/topicResolverSender/export_test.go, dataRetriever/resolvers/topicResolverSender/topicResolverSender.go, dataRetriever/resolvers/topicResolverSender/topicResolverSender_test.go, p2p/libp2p/directSender.go, p2p/libp2p/export_test.go, p2p/libp2p/mutexHolder.go, p2p/libp2p/mutexHolder_test.go, p2p/libp2p/netMessenger.go, p2p/p2p.go
Direct sender fixed, stream reset issue should not appear
TopicResolverSender tries to send the request to the next peer if a send to a peer fails.
=> Fixed stream reset and peer is not directly connected errors

cmd/node/config/config.toml, cmd/node/main.go, process/block/preprocess/basePreProcess.go
fixed a bug in preprocessor when a new tx is intercepted. It should write on received chan only if it was requested.
added process ID in main.go
=> bugfix for stuck go routines writing on a chan in basePreProcess

cmd/node/main.go, process/sync/metablock.go, process/sync/shardblock.go
This implementation should fix a situation when all peers would been replaced in their headerNonceHash pool a good/used header in their blockchain construction, with a wrong/unused header on which they didn't construct, but which came after a late broadcast from a valid proposer.
=> Bug/en 3192 fix bug when a wrong/unused fork requested header is received

dataRetriever/dataPool/nonceSyncMapCacher.go, dataRetriever/dataPool/nonceSyncMapCacher_test.go, dataRetriever/interface.go, dataRetriever/mock/uint64SyncMapCacherStub.go, integrationTests/consensus/consensus_test.go, process/block/baseProcess.go, process/block/baseProcess_test.go, process/block/metablock_test.go, process/block/shardblock.go, process/block/shardblock_test.go, process/coordinator/process_test.go, process/errors.go, process/mock/uint64SyncMapCacherStub.go, process/sync/metablock.go, process/sync/metablock_test.go, process/sync/shardblock.go, process/sync/shardblock_test.go
* Fixed "Has" method from nonceSyncMapCacher
* ErrInvalidBlockHash has been split in two different errors (one for current shard blocks and one for notarized blocks) to help debugging
=> Bug/en 3214 fix bug in "Has" method from nonceSyncMapCacher

dataRetriever/factory/containers/export_test.go, dataRetriever/factory/containers/resolversContainer.go, process/factory/containers/export_test.go, process/factory/containers/interceptorsContainer.go, process/factory/containers/intermediateTransactionHandlersContainer.go, process/factory/containers/preProcessorsContainer.go, process/factory/containers/vmContainer.go, process/factory/containers/vmContainer_test.go, process/factory/shard/vmContainerFactory.go, process/interface.go, process/smartContract/process.go
made containers private. only interface is visible
=> rename/Renamed containers, made them private

api/node/routes_test.go, core/constants.go, facade/elrondNodeFacade_test.go, node/heartbeat/hearbeatMessageInfo.go, node/heartbeat/hearbeatMessageInfo_test.go, node/heartbeat/heartbeat.go, node/heartbeat/monitor.go, node/heartbeat/monitor_test.go, node/heartbeat/sender.go, node/heartbeat/sender_test.go
Heartbeat shard ID divided into received shard id and computed shard id in order to enable checking the validity of this information
=> EN-3605 - heartbeat shard ID split into received and computed

cmd/node/factory/structs.go, consensus/broadcast/shardChainMessenger.go, core/partitioning/simpleDataPacker.go, core/partitioning/simpleDataPacker_test.go, integrationTests/multiShard/smartContract/testInitilalizer.go, integrationTests/singleShard/transaction/interceptedBulkUnsignedTx_test.go, integrationTests/testProcessorNode.go, node/node.go, node/nodeTesting.go
Added a new implementation of DataPacker that calculates less precise but more optimum the packed size in bytes.
=> En 3833 observers get out of mem

cmd/node/factory/structs.go, integrationTests/multiShard/smartContract/testInitilalizer.go, integrationTests/testProcessorNode.go, integrationTests/testSyncNode.go, process/block/argProcessor.go, process/block/argsProcessor.go, process/block/baseProcess_test.go, process/block/export_test.go, process/block/shardblock.go, process/block/shardblock_test.go
Refactor shard processor constructor.
All constructor parameters was moved in a new struct.
Modify failing tests.
=> En 4077 refactor shard processor constructor

data/interface.go, data/trie/errors.go, data/trie/evictionWaitingList/evictionWaitingList.go, data/trie/evictionWaitingList/evictionWaitingList_test.go, marshal/jsonMarshalizer.go
Implement evictionWaitingList, which caches keys that need to be removed from a certain database. If the cache is full, the keys will be stored in the underlying database.
=> En 3996 implement db eviction cache

cmd/node/config/config.toml, process/block/baseProcess.go, process/block/baseProcess_test.go, process/block/metablock.go, process/block/metablock_test.go, process/block/preprocess/basePreProcess.go, process/block/preprocess/smartContractResults.go, process/block/preprocess/smartContractResults_test.go, process/block/preprocess/transactions.go, process/block/shardblock.go, process/block/shardblock_test.go, process/constants.go, process/coordinator/process.go, process/coordinator/process_test.go, process/errors.go, process/interface.go, process/mock/preprocessorMock.go, process/mock/transactionCoordinatorMock.go, process/sync/baseForkDetector.go, process/sync/baseForkDetector_test.go, process/sync/export_test.go, process/sync/metaForkDetector.go, process/sync/shardForkDetector.go
**process/block**
* Added and refactored some print info which were confusing
* Added a new header request by hash on process block, if the new block does not pass the check block validity because of its previous hash
* Replaced the old method getOrderedHdrs with a new one getFinalityAttestingHeaders which is more efficient and solves one edge case, when requested final header has a higher round than current one at which the node reached with its bootstrap mechanism
**process/block/preprocess and process/coordinator**
* Removed some unused old code and refactored methods which were affected by it
* Changed the old mechanism which creates many miniblocks from the same sender to the same receiver (now the txs pool is sorted once per round)
**process/sync**
* Fixed an edge case in fork …
=> En 4102 improve fork detector

process/block/metablock.go
- added a trailing comma in the string representing the blocks heights notarized by metachain for all shards. This will help fetching the data further
=> Trailing comma in cross block height string

process/block/preprocess/rewardTxPreProcessor.go
removed concurrent issue on elrond-go/process/block/preprocess/rewardTxProcessor.go line 245
function AddComputedRewardMiniBlocks now protects rtp.rewardTxsForBlock.txHashAndInfo map write access.
=> removed concurrent issue on rewardTxProcessor.goL245

data/rewardTx/rewardTx.go, data/transaction/transaction.go, integrationTests/mock/feeHandlerStub.go, integrationTests/multiShard/block/executingRewardMiniblocks_test.go, integrationTests/multiShard/smartContract/testInitializer.go, integrationTests/singleShard/transaction/interceptedResolvedTx_test.go, integrationTests/state/stateExecTransaction_test.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, process/block/preprocess/transactions.go, process/block/preprocess/transactions_test.go, process/block/shardblock_test.go, process/coordinator/process_test.go, process/economics/economicsData.go, process/economics/economicsData_test.go, process/economics/testEconomicsData.go, process/errors.go, process/interface.go, process/mock/feeHandlerStub.go, process/transaction/interceptedTransaction.go, process/transaction/interceptedTransaction_test.go, process/transaction/process.go, process/transaction/process_test.go
transaction fee calculation refactor:
- changed the fee handler so it can compute fees, required gas limits and such: behavior is now consistent between interceptor and transaction processor
- found and fixed the bug that made the cost of a transaction minTxGasLimit * minTxGasPrice regardless the tx data notarized
- found and fixed a bug that made the miniblock max gaslimit calculation based only on minGasLimit instead of the real gas limit of the transaction
=> transaction fee calculation refactor:

data/trie/branchNode.go, data/trie/branchNode_test.go, data/trie/extensionNode.go, data/trie/extensionNode_test.go, data/trie/leafNode.go, data/trie/leafNode_test.go, data/trie/node.go, data/trie/node_test.go, data/trie/patriciaMerkleTrie.go
Add db, marshalizer and hasher to nodes instead of passing them around as parameters to functions.
=> En 4551 trie node refactoring

process/constants.go, process/sync/baseForkDetector.go, process/sync/baseForkDetector_test.go, process/sync/export_test.go, process/sync/metaForkDetector.go, process/sync/shardForkDetector.go
* Added a new state for late received headers, which are added in fork detector, instead of rejected them. These headers would trigger that a probable highest nonce exists and the longest chain should be selected by other nodes, which would be entered in sync mode requesting for that nonce.
=> EN-4967-Fix-network-split-in-metachain

p2p/errors.go, p2p/libp2p/discovery/kadDhtDiscoverer.go, p2p/libp2p/discovery/kadDhtDiscoverer_test.go, p2p/libp2p/libp2pConnectionMonitor.go, p2p/libp2p/libp2pConnectionMonitor_test.go, p2p/libp2p/networksharding/kadSharder.go, p2p/libp2p/networksharding/kadSharder_test.go, p2p/libp2p/networksharding/noSharder.go, p2p/libp2p/networksharding/sharder.go, p2p/libp2p/networksharding/sharder_test.go, p2p/libp2p/networksharding/sortingList.go, p2p/mock/reconnecterStub.go, p2p/p2p.go
- Don't pause discovery unless the upper layers agrees
- Only pause after trimming
- Do an automatic (limited) discovery every 20 conn intervals skipped
- Increase the number of discovery queries
=> [Net shard.] Discovery pause rework

cmd/node/factory/structs.go, integrationTests/consensus/testInitializer.go, integrationTests/testSyncNode.go, process/block/metablock.go, process/block/shardblock.go, process/sync/baseForkDetector.go, process/sync/baseForkDetector_test.go, process/sync/baseSync.go, process/sync/errors.go, process/sync/metaForkDetector.go, process/sync/metaForkDetector_test.go, process/sync/metablock_test.go, process/sync/shardForkDetector.go, process/sync/shardForkDetector_test.go, process/sync/shardblock_test.go
* Added prints info
* Added request for missing overwritten header when a finality check is done
* Added check for genesis time missmatch in fork detector
=> En 5276 added genesis time check in fork detector

data/mock/evictionWaitingListMock.go, data/trie/branchNode_test.go, data/trie/errors.go, data/trie/evictionWaitingList/evictionWaitingList_test.go, data/trie/node_test.go, data/trie/patriciaMerkleTrie.go, data/trie/patriciaMerkleTrie_test.go, data/trie/sync.go, data/trie/sync_test.go, integrationTests/state/stateTrie_test.go, process/interceptors/processor/trieNodeInterceptorProcessor.go, process/mock/trieStub.go
Implemented trie checkpoint.
Recreate trie also checks snapshots for root hash.
Fix golangcibot comments from feat/storage-trie-pruning.
=> trie checkpoint

cmd/node/main.go
Added chain ID as the parent folder in the db.
Now the structure will be:
working-dir/db/CHAIN_ID/Epoch_X/Shard_X
to avoid situations when running with a common database in multiple chains
=> Chain ID directory for databases

data/trie/patriciaMerkleTrie.go, data/trie/trieStorageManager.go, data/trie/trieStorageManager_test.go, integrationTests/state/stateTrie_test.go, process/sync/baseSync.go, scripts/testnet/include/nodes.sh
Bug 1: if root hash stays the same in some consecutive blocks, and then one block does a rollback, rootHash+newRootIdentifier will be pruned from db, thus removing values that are needed. 
Bug 2: When bootstrapping from storage, if there were some trie snapshots, they were not taken in consideration.
=> fix pruning on rollback

epochStart/metachain/pendingMiniBlocks_test.go
fixed TestPendingMiniBlockHeaders_AddProcessedHeaderCannotMarshalShouldRevert test
=> Fixed pending minblocks test

data/trie/extensionNode.go, data/trie/leafNode.go, data/trie/leafNode_test.go, data/trie/trieStorageManager.go, data/trie/trieStorageManager_test.go
- When canceling prune, also remove the hash from pruning buffer.
- When updating the trie with an existent key-value pair, nothing should be modified.
=> En 5702 fix trie bugs

cmd/node/factory/structs.go, consensus/spos/bls/blsWorker.go, consensus/spos/bls/blsWorker_test.go, consensus/spos/errors.go, consensus/spos/interface.go, consensus/spos/worker.go, consensus/spos/worker_test.go, core/constants.go, integrationTests/consensus/testInitializer.go, process/block/poolsCleaner/crossTxsPoolsCleaner.go, process/block/poolsCleaner/miniBlocksCleaner.go, process/block/preprocess/basePreProcess.go, process/block/preprocess/rewardTxPreProcessor.go, process/block/preprocess/smartContractResults.go, process/block/preprocess/smartContractResults_test.go, process/block/preprocess/transactions.go
* Fixed wrong type assertion for received transactions
* Added guard checks for message type and message round in consensus topic interceptor
* Fixed memory leak in miniblocks/cross txs pools cleaner when pending miniblocks would not reached to 0 for a long time
* Added guard check for received header hash size from consensus message in consensus topic interceptor
=> Fixed wrong type assertion for received transactions

epochStart/bootstrap/epochStartMetaBlockProcessor.go, epochStart/bootstrap/epochStartMetaBlockProcessor_test.go, epochStart/bootstrap/export_test.go
when the context expires for getting the epoch start metablock, first check if at least a minimum number of peers sent a metablock and return it instead of returning a time out error.
+ unit test
=> return metablock if at least num of peers send it

dataRetriever/factory/resolverscontainer/baseResolversContainerFactory.go, dataRetriever/factory/resolverscontainer/metaResolversContainerFactory.go, dataRetriever/factory/resolverscontainer/shardResolversContainerFactory.go, epochStart/bootstrap/epochStartMetaBlockProcessor.go, epochStart/bootstrap/epochStartMetaBlockProcessor_test.go, epochStart/bootstrap/export_test.go, epochStart/bootstrap/fromLocalStorage.go, epochStart/bootstrap/process.go, epochStart/shardchain/trigger.go, epochStart/shardchain/triggerRegistry_test.go, integrationTests/multiShard/transaction/interceptedResolvedBulkTx/interceptedResolvedBulkTx_test.go, integrationTests/state/stateTrieSync/stateTrieSync_test.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, node/mock/messengerStub.go, node/node.go, node/node_test.go, p2p/libp2p/netMessenger.go, p2p/libp2p/netMessenger_test.go, process/block/shardblock.go, update/factory/fullSyncResolversContainerFactory.go
- We observed an edge case in processing and validating epoch start block and the consequent blocks for the new epoch coming from epoch. There is an edge case where the epoch start block is created by a malicious leader, he gathers the signatures, but will release that only later. 
- The specific scenario was having a set of metablocks with (R:543,N:543), (R:544, N:544), (R:545, N:545, NewEpoch) and the other chain of the same (R:543, N:543) and (R:545:N:544, NewEpoch). In this case the previous hash of the epoch start metablock is different for the 2 different cases, thus resulting a different nodesConfig after shuffling. 
- The fix is keeping a defined order of processing, shuffling nodes according to the received metablocks, in this case as the longer chain is the first one, the …
=> fix the order of processing epoch start metablock in case of conflicts.

consensus/mock/headerHandlerStub.go, consensus/spos/worker.go, p2p/libp2p/netMessenger.go, process/dataValidators/txValidator.go, process/dataValidators/txValidator_test.go, process/interceptors/common.go, process/sync/baseSync.go, process/sync/export_test.go, process/sync/shardblock_test.go, process/sync/storageBootstrap/baseStorageBootstrapper.go
* Fixed situation when sync would be stuck, because forced fork and reset probable highest nonce are prevented by two consecutive blocks synced, first one without errors and the next one with errors. Now, synced blocks with errors are counted per nonce.
=> Fix edge case when forced fork and reset probable highest nonce are prevented

data/mock/marshalizerStub.go, data/mock/pubkeyConverterStub.go, data/transaction/errors.go, data/transaction/interface.go, data/transaction/transaction.go, data/transaction/transaction_test.go, integrationTests/frontend/wallet/txInterception_test.go, integrationTests/multiShard/transaction/txRouting/txRouting_test.go, integrationTests/singleShard/transaction/interceptedResolvedTx/interceptedResolvedTx_test.go, integrationTests/testInitializer.go, node/nodeTesting.go, process/transaction/interceptedTransaction.go
This PR changes the way the transactions are signed. Originally, the signature was generated by the following algorithm:
```
tx := tuple(
nonce, //as uint64
value, //as string
receiver, //as byte array, encoded by the json serializer as base64 string
sender, //as byte array, encoded by json serializer as base64 string
gasPrice, //as uint64
gasLimit, //as uin64
data, //as byte array, encoded by json serializer as base64 string
)
txbuff := encode_JSON(tx)
signature := sign_ed25519(txbuff, sender_sk)
txbuff.signature = hex(signature)
```
The new algorithm can be described as follows:
```
tx := tuple(
nonce, //as uint64
value, //as string
receiver, //as string, bech32 format directly
sender, //as string, bech32 format directly
gasPrice, //as uint64
gasLimit, //as uin64
data, //as byte array, …
```
=> Changed the way transactions are signed using bech32 addresses

node/heartbeat/export_test.go, node/heartbeat/heartbeatMessageValidator.go, node/heartbeat/messageProcessor_test.go, node/heartbeat/sender.go, node/heartbeat/sender_test.go
- added early checking of the application version string so the application will not "silently" drop heartbeat messages
- wrapped errors in heartbeatMessageValidator.go
=> Early check of app version string

cmd/node/main.go, cmd/node/metrics/machineStatistics.go, cmd/node/metrics/metrics.go, core/constants.go
- added new info line in node/status route that will specify the number of shards without metachain
- added number of shards and shard ID to the automatic refreshing system in order to correctly specify the shard ID if the node does not restart
=> Added num of shards in node/status route

data/state/trackableDataTrie.go, process/smartContract/hooks/blockChainHook.go, storage/interface.go, storage/leveldb/batch.go, storage/leveldb/leveldb.go, storage/leveldb/leveldbSerial.go, storage/leveldb/leveldbSerial_test.go, storage/leveldb/leveldb_test.go, storage/leveldb/serialActions.go
added a cache for batched data
Previously get was not possible to return data from batch, now it returns the data from cache.
Also remove had to go directly to disk and it could have been very disk intensive.
It is no longer required to correlate the sizes of cache and batch for storers.
=> storage: get from batch, remove with batch

cmd/node/factory/structs.go, cmd/node/main.go, epochStart/bootstrap/fromLocalStorage.go, sharding/indexHashedNodesCoordinator.go, sharding/indexHashedNodesCoordinator_test.go
start in epoch with DB without the node shuffled to another shard started with the genesisNodesConfig and couldn't continue
added currentNodesConfig saved in the DB also for the case the node was not shuffled
=> bootStrapFrom storage if no shuffle fixed

storage/factory/bootstrapDataProvider.go, storage/leveldb/common.go, storage/leveldb/leveldb.go, storage/leveldb/leveldbSerial.go, storage/leveldb/leveldb_test.go
- fixed closing the bootstrap storage if an error occurred when trying to fetch initial data from that storage
- added waiting time and retries when opening a persister. This will prevent returning immediately when encountering the "resource temporarily unavailable" error
- added a fix to the levelDB implementation so close can be called multiple times
=> fixed closing the bootstrap storage

dataRetriever/requestHandlers/requestHandler.go, debug/resolver/interceptorResolver.go, epochStart/bootstrap/process.go, epochStart/bootstrap/process_test.go, process/interceptors/processor/miniblockInterceptorProcessor.go, process/sync/baseForkDetector.go, process/sync/baseForkDetector_test.go, process/sync/export_test.go, process/track/metaBlockTrack.go, process/track/shardBlockTrack.go, sharding/nodesSetup.go
- fixed edge case when received metablocks were added in cache before the block tracker initialization leading to perpetual requests of metablocks that were actually long time received
- fixed trie node requester log prints
- fixed the event timestamp in resolver debugger
- changed some log prints into log.Trace
- changed the order of the nodesSetup fields
=> fixed cleaning of header cache after the block tracker initialization

epochStart/bootstrap/epochStartMetaBlockProcessor.go, epochStart/bootstrap/process.go
In case of bootstrap if syncing the epoch start metablock returns with any error, this should be treated as critical, node should not start.
=> sync should be critical error in bootstrap

core/indexer/common.go, core/indexer/data.go, core/indexer/elasticsearchDatabase_test.go, core/indexer/processTransactions.go, core/indexer/processTransactions_test.go, process/block/metablock.go
Bug fix : rewards transactions was not indexed anymore because method that gets rewards transactions from pool was called after transactions was removed from pool.
FIX : call the method that reads the transactions before they are removed from the pool
Also the field 'gasUsed' of structure Transaction that is saved in elasticsearch database  is now calculated in gas units. To convert the field 'gasUsed'  in ERD must by multiply with gas price.
=> get rewards txs from pool before commitEpochStart method

data/mock/cacherMock.go, data/trie/branchNode.go, data/trie/extensionNode.go, data/trie/sync.go, data/trie/sync_test.go
When intercepting the same node, do not override in nodesForTrie cache.
=> En 6453 fix trie sync

genesis/checking/nodesSetupChecker.go, genesis/checking/nodesSetupChecker_test.go
- Fixed the case in which the delegation is done before staking and the checker wrongly subtracted the value of a staked node.
=> Fix checker genesis

process/block/metablock.go
validator statistics was queried from the peerAccountTrie with a "lastFinalizedRootHash" which was 2 blocks behind. In some cases, the next block was ready to be committed and the 3rd block behind was pruned.
- fixed validator statistics is empty by querying the trie with the previous block's rootHash (lastMetaBlock) not two blocks (prevHeader) behind
=> fixed empty validator statistics

cmd/node/main.go
- removed logger file closing when the startNode finished in order to capture the last error in the file. Logger file will close when the GC will try to clean-up the logger objects through a setFinalizer function (called inside the prepareLogFile function).
=> En 6508 fix logger in main

core/indexer/elasticsearch.go, core/indexer/elasticsearch_test.go, scripts/testnet/include/config.sh, scripts/testnet/variables.sh
- Modified testnet scripts to generate setting for proxy application to connects to observer that are on metachain. 
- Also remove log.Debug(...) that is displayed when observers that are connected to `elasticsearch` database try to index a block that does not have miniblocks.
=> Scrips proxy connects meta observers

storage/immunitycache/cache_test.go, storage/immunitycache/chunk.go, storage/txcache/maps/bucketSortedMap.go, storage/txcache/maps/bucketSortedMap_test.go, storage/txcache/maps/concurrentMap.go, storage/txcache/maps/concurrentMap_test.go, storage/txcache/txByHashMap.go, storage/txcache/txListBySenderMap.go
[Original conversation in PR 1802](https://github.com/ElrondNetwork/elrond-go/pull/1802#discussion_r431027949).
Fixed some inconsistent counters for senders and transactions within the internal structures of the transactions pool. Inconsistencies could occur in case of high concurrency and / or concurrent removals (eviction plus removal due to commit / finalize). The bug was mostly benign, but if it were, say, thousands of such events, the counters would have become slightly off and therefore could have lead - in extreme cases - to OOM (since eviction would have been based on bad, low counters).
Extra - fixed some linting issues within package `storage/immunitycache`.
Details of the fix:
- `txListBySenderMap.addSender()`: counter is consistent because the function is called under …
=> [Minor bug / minor fix] TxPool - fix inconsistent counters (estimators)

cmd/node/main.go, epochStart/bootstrap/common.go, epochStart/bootstrap/process.go, epochStart/bootstrap/process_test.go, epochStart/mock/appStatusHandlerStub.go, integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go, process/sync/loadPersistentMetrics.go, statusHandler/persister/persistentHandler.go
Made metrics related to nonce and round at epoch start persistent
=> made epoch start metrics persistent and/or fetch from epoch bootstrapper

consensus/spos/bls/constants.go, process/sync/baseForkDetector.go, process/sync/baseForkDetector_test.go
* Reduced time to wait after all signatures from 75% to 50% from signature total subround time (this will give more time for broadcast block to reach to all peers in useful time, instead of collecting more signatures. The problem is more evident in metachain where consensus group = eligible list, and if only one signature is missing the proposer will wait until 75% of signature subround time is reached)
* Fixed a situation when two valid blocks with the same nonce and the same round (double signed situation) could triggered forks with bad consequences. (now, if there are two blocks with the same round and the same nonce, the fork is not triggered anymore if meantime was received a proposed block with a higher nonce)
=> Fix fork detector after double sign

cmd/node/factory/structsStatusHandlers.go, cmd/node/main.go, cmd/node/metrics/metrics.go, cmd/termui/main.go, cmd/termui/provider/logProvider.go, process/block/metrics.go, statusHandler/errors.go, statusHandler/factory/interface.go, statusHandler/view/termuic/termuiConsole.go
Fixed the following bugs:
- if the node started with TermUI and the `Ctrl+C` signal was intercepted, the node's process didn't stop as expected. Now the TermUI console will start only after the initial pre-requisites are met (start in epoch, p2p bootstrap, and so on) so the process will be stopped accordingly.
- if the node started with TermUI the log file did not contain all logs. Fixed
- if the TermUI application didn't succeed when connecting to a node, it failed. Now it will keep trying connecting until successful 
- epoch number displayed in TermUI was delayed in comparison with the epoch which was displayed in logs. Fixed by fetching the epoch displayed in TermUI from shard header instead of meta block
- latest stable software version wasn't displayed right in TermUI and an …
=> TermUI issues fix

api/errors/errors.go, api/mock/facade.go, api/node/routes.go, api/node/routes_test.go, cmd/node/config/api.toml, consensus/interface.go, consensus/mock/networkShardingCollectorStub.go, core/p2pCore.go, facade/interface.go, facade/mock/nodeStub.go, facade/nodeFacade.go, facade/nodeFacade_test.go, heartbeat/interface.go, heartbeat/mock/messengerStub.go, integrationTests/mock/networkShardingCollectorMock.go, node/errors.go, node/interface.go, node/mock/messengerStub.go, node/mock/networkShardingCollectorStub.go, node/node.go, node/node_test.go, p2p/libp2p/netMessenger.go, p2p/libp2p/netMessenger_test.go, p2p/memp2p/messenger.go, p2p/p2p.go, sharding/networksharding/peerShardMapper.go, sharding/networksharding/peerShardMapper_test.go
- added peer info route that will output information for a provided peer (or part of a peer) like: known addresses, its hex public key, if is black listed or not.
Usage: `http://127.0.0.1:8080/node/peerinfo?pid=[part of the pid]`
=> Add peer info route

cmd/node/config/config.toml
Some caches have been resized, reducing the effective in-use memory by 600 MB, after enough time passes.
=> cmd: resize some caches

data/trie/trieStorageManager.go, data/trie/trieStorageManager_test.go
When taking a trie snapshot, check only in the last snapshot DB if the snapshot was already taken.
=> Save snapshot bug

cmd/node/config/config.toml
Activated size check marshalizer. Now messages that are propagated over p2p network that are bigger with 10% than the expected size will be rejected.
=> reactivate size check marshalizer

factory/networkComponents.go, integrationTests/longTests/antiflooding/antiflooding_test.go, integrationTests/mock/peerBlackListHandlerStub.go, integrationTests/p2p/antiflood/blacklist/blacklist_test.go, node/mock/peerBlackListHandler.go, process/interface.go, process/mock/peerBlackListHandlerStub.go, process/throttle/antiflood/blackList/p2pBlackListProcessor.go, process/throttle/antiflood/blackList/p2pBlackListProcessor_test.go, process/throttle/antiflood/disabled/peerBlacklistHandler.go, process/throttle/antiflood/factory/p2pAntifloodAndBlacklistFactory.go, process/throttle/antiflood/factory/p2pAntifloodAndBlacklistFactory_test.go, storage/interface.go, storage/mock/timeCacheStub.go, storage/timecache/export_test.go, storage/timecache/peerTimeCache.go, storage/timecache/peerTimeCache_test.go, storage/timecache/timeCache.go, storage/timecache/timeCache_test.go
- removed self ban situation when observers try to send more data than can handle
- added a new functionality on peer blacklist handler that will update the ban duration if the ban duration is higher than existing
=> Fix antiflood self blacklisted

cmd/termui/main.go, cmd/termui/provider/logProvider.go
Implemented a mechanism that keeps trying to re-connect to the node when log messages are not received anymore. this could have happened when the node was shuffled out or was simply stopped.
=> fix termui app when shuffled out or node stops

process/scToProtocol/stakingToPeer.go, process/scToProtocol/stakingToPeer_test.go, vm/systemSmartContracts/auction.go, vm/systemSmartContracts/auction_test.go, vm/systemSmartContracts/staking.go, vm/systemSmartContracts/staking_test.go
jailed nodes remained jailed also after unjail, rating was reset but were not set to "new" list
- fixed unjail nodes
=> unjailed nodes fix

data/interface.go, data/mock/storageManagerStub.go, data/trie/patriciaMerkleTrie.go, data/trie/patriciaMerkleTrie_test.go, data/trie/snapshotDb.go, data/trie/trieStorageManager.go, data/trie/trieStorageManager_test.go, epochStart/mock/storageManagerStub.go, genesis/mock/storageManagerStub.go, update/mock/storageManagerStub.go
_Bug_: When GetSnapshotThatContainsHash() is called, the pointer to the snapshotDb is returned. But concurrently, the same db could have been closed and removed, thus resuting in a concurrency problem.
=> Fix trie snapshot concurrency

data/trie/trieStorageManager.go, data/trie/trieStorageManager_test.go
_Bug_: The trieStorageManager did not load snapshots in order. Each trie snapshot has an integer as directory name for the snapshot db. When the node loads the snapshots, they must be loaded in order (directory 9 before 10).
=> load snapshots in order

cmd/node/config/config.toml, dataRetriever/txpool/shardedTxPool.go, dataRetriever/txpool/shardedTxPool_test.go
Tx Pool capacity = 600000 items or 400 MB:
- `[source == me]` gets 300000 items or 200 MB
- `[source == the other, destination == me]` gets 150000 items or 100000 MB
- `[source == meta, destination == me]` gets 150000 items or 100000 MB
Also, adjusted storage cache config for some components.
=> Adjust (lower) pool size. Fix capacity allocation.

process/block/shardblock.go
* Fixed situation when shards will consider metachain stuck forever if the state would be set to stuck and because there was no way to reset this state back, as all the created blocks were empty. Shards should process txs cross me where they also would include new meta blocks, so the unstuck state of metachain could be restored.
=> Fix state of meta is stuck 

cmd/node/main.go, genesis/process/baseGenesisProcessorsFactory.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, go.mod, go.sum
- closed vm container to close the arwen process
- switched to new logger version
- main closing wait will be done only if the components could not be gracefully closed
=> EN 6803 close arwen after genesis

process/economics/economicsData.go, process/economics/economicsData_test.go, process/errors.go, process/interface.go, process/transaction/interceptedTransaction.go, process/transaction/interceptedTransaction_test.go
verification of txValue and length of usernames
=> EN-6798/tx-integrity-checks

statusHandler/presenter/blockInfoGetters_test.go, statusHandler/presenter/common.go
changed the message displayed when a key is missing in TermUI from `[key not found]` to `N/A`. Before, that message wasn't displayed correctly and could lead to references to the validator key.
=> changed the message displayed when a key is not available in termui

debug/p2p/export_test.go, debug/p2p/p2pDebugger.go, debug/p2p/p2pDebugger_test.go, integrationTests/longTests/antiflooding/antiflooding_test.go, p2p/libp2p/export_test.go, p2p/libp2p/netMessenger.go, p2p/libp2p/netMessenger_test.go, p2p/p2p.go
- added p2p debugger component that will display bandwidth used by a node split by topic usage.
To enable it, run the node with `*:INFO,debug/p2p:TRACE`
=> EN 6813 p2p debugger

api/middleware/globalThrottler.go, node/nodeTransactions.go
Added metachain id in sender field for reward transactions that are returned by api route `/transaction/:hash`
Also added an return message when `code 429 [TooManyRequests]` is returned by an observer
=> added an error message when are to many request to an observer

integrationTests/multiShard/transaction/interceptedResolvedBulkTx/interceptedResolvedBulkTx_test.go
- reduced the number of transactions generated and sent in TestNode_InterceptorBulkTxsSentFromOtherShardShouldBeRoutedInSenderShardAndRequestShouldWork
=> Fixed intercepted txs test

cmd/node/main.go, go.mod, go.sum
- added machine ID in version string
=> Add machine ID in version string

p2p/libp2p/netMessenger.go
- fixed a wrongly used mutex in p2p network messenger, UnjoinAllTopics function
=> Hotfix p2p unjoin mutex

cmd/node/main.go
removed `handleAppClose` and `newStartInEpoch` functions from main as they were not working as expected. When running a node using `elrond-go-scripts-v2` it caused additional log files due to multiple processes creation.
=> removed process start function when shuffled out

integrationTests/resolvers/miniblocks/miniblocks_test.go, integrationTests/singleShard/block/interceptedRequestTxBlockBody/interceptedRequestTxBlockBody_test.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithMultisigner.go, process/interceptors/multiDataInterceptor.go, process/interceptors/processor/miniblockInterceptorProcessor.go
* Implemented a mechanism which will add only whitelisted miniblocks received in pool
* Fixed an edge case in multidata interceptor related to a throttle mechanism
=> Reject miniblocks which are not whitelisted

cmd/node/factory/structs.go, dataRetriever/requestHandlers/requestHandler.go, epochStart/bootstrap/factory/epochStartInterceptorsContainerFactory.go, epochStart/bootstrap/syncEpochStartMeta.go, integrationTests/testProcessorNode.go, process/block/interceptedBlocks/argInterceptedBlockHeader.go, process/block/interceptedBlocks/common.go, process/block/interceptedBlocks/common_test.go, process/block/interceptedBlocks/interceptedBlockHeader.go, process/block/interceptedBlocks/interceptedBlockHeader_test.go, process/block/interceptedBlocks/interceptedMetaBlockHeader.go, process/block/interceptedBlocks/interceptedMetaBlockHeader_test.go, process/factory/interceptorscontainer/args.go, process/factory/interceptorscontainer/metaInterceptorsContainerFactory.go, process/factory/interceptorscontainer/metaInterceptorsContainerFactory_test.go, process/factory/interceptorscontainer/shardInterceptorsContainerFactory.go, process/factory/interceptorscontainer/shardInterceptorsContainerFactory_test.go, process/interceptors/factory/argInterceptedDataFactory.go, process/interceptors/factory/interceptedMetaHeaderDataFactory.go, process/interceptors/factory/interceptedMetaHeaderDataFactory_test.go, process/interceptors/factory/interceptedShardHeaderDataFactory.go, process/interceptors/factory/interceptedShardHeaderDataFactory_test.go, process/interceptors/whiteListDataVerifier.go, process/interceptors/whiteListDataVerifier_test.go, update/factory/fullSyncInterceptors.go
- fixed the checking of whitelisting intercepted data that will include the checking of nonce or epoch start in the case of shard/meta headers. This will prevent dropping the messages from observers because they were not whitelisted.
=> Fix whitelisting of nonce/epoch requests

consensus/broadcast/metaChainMessenger.go, consensus/broadcast/shardChainMessenger.go, consensus/broadcast/shardChainMessenger_test.go, consensus/interface.go, consensus/mock/broadcastMessangerMock.go, consensus/spos/bls/subroundEndRound.go, process/block/export_test.go, process/block/poolsCleaner/miniBlocksPoolsCleaner.go, process/block/poolsCleaner/txsPoolsCleaner.go, process/block/shardblock.go, process/block/shardblock_test.go
* Fixed edge case on bootstrap from storage when the highest final nonce was higher than highest self notarized nonce committed in the last block (this situation could happen when a node is in sync mode and each committed block become final because the node has in advance info from metachain, which confirms the finality of the committed block, and also that the node is on right chain)
* Fixed/optimized lock/unlock situation in txPoolsCleaner and miniBlockPoolsCleaner
* Optimized computation for PrepareBroadcastBlockDataValidator in subround EndRound
=> Fix pools cleaner lock-unlock and start from storage edge case

cmd/node/config/ratings.toml, config/ratingsConfig.go, integrationTests/testProcessorNode.go, process/rating/ratingsData.go, process/rating/ratingsData_test.go, sharding/indexHashedNodesCoordinator.go
- differentiate rating increases and decreases to have a higher value in the metachain of ~10% for each shard => 20% increase  in a setup with 2 shards and metachain
- added round and shardId to nodescoordinator.ComputeConsensusGroup for log.Debug
=> ratings increases and decreases for metachain are 20% more than in the shards

core/alarm/alarm.go
- fixed panic in alarm.go by correctly treating the ok flag after fetching the alarm struct from the internal map
=> Fixed panic in alarm

cmd/node/config/config.toml, data/state/accountsDB.go, data/state/accountsDB_test.go, data/state/errors.go, data/state/export_test.go, data/state/journalEntries.go, data/state/journalEntries_test.go, integrationTests/testProcessorNode.go
When an account is removed, also remove  the code (or decrease numReferences).
Removed unneeded code.
Change max trie snapshots to remember from config.
Use a real fork detector in integration tests.
=> En 6993 prune code on remove account

consensus/broadcast/delayedBroadcast.go
Fix: TrimLeft removes characters left not prefixes, use TrimPrefix instead.
=> consensus: fix: TrimPrefix instead of TrimLeft for trimming prefixes

README.md
changed the Elrond logo img reference to raw as Dockerhub can't render it otherwise
=> use raw github elrond logo img

go.mod, go.sum
This PR references the new release for concurrent-map which should fix the memory leak in fifoShardedCache.
=> gomod: reference latest release for concurrent-map

api/errors/errors.go, api/middleware/globalThrottler.go, api/mock/facade.go, api/mock/throttlerStub.go, api/shared/shared.go, api/transaction/routes.go, api/transaction/routes_test.go, cmd/node/config/config.toml, cmd/node/main.go, config/config.go, core/interface.go, debug/antiflood/debugger.go, facade/nodeFacade.go, facade/nodeFacade_test.go, node/node.go, node/nodeTransactions.go, node/nodeTransactions_test.go, node/options.go
- implemented custom endpoints throttlers in order to be able to limit the maximum number of simultaneous requests (or goroutines) at once.
- removed old implementation for `/transaction/:hash`'s throttler and switched to this approach
- corrected a typo
=> EN-7054: Rest API endpoints throttlers

core/interface.go, core/keyValStorage/keyValStorage.go, core/keyValStorage/keyValStorage_test.go, data/interface.go, data/mock/trieStub.go, data/trie/branchNode.go, data/trie/extensionNode.go, data/trie/interface.go, data/trie/leafNode.go, data/trie/patriciaMerkleTrie.go, data/trie/patriciaMerkleTrie_test.go, dataRetriever/mock/trieStub.go, epochStart/mock/trieStub.go, node/mock/trieStub.go, process/mock/trieStub.go, update/mock/trieStub.go
Add a new trie functionality, getAllLeavesOnChannel, which returns all the trie leaves on a channel. When all the leaves have been sent, the channel closes.
=> GetAllLeaves On Channel 

cmd/node/config/config.toml, cmd/node/main.go, config/config.go, epochStart/bootstrap/process_test.go, storage/factory/pruningStorerFactory.go, storage/pruning/pruningStorer.go, storage/pruning/pruningStorerArgs.go, storage/pruning/pruningStorer_test.go, testscommon/generalConfig.go
renamed boolean parameter `FullArchive` to `CleanOldEpochsData`
=> renamed fullArchive to cleanOldEpochsData

process/track/baseBlockTrack.go, process/track/baseBlockTrack_test.go, process/track/export_test.go
* Rejected whitelisting miniblocks included in headers which are out of range (this will fix the situation when a node is syncing and it will receive headers with higher nonces compared with the last one processed. Because of these headers which are received, it will whitelist its miniblocks and afterwards its transactions. More than this it will also add these transactions into immunized cache. This will fill up these caches (whitelist cache, immunized cache) with a lot of information which is not needed right now and which will also be evicted until its time will come)
=> Avoid whitelisting out of range block data

epochStart/bootstrap/process.go, epochStart/bootstrap/process_test.go
fixed the situation where if an entire testnet started with the same `prefs.toml` file and it's value of `DestinationShardAsObserver` would have not been set to `disabled` then all the nodes joined as observers in that shard.
=> check if node exists in genesis config before setting destination shard

core/file.go
Previously, the node used to generate log files of the form `elrond-go-YYYY-DD-MM-HH-MM-SS.log` (note the order year-day-month). This PR fixes the order in the date format, changing it to the more readable `YYYY-MM-DD` (year-month-date).
=> Fix date in log file name

epochStart/bootstrap/disabled/disabledValidityAttester.go, epochStart/metachain/epochStartData.go, epochStart/metachain/epochStartData_test.go, integrationTests/mock/blockTrackerStub.go, node/mock/blockTrackerStub.go, process/block/baseProcess.go, process/block/interceptedBlocks/interceptedBlockHeader.go, process/block/interceptedBlocks/interceptedMetaBlockHeader.go, process/block/metablock.go, process/block/shardblock.go, process/constants.go, process/interface.go, process/mock/blockTrackerMock.go, process/mock/finalityAttesterStub.go, process/track/baseBlockTrack.go, process/track/baseBlockTrack_test.go
* Fixed a possible problem which could avoid whitelisting miniblocks
* Fixed situation when on headers interceptor and also in block tracker component, some old headers are dropped because they have nonces behind final, but the node still needs them (especially in epoch start headers could exist some old references to headers behind final and they should be accepted, as they are requested and whitelisted)
* Changed some behavior of getting headers from storage with getting headers from pool and afterward from storage
=> Fix whitelisting in advance for miniblocks

process/block/baseProcess.go, process/block/baseProcess_test.go, process/block/export_test.go, process/block/metablock.go, process/block/shardblock.go, process/block/shardblock_test.go
* Fixed sync problem when attesting finality header is not requested in advance
=> Fix sync speed problem with attesting finality headers which are not requested in advance

process/block/metablock.go, process/constants.go
* Fixed computation of number of shard headers which could be included in one meta block
=> Fix number of shard headers included in one meta block

statusHandler/presenter/chainInfoGetters.go, statusHandler/presenter/chainInfoGetters_test.go, statusHandler/presenter/presenterStatusHandler.go
Change input data for formula that is used to calculate synchronization time (estimation). 
Instead of using current synchronized nonce now is used current synchronized round because if we are using nonce we will have an estimation for current epoch not for  all the epochs that are needed to be synchronized.
=> Use round instead of nonce for synchronization estimation

cmd/node/config/config.toml, cmd/node/factory/structs.go, config/config.go, process/errors.go, process/smartContract/process.go, process/smartContract/process_test.go
disable deployment of contracts through config. deployment and execution of any contract calls are safe.
=> disable-sc-deploy

cmd/node/main.go, cmd/seednode/main.go, factory/networkComponents.go, factory/networkComponents_test.go, integrationTests/testInitializer.go, p2p/errors.go, p2p/example/libp2p/autodiscovery/main.go, p2p/libp2p/export_test.go, p2p/libp2p/issues_test.go, p2p/libp2p/localSyncTimer.go, p2p/libp2p/netMessenger.go, p2p/libp2p/netMessenger_test.go, p2p/mock/syncTimerStub.go, p2p/p2p.go
- made the network messenger use an NTP syncer in order to not throw away p2p messages just because the local system clock is out of sync
=> Fix messenger sync clock problem

core/indexer/elasticsearch.go
Indexing validator public keys moved on separate goroutine to not block consensus, otherwise, in some cases consensus is blocked for more than the expiry time of the consensus watchdog and causes a node reset
=> fix validator keys indexing watchdog expiry

debug/antiflood/debugger.go, p2p/libp2p/connectionMonitorWrapper.go, process/throttle/antiflood/p2pAntiflood.go
- reduced the large amount of p2p/antiflood prints. To test this, can connect to an existing network (BoN/mainnet and deliberately change the chain ID from nodesSetup.json)
=> Reduced the large amount of p2p/antiflood prints

process/smartContract/scQueryService.go, process/smartContract/scQueryService_test.go
Currently, the REST response produced by a call to the `SCQueryService` does not contain `vmOutput.ReturnMessage` in case of failure. This error message is very useful for developing apps that interface with a custom SC.
The PR adds `vmOutput.ReturnMessage` to the error produced by `SCQueryService.ExecuteQuery()`, in case the execution fails.
=> Add VM return message into the REST response

genesis/errors.go, genesis/interface.go, genesis/mock/deployProcessorStub.go, genesis/process/genesisBlockCreator.go, genesis/process/intermediate/deployLibrarySC.go, genesis/process/intermediate/deployProcessor.go, genesis/process/intermediate/deployProcessor_test.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, genesis/process/testdata/genesisTest1.json, genesis/process/testdata/genesisTest2.json, integrationTests/testInitializer.go
- added protection against delegation to undeployed SC in the genesis process
=> Protection for undeployed delegation

cmd/node/config/config.toml, consensus/broadcast/delayedBroadcast.go, consensus/broadcast/delayedBroadcast_test.go
memory leak is caused by accumulation of metablocks.
the references to metablocks are stored in an array in the delayed broadcast implementation, where they should get removed also when alarms  are canceled, not only when alarms expire. 
fix is to remove the reference as well on canceling the alarms.
=> consensus: memory leak debug data

cmd/node/config/config.toml, config/config.go, config/tomlConfig_test.go, dataRetriever/interface.go, integrationTests/consensus/testInitializer.go, integrationTests/mock/transactionCoordinatorMock.go, integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go, integrationTests/testInitializer.go, node/nodeMemoryConfig_test.go, process/block/baseProcess.go, process/block/baseProcess_test.go, process/block/metablock.go, process/block/shardblock.go, process/coordinator/process.go, process/coordinator/process_test.go, process/interface.go, process/mock/intermediateTransactionHandlerMock.go, process/mock/transactionCoordinatorMock.go, process/sync/shardblock_test.go, process/track/baseBlockTrack_test.go, storage/factory/pruningStorerFactory.go, testscommon/generalConfig.go, update/mock/transactionCoordinatorMock.go, update/process/shardBlock.go, update/process/shardBlock_test.go, update/sync/syncHeaders_test.go
* Added receipts hash storer which holds cumulative receipt hash as a key and all the receipts hashes list marshalized as a value, for each committed block
Testing steps:
a) Prerequisites
b) Test steps
Start a normal testnet
c) Expected results
We should have another storage/folder/db created in: .../Epoch_X/Shard_Y/**Receipts** which holds cumulative receipt hash as a key and all the receipts hashes list marshalized as a value, for each committed block
d) Actual results
Test process is in pending
=> Add receipts hash storer

process/block/baseProcess.go, process/coordinator/process.go, update/process/shardBlock.go
Previously, the function which computed the receipts hash would have returned a hash even if no receipts was present. Added an extra check
=> fixed the situation when empty receipts would have been saved

epochStart/bootstrap/fromLocalStorage.go, genesis/process/metaGenesisBlockCreator.go, process/coordinator/process.go
* Fixed situation when node is restarted in epoch 0 with db and with StartInEpochEnabled flag set to false
Testing steps:
a) Prerequisites
b) Test steps
Start a normal testnet with StartInEpochEnabled flag from config.toml set to false. Restart nodes during the epoch 0 with db.
c) Expected results
Nodes should be able to start OK after restart in epoch 0 with db and with StartInEpochEnabled flag set to false.
d) Actual results
Test process is in pending
=> Fix save genesis meta to storage

core/indexer/common.go, core/pubkeyConverter/bech32PubkeyConverter.go, storage/pruning/pruningStorer.go
- added prints in pruning storer
- fixed a bech32 conversion WARN in indexer
- added stack dump in pubkey converter to easily debug wrong usage of a pub key converter
=> Bughunt WARN messages on bech32 pubkey converter

dataRetriever/factory/storageResolversContainer/baseResolversContainerFactory.go, dataRetriever/storageResolvers/headerResolver.go, dataRetriever/storageResolvers/sliceResolver.go, dataRetriever/storageResolvers/sliceResolver_test.go, dataRetriever/storageResolvers/storageResolver.go
- fixed the stopping process when importing data with the offline syncer
Testing procesures:
- as in PR #2248, the import process should run as expected until a missing data error happens. This time can be any data (tx, miniblock, nonce-hash, receipt, etc.), not just the hash-header info.
=> Fix stop offline syncer

cmd/node/config/config.toml, core/dblookupext/historyRepository.go, core/dblookupext/historyRepository_test.go, data/transaction/apiTransactionResult.go, data/transaction/status.go, data/transaction/status_test.go, node/nodeTransactions.go, node/nodeTransactions_test.go
The metachain directly notarizes miniblocks towards it - at commit block time. Therefore, there's the time to set the hyperblock coordinates for the miniblocks in question. At the source shard, the "block notarized" notifications arrive in a slightly different manner - the payload is a `block.Header`, not a `block.MetaBlock`.
Therefore,
- Gather hyperblock coordinates for transactions towards meta as well
- Refactoring: separate normal from invalid transactions in `nodeTransactions.go`
- Return extra fields for `unsigned` transactions (e.g. return message, original transaction hash)
- Improve transaction status (API) reporting when `DatabaseLookupExtensions` are enabled (that is, return `executed` if hyperblock coordinates are fully set, that is, if parent miniblock is fully notarized)
- …
=> Handle transactions towards metachain in DbLookupExtensions

cmd/node/factory/structs.go, cmd/node/main.go, epochStart/notifier/manualEpochStartNotifier.go
- fixed the initial epoch after the instantiation of the manualEpochStartNotifier object
- automatically alter checkpoint modulus value when importing DB
Testing procedures:
- start the import process, let it sync for about 5 epochs
- close the node that does the import
- restart the process
Expected results:
- the node should resume its import process, should not close prematurely stating:
```
terminating at internal stop signal      reason = importComplete description = import ended because data from epochs 0 or 1 does not exist
```
=> Fix epoch set in manual epoch notifier

consensus/mock/forkDetectorMock.go, integrationTests/mock/forkDetectorStub.go, node/mock/forkDetectorMock.go, process/interface.go, process/mock/forkDetectorMock.go, process/sync/baseForkDetector.go, process/sync/baseForkDetector_test.go, process/sync/storageBootstrap/baseStorageBootstrapper.go
* Implemented a mechanism of setting the final checkpoint to the last checkpoint added in list, when a node starts in epoch and it has only one block (start of epoch block) added in fork detector. This should prevent the possible rollbacks behind final block which would been done if the node would not been received the next requested block from the network in some few number of rounds.
=> Fix set of final block after restart in epoch

cmd/node/factory/structs.go
- passed the enabled epoch configs to the smart contract processor for the metachain nodes
This caused the mainnet import DB folder to cause a stuck situation on a meta node @ nonce 12801
Manual testing procedure:
import a meta node full history from epoch 0. The process should work (should get pass of the nonce 12801)
=> Fixed meta smart contract processor arguments

consensus/mock/headerHandlerStub.go, data/block/block.go, data/block/block_test.go, data/block/metaBlock.go, data/block/metaBlock_test.go, data/interface.go, integrationTests/multiShard/relayedTx/edgecases/edgecases_test.go, integrationTests/multiShard/relayedTx/relayedTx_test.go, process/coordinator/process.go, process/coordinator/process_test.go, process/mock/headerHandlerStub.go, sharding/mock/headerHandlerStub.go
* Implemented execution in a chronological way for cross shard mini blocks, taking into consideration the round in which they were created/executed in sender shard
* Unskipped the relayed integration tests
=> Fix execution order of cross mini blocks

core/statistics/tpsBenchmark.go, core/statistics/tpsBenchmark_test.go
Fix concurrent access on map that store shard statistics information for TPS Benchmark. 
When method ShardStatistics() is called will return a copy of map that contains shard statistics.
=> Bug fix panic tps benchmark

api/mock/facade.go, api/vmValues/routes.go, api/vmValues/routes_test.go, data/vm/vmOutputApi.go, data/vm/vmOutputApi_test.go, facade/nodeFacade.go
created a wrapped structure which will be returned when calling a `vm-values` endpoint. Now it will display addresses in bech32 format when needed and added custom json tags (with lowercase)
- run a testnet
- make a POST request to `vm-values/query` for example and the output should follow json format and not having unreadable characters
=> wrapped vm output api response

cmd/seednode/api/api.go, cmd/seednode/main.go
Added the `/log` route inside the seednode. If enabled (Rest API interface is not set to "off") then the logs can be fetched via the `logviewer` app. 
-run the seednode. Default API interface is `localhost:8080` and can be replaced with the `--rest-api-interface X` flag 
-try to connect via the `logviewer` app: `./logviewer -address 127.0.0.1:8080` . If seednode's Rest API interface is not "off", it should work and fetch logs real time. If seednode's Rest API interface was set to "off" (`./seednode --rest-api-interface off`), then no connection should be made.
=> EN-6936: log route on seednode

process/block/baseProcess.go, process/block/baseProcess_test.go, process/block/export_test.go, process/block/metablock.go, process/block/metablock_test.go, process/block/shardblock.go, process/block/shardblock_test.go, process/mock/blockTrackerHandlerMock.go, process/track/baseBlockTrack.go, process/track/baseBlockTrack_test.go, process/track/blockProcessor.go, process/track/blockProcessor_test.go, process/track/export_test.go, process/track/interface.go
* Sync tracker pool with headers pool LRU cacher when missing headers from tracker are requested (in this situation a delete will be done in headers pool, just to be sure that the notifiy event will be called for the requested/received header, even if in some edge case situations the requested header exists only in headers pool but not in tracker pool)
This situation could appear only in some rare events of restarting the node after more than 1000 rounds from its last commit
=> Sync tracker pool with headers pool

cmd/node/factory/structs.go, cmd/node/main.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithStateCheckpointModulus.go, integrationTests/testSyncNode.go, integrationTests/vm/arwen/utils.go, integrationTests/vm/mockVM/vmGet/vmGet_test.go, integrationTests/vm/testInitializer.go, process/block/argProcessor.go, process/block/metablock.go, process/block/metablock_test.go, process/scToProtocol/stakingToPeer.go, process/scToProtocol/stakingToPeer_test.go, process/smartContract/scQueryService.go, process/smartContract/scQueryService_test.go, vm/systemSmartContracts/staking.go, vm/systemSmartContracts/staking_test.go
RegisterNonce for waiting and view function.
This code is backward compatible if stake was not enabled - after that it is not. Should be merged before enabling staking.
=> RegisterNonce for waiting and view function 

cmd/node/config/ratings.toml, statusHandler/view/termuic/termuiRenders/widgetsRender.go
- fixed the wrong termui gauge display when a too long label was provided by trimming the label according to the actual space that a gauge has
=> Resize termui gauge label

cmd/node/config/ratings.toml, process/peer/process.go
set to jailed when account is inactive and with infinite unstaked epoch after jailing is enabled.
=> set-to-jail-from-inactive

vm/systemSmartContracts/staking.go, vm/systemSmartContracts/staking_test.go
receipt hash missmatch because config was not added into scr as in mainnet
=> receipt-hash-unjail

data/state/accountsDB.go, integrationTests/vm/systemVM/stakingSC_test.go, vm/systemSmartContracts/eei.go, vm/systemSmartContracts/eei_test.go, vm/systemSmartContracts/staking.go, vm/systemSmartContracts/staking_test.go
- removed some direct nil comparison in accounts DB
- added prints for IsValidator function
=> Accounts DB fixes + prints

vm/systemSmartContracts/auction.go, vm/systemSmartContracts/auction_test.go
Added a view function for the auctions system sc that returns (blsKey - status) pairs.
=> EN-7793-view-func-bls-keys-status

cmd/node/config/p2p.toml, cmd/node/main.go, cmd/seednode/config/p2p.toml, config/p2pConfig.go, dataRetriever/factory/storageResolversContainer/baseResolversContainerFactory.go, dataRetriever/factory/storageResolversContainer/metaResolversContainerFactory.go, dataRetriever/factory/storageResolversContainer/shardResolversContainerFactory.go, dataRetriever/storageResolvers/headerResolver.go, dataRetriever/storageResolvers/headerResolver_test.go, dataRetriever/storageResolvers/sliceResolver.go, dataRetriever/storageResolvers/sliceResolver_test.go, dataRetriever/storageResolvers/storageResolver.go, dataRetriever/storageResolvers/storageResolver_test.go, factory/cryptoSigningParams.go, factory/cryptoSigningParams_test.go, integrationTests/p2p/peerDisconnecting/peerDisconnecting_test.go, p2p/libp2p/connectionMonitor/factory/connectionMonitorFactory.go, p2p/libp2p/connectionMonitor/libp2pConnectionMonitorSimple.go, p2p/libp2p/connectionMonitor/libp2pConnectionMonitorSimple_test.go, p2p/libp2p/netMessenger.go
Improved the import-db process:
- added a delay before the import process will stop the node in order to have the time to commit received data
- added ThresholdMinConnectedPeers as a config in order to be overridden by the import db process
- made the import-db process automatically generate a new BLS key in order to avoid accidental usage of a validator BLS key that migh trigger the node shuffle-out
=> Refined import db process

integrationTests/multiShard/relayedTx/common.go, integrationTests/singleShard/transaction/interceptedBulkTx/interceptedBulkTx_test.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, integrationTests/vm/systemVM/stakingSC_test.go, node/errors.go, node/node.go, node/node_test.go
- removed the possibility to broadcast a transaction from any node in the network. Each transaction will get broadcast only if it will be routed to the sender's shard ID node.
- added unit and integration tests that prove that the transaction validation works as expected
=> EN 7439 transaction routing fixes

api/mock/facade.go, api/transaction/routes.go, api/transaction/routes_test.go, facade/interface.go, facade/mock/nodeStub.go, facade/nodeFacade.go, node/node.go
- fixed the tx simulation process
- added unit tests for tx simulation rest api endpoint
=> EN 7890 fix cannot simulate tx

core/indexer/processTransactions.go, core/indexer/processTransactions_test.go, data/transaction/status.go, data/transaction/status_test.go, node/nodeTransactions_test.go, node/txsimulator/txSimulator.go
data field for ok smart contract results changed from `@ok` to `@hex("ok")` 
updated the condition in elastic search indexer
Also changed transactions' statuses messages:
```
successful -> success
unsuccessful -> fail
invalid -> invalid
pending -> pending
```
=> changed condition for ok smart contract results indexing

go.mod, process/block/postprocess/intermediateResults.go, process/smartContract/process.go, process/smartContract/process_test.go
- fixed testnet compatibility issue that happened when trying to import a DB on the testnet version T1.1.3.0
Manual testing procedure: import-db on shard 0 with the T1.1.3.0 version configs & resulted DB. The process will work up until epoch 6 where the new "bad" code kicked-in. (by using a small hack that reverted this fix for epochs>=5, I was able to fully sync the 12 epochs)
=> Bugfix import db testnet version T1.1.3.0 compatibility issue

epochStart/metachain/systemSCs.go, epochStart/metachain/systemSCs_test.go, process/scToProtocol/stakingToPeer.go, process/scToProtocol/stakingToPeer_test.go, vm/systemSmartContracts/auction.go, vm/systemSmartContracts/auctionSaveLoad.go, vm/systemSmartContracts/auction_test.go, vm/systemSmartContracts/common.go, vm/systemSmartContracts/governance.go, vm/systemSmartContracts/governance_test.go, vm/systemSmartContracts/proto/staking.proto, vm/systemSmartContracts/staking.go, vm/systemSmartContracts/staking.pb.go, vm/systemSmartContracts/stakingSaveLoad.go, vm/systemSmartContracts/stakingWithWaiting_test.go, vm/systemSmartContracts/staking_test.go
- added `setOwner` functionality in staking SC and `updateStakingV2` in auction SC
- added a new stakingData structure that can hold the owner of the BLS key
- previous `stakingDataV2` becomes `stakingDataV1P1` in order to match data structure versions with the activation flag name
- added unit tests for the new functionality
=> En 7744 top up staking v2

vm/interface.go, vm/mock/systemEIStub.go, vm/systemSmartContracts/auction.go, vm/systemSmartContracts/auction_test.go, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/eei.go
When a user stakes - those values must be sent to the auction smart contract to make a topup of the existing values.
When a user unDelegates -the auction smart contract has to be announced as well, with the required amount. If the required amount if bigger than the top-up value, the nodes must be unstaked as well.
When a user withdraws, the required amount must be undelegated from the auction smart contract, if the required amount is bigger than the available unstaked funds, nodes must be undonded as well.
=> En 7776/delegation fund protection

cmd/node/main.go, dataRetriever/storageResolvers/headerResolver.go
This PR fixes the edge case found in testnet when a shard stopped including metaheaders for 2 epochs
- made the storage resolvers open 2 epochs in advance. Also, the maximum active persisters value is set to the maximum value it can hold (config.StoragePruning.NumEpochsToKeep) in import-db mode
=> Fix import-DB for the testnet edge case

cmd/node/main.go, core/indexer/dataDispatcher_test.go, core/indexer/dataIndexerArgs.go, core/indexer/dataIndexer_test.go, core/indexer/elasticProcessor.go, core/indexer/elasticProcessor_test.go, core/indexer/errors.go, core/indexer/factory/indexerFactory.go, core/indexer/factory/indexerFactory_test.go, core/indexer/processTransactions.go, core/indexer/processTransactions_test.go, core/mock/shardCoordinatorMock.go
- made the elastic search not index transactions if the node is node in the destination shard when running in import-db
=> Fix indexing pending problem when running in import-DB mode

epochStart/metachain/systemSCs_test.go, integrationTests/multiShard/smartContract/scCallingSC_test.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, process/factory/metachain/vmContainerFactory.go, process/factory/metachain/vmContainerFactory_test.go, vm/errors.go, vm/factory/systemSCFactory_test.go, vm/process/systemVM.go, vm/process/systemVM_test.go
Implemented gas lock mechanism in system vm
=> EN-7957/Gas lock in system vm

cmd/node/factory/structs.go, epochStart/metachain/rewards.go, epochStart/metachain/rewards_test.go
there is an edge case in rewards distribution which is not treated correctly:
if an eligible node is not selected at all the entire epoch as block producer but participates in signing all the blocks it is assigned in consensus group and all those blocks end up in the canonical blockchain, then the node will not receive any rewards for that particular epoch, although it should have received.
this PR fixes this.
=> epochStart: rewards computation edgecase fix

consensus/spos/bls/subroundSignature.go, consensus/spos/bls/subroundSignature_test.go, consensus/spos/consensusState.go, consensus/spos/consensusState_test.go, go.mod, go.sum, ntp/syncTime.go
* Fixed an edge case in signature round when proposer is waiting after all sigs and meantime a NTP sync update is done with a negative offset
* Added warn log if NTP sync offset is out of normal bounds
* Updated beevik/ntp library to version v0.3.0
**How to be tested:**
**Start a normal system test with #allin and set in config.toml the value of the SyncPeriodSeconds parameter from [NTPConfig] section to a lower value. Ex: from 3600 to 60 seconds. This will help to have more NTP syncs after 1-2 hours of testing and afterwards we can analyze if the behavior of the updated NTP library is good and also if the edge case found is fixed or not.**
=> Fix waiting all signatures edge case after NTP sync

cmd/node/config/config.toml, cmd/node/factory/structs.go, cmd/node/main.go, config/config.go, dataRetriever/interface.go, epochStart/bootstrap/metaStorageHandler.go, epochStart/bootstrap/shardStorageHandler.go, factory/dataComponents.go, factory/dataComponents_test.go, integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go, process/block/baseProcess.go, process/block/baseProcess_test.go, process/block/export_test.go, process/block/metablock.go, process/block/shardblock.go, storage/factory/pruningStorerFactory.go, storage/storageUnit/nilStorer.go
Added a new storer for `import-db` mode that will hold the `epoch` - `root hash` pairs related to tries snapshots. Based on this, we will be able to re-load the trie state at each end of epoch
=> EN-7932: add storer for epoch-root hash in import db mode

update/common.go, update/errors.go, update/genesis/base.go, update/genesis/export.go, update/genesis/export_test.go, update/genesis/import.go, update/genesis/import_test.go, update/interface.go, update/mock/headerSyncHandlerStub.go, update/mock/importHandlerStub.go, update/mock/pendingTransactionProcessorStub.go, update/mock/syncStateStub.go, update/process/processPending.go, update/process/processPending_test.go, update/process/shardBlock.go, update/process/shardBlock_test.go, update/sync/coordinator.go, update/sync/syncHeaders.go, update/sync/syncMiniBlocks.go, update/sync/syncMiniBlocks_test.go
* Implemented a fix in Hardfork mechanism, which would execute all pending transactions in the correct order
* Exported/Imported unFinished metaBlocks as well, as they are needed for execution of pending transactions in the correct order
* Extracted common used code in a new file
* Refactored some prints and some methods names
=> Hardfork: execute pending txs in correct order

epochStart/bootstrap/process.go, epochStart/bootstrap/syncEpochStartMeta.go, epochStart/bootstrap/syncEpochStartMeta_test.go, epochStart/errors.go, epochStart/mock/epochStartMetaBlockProcessorStub.go
- refactored epochStartMetaSyncer struct as to use an injected EpochStartMetaBlockInterceptorProcessor rather than a constructed one
=> Refactor bootstrapper injection

cmd/node/factory/structs.go, epochStart/interface.go, epochStart/metachain/baseRewards.go, epochStart/metachain/baseRewards_test.go, epochStart/metachain/economics.go, epochStart/metachain/economics_test.go, epochStart/metachain/rewards.go, epochStart/metachain/rewardsCreatorProxy.go, epochStart/metachain/rewardsCreatorProxy_test.go, epochStart/metachain/rewardsV2.go, epochStart/metachain/rewardsV2_test.go, epochStart/metachain/rewards_test.go, epochStart/mock/rewardsCreatorStub.go, integrationTests/mock/epochEconomicsStub.go, integrationTests/mock/epochRewardsCreatorStub.go, process/block/metablock.go, process/interface.go, process/mock/epochEconomicsStub.go, process/mock/epochRewardsCreatorStub.go
- fix number of blocks considered at the end of epoch for rewards v2 (previously EoE economics was computed after the rewards miniblocks on consensus validators while for block proposer it was computed before)
- use own computed economics for validation instead of the one coming from metablock header
- reject negative adjustments for protocol sustainability
=> Fixes top up rewards

cmd/node/config/config.toml
Fixed the configuration for the `TrieEpochRootHashStorage`. The previous config would have caused the node to stop with the error `cache size is lower than batch size`
=> fix epoch-root hash storer config

cmd/keygenerator/main.go
- refactored keygenerator app: 
1. added the possibility to output data on the console (through the extra `-console-out` flag)
2. create a single file with all the generated keys (based on type) (through the extra `no-split` flag)
This will also solve issue #1982
=> Keygenerator refactor

epochStart/shardchain/trigger.go, process/track/baseBlockTrack.go
* Fixed situation when previous epoch start meta block is missing and trigger was not activated
* Fixed a sort situation when more headers have the same nonce in block tracker component
=> Fix epoch start trigger when epoch start previous header is missing

cmd/node/config/systemSmartContractsConfig.toml, config/systemSmartContractsConfig.go, process/scToProtocol/stakingToPeer.go, vm/systemSmartContracts/auction.go, vm/systemSmartContracts/auction_test.go
fix log message. added protection against staking same key two times in the same stake call.
=> fix-log-message-double-stake

cmd/node/main.go, dataRetriever/resolvers/miniblockResolver.go, dataRetriever/resolvers/miniblockResolver_test.go, dataRetriever/resolvers/topicResolverSender/topicResolverSender.go, dataRetriever/resolvers/transactionResolver.go, integrationTests/resolvers/metablock/metablock_test.go
- fixed the following resolver-requester issues:
- fixed reporting of missing transactions and miniblocks in resolvers to the debugging component
- replaced function that gets the data from persister in miniblock resolver from `Get` to `SearchFirst` as to align with the rest of the resolvers.
- removed unused flags in main.go
- fixed a wrong iteration on an int slice
Testing:
Launch a normal testnet with #AllIn, things should go pretty smooth and no node should be left behind especially at the epoch change event.
=> Resolver fixes

cmd/node/factory/structs.go, epochStart/errors.go, epochStart/interface.go, epochStart/metachain/economicsDataProvider.go, epochStart/metachain/rewards.go, epochStart/metachain/rewardsCreatorProxy.go, epochStart/metachain/rewardsCreatorProxy_test.go, epochStart/metachain/rewardsV2.go, epochStart/metachain/rewardsV2_test.go, epochStart/metachain/rewards_test.go, epochStart/metachain/stakingDataProvider.go, epochStart/metachain/stakingDataProvider_test.go, epochStart/metachain/systemSCs.go, epochStart/metachain/systemSCs_test.go, epochStart/mock/stakingDataProviderStub.go, integrationTests/mock/epochStartSystemSCStub.go, integrationTests/testProcessorNode.go, process/block/argProcessor.go, process/block/metablock.go, process/errors.go, process/interface.go, process/mock/epochStartSystemSCStub.go, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/staking.go, vm/systemSmartContracts/staking_test.go, vm/systemSmartContracts/validator.go, vm/systemSmartContracts/validator_test.go
logic has been implemented - tests and fixes of broken tests in next commits
=> En 8340/selection at end of epoch

data/trie/sync.go
Instead of keeping the whole trie in memory during the syncing process, and Commit() the trie when it is fully synced, only keep the collapsed root and commit each node individually as it is synced.
=> EN-8343-optimize-trie-sync

cmd/node/config/config.toml, cmd/node/main.go, cmd/storer2elastic/main.go, config/config.go, sharding/errors.go, sharding/nodesSetup.go, sharding/nodesSetup_test.go, testscommon/generalConfig.go
Add maximum number of shards for genesis nodes config
This will allow more flexible initial test-net nodes config.
Should be backwards compatible, as long as the set maximum number of shards >=  with the legacy end result (3 shards without MetaChain)
Legacy implementation would have split the nodes into maximum number of shards allowed by the constraints (number of eligible nodes per shard + minimum hysteresis for waiting nodes), now even if more shards could be created, the given maximum number of shards is kept as a hard limit, the remaining nodes being distributed to the shards waiting lists.
=> max number of shards for genesis config

process/block/baseProcess.go, process/block/baseProcess_test.go, process/block/export_test.go, process/block/metablock.go, process/block/shardblock.go
fix so that the root hash when storing into EpochRootHashStorer is exactly the same as the snapshot's root hash. Before this, there were some inconsistencies and the test was not relevant.
=> [Import DB] change the way the root hash is fetched

node/nodeTransactions.go, node/nodeTransactions_test.go
- fixed original sender encoding in nodeTransactions.go, `prepareUnsignedTx` function
=> Fixed the OriginalSender encoding in nodeTransactions.go

epochStart/metachain/rewards.go
[low prio]
Useful when parsing logs with `grep` or other tools.
=> Arithmetic difference economics useful print

epochStart/metachain/systemSCs.go, epochStart/metachain/systemSCs_test.go, sharding/common.go, vm/systemSmartContracts/staking.go
- fixed the situation when the waiting queue bls key had to become eligible but the bls key owner was not set
- fixed the situation when more-than-expected waiting queue bls keys became eligible 
- optimized some prints when displayValidatorsForRandomness was called
=> Staking fixes

cmd/node/factory/structs.go, epochStart/metachain/economics.go, epochStart/metachain/economics_test.go, process/smartContract/process_test.go
Fixed a mismatch between validator statistics accumulation of block proposer fees and end of epoch economics computation.
In validator statistics, the block proposer fees was accumulated considering 10% out of (feesPerBlock - devFees) while the end of epoch economics was considering the fee as 10% out of feesPerBlock. 
The effect was that in the end of epoch metachain block there were a bit more tokens reported as distributed for rewards than actually distributed.
Added also several tests for the computation of developer fees out of the transaction fees.
=> process: add some unit tests for devFee and accumulatedFee

core/indexer/common.go, core/indexer/common_test.go, core/indexer/processTransactions_test.go
**Bugfix**: fixed problem when we have a cross-shard smart contract call with too much gas provided. The value of gasUsed field was wrong because on destination shard when the transaction is indexed in elasticsearch gasUsed field was not updated.
=> Bug fix gas used field 

core/indexer/processTransactions.go, core/indexer/processTransactions_test.go
Fixed problem with the gasUsed field of the relayed transactions that are indexed in the elasticseach database.
=> fix gas used relayed transactions

process/transaction/shardProcess.go
Added a log that displays the fail reason (which is the error that caused the transaction to be invalid). Useful when debugging relayed transactions processing for example
=> added trace log for invalid transaction

cmd/node/config/config.toml, cmd/node/factory/structs.go, cmd/node/main.go, config/config.go, process/errors.go, process/interface.go, process/smartContract/scQueryServiceDispatcher.go, process/smartContract/scQueryServiceDispatcher_test.go
- added scQueryServiceDispatcher functionality that can launch a specified number of VMs used in query service and will route each and every request to such generated SC query service in a round-robin fashion
=> SC query service dispatcher

cmd/node/config/config.toml, cmd/node/config/systemSmartContractsConfig.toml
- changed the configuration flags as to better emulate mainnet transitions
All flags should be disabled during epoch 0 while running the v1.1.10 variant. During epoch 1 the upgrade process will complete, compiling a derived branch from `development`. Now, some flags will have the enable epoch 2. Those flags should be the already activated flags on mainnet. The Maiar-dependent flags will get activated at epoch 3. The rest, at the start of the epoch 4.
=> Mainnet like configs

process/block/preprocess/rewardTxPreProcessor.go, process/block/preprocess/rewardTxPreProcessor_test.go, process/block/preprocess/smartContractResults.go, process/block/preprocess/smartContractResults_test.go, process/block/preprocess/transactions.go, process/block/preprocess/validatorInfoPreProcessor.go, process/block/preprocess/validatorInfoPreProcessor_test.go, process/coordinator/process.go, process/coordinator/process_test.go, process/interface.go, process/mock/preprocessorMock.go
* Fixed misleading info about number of txs processed for a cross shard miniblock when an error is occured ("time is out" or any other error)
=> Fixed misleading info about cross-shard miniblocks processing

sharding/multiShardCoordinator.go
The correct `numberOfShards` -> `bytesNeed` mapping should be:
```
1~2**8 : 1
2**8+1~2**16 : 2
2**16+1~2**24 : 3
2**24+1~2**32 : 4
```
(`numberOfShards` is guaranteed `>=1` in constructor)
For example, if `numberOfShards` is 256*4, the `bytesNeed` should be 2 instead of 5.
=> sharding: make the math right for ComputeIdFromBytes

cmd/node/factory/structs.go, go.mod, go.sum, process/scToProtocol/stakingToPeer.go, vm/systemSmartContracts/validator.go
- removed unnecessary backwards compatibility flag from stakingToPeer as the v1.1.10 does not change the peer state on unBond operation.
=> Backwards compatibility fixes

process/track/baseBlockTrack.go
`shardID != core.MetachainShardId` is already guaranteed by Line 614.
=> process/track: rm redundant check

node/node.go, node/node_test.go
- backwards compatibility fix on create transaction in node.go. Relaxed the limits as to allow empty fields to work on gasCost computation route.
Pending: add integration tests with real payload
=> Backwards compatibility fix on transaction routes

cmd/node/main.go, core/partitioning/sizeDataPacker_test.go, process/economics/economicsData.go
Made the `gas price modifier` metric to update when the flag is set.
Passed the `app status handler` to `economics data` using `null object design pattern` in order to avoid constructor/arguments changes. This way, the `app status handler` is initialized as a `nil implementation` on the constructor and can be changed using a `setter`.
-after starting a node check the endpoint `node-url:port/network/config` and look after the `erd_gas_price_modifier` metric (`1` for current configuration)
-after a number of epochs equal to `GasPriceModifierEnableEpoch` from `config.toml` check the endpoint again. The value should be updated to the one from `economics.toml` (`0.01` for current configuration)
=> EN-8728: gas price modifier metric update

api/address/routes.go, api/address/routes_test.go, api/errors/errors.go, api/mock/facade.go, cmd/node/config/api.toml, facade/interface.go, facade/mock/nodeStub.go, facade/nodeFacade.go, facade/nodeFacade_test.go, node/node.go, node/node_test.go
Implemented the `address/{address}/keys` endpoint that will return a map containing all keys and their values for an account. The value is represented in hexadecimal encoding.
-start a testnet using the corresponding proxy's branch
-find an address that must have saved something inside it's key-value storage (for example, an address that interacted with an ESDT token) and make an API call to `proxy-url/address/erd1.../keys`. it should return a map containing all its keys
=> EN-8854: get all key-value pairs for an account API endpoint

vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegation_test.go
The agency SC can be initiated with an infinity delegation cap. 
Once we change the delegation cap to a higher value and later one we try to set it back to infinity the SC is throwing ```cannot make total delegation cap smaller than active``` [TX](https://testnet-explorer.elrond.com/transactions/e247a401609144ece061abf1e890d50e1b91e3313e0a839d8c962502d56f5846)
Modified the ```if``` condition to check if the new value is not equal to ```0``` before returning the error.
A new unit test was added testing the flow where the infinity max cap is used again after a higher value.
=> Fix the modifyTotalDelegationCap for infinity amount

factory/coreComponents.go, factory/coreComponentsHandler.go
fixed the deadlock situation when a method that was mutex-protected was called inside a function that was already protected by the same mutex
=> [soft restart] fixed issue when checking core subcomponents

vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegation_test.go
- Fixed the situation when the TotalCumulatedRewards rewards did not contain the `claimRewards` value
=> Add claimRewards value to TotalCumulatedRewards

examples/messageSign_test.go
Added examples for message signing:
-> a test that confirms that the data obtained from the Ledger App is valid
-> a test that signs a message on behalf of a hardcoded address and prints the results
-> a test that verifies the signature for the above results
=> Message signing examples

dataRetriever/requestHandlers/requestHandler.go
Change log level to `trace` when requesting trie nodes from network. Otherwise, when syncing using epoch bootstrapper, this log would have appeared way to many times and the node was prone to remain unsynced.
=> changed log level when requesting trie nodes from network

integrationTests/multiShard/relayedTx/relayedTx_test.go, integrationTests/testProcessorNode.go, integrationTests/vm/esdt/esdtLocalFunsSC_test.go, integrationTests/vm/esdt/esdtMultisign_test.go, integrationTests/vm/esdt/esdtNFTSCs_test.go, integrationTests/vm/esdt/esdtNft_test.go, integrationTests/vm/esdt/esdtProcess_test.go, integrationTests/vm/esdt/esdtRoles_test.go, vm/systemSmartContracts/esdt.go, vm/systemSmartContracts/esdt_test.go
deleted all token list from esdt metachain system sc
=> Delete list from esdt

api/address/routes.go, cmd/node/config/api.toml, node/node.go, node/node_test.go
Formatted the NFT identifier in `/address/:address/esdt` endpoint. 
Now, if a token is regular esdt, the key for it would follow the syntax `TICKER-3e3e3e` and if it the token is a NFT, then it would follow the syntax `TICKER-3e3e3e-02` where `02` is the hex encoded nonce.
Before this PR, the token identifier for NFTs would have resulted in non readable characters
=> Formatted NFT identifier in api response

core/constants.go, process/smartContract/builtInFunctions/esdtLocalMint.go, process/smartContract/builtInFunctions/esdtLocalMint_test.go, vm/systemSmartContracts/esdt.go, vm/systemSmartContracts/esdt_test.go
prevents minting and issueing balance with over 100 bytes length
=> prevent too much mint

cmd/node/factory/structs.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, integrationTests/testProcessorNode.go, process/block/postprocess/basePostProcess.go, process/block/postprocess/intermediateResults.go, process/block/postprocess/intermediateResults_test.go, process/block/postprocess/oneMBPostProcessor.go, process/block/postprocess/oneMBPostProcessor_test.go, process/block/postprocess/testIntermediateResult.go, process/coordinator/process_test.go, process/factory/metachain/intermediateProcessorsContainerFactory.go, process/factory/metachain/intermediateProcessorsContainerFactory_test.go, process/factory/shard/intermediateProcessorsContainerFactory.go, process/factory/shard/intermediateProcessorsContainerFactory_test.go
* Fixed out of gas situation created by scrs generated in destination shard and added in one single mini block and sent back to the source shard
**How to be tested**
Repeat scenario in which there are unstaked many nodes, forcing meta to create a mini block with too many scrs, which would lead to a stuck situation in the initial source shard
After the scenario will be finished, search after message "basePostProcessor.splitMiniBlocksIfNeeded: gas limit exceeded". If this message will be found that means that a stuck situation was avoided, by splitting the resulted scrs mini block in more mini blocks each of them containing a limited number of txs, whose gas used is not exceed the max gas limit accepted per one mini block.
=> Fix stuck situation created by too many scrs generated in one single mini block

epochStart/metachain/economics.go, epochStart/metachain/economics_test.go
This PR adjusts the economic invariant to take into consideration the blocks unnotarized in a previous epoch that were notarized in the last epoch.
=> epochStart: adjust eoe economics invariant to consider carry blocks

core/converters.go, core/converters_test.go, factory/shardingFactory.go
Before this fix, if no destination shard as observer was set (so `DestinationShardAsObserver = "disabled"` in `prefs.toml`) then the "chosen" shard would have been `0`. In order to avoid this, a random (or at least one that isn't always `0`) shard should be generated.
Because the default `0` value was set in multiple instances, a deterministic algorithm for the same entry was needed. So, the last byte from the public key is divided by the number of shards, assigning the reminder to the shard ID.
=> Different default shard as observer

integrationTests/vm/esdt/esdtProcess_test.go, integrationTests/vm/esdt/esdtRoles_test.go, process/smartContract/builtInFunctions/esdtBurn_test.go, process/smartContract/builtInFunctions/esdtFreezeWipe_test.go, process/smartContract/builtInFunctions/esdtTransfer.go
=> Delete nil esdt data

cmd/node/factory/structs.go, epochStart/errors.go, epochStart/metachain/systemSCs.go, epochStart/metachain/systemSCs_test.go, integrationTests/testProcessorNode.go, vm/errors.go, vm/factory/systemSCFactory.go, vm/systemSmartContracts/esdt.go, vm/systemSmartContracts/esdt_test.go
- Fixed the ESDT bad initialization of the owner address. At the end of epoch, when the ESDT will be activated, the ESDT owner will be re-rewritten in the contract in the correct form. After that, some contract APIs like `configChange` will work as expected.
Testing scenario: launch a testnet, wait until ESDT feature becomes active (epoch 4) and try issue an ESDT with a base issuing value less than 5 eGLD. The transaction should fail. When trying to issue an ESDT with 5 eGLD, it should work. Use the `erd1fpkcgel4gcmh8zqqdt043yfcn5tyx8373kg6q2qmkxzu4dqamc0swts65c` address (pem file is located in elrond-go/cmd/node/testKeys/esdtWalletKey.pem) to send a transaction with the following parameters:
```
- sender: erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u
- value: 0 eGLD
- …
```
=> ESDT system SC correct initialization at end-of-epoch

cmd/node/main.go, core/converters.go, core/converters_test.go
different destination shard as an observer when no shard is specified. same as #2960 but targeted to `master` branch
- start an observer by using this branch
- if the key is not in consensus and the node will start as observer, it should be routed to a "random" shard. The same key in multiple tries should be routed to the same shard.
- try with multiple keys in order to see the shard balancing
=> balanced destination shard as observer

integrationTests/vm/esdt/esdtNFTSCs_test.go, integrationTests/vm/esdt/esdtNft_test.go, process/smartContract/builtInFunctions/esdtBurn.go, process/smartContract/builtInFunctions/esdtNFTTransfer.go, process/smartContract/builtInFunctions/esdtTransfer.go, process/smartContract/common.go, process/smartContract/process.go
fix nft transfer and execute from user to smart contract
=> fix nft transfer and execute from user to smart contract

go.mod, go.sum
arwen 1.2.6 release
This release fixes a possible cyclic import that involves the arwen and elrond-go repo through some mock implementation.
=> arwen 1.2.6

vm/systemSmartContracts/esdt.go, vm/systemSmartContracts/esdt_test.go
Added 3 missing fields in esdt `getTokenProperties` view function and extended the existing unit test.
Added a new view function `getSpecialRoles` that returns all the addresses and their roles for an ESDT.
Remove the entry for an address from `SpecialRoles` if no more role remains.
=> Additional fields in esdt getTokenProperties

integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, integrationTests/vm/esdt/nft/esdtNFTSCs_test.go, integrationTests/vm/esdt/process/esdtProcess_test.go, process/smartContract/builtInFunctions/esdtNFTTransfer.go, process/smartContract/builtInFunctions/esdtNFTTransfer_test.go, process/smartContract/builtInFunctions/esdtTransfer.go, process/smartContract/builtInFunctions/esdtTransfer_test.go, process/smartContract/builtInFunctions/factory.go, process/smartContract/process.go, process/smartContract/process_test.go
add the value to the destination if async callback fails
=> Fix transfer back asynccall

integrationTests/vm/esdt/common.go, integrationTests/vm/esdt/process/esdtProcess_test.go, process/block/postprocess/basePostProcess.go, process/block/preprocess/basePreProcess.go, process/block/preprocess/transactions.go
Limit miniblocks to shardlimit - no gasRefund on cross shard miniblock gas limit computation
=> Limit miniblocks to shardlimit

api/network/routes.go, api/network/routes_test.go, core/constants.go, data/api/apiBlock.go, node/trieIterators/commonStakingProcessor.go, node/trieIterators/directStakedListProcessor.go, node/trieIterators/directStakedListProcessor_test.go, node/trieIterators/stakeValuesProcessor.go, node/trieIterators/stakeValuesProcessor_test.go
- fixed staking processors for the API routes
Testing scenario: do a top-up stake on an existing node. The routes: `/network/economics` should return the  `erd_total_base_staked_value` value as a multiple of 2500 and `erd_total_top_up_value` the exact top-up-ed value. Next, the `/network/direct-staked-info` should return the correct value for that top-up-ed address (the `BaseStaked` should be a 2500 multiple, the `TopUp` should contain the top up value and the `Total` should be BaseStaked + TopUp)
=> Fixed staking processors for the API routes

consensus/broadcast/delayedBroadcast.go, consensus/broadcast/delayedBroadcast_test.go, process/interceptors/baseDataInterceptor.go
In case of miniblocks with transactions to be processed by metachain, validators in consensus groups were not monitoring the right topic in order to find when the agreed miniblocks were broadcast. 
This caused all consensus group validators to consider every shard to meta miniblocks not broadcast by leader and the other validators in consensus, and each of them trying to re-broadcast it on their slot.
TODO: move back the changed log to trace
=> consensus: monitor also shard-to-meta miniblocks topics for rebroadcast

cmd/node/config/gasSchedules/gasScheduleV1.toml, cmd/node/config/gasSchedules/gasScheduleV2.toml, cmd/node/config/gasSchedules/gasScheduleV3.toml, cmd/node/config/systemSmartContractsConfig.toml, cmd/node/factory/structs.go, config/systemSmartContractsConfig.go, process/factory/metachain/vmContainerFactory_test.go, process/scToProtocol/stakingToPeer.go, vm/factory/systemSCFactory.go, vm/gasCost.go, vm/interface.go, vm/mock/systemEIStub.go, vm/systemSmartContracts/defaults/gasMap.go, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegationManager.go, vm/systemSmartContracts/eei.go, vm/systemSmartContracts/staking.go, vm/systemSmartContracts/validator.go
The first part of the implementation of moving validators to delegation contracts. All being optional.
Implemented the first version where the owner makes a new contract and moves the data there.
=> En 9502/validator to delegation

cmd/node/config/systemSmartContractsConfig.toml, config/systemSmartContractsConfig.go, integrationTests/vm/testInitializer.go, integrationTests/vm/txsFee/validatorSC_test.go, vm/systemSmartContracts/validator.go, vm/systemSmartContracts/validator_test.go
- new implementation for unBondTokens as to circumvent found issue
Testing scenario that should happen in epochs 1-4 and should be carried on the `test-fix-unbond-tokens` branch:
1. stake one node in the queue with 2619 eGLD.
2. unstake 119 eGLD top up and check that you have to wait 3 epoch changes.
3. unstake 2500 eGLD from the node (direct from wallet, use the 3 dot button beside the BLS key)
4. finalize the withdraw of 2500 eGLD part, should get "no tokens that can be unbond at this time" error
Wait for epoch 4 that activates the new unBondTokens variant, repeat step 4, should unbond the 2500 value (after a total of 5 epochs between the first unstake, another unBond call should return also the last 119 eGLD).
repeat steps 1-3 with another key. Step 4 should not error, should return …
=> New unBondTokens implementation

api/mock/facade.go, api/network/routes.go, api/network/routes_test.go, cmd/node/config/api.toml, facade/interface.go, facade/mock/nodeStub.go, facade/nodeFacade.go, facade/nodeFacade_test.go, node/node.go, node/node_test.go
Added 3 new endpoints that return only tokens of a specific type:
- `/network/esdt/fungible-tokens`
- `/network/esdt/semi-fungible-tokens`
- `/network/esdt/non-fungible-tokens`
Also, kept the old `network/esdts` functionality due to backwards compatibility reasons.
- start a testnet and send transactions for issuing ESDTs, SFTs and NFTs
- check the endpoints:
- `/network/esdts` -> should contain all the issued tokens
- `/network/esdt/fungible-tokens` -> should contain only ESDT (fungible) tokens
- `/network/esdt/semi-fungible-tokens` -> should contain only semi fungible tokens
- `/network/esdt/non-fungible-tokens` -> should contain only non fungible tokens
=> new endpoints for esdt, sft and nft

data/api/apiBlock.go, node/blockAPI/metaBlock.go, node/blockAPI/metaBlock_test.go
Added in the API block  information about the epoch start block like:
- Total supply
- Total to distribute
- Total newly minted
- Previous epoch start block hash
=> Epoch start info meta block API

cmd/node/config/economics.toml, cmd/node/config/systemSmartContractsConfig.toml, config/economicsConfig.go, config/systemSmartContractsConfig.go, config/tomlConfig_test.go, vm/errors.go, vm/factory/systemSCFactory.go, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegationManager_test.go, vm/systemSmartContracts/delegation_test.go
- added redelegation dust check on the delegation system SC
- fixed some issues regarding ValidatorToDelegationEnableEpoch flags
- refactored economics.toml file
Testing scenario:
start with the `test-redelegate-dust-check` that will activate the feature in epoch 6.
In epoch 2 launch a delegation SC. In epoch 3, merge an existing validator into the delegation SC. 
Take 2 addresses (let's call them A and B), delegate a few egld on that delegation SC. 
In epochs 3-5 (whenever is possible), check rewards for address A. It should be in the interval (0, 1) eGLD. 
Undelegate everything. After that, do a redelegate. Now A just delegated some dust, which is not ok.
After epoch 6 activates the extra check, try the same with address B. Remember, claimable rewards should be up until 1eGLD. 
When B …
=> Re-delegate dust check

api/address/routes.go, api/address/routes_test.go, api/errors/errors.go, api/mock/facade.go, cmd/node/config/api.toml, core/computers.go, core/computers_test.go, facade/interface.go, facade/mock/nodeStub.go, facade/nodeFacade.go, facade/nodeFacade_test.go, integrationTests/interface.go, node/errors.go, node/node.go, node/node_test.go
Added 2 endpoints:
- `/address/<address>/esdts-with-role/<role>` that returns all token identifiers of the tokens where the given address has the given role assigned
- `/address/<address>/owned-nfts` that returns all token identifiers of the NFTs/SFTs where the given address is the owner
=> EN-9839: esdt tokens new endpoints

cmd/node/factory/structs.go, cmd/node/main.go, epochStart/metachain/systemSCs_test.go, genesis/process/metaGenesisBlockCreator.go, integrationTests/testProcessorNode.go, integrationTests/vm/delegation/delegation_test.go, integrationTests/vm/testInitializer.go, process/factory/metachain/vmContainerFactory.go, process/factory/metachain/vmContainerFactory_test.go, vm/errors.go, vm/factory/systemSCFactory.go, vm/factory/systemSCFactory_test.go, vm/mock/shardCoordinatorStub.go, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegationManager.go, vm/systemSmartContracts/delegationManager_test.go, vm/systemSmartContracts/delegation_test.go, vm/systemSmartContracts/staking_test.go, vm/systemSmartContracts/validator.go, vm/systemSmartContracts/validator_test.go
- changed message when a call to `makeNewContractFromValidatorData` is done from an address with 0 staked nodes
- added protection on `makeNewContractFromValidatorData` call as to not let the same validator to create more than one delegation SC
- added automatic clear whitelisted address feature and a view function for the current set whitelisted address for merge
- changed message when a call to `mergeValidatorToDelegationSameOwner` is done from an address that is not an owner in a delegation SC
- added extra protection when calling validator.changeRewardAddress function so a user can not set metachain addresses, jailing address or end of epoch address 
Testing scenario: 
start a testnet. Before epoch 3 do a staking transaction and then call the function …
=> Staking phase 3p5 minor changes

cmd/node/factory/interface.go, factory/block/errors.go, factory/block/headerVersionHandler.go, factory/block/headerVersionHandler_test.go, factory/block/metaHeaderFactory.go, factory/block/metaHeaderFactory_test.go, factory/block/shardHeaderFactory.go, factory/block/shardHeaderFactory_test.go, factory/bootstrapComponents.go, factory/interface.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithMultisigner.go, node/nodeBlocks_test.go, process/headerCheck/errors.go, process/headerCheck/headerIntegrityVerifier.go, process/headerCheck/headerIntegrityVerifier_test.go, testscommon/headerVersionHandlerMock.go, testscommon/headerVersionHandlerStub.go, testscommon/mainFactoryMocks/bootstrapComponentsStub.go
This PR implements a versioned header factory
=> cmd, process, factory, node, integrationTests: versioned header factory

data/trie/patriciaMerkleTrie.go, statusHandler/presenter/chainInfoGetters.go, vm/systemSmartContracts/delegationManager.go, vm/systemSmartContracts/delegationManager_test.go
- fixed 3 linter issues
testing scenario: try to do a `mergeValidatorToDelegationSameOwner` or `mergeValidatorToDelegationWithWhitelist` operation that will fail (the validator has unstaked/jailed nodes). The transaction should correctly be reported as a failed transaction.
=> Linter fixes

dataRetriever/factory/resolverscontainer/baseResolversContainerFactory.go, dataRetriever/factory/resolverscontainer/metaResolversContainerFactory.go, dataRetriever/factory/resolverscontainer/shardResolversContainerFactory.go, dataRetriever/resolvers/topicResolverSender/topicResolverSender.go, go.sum
Refactored target shard ID inside resolvers. Removed `defaultShardID` and used only the relevant shard ID. it will be used in the next PR for fetching a preferred peer for a given shard
=> Refactor target shard ID in resolvers

factory/processComponents.go, genesis/process/argGenesisBlockCreator.go, genesis/process/genesisBlockCreator_test.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, integrationTests/multiShard/hardFork/hardFork_test.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithStateCheckpointModulus.go
- fixed Arwen locker usage by having a different instance in the genesis process and thus, avoiding deadlock at genesis time
=> Arwen locker fix for genesis

dataRetriever/requestHandlers/requestHandler.go, genesis/process/disabled/requestHandler.go, process/errors.go, process/interceptors/export_test.go, process/interceptors/multiDataInterceptor.go, process/interceptors/multiDataInterceptor_test.go, process/interceptors/processor/chunk/chunk.go, process/interceptors/processor/chunk/chunk_test.go, process/interceptors/processor/trieNodeChunksProcessor.go, process/interceptors/processor/trieNodeChunksProcessor_test.go, process/interface.go, process/mock/chunkProcessorStub.go, testscommon/hasherStub.go, testscommon/requestHandlerStub.go
- added the trie nodes chunk processor. This processor is able to hold the completeness of a large trie nodes set and also is able to trigger requests for the missing parts.
=> Trie nodes chunk processor

process/factory/shard/vmContainerFactory.go
- fixed deadlock in vmContainerFactory.go
=> [Hot fix] - Fixed deadlock in vmContainerFactory.go

cmd/node/config/config.toml, go.mod, go.sum
- bump arwen version to 1.3.17
- removed arwen version switching in config.toml
=> Hotfix for Wasmer error leak and removed Arwen version switching

cmd/node/config/economics.toml, cmd/node/factory/structs.go, epochStart/metachain/rewardsCreatorProxy.go, epochStart/metachain/rewardsCreatorProxy_test.go, epochStart/metachain/rewardsV2.go, epochStart/metachain/rewardsV2_test.go, integrationTests/testProcessorNode.go
This PR activates the APR changes which failed to activate previously due to some duplicated code.
Duplicated code was removed and rewards computation uses the common handler which is aware of the changed parameters.
=> cmd, epochStart, integrationTests: fix failed activation

go.mod, go.sum
=> Fix upgradeContract() in Arwen

node/node.go, process/sync/argBootstrapper.go, process/sync/baseSync.go, process/sync/baseSync_test.go, process/sync/export_test.go, process/sync/metablock.go, process/sync/metablock_test.go, process/sync/shardblock.go, process/sync/shardblock_test.go
- added an exception to the block syncer as to always consider itself not synchronized in the import-db process
Testing scenario: in the normal operation, the network should behave normally, the WARN message `using always-not-synced status because the node is running in import-db` should not appear on any node. During the import-db operation, the above WARN message should appear and the node should not wait more that 10 rounds between epochs on the metachain.
When testing the import-db operation, the branch `test-always-not-synced-in-import-db` should be used.
=> Always-not-synced exception in block syncer during import-db operation

data/interface.go, data/state/accountsDB.go, data/state/accountsDB_test.go, data/state/peerAccountsDB.go, data/state/storagePruningManager/storagePruningManager_test.go, data/trie/branchNode.go, data/trie/branchNode_test.go, data/trie/extensionNode.go, data/trie/extensionNode_test.go, data/trie/interface.go, data/trie/leafNode.go, data/trie/node_test.go, data/trie/patriciaMerkleTrie.go, data/trie/patriciaMerkleTrie_test.go, data/trie/sync_test.go, data/trie/trieStorageManager.go, data/trie/trieStorageManagerWithoutPruning.go, data/trie/trieStorageManagerWithoutPruning_test.go, data/trie/trieStorageManager_test.go, storage/storageCacherAdapter/storageCacherAdapter.go, testscommon/storageManagerStub.go
On state checkpoint and snapshot, when traversing the main trie to verify what nodes need to be commited to the snapshot DB, return all leaves found on a channel, so that subsequent data tries can be commited directly, without another main trie traversing.
=> Refactor state snapshot

process/smartContract/builtInFunctions/esdtNFTCreate.go
Removed token type from log entry that is generated on the NFTCreate.
We cannot know the token type from shard perspective.
=> Remove token type from log entry

process/smartContract/hooks/blockChainHook.go
return same pointer if bytes are equal on load account
=> BlockChainHook return same pointer on LoadAccounts

go.mod, go.sum, process/smartContract/process.go, process/smartContract/process_test.go
Use latest commit from [arwen repository](https://github.com/ElrondNetwork/arwen-wasm-vm/commit/e03405ee6e0b63c9d2cf7da75c2cb06a4d94de73)
Use the latest release from [vm-common](https://github.com/ElrondNetwork/elrond-vm-common/releases/tag/v1.0.0) repository.
=> update arwen and vm-common

cmd/node/flags.go, data/trie/hashesHolder/checkpointHashesHolder.go, data/trie/hashesHolder/checkpointHashesHolder_test.go
- removed unnecessary import-db parameter override
- simplified checkpointHashesHolder.go implementation
=> Import-DB parameter override fix

node/nodeTransactions.go
- fixed merge error in nodeTransactions.go
The warning was:
```
DEBUG[2021-08-10 11:56:15.092]   bech32PubkeyConverter.Encode PkBytesLength hex buff =  error = wrong size stack trace = goroutine 23238 [running]:
runtime/debug.Stack(0x0, 0x36dbf80, 0x0)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/ElrondNetwork/elrond-go-core/core/pubkeyConverter.(*bech32PubkeyConverter).Encode(0xc00092d820, 0x0, 0x0, 0x0, 0x40, 0x20)
/home/ubuntu/go/pkg/mod/github.com/!elrond!network/elrond-go-core@v1.0.1-0.20210802100738-75f99b3e75a0/core/pubkeyConverter/bech32PubkeyConverter.go:88 +0x105
github.com/ElrondNetwork/elrond-go/node.(*Node).prepareUnsignedTx(0xc0166643c0, 0xc001fab7a0, 0xc001fab7a0, 0xc01f3ba790, 0xa6)
/home/ubuntu/go/src/github.com/ElrondNetwork/elrond-go/node/nodeTransactions …
```
=> Fixed merge error in nodeTransactions.go

README.md
The arwen binary is no longer built through `make arwen` as this command has been marked as deprecated and does not build arwen anymore.
I updated the readme to reflect this.
=> Readme arwen

integrationTests/testProcessorNode.go, integrationTests/vm/delegation/liquidStaking_test.go, testscommon/txDataBuilder/builder.go, vm/errors.go, vm/factory/systemSCFactory.go, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegation_test.go, vm/systemSmartContracts/eei.go, vm/systemSmartContracts/eei_test.go, vm/systemSmartContracts/esdt.go, vm/systemSmartContracts/esdt_test.go, vm/systemSmartContracts/liquidStaking.go, vm/systemSmartContracts/liquidStaking_test.go
Liquid staking unit tests
Liquid staking integration tests
=> Liquid staking unit and integration tests

state/syncer/userAccountsSyncer.go, trie/trieStorageManager.go
- fixed OOM exceptions by correctly closing all involved channels when performing snapshot/checkpoint. The fix introduce a new method that consumes all remaining entries in the process channels *after* the component has been successfully closed. This will make all snapshot/checkpoint go routines started in accountsDB.go to finish and eventually close.
- fixed OOM exceptions by correctly using the throttler inside the user accounts syncer as to not allow starting of a large number of go routines
=> Fixed OOMs 2021.08.31

api/errors/errors.go, api/groups/addressGroup.go, api/groups/addressGroup_test.go, api/groups/baseGroup.go, api/groups/blockGroup.go, api/groups/blockGroup_test.go, api/groups/common_test.go, api/groups/export_test.go, api/groups/hardforkGroup.go, api/groups/hardforkGroup_test.go, api/groups/networkGroup.go, api/groups/networkGroup_test.go, api/groups/nodeGroup.go, api/groups/nodeGroup_test.go, api/groups/proofGroup.go, api/groups/proofGroup_test.go, api/groups/transactionGroup.go, api/groups/transactionGroup_test.go, api/groups/validatorGroup.go, api/groups/validatorGroup_test.go, api/groups/vmValuesGroup.go, api/groups/vmValuesGroup_test.go, api/middleware/endpointThrottler.go, api/shared/interface.go, api/shared/shared.go
What has been done:
- refactored API routes handler: from exported, state-less functions to methods of structures;
- eliminate the `facade` that was set in gin's context -> instead, have it as a member in structures;
- copied and adapted all the endpoints and their unit tests.
What's left to do:
- integrate the new structures inside API starter;
- remove old routes handlers;
- integrate in nodeRunner the new version -> the gin server shouldn't be restarted anymore.
=> EN-10523: Web server refactoring

state/syncer/userAccountsSyncer.go
- fixed trie sync timeout false positive trigger by resetting the watchdog when the node builds up its list of data tries to be synced
=> Fix trie sync timeout when the node is building the list of data tries to be synced

integrationTests/consensus/testInitializer.go, integrationTests/testP2PNode.go, integrationTests/testProcessorNode.go, node/node.go, node/node_test.go, node/options.go, node/options_test.go
inside `node.go` -> use network sharding collector (peer mapper) from `processComponents` instead of direct field
=> refactor peer mapper in node.go

vm/systemSmartContracts/logs.go
Bugfix: Do not display `log.Warn` when delegator.ActiveFund is empty
=> fix logs delegation contract

api/gin/common_test.go, api/gin/webServer.go, facade/initial/disabledStatusMetrics.go, facade/initial/disabledStatusMetrics_test.go, facade/initial/initialNodeFacade.go, facade/initial/initialNodeFacade_test.go, node/nodeRunner.go
After merging `feat/web-server-refactor` - the pprof route was missing. This PR adds it back.
- start a testnet with the `--profile-mode` added to nodes
- `go tool pprof <node-ip>:<node-port>/debug/pprof/goroutine` - should work and not return 404 code
=> fix missing pprof endpoint

factory/processComponents.go, factory/processComponentsHandler_test.go
- fixed the node redundancy mechanism by providing a new private key
Testing scenario:
1. Start a new testnet, choose a validator node (we call this node A). Store its validatorKey.pem. 
2. Stop another node (doesn't matter the node - we will call it B). Provide it with the stored public key file (node's A key). 
3. Change the B's prefs.toml file, set the `RedundancyLevel` value to 1. 
4. Start the B node. Grep the log by the `broadcasting message heartbeat message` message. Should not use the public key from the provided file (should not broadcast A's public key), but a random BLS key (you can find this random key by grepping on `generated BLS private key for redundancy handler`).
5. Stop node A for ~30 rounds. Grep node B's log for `broadcasting message heartbeat message`, should find …
=> Fixed the node redundancy mechanism

cmd/node/main.go, p2p/libp2p/discovery/continuousKadDhtDiscoverer.go, p2p/libp2p/discovery/optimizedKadDhtDiscoverer.go
- fixed connect to seeders print
- added missing log print on node start error
Testing scenario:
1. build the node binary from `master` branch and run it in a new folder **without** the config folders. The node will close itself without printing any messages. Repeat the step from this branch: should see a log print error message.
2.a. run node (with configs) from `master` branch (no seeder, nothing else and log level `-log-level *:DEBUG`). You should see the log debug print `error connecting to seeder` (this is correct). 
2.b. Now, change in the p2p.toml file, place these seeders:
```
InitialPeerList = [
"/dns4/gondor.mainnet.elrond.com/tcp/10000/p2p/16Uiu2HAmQihd2Di6JrDCRf6bnxXEmgfFy8C3S7WDnq7WNXscfkrG",
"/dns4/isengard.mainnet.elrond.com/tcp/10000/p2p/16Uiu2HAkxWoEwkkxMfUgi2CkxjWkZ7cccjv …
```
=> Fixed connect to seeders print + main print

process/transaction/transactionCostEstimator.go, process/transaction/transactionCostEstimator_test.go
small improvement for the situation when the transaction to be estimated is a simple move balance
=> improve tx cost computation

cmd/node/flags.go
Previously, if the node was started as a full archive, the number of epochs to keep config value would have been overridden to Max uint64, which is not useful anymore, as now we have full history pruning storer. This solves the situation when a full archive node opens all the databases from the current epoch to genesis when starting the node.
1. start a testnet with some nodes (not all of them) being full archive (setting the `--full-archive` flag when starting or setting ` FullArchive = true` inside prefs.toml 
2. after a few epochs (let's say 10 epochs) restart a full archive node
3. check it's log and search for `initPersistersInEpoch` - epochs older than current epoch - 4 should not be observed in those log lines
4. repeat for more full archive nodes
=> Fix number of epochs to keep in case of full archive

go.mod, go.sum
Updated the elrond-vm-common module
The new version of the module contains a fix for an event that is generated on an ESDT NFT Transfer operation cross-shard
=> New vm-common fix event nft transfer

common/interface.go, dataRetriever/dataPool/currentBlockPool.go, dataRetriever/dataPool/currentBlockPool_test.go, dataRetriever/factory/dataPoolFactory.go, dataRetriever/factory/dataPoolFactory_test.go, epochStart/bootstrap/process.go, epochStart/bootstrap/process_test.go, epochStart/metachain/baseRewards.go, epochStart/metachain/systemSCs_test.go, factory/consensusComponents.go, factory/dataComponents.go, integrationTests/state/stateTrieSync/stateTrieSync_test.go, integrationTests/vm/delegation/delegationScenarios_test.go, state/syncer/baseAccountsSyncer.go, state/syncer/errors.go, state/syncer/userAccountsSyncer.go, storage/storageCacherAdapter/storageCacherAdapter.go, storage/storageCacherAdapter/storageCacherAdapter_test.go, testscommon/dataRetriever/poolFactory.go, testscommon/dataRetriever/poolsHolderMock.go, trie/baseTrieSync.go, trie/doubleListSync.go, trie/doubleListSync_test.go, trie/statistics/trieSyncStatistics.go, trie/statistics/trieSyncStatistics_test.go, trie/sync.go, trie/syncCreator.go, update/factory/accountDBSyncerContainerFactory.go, update/factory/exportHandlerFactory.go
- optimized trie nodes loading when searching in the missing hashes map
- added more info in the trie sync prints
- added data tries statistics when syncing the state
=> Trie sync fixes & optimizations

consensus/broadcast/delayedBroadcast_test.go, epochStart/bootstrap/shardStorageHandler.go, epochStart/bootstrap/shardStorageHandler_test.go
fixes the computation of pending miniblocks and processed miniblocks at start in epoch
Some details:
At start in epoch, the pending/processed miniblocks are computed out of the start of epoch metablock and used for bootstrapping and setting the tracker with the correct information.
In cases where there are partially processed Metablocks referenced in the start of epoch metablock for a shard, the miniblocks That were already processed are not set as processed.
One other fix, also for the pending miniblocks at bootstrap is that the shardID for the pending miniblocks was wrongly set to the sender shard instead of the receiver shard, although this does not have an effect, as the shard ID is not used afterwards.
=> epochStart: fix pending miniblocks computation at start in epoch

factory/coreComponents.go, factory/coreComponentsHandler.go, factory/interface.go, factory/mock/coreComponentsMock.go, integrationTests/mock/coreComponentsStub.go, integrationTests/testProcessorNode.go, integrationTests/vm/testInitializer.go, integrationTests/vm/txsFee/moveBalance_test.go, node/mock/factory/coreComponentsStub.go, node/node.go, node/nodeBlocks_test.go, process/economics/apiEconomicsData.go, process/economics/apiEconomicsData_test.go, process/economics/economicsData.go, process/economics/economicsData_test.go, process/errors.go
- removed backwards compatibility issue on transactions at interceptor level
- added protection on the API for transactions with higher gas limit than the transaction processor can cope
=> Backwards compatibility fix on tx interceptor for gaslimit value

cmd/node/config/enableEpochs.toml, config/epochConfig.go, config/tomlConfig_test.go, genesis/process/shardGenesisBlockCreator.go, node/nodeRunner.go, vm/systemSmartContracts/esdt.go, vm/systemSmartContracts/esdt_test.go
=> Transform to multi create

examples/address_test.go, factory/processComponents.go, genesis/dtos.go, genesis/interface.go, genesis/mock/txExecutionProcessorStub.go, genesis/parsing/accountsParser.go, genesis/parsing/accountsParser_test.go, genesis/process/genesisBlockCreator_test.go, genesis/process/intermediate/standardDelegationProcessor.go, genesis/process/intermediate/txExecutionProcessor.go, genesis/process/intermediate/txExecutionProcessor_test.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, integrationTests/state/genesisState/genesisState_test.go, node/nodeRunner.go
- fixes after review
- more unit tests
- set TxCount for genesis block header
=> Fixes after review - genesis indexing

state/peerAccountsDB.go, trie/snapshotTrieStorageManager.go, trie/trieStorageManager.go
Do not snapshot after start in epoch on peer trie. (this was done for the user trie on a previous PR)
=> Fix some trie prints on dev

factory/processComponents.go
Use a clone of the genesis header when changing it for indexing genesis data. Otherwise, an observer would have lost sync with the network
=> Fix genesis header changes

statusHandler/export_test.go, statusHandler/statusMetricsProvider.go, statusHandler/statusMetricsProvider_test.go
introduced rwmutexes for all operations done on status metrics component
also, changed from sync.Map to 3 regular maps as sync.Map's concurrency is not needed anymore as now we have a mutex for each operation
=> status metrics - concurrent operations

common/context.go, common/context_test.go, consensus/chronology/chronology.go, consensus/chronology/export_test.go, consensus/interface.go, consensus/mock/subroundHandlerMock.go, consensus/spos/bls/export_test.go, consensus/spos/bls/subroundBlock.go, consensus/spos/bls/subroundEndRound.go, consensus/spos/bls/subroundSignature.go, consensus/spos/bls/subroundStartRound.go, consensus/spos/subround.go, consensus/spos/subround_test.go, process/mock/syncStarterStub.go, process/sync/baseSync.go, process/sync/interface.go, process/sync/metablock.go, process/sync/metablock_test.go, process/sync/shardblock.go, process/sync/shardblock_test.go
- suppressed original processing errors when the node is shuffling between shards
=> No process error on shuffle out

cmd/node/config/config.toml, common/constants.go, state/syncer/userAccountsSyncer.go, state/syncer/validatorAccountsSyncer.go, trie/trieStorageManager.go
skip snapshot if trie was synced
=> Snapshot after sync fix

dataRetriever/chainStorer.go, dataRetriever/chainStorer_test.go, factory/processComponents.go, genesis/process/genesisBlockCreator.go, trie/trieStorageManager.go
- fixed error on genesis block save
- switched some prints to log level TRACE
=> Fixed error on genesis block save

factory/apiResolverFactory.go, factory/blockProcessorCreator.go, genesis/process/genesisBlockCreator.go, genesis/process/genesisBlockCreator_test.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, go.sum, process/block/shardblock.go, process/mock/accountWrapperMock.go, process/smartContract/hooks/blockChainHook.go, process/smartContract/hooks/blockChainHook_test.go, process/smartContract/hooks/export_test.go
- backwards compatibility fix by using old method of retrieving the ESDT token from the trie. The legacy function is tight to the `optimize nft metadata store` flag
- fixed the forgotten epoch configs flags on the blockchain hook implementation
=> Backwards compatibility fixes 2022.01.27

process/block/baseProcess_test.go, process/block/export_test.go, process/block/pendingMb/pendingMiniBlocks_test.go, process/block/preprocess/scheduledTxsExecution_test.go
Improve unit tests coverage in process/block:
- scheduled related stuff: in baseProcess and preprocess/ScheduledTxsExecution
- pendingMiniBlocks
=> Improve code coverage scheduled transactions

process/smartContract/hooks/blockChainHook.go
Replaced `log.LogIfError` -> `log.Debug` in `blockchainHook.go`
=> Fix blockchain hook error prints

state/accountsDB.go, state/accountsDB_test.go, state/peerAccountsDB.go, state/peerAccountsDB_test.go
When starting a node, if a snapshot is necessary, start the snapshoting process from the last snapshotRootHash that was not completed.
=> snapshot last rootHash after restart

heartbeat/errors.go, heartbeat/interface.go, heartbeat/mock/keyMock.go, heartbeat/mock/marshallerMock.go, heartbeat/mock/marshallerStub.go, heartbeat/mock/messengerStub.go, heartbeat/mock/peerSignatureHandlerStub.go, heartbeat/mock/senderHandlerStub.go, heartbeat/mock/timerHandlerStub.go, heartbeat/process/messageProcessor.go, heartbeat/process/messageProcessor_test.go, heartbeat/process/monitor.go, heartbeat/process/monitorEdgeCases_test.go, heartbeat/process/monitor_test.go, heartbeat/process/sender.go, heartbeat/process/sender_test.go, heartbeat/sender/interface.go, heartbeat/sender/peerAuthenticationSender.go, heartbeat/sender/peerAuthenticationSender_test.go, heartbeat/sender/routineHandler.go, heartbeat/sender/routineHandler_test.go, heartbeat/sender/timerWrapper.go, heartbeat/sender/timerWrapper_test.go, heartbeat/storage/heartbeatStorer.go, heartbeat/storage/heartbeatStorer_test.go, node/nodeTesting_test.go, p2p/p2p.go, testscommon/p2pmocks/messengerStub.go
- added peer authentication sender
- added routineHandler & timerWrapper sub-components
- renamed some interfaces, stub implementations and errors
=> Peer authentication sender

common/tokensParser.go, common/tokensParser_test.go
fix for "ExtractTokenIDAndNonceFromTokenStorageKey" when the nonce could have been represented as a hyphen when the key is converted to string. also, added more guards in regards to the ticker's min/max length + optimize by using `Index` instead of `Split`
=> fix tokensParser + more unit tests

factory/blockProcessorCreator.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, integrationTests/multiShard/relayedTx/common.go, integrationTests/testProcessorNode.go, process/block/baseProcess_test.go, process/coordinator/printDoubleTransactionsDetector.go, process/coordinator/printDoubleTransactionsDetector_test.go, process/coordinator/process.go, process/coordinator/process_test.go, process/errors.go, process/interceptors/baseDataInterceptor.go, process/interface.go, process/transaction/interceptedTransaction.go, process/transaction/interceptedTransaction_test.go, process/unsigned/interceptedUnsignedTransaction.go, process/unsigned/interceptedUnsignedTransaction_test.go, storage/txcache/txCache.go, storage/txcache/txListForSender.go, storage/txcache/txListForSender_test.go, testscommon/loggerStub.go, testscommon/panicDoubleTransactionsDetector.go
- minor fix in tx cache transaction selection & adding a critical section
- fixed some prints in the intercepted data implementations
- added double transactions detector
=> Double transactions detector & tx cache fixes

common/logging/fileLogging_test.go, epochStart/metachain/systemSCs_test.go, go.mod, integrationTests/longTests/storage/storagePutRemove_test.go, integrationTests/multiShard/hardFork/hardFork_test.go, integrationTests/state/stateTrieSync/stateTrieSync_test.go, storage/factory/directoryhandler/directoryReader_test.go, storage/leveldb/leveldbSerial_test.go, storage/leveldb/leveldb_test.go, storage/pruning/fullHistoryPruningStorer_test.go, storage/pruning/pruningStorer_test.go, storage/storageUnit/storageunit_test.go, trie/doubleListSync_test.go, trie/interceptedNode_test.go, trie/iterator_test.go, trie/patriciaMerkleTrie_test.go, trie/trieStorageManager_test.go, update/genesis/export_test.go, update/trigger/importStartHandler_test.go
A testing enhancement.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
**Note:** `T.TempDir` requires Go 1.15 or higher, hence the `go` directive in `go.mod` is bumped to `1.15`.
Reference: https://pkg.go.dev/testing#T.TempDir
=> test: use `T.TempDir` to create temporary test directory

node/external/transactionAPI/apiTransactionResults.go, node/external/transactionAPI/apiTransactionResults_test.go
- Fix the check there is set `sender` and `receiver` address for smart contract results
=> FIX block API

common/channels.go, common/channels_test.go, factory/apiResolverFactory.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithStateCheckpointModulus.go, integrationTests/testSyncNode.go, integrationTests/vm/arwen/utils.go, integrationTests/vm/mockVM/vmGet/vmGet_test.go, integrationTests/vm/testInitializer.go, node/nodeRunner.go, process/errors.go, process/smartContract/scQueryService.go, process/smartContract/scQueryService_test.go
temporary improvement for observers that have struggles syncing with the network after a restart when multiple VM Query API calls occur.
=> block VM Queries API calls right after node starts

api/groups/addressGroup.go, api/groups/addressGroup_test.go
When calling node's API for fetching tokens data, the properties are now exported as hex instead of plain string, in order to avoid non readable characters
=> [esdt api] export token's properties as hex

factory/statusComponentsHandler.go, node/nodeHelper.go
Changed closable components order on close: set network components to be closed at first, so that network traffic will not be initiated while data and state components are still active.
Added nil checks for status handler goroutine which will try to fetch network components metric:
- nil check for network messenger component
=> Close network components first

dblookupext/esdtSupply/esdtSuppliesProcessor_test.go, dblookupext/esdtSupply/logsProcessor.go
Fixed the situation when the initial quantity wasn't added as minted value as well for the ESDT supply endpoint 
+ added unit test to confirm the behaviour
=> [esdt supply api] set minted for create

api/groups/networkGroup.go, api/groups/networkGroup_test.go, cmd/node/config/api.toml
Rename `network/genesisnodes` endpoint to `network/genesis-nodes`
=> Rename network/genesisnodes to network/genesis-nodes

factory/mock/blockTrackerStub.go, genesis/process/disabled/blockTracker.go, go.mod, go.sum, integrationTests/mock/blockTrackerStub.go, node/mock/blockTrackerStub.go, process/block/preprocess/interfaces.go, process/block/preprocess/transactions.go, process/constants.go, process/interface.go, process/mock/blockTrackerMock.go, process/sync/baseSync.go, process/sync/baseSync_test.go, process/track/baseBlockTrack.go, process/track/shardBlockTrack.go, testscommon/headerHandlerStub.go
This PR adds another layer of protection for stuck shard extreme scenarios.
In case there are a lot of cross shard transactions for one shard, the previous condition was not sufficient to allow the shard to catch up with processing the metachain blocks. 
To ensure the recovery, another condition was added to stop all shard originating transactions while the pending miniblocks or delta metachain block nonces are above a new defined threshold.
=> process: add global shard stuck condition for chain recovery

cmd/node/config/config.toml, config/config.go, config/tomlConfig_test.go, go.mod, go.sum, process/factory/shard/vmContainerFactory.go
=> integrate new vm parameters

cmd/node/config/config.toml, process/constants.go
- miniblocks cache size tweak
- higher timeout duration for transactions & miniblocks before they are cleaned from pool
=> Miniblocks cache size tweak

process/block/baseProcess.go, process/sync/baseForkDetector.go, process/sync/baseForkDetector_test.go
* Fixed cleanup of notarized headers from block tracker (now is done behind the previous final block nonce)
=> Fix cleanup notarized header in block tracker

cmd/node/config/config.toml, cmd/node/factory/interface.go, cmd/node/main.go, cmd/seednode/config/config.toml, cmd/seednode/main.go, common/logging/errors.go, common/logging/fileLogging.go, common/logging/fileLogging_test.go, common/logging/lifeSpanner.go, common/logging/lifeSpanner_test.go, config/config.go
- implemented log life spanner for file size
=> Log life spanner for file size

facade/nodeFacade.go, facade/nodeFacade_test.go
fixed the situation when VM queries that generate logs didn't return anything + added unit test that covers the entire conversion function
=> Fix for vm query api logs

.github/workflows/golangci-lint.yml, cmd/node/config/config.toml, cmd/node/config/economics.toml, cmd/node/config/enableEpochs.toml, config/config.go, dataRetriever/factory/dataPoolFactory.go, dataRetriever/factory/dataPoolFactory_test.go, epochStart/bootstrap/shardStorageHandler.go, epochStart/bootstrap/shardStorageHandler_test.go, epochStart/bootstrap/startInEpochScheduled.go, epochStart/bootstrap/startInEpochScheduled_test.go, go.mod, go.sum, process/block/preprocess/miniBlockBuilder.go, process/block/preprocess/scheduledTxsExecution.go, process/block/preprocess/scheduledTxsExecution_test.go, process/block/preprocess/transactions.go, process/block/preprocess/transactions_test.go, process/smartContract/process.go, storage/disabled/persister.go, storage/disabled/persister_test.go, testscommon/genericMocks/chainStorerMock.go, testscommon/shardedDataCacheNotifierMock.go, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/logs.go, vm/systemSmartContracts/logs_test.go
* Fixed setting of processed mini blocks in start in epoch component, when scheduled is activated and it should roll back to previous header of the last notarized header
=> Fix partial mini blocks execution

integrationTests/vm/delegation/liquidStaking_test.go, state/validatorsInfoMap_test.go, vm/mock/systemEIStub.go, vm/systemSmartContracts/liquidStaking.go
Fixed linter errors on `feat/liquid-staking`:
- ineffectual assignment to `nonce`, `round` in `liquidStaking_test.go`
- ineffectual assignment to `validators` in `validatorsInfoMap_test.go`
- redundant `return` in `systemEIStub.go`
- unused `sigVerifier` in `liquidStaking.go`
=> FIX: Linter errors

api/groups/transactionGroup.go, api/groups/transactionGroup_test.go, api/mock/facadeStub.go, api/shared/interface.go, cmd/node/config/api.toml, common/dtos.go, dataRetriever/interface.go, dataRetriever/shardedData/shardedData.go, dataRetriever/shardedData/shardedData_test.go, dataRetriever/txpool/shardedTxPool.go, dataRetriever/txpool/shardedTxPool_test.go, facade/initial/initialNodeFacade.go, facade/initial/initialNodeFacade_test.go, facade/interface.go, facade/mock/apiResolverStub.go, facade/nodeFacade.go, facade/nodeFacade_test.go, integrationTests/interface.go, node/external/interface.go, node/external/nodeApiResolver.go, node/external/nodeApiResolver_test.go, node/external/transactionAPI/apiTransactionProcessor.go, node/external/transactionAPI/apiTransactionProcessor_test.go, node/mock/apiTransactionHandlerStub.go, testscommon/shardedDataCacheNotifierMock.go, testscommon/shardedDataStub.go
added a new API endpoint GET `/transaction/pool` that returns the txs hashes for regular transactions, smart contract results or rewards txs
=> transactions pool API endpoint

cmd/node/config/enableEpochs.toml, config/epochConfig.go, factory/apiResolverFactory.go, factory/blockProcessorCreator.go, genesis/process/shardGenesisBlockCreator.go, go.mod, go.sum, integrationTests/vm/esdt/nft/esdtNft_test.go, node/nodeRunner.go, process/smartContract/builtInFunctions/factory.go
=> fix-transferRole-check-on-esdtTransfer

process/smartContract/process.go, process/smartContract/process_test.go
- Fix the order in how the logs are generated. 
- The logs generated by a built-in function with a smart contract call were put last instead of first.
=> Fix logs order

epochStart/bootstrap/process.go, node/metrics/metrics.go, node/metrics/metrics_test.go, process/sync/loadPersistentMetrics.go, statusHandler/persister/persistentHandler.go
fixed round at epoch start and nonce at epoch start metrics.
=> fixed epoch start metrics

cmd/node/config/config.toml, config/config.go, config/tomlConfig_test.go, factory/apiResolverFactory.go, process/smartContract/scQueryService.go, process/smartContract/scQueryService_test.go
extracted the maximum gas limit to be used for vm queries inside config.toml
=> extracted max gas limit for vm query to config

cmd/node/flags.go
Called `runtime.SetMutexProfileFraction(...)` if the profiling mode is enabled. This allows developers taking mutex profiles while running the node.
=> add mutex profiling support

integrationTests/testProcessorNode.go, integrationTests/vm/delegation/liquidStaking_test.go, process/coordinator/process.go
- Fixed sync time by increasing `time.Sleep` period
- Fixed more activation flags
=> Fix latency unit test

epochStart/bootstrap/shardStorageHandler_test.go
the `getProcessedMiniBlocks` function uses a map inside, which can result in the test failing from time to time. fixed by checking the order before asserting
=> fixed Test_getProcessedMiniBlocks that failed from time to time

process/coordinator/process.go, process/coordinator/process_test.go
- fixed init call on transaction coordinator when processing a new miniblock
- removed some weak warnings
=> Fixed the init call in transaction coordinator

common/interface.go, integrationTests/state/stateTrieClose/stateTrieClose_test.go, node/interface.go, node/nodeRunner.go, process/interceptors/baseDataInterceptor.go, state/syncer/baseAccountsSyncer.go, trie/doubleListSync.go, trie/statistics/trieSyncStatistics.go, trie/statistics/trieSyncStatistics_test.go
- started the health service as the first step when creating a node
- fixed one integration test
- added mutex protection in interceptors
- added more metrics in the trie syncer
=> Nil pointer dereference panic fix 

factory/apiResolverFactory.go, factory/blockProcessorCreator.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithTestWebServer.go, integrationTests/vm/arwen/arwenvm/arwenVM_test.go, integrationTests/vm/arwen/utils.go, integrationTests/vm/testInitializer.go, process/coordinator/transactionType.go, process/coordinator/transactionType_test.go, process/transaction/metaProcess_test.go, process/transaction/shardProcess_test.go
- `isRelayedTransactionV2` does not check the flag anymore, only returns if the transaction is of type `RelayedTxV2` and the flag check is done on `processRelayedTxV2`. With this check on, `ComputeTransactionType` returns type `MoveBalance` for a `RelayedTxV2` with the flag disabled.
=> Fix isRelayedTransactionV2

factory/apiResolverFactory.go, factory/blockProcessorCreator.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, go.mod, go.sum, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithTestWebServer.go, integrationTests/vm/arwen/arwenvm/arwenVM_test.go, integrationTests/vm/arwen/utils.go, integrationTests/vm/testInitializer.go, node/external/transactionAPI/apiTransactionArgs.go, node/external/transactionAPI/apiTransactionProcessor.go, node/external/transactionAPI/apiTransactionProcessor_test.go, node/external/transactionAPI/apiTransactionResults.go, node/external/transactionAPI/apiTransactionResults_test.go, node/external/transactionAPI/check.go, node/external/transactionAPI/errors.go, node/external/transactionAPI/interface.go, node/external/transactionAPI/unmarshaller.go, process/coordinator/transactionType.go, process/coordinator/transactionType_test.go, process/transaction/metaProcess_test.go, process/transaction/shardProcess_test.go, testscommon/dataFieldParserStub.go
- Merge dev into liquid staking 16 06 2022
=> Merge dev into liquid staking 16 06 2022

factory/apiResolverFactory_test.go, factory/blockProcessorCreator_test.go, factory/bootstrapComponentsHandler_test.go, factory/bootstrapComponents_test.go, factory/consensusComponentsHandler_test.go, factory/consensusComponents_test.go, factory/coreComponentsHandler_test.go, factory/coreComponents_test.go, factory/cryptoComponentsHandler_test.go, factory/cryptoComponents_test.go, factory/dataComponentsHandler_test.go, factory/dataComponents_test.go, factory/heartbeatComponentsHandler_test.go, factory/heartbeatComponents_test.go, factory/networkComponentsHandler_test.go, factory/networkComponents_test.go, factory/processComponentsHandler_test.go, factory/processComponents_test.go, factory/stateComponentsHandler_test.go, factory/stateComponents_test.go, factory/statusComponentsHandler_test.go, factory/statusComponents_test.go
- fixed `factory` package unit tests by skipping them when ran with `-race -short` flags
=> Fixed `factory` unit tests

process/block/baseProcess.go
* Updated self to self intermediate mini block after scheduled execution. Needed to be saved into storage to resolve some requests only by some APIs, not needed by the protocol which always recreates it by the time of block execution. (these mini blocks are also deleted from body as they are self to self receipts or scrs)
=> Update self to self intermediate mini block after scheduled execution

consensus/spos/bls/export_test.go, consensus/spos/bls/subroundEndRound.go, consensus/spos/bls/subroundEndRound_test.go, consensus/spos/bls/subroundSignature.go, consensus/spos/bls/subroundSignature_test.go, consensus/spos/errors.go, testscommon/cryptoMocks/multisignerMock.go
Optimistic signature aggregation on consensus:
- the consensus nodes will not verify signature share anymore, since the leader will verify the aggregated signature anyway
- if the agg sig verifcation fail, the leader will check every signature share for each node, and if the number of valid signature shares will be higher than the threshold, it will send the partial agg signature
- unit tests
=> Optimistic signature aggregation by leader

api/groups/transactionGroup.go, api/groups/transactionGroup_test.go, api/mock/facadeStub.go, api/shared/interface.go, cmd/node/config/api.toml, dataRetriever/txpool/interface.go, facade/initial/initialNodeFacade.go, facade/initial/initialNodeFacade_test.go, facade/interface.go, facade/mock/apiResolverStub.go, facade/nodeFacade.go, facade/nodeFacade_test.go, integrationTests/interface.go, integrationTests/testProcessorNodeWithTestWebServer.go, node/external/interface.go, node/external/nodeApiResolver.go, node/external/nodeApiResolver_test.go, node/external/transactionAPI/apiTransactionProcessor.go, node/external/transactionAPI/apiTransactionProcessor_test.go, node/external/transactionAPI/errors.go, node/mock/apiTransactionHandlerStub.go, storage/txcache/crossTxCache.go, storage/txcache/crossTxCache_test.go, storage/txcache/disabledCache.go, storage/txcache/txCache.go, storage/txcache/txCache_test.go
- added new endpoint `/pool/by-sender/last-nonce/:sender` for the last nonce in tx pool for sender
- small refactor on recently added logic on `apiTransactionProcessor.go` in order to reduce duplicate code
---
In order to test the changes, the following steps are needed:
1. start a local testnet with this branch
2. clone `elrond-txgen-go` and update the following:
- in `cmd/txgen/config/config.toml`, leave `Scenarios = ["badNonce"]`, update `ProxyServerURL` with the port that your local proxy uses, optional update `MintingValue` to a smaller one
- copy from the newly generated `node/config/walletKey.pem`(local testnet) one of the private keys and paste it into `cmd/txgen/config`
4. start txgen `./txgen --new-account --num-accounts 10`
5. run ./scripts/badNonce.sh
6. make a Get request to …
=> Last nonce in pool for sender endpoint

go.mod, go.sum, node/external/blockAPI/baseBlock.go, node/external/blockAPI/baseBlock_test.go, node/external/blockAPI/metaBlock.go, node/external/blockAPI/shardBlock.go
On API, inform clients when the miniblock was loaded from the receipts storage (as opposed to being loaded from the block body).
=> On API, populate field "miniblock.isFromReceiptsStorage".

api/groups/transactionGroup.go, api/groups/transactionGroup_test.go, api/mock/facadeStub.go, api/shared/interface.go, cmd/node/config/api.toml, common/dtos.go, dataRetriever/txpool/interface.go, facade/initial/initialNodeFacade.go, facade/interface.go, facade/mock/apiResolverStub.go, facade/nodeFacade.go, facade/nodeFacade_test.go, integrationTests/interface.go, integrationTests/testProcessorNodeWithTestWebServer.go, node/external/interface.go, node/external/nodeApiResolver.go, node/external/nodeApiResolver_test.go, node/external/transactionAPI/apiTransactionProcessor.go, node/external/transactionAPI/apiTransactionProcessor_test.go, node/mock/apiTransactionHandlerStub.go, storage/txcache/crossTxCache.go, storage/txcache/crossTxCache_test.go, storage/txcache/disabledCache.go, storage/txcache/disabledCache_test.go, storage/txcache/txCache.go, storage/txcache/txCache_test.go
- added new endpoint for nonce gaps by sender `"/pool/by-sender/nonce-gaps/:sender"`
- small refactor to remove code duplicate + for further improvements. Now `txCache` returns a slice of entire wrapped transactions which have all the info needed(hashes, nonces, etc)
- now received wrapped txs from all txCaches are merged and sorted on `apiTransactionProcessor`
---
In order to test the changes, the following steps are needed:
1. start a local testnet with this branch
2. clone `elrond-txgen-go` and update the following:
- in `cmd/txgen/config/config.toml`, leave `Scenarios = ["badNonce"]`, update `ProxyServerURL` with the port that your local proxy uses, optional update `MintingValue` to a smaller one
- copy from the newly generated `node/config/walletKey.pem`(local testnet) one of the …
=> Nonce gaps endpoint

api/groups/blockGroup.go, api/groups/internalGroup.go, api/groups/networkGroup.go, api/shared/logging/logging.go, node/external/blockAPI/baseBlock.go
before this PR, all durations of certain API actions would have been logged. this PR unifies the logging via a single function which only logs if the duration is above a threshold
=> improve api call actions logs

.github/workflows/create_release.yml
On github workflow for create release, sleep 10 seconds between creating the tag and uploading the artifacts.
=> Fix github workflow for create release

cmd/node/CLI.md, cmd/node/flags.go, config/contextFlagsConfig.go, factory/cryptoComponents.go, factory/cryptoComponents_test.go, node/nodeRunner.go
- Added an extra flag `no-key` and if set, the node will generate at the start a new BLS key
- With this flag enabled a file with a BLS key will be no longer required
=> Generate bls key flag

node/external/transactionAPI/apiTransactionProcessor.go, node/external/transactionAPI/apiTransactionProcessor_test.go
in case no tx is found in the pool for a sender, return an empty slice instead of an error.
not applicable for `last nonce` because `0` would be confusing (`0` vs `null`)
=> return empty list if sender is not found in pool for sender

go.mod, go.sum
- Fixed unnecessary `log.Warn` (elastic indexer)
=> Fix indexer warn logs

heartbeat/sender/routineHandler.go, heartbeat/sender/routineHandler_test.go
Fixed the heartbeat v2 integration with the hardfork trigger by adding an extra blocking time.sleep when the trigger is activated. This will prevent the continuous re-entry on the `Execute` function which will raise havoc at the p2p level (high amount of messages sent)
=> [FIX]Heartbeat v2 integration with the hardfork trigger

state/accountsDB.go, state/accountsDB_test.go, state/peerAccountsDB_test.go
If a snapshot finished successfully, remove lastSnapshotStarted from storage in order to prevent a new snapshot for the same rootHash if the node restarts.
=> Remove lastSnapshotStarted if the snapshot finished successfully

.github/release.yml
- Need an automated way of generating categorized release notes
- use the built-in feature from github.com -> https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
- use proper labels and expect headings : 
1. Breaking Changes(for _type:breaking-change label_),
2. Bugfixes(for _type:bug_ label),
3. New Features(for _type:feature_ label),
4. Improvements(for _type:improvement_ & _type:performance_ label),
5. We care about documentation ( for _type:docs_ label).
PR's labeled _ignore-for-release_ should not be enumerated in the generated Release Note.
=> Customized automated release note

dataRetriever/factory/storageResolversContainer/baseResolversContainerFactory.go, dataRetriever/factory/storageResolversContainer/metaResolversContainerFactory.go, dataRetriever/factory/storageResolversContainer/metaResolversContainerFactory_test.go, dataRetriever/factory/storageResolversContainer/shardResolversContainerFactory.go, dataRetriever/factory/storageResolversContainer/shardResolversContainerFactory_test.go, dataRetriever/resolvers/disabled/peerAuthenticationResolver.go, dataRetriever/resolvers/disabled/peerAuthenticatorResolver_test.go
- added a disabled peer authentication resolver when the node is running in import-db mode to avoid the benign error messages like:
```
ERROR[2022-07-26 13:51:57.318]   RequestPeerAuthenticationsChunk.MetaChainResolver error = element does not exist in container in resolvers container for key peerAuthentication topic = peerAuthentication shard = 0 chunk = 13 epoch = 301
```
- added a new disabled resolver in order to avoid the error signaled by the requestHandler component 
- standard internal testnet procedure and re-run the import-db process and validate that the aforementioned error does not appear
=> [FIX]Added a disabled peer authentication resolver in import-db mode

epochStart/metachain/epochStartData.go, epochStart/metachain/epochStartData_test.go, factory/blockProcessorCreator.go, process/block/baseProcess.go
- backwards compatibility for the partialExecution on the meta epochStartData
- added MiniBlockPartialExecutionEnableEpoch to epochStartData to take partialExecution enableEpooch into consideration
- import-db should work now
=> added backwardsCompatibility for partialExecution on epochStartData

epochStart/metachain/epochStartData.go, state/accountsDB.go, state/accountsDB_test.go, state/peerAccountsDB.go, state/peerAccountsDB_test.go
- there was a bug in the import-db process if we have used the old version of DBs that did not contain the `ActiveDB` marker. The versions <=1.3.36 did not care about it as it would have re-written anyway that marker and the snapshotting process worked as expected. With the rc/2022-july branch, a new condition appeared as to write the marker only on epoch 0;
- some prints regarding the wrong epoch data were not in line with the rest of the project, refactored the prints for better debugging experience.
- add a composed condition in which, we take for granted in `import-db` process that the DB is correctly constructed as to reuse the old trie databases.
- `import-db` process should work as expected, without ERRORs or WARNs;
- internal testing scenarios should work.
=> Fixed import-db

storage/pruning/triePruningStorer.go, storage/pruning/triePruningStorer_test.go
- The pruning storer will keep only 3 db's open. When a snapshot takes longer than an epoch, it will close a db that is needed. To fix this case, always keep a minimum of 2 db's that are marked as active, opened.
-  Modify `minNumOfActiveDBsNecessary` from 1 to 2
- Add a time.Sleep() on Snapshot(), so that it will take more than 1 epoch, and check that the storer life was extended. After the snapshot is completed, verify that the correct db's are closed - (already tested this case)
=> Always keep a minimum of 2 active dbs open

cmd/node/flags.go
- there was a bug when the node ran in import-db that automatically reset the flag `SnapshotsEnabled` causing the node to not start due to the fact it didn't found the main trie data
- remove the auto-reset operation in import-db mode
- import-db process should work when starting on a non-zero epoch and regular system test should pass
=> Fix flag in import-db

process/block/shardblock.go
- If pruning was disabled, the snapshotting process was automatically disabled. Snapshotting is needed to copy from an older db to a new one (because db pruning is enabled even if trie pruning is disabled)
- Snapshot the state even if trie pruning is disabled
- Test with `AccountsStatePruningEnabled = false` and with `AccountsStatePruningEnabled = true` and both scenarios should work
=> Enable snapshot even if pruning is disabled

.github/release.yml
- previously named `ignore-for-release` label was changed to `ignore-for-release-notes` to remove any confusion with regards to the scope of the PR
- change the name of the label
- automatically generate a release note and check if PR's are  distributed to proper chapter.
=> change label name to ignore-for-release-notes

cmd/node/config/config.toml, heartbeat/sender/baseSender.go, heartbeat/sender/baseSender_test.go, heartbeat/sender/heartbeatSender.go, heartbeat/sender/peerAuthenticationSender.go
- time between hardfork messages is too low at 10 seconds
- increase the time to 1 min and use a random component to avoid always having exactly 1 min
- system test
=> Increased HardforkTimeBetweenSendsInSec to 1 minute

process/sync/metablock.go, process/sync/shardblock.go
- When the node is closing, the sync block will fail because it can not get from storage, so it starts a state sync process. 
- If the node is closing, do not start the state sync process
- We should not have any `base sync: started syncUserAccountsState` WARNs
=> Do not start state sync if the node is closing

cmd/node/config/enableEpochs.toml, common/enablers/enableEpochsHandler.go, common/enablers/epochFlags.go, common/interface.go, config/epochConfig.go, config/tomlConfig_test.go, integrationTests/vm/delegation/delegationScenarios_test.go, node/nodeRunner.go, process/factory/metachain/vmContainerFactory.go, sharding/mock/enableEpochsHandlerMock.go, testscommon/enableEpochsHandlerStub.go, vm/errors.go, vm/systemSmartContracts/delegationManager_test.go, vm/systemSmartContracts/delegation_test.go, vm/systemSmartContracts/eei.go, vm/systemSmartContracts/eei_test.go, vm/systemSmartContracts/esdt_test.go, vm/systemSmartContracts/stakingWithWaiting_test.go, vm/systemSmartContracts/staking_test.go, vm/systemSmartContracts/validator_test.go
=> Merge dev into feat refactor peers mbs 19.08.2022

cmd/node/config/config.toml, epochStart/shardchain/trigger.go, process/block/baseProcess.go, process/sync/baseSync.go, process/sync/metablock.go, process/sync/shardblock.go, sharding/nodesCoordinator/indexHashedNodesCoordinator.go, storage/leveldb/leveldb.go, storage/leveldb/leveldbSerial.go
- added more prints in the level DB constructors
- handled some log.Warn and log.Error prints when encountering the `DB is closed` error
- health records parameters adjustments
- added prints to determine how much time it takes for the constructor to finish
- added better handling
- standard internal testnets procedure
=> Prints fixes for rc/2022-july

cmd/node/config/prefs.toml, config/prefsConfig.go, keysManagement/errors.go, keysManagement/keysHolder.go, keysManagement/keysHolder_test.go, keysManagement/peerInfo.go
- integrate changes on prefs config, which now provides identities that runs nodes on the multisig
- extend `peerInfo` structure to hold node name and identity as well
- use bls keys + name and identity from prefs config on `keysHolder`
- system test
=> Integrate named identities

factory/heartbeatV2Components.go, heartbeat/processor/directConnectionsProcessor.go, heartbeat/processor/directConnectionsProcessor_test.go, heartbeat/processor/export_test.go, heartbeat/processor/interface.go, integrationTests/node/heartbeat/heartbeat_test.go, integrationTests/node/heartbeatV2/heartbeatV2_test.go, integrationTests/p2p/networkSharding-hbv2/networkSharding_test.go, integrationTests/testHeartbeatNode.go, process/errors.go
- Fixed the direct connection processor to not continuously send messages to the connected peers
- clean the map only after notifying the new peers and then insert all connected peers so in case of no connected peers changes we won't resend the messages.
- standard testing procedure should reveal problems (continuously resend) if the test is carried with the log level `*:DEBUG,heartbeat/processor:TRACE`. If ran with this branch the sending will be done only on new connected peers.
=> Fix direct connections processor

storage/factory/pruningStorerFactory.go, storage/storageUnit/storageunit.go
- if a persister could have not been created (for example, when extra tweaking the configuration and the system's ulimit was too low), all the opened DBs would have been destroyed, which should only be valid if the databases are created (not opened)
- remove the code block that called `DestroyUnit()`
- specific scenario already tested and validated
- these changes don't affect other storage operations
=> remove destroy persisters calls

go.mod, go.sum, integrationTests/vm/txsFee/utils/utilsESDT.go
- the current vm-common has some issues with the auto liquidity removal
- reference a version with fixes
- liquidity should be removed accordingly
=> Auto liquidity cleanup fixes

api/errors/errors.go, api/groups/addressGroup.go, api/groups/addressGroup_test.go, api/mock/facadeStub.go, api/shared/interface.go, cmd/node/config/api.toml, facade/initial/initialNodeFacade.go, facade/initial/initialNodeFacade_test.go, facade/interface.go, facade/mock/nodeStub.go, facade/nodeFacade.go, facade/nodeFacade_test.go, go.mod, go.sum, integrationTests/interface.go, node/export_test.go, node/node.go, node/node_test.go, process/guardian/disabled/disabledGuardedAccount.go, process/guardian/guardedAccount.go, process/guardian/guardedAccount_test.go, process/interface.go, testscommon/guardianMocks/guardianAccountHandlerStub.go
This PR adds a rest API for getting the guardian data of an address
The guardianData returned on the API will give several useful information such as
- the active guardian (bech32 if any) and its activation epoch
- the pending guardian (bech32 if any) and its activation epoch
- frozen state of the account - bool
- add guardian on an account and use the API to check the guardian data (one pending guardian)
- wait the expected time for the guardian to become active, then use the API to check the guardian data is as expected (one active guardian)
- add another guardian and use the API to check the guardian data (one active one pending)
- set account in frozen state then check the guardian data (one active guardian, the pending was cleared by freeze account action, and account is in frozen …
=> add guardian data REST api

process/interceptors/singleDataInterceptor.go
- there was a bug in the `SingleDataInterceptor` that caused a mutex to be held for too much time. The mutex involved is `mutDebugHandler` that protects the `debugHandler` resource and is correctly used in the `baseDataInterceptor` common struct. The extra usage in `SingleDataInterceptor` remained from the last refactor that was carried ~2 years ago.
- remove the extra usage of the mutex in the `SingleDataInterceptor`
- standard testing procedure
=> Remove mutex use in interceptor

factory/heartbeatV2Components.go, heartbeat/monitor/monitor.go, heartbeat/monitor/monitor_test.go
- heartbeat v2 only responds with validator/observer as peer type on `/node/heartbeatstatus`
- integrate `peerTypeProvider` into heartbeat v2 monitor in order to properly compute the peer type
- system test + proxy call to `/node/heartbeatstatus` after epoch 3(when heartbeat v1 is disabled) in order to check if eligible/waiting is displayed for validators
=> Fix heartbeat monitor to properly set peer type

process/guardian/guardedAccount.go
Remove active guardian from getPendingGuardian result (guardians with activation epoch == current epoch are active not pending)
=> Fixes guardian api

node/external/transactionAPI/apiTransactionProcessor.go, node/external/transactionAPI/apiTransactionProcessor_test.go
- same tx is displayed multiple times in the response of `/transaction/pool?by-sender=erd1...` as `ShardDataStore` returns the same data storer for all ids "0", "0_1", "0_2", "0_META"
- removed the iteration through all data stores with ids `sourceShard_destinationShard` as they all point to the same one, leading to duplicates
- scenario:
- get one or 2 txs in pool(save the sender if possible..if not, get `/transaction/pool` on the observer from the shard you sent txsf and copy a sender address)
- running `/transaction/pool?by-sender=sender_addr_from_above_point` on either proxy or intra shard observer, tyou should not the duplicates among tx hashes received in response
=> Fix duplicated txs into tx pool api response

api/groups/addressGroup_test.go, facade/nodeFacade_test.go, go.mod, go.sum, node/node.go, node/node_test.go
elrond-go-core API field name change propagation
Adapt code to the changed fieldname
Use the API and check the results for an account that has a guardian
/address/:address/guardian-data
=> Rename api guardian field

integrationTests/testHeartbeatNode.go
- fixed integration tests by correctly setting the `heartbeatExpiryTimespanInSec` in `TestHeartbeatNode` struct
=> Fixed integration test in rc/2022-july

cmd/node/config/config.toml, config/config.go, factory/heartbeatV2Components.go, factory/heartbeatV2Components_test.go, factory/interface.go, heartbeat/monitor/monitor.go, heartbeat/monitor/monitor_test.go, heartbeat/process/monitor.go, heartbeat/process/monitor_test.go, heartbeat/sender/heartbeatSender.go, heartbeat/sender/heartbeatSender_test.go, heartbeat/sender/sender.go, heartbeat/sender/sender_test.go, integrationTests/testHeartbeatNode.go, integrationTests/testProcessorNode.go, testscommon/cacherMock.go, testscommon/generalConfig.go
- when validators change their shards in the normal shuffle out process, they no longer output messages on the old shard's heartbeat topic. The old shard's nodes will make them inactive **but keep them in the cache** because they are still validators. This will pollute the node's API response for the heartbeat status with a lot of old messages. 
- some metrics were not updated at all with this hb v2 system
- termui reported some misleading information now that the heartbeat v2 subsystem is running. Also, heartbeat v1 subsystem still pushed some metrics.
- the solution here is to allow the deletion from the cache of old nodes despite the fact that the nodes are validators or observers
- push statuses in app status handler from both sender & monitor components
- make hb v1 subsystem not …
=> Fix hb v2 metrics issues + hb status returned

cmd/node/flags.go, config/contextFlagsConfig.go, factory/consensusComponents.go, factory/stateComponents.go, node/nodeRunner.go, state/accountsDB.go, state/accountsDB_test.go, state/export_test.go, state/peerAccountsDB.go
- During import-db, _snapshotting procedures_ and _processing procedures_ are serialized, which leads to **fast** snapshotting.
- When an observer is fully synchronized and in it's in the _normal_ processing mode, snapshotting is **fast**, as well (at the beginning of a new epoch).
- Syncing a large number of epochs for a full history devnet observer leads to snapshots that are concurrent with the syncing procedures. In this case (syncing from the past, plus concurrent snapshots), snapshotting happens **slowly** (which can often be problematic).
- Add new CLI flag: `--serialize-snapshots` - this will force the state snapshotting to be serialized with processing.
- Add new CLI flag: `--disable-consensus-watchdog` - necessary to allow snapshotting that takes more than 10 rounds (which is …
=> Add new flags (useful for some observers): "serialize-snapshots", "disable-consensus-watchdog"

dataRetriever/requestHandlers/requestHandler.go, dataRetriever/resolvers/peerAuthenticationResolver.go, dataRetriever/resolvers/peerAuthenticationResolver_test.go
- epoch is missing from `RequestData` object, while requesting peer authentication messages, leading to always requesting from epoch 0, which sometimes therefore leads to querying nodes from full history list, which may be empty
- add epoch on `RequestData` object
- standard system test, looking for `peer list is empty or errors during the sending, topic: peerAuthentication` **not to be present**
=> Fix missing epoch on peer authentication messages requests

storage/pruning/triePruningStorer.go, storage/pruning/triePruningStorer_test.go, testscommon/snapshotPruningStorerMock.go, testscommon/trie/snapshotPruningStorerStub.go, trie/interface.go, trie/snapshotTrieStorageManager.go, trie/snapshotTrieStorageManager_test.go, trie/trieStorageManager.go, trie/trieStorageManager_test.go
- There are some edgecases in which a certain trie node is not saved in the proper storer. The problem is that we will have storers that do not have the complete state.
- During the snapshot process, if a trie node is not present in the previous storer (which should have had the entire state), it will also be saved there.
- Normal test, but with "*:DEBUG,trie:TRACE" log level, and we will see in the logs that the missing nodes are also saved in the  previous storer.
=> State snapshot improvement

outport/outport.go, outport/outport_test.go
- Whenever an outport driver gets stuck the node will stop processing new blocks as to disallow dropping information from the chain for each driver. The stop is done without much information in the node's log so any integrator hitting in to this issue will have no clue what it's happening.
- added timeout log prints whenever a driver gets stuck
- standard testing procedure
- start a system testnet, stop an observer, edit the external.toml file enabling the EventNotifierConnector driver without attaching a go notifier and restart the node. The node should stop adding new blocks, after ~30seconds we should have a warning log print stating `outport.monitorCompletionOnDriver took too long`
=> Outport driver stuck prints

trie/trieStorageManagerInEpoch.go
Add extra logging information for `trieStorageManagerInEpoch`.
=> Improve logging for "get from epoch"

go.mod, go.sum
-  Update the elastic indexer module to version v1.2.40
- PRs from indexer: https://github.com/ElrondNetwork/elastic-indexer-go/pull/169
- The new indexer version will extend the block structure with extra fields about the execution of a miniblock (the block structure will contain the indices of the first and last transaction processed from a specific miniblock)
- Run a system test with a lot of transactions.
- Find a block with partial executed miniblocks.
- Check if the specific block indexed in the ES contains information about the execution of the miniblock.
=> Upgrade indexer

storage/factory/pruningStorerFactory.go
- If snapshots are disabled, the trie should use a static storer instead of a pruning storer (that creates a db for each epoch). The meta is using a pruning storer even if snapshots are disabled.
- Use static storer for meta if snapshots are disabled.
- Normal test
- Test with snapshots disabled
=> Create static storer for meta if snapshots are disabled

integrationTests/multiShard/smartContract/polynetworkbridge/bridge_test.go, process/smartContract/process.go, process/smartContract/process_test.go
Inconsistency  of arguments when creating asynchronous callback SCR from an output transfer
Added missing argument. Only after activation of special flag (backward compatibility issues).
Deploy a contract, issue a token from that contract through asnycCall, check one of the resulting SCRs which is with type AsyncchronousCallback. It should start with "@00" after activation. Before activation this one is missing.
=> async callback arguments inconsitency fix

cmd/node/config/enableEpochs.toml, config/epochConfig.go, config/tomlConfig_test.go, integrationTests/multiShard/smartContract/polynetworkbridge/bridge_test.go, node/nodeRunner.go, process/smartContract/process.go, process/smartContract/process_test.go
- the async callback fix was not backwards compatible with the testnet and devnet versions
- added new flag for the fix
- standard system testing procedure
- async callback fix. Before epoch 6 should not return the data, starting from epoch 6 it should return the data parameter
=> New flag for async call fix

errors/errors.go, factory/cryptoComponents.go, factory/cryptoComponentsHandler.go, factory/cryptoComponentsHandler_test.go, factory/heartbeatV2Components.go, factory/interface.go, factory/mock/cryptoComponentsMock.go, heartbeat/errors.go, heartbeat/interface.go, heartbeat/sender/heartbeatSenderFactory.go, heartbeat/sender/heartbeatSenderFactory_test.go, heartbeat/sender/multikeyHeartbeatSender.go, heartbeat/sender/multikeyHeartbeatSender_test.go, heartbeat/sender/multikeyPeerAuthenticationSender.go, heartbeat/sender/multikeyPeerAuthenticationSender_test.go, heartbeat/sender/peerAuthenticationSenderFactory.go, heartbeat/sender/peerAuthenticationSenderFactory_test.go, heartbeat/sender/sender.go, heartbeat/sender/sender_test.go, integrationTests/mock/cryptoComponentsStub.go, integrationTests/testHeartbeatNode.go, integrationTests/testProcessorNode.go, keysManagement/managedPeersHolder.go, keysManagement/managedPeersHolder_test.go, node/mock/factory/cryptoComponentsStub.go, node/nodeTesting_test.go, testscommon/managedPeersHolderStub.go
- renaming keysHolder to managedPeersHolder
- renaming keysHolder to managedPeersHolder
- N/A
=> Keys holder renaming

go.mod, go.sum
- Upgrade the elrond-vm-cmmon module
PR from elrond-vm-cmmon: https://github.com/ElrondNetwork/elrond-vm-common/pull/131
- Upgrade the elastic-indexer-go module
PR from elastic-indexer-go: https://github.com/ElrondNetwork/elastic-indexer-go/pull/170
- Fixed log that is generated when a new NFT / SFT or MetaESDT is created.
- Create a smart contract that can create an NFT and transfer it in the same block
- Do an ESDTNFTCreate cross-shard through the contract and transfer it in the same block 
- Information about the new NFT should be indexer in the Elasticsearch database in the `tokens` index
=> Upgrade vm common and indexer

cmd/node/config/external.toml, config/externalConfig.go, factory/statusComponents.go, go.mod, go.sum, outport/factory/outportFactory.go, outport/factory/outportFactory_test.go
- Covalent team decided not to use websockets anymore, but use RestAPI instead
- Removed covalent indexer from node
- Nonce, code is deleted
=> FEAT: Remove covalent indexer from node

errors/errors.go, factory/heartbeat/heartbeatV2Components.go, factory/heartbeat/heartbeatV2Components_test.go, heartbeat/processor/peerAuthenticationRequestsProcessor.go
=> Update p2p separate repo rc v1.4.0

factory/consensus/consensusComponents.go, factory/crypto/cryptoComponents.go, factory/crypto/cryptoComponentsHandler.go, factory/crypto/errors.go, factory/crypto/signatureHolder.go, factory/crypto/signatureHolder_test.go, factory/interface.go, factory/mock/cryptoComponentsMock.go, integrationTests/consensus/consensusSigning_test.go, integrationTests/consensus/consensus_test.go, integrationTests/mock/cryptoComponentsStub.go, integrationTests/testConsensusNode.go, node/mock/factory/cryptoComponentsStub.go, testscommon/components/default.go
- Integration test for consensus signing
- added new integration test in consensus, with changes regarding multiSigner and signing components
- use real components for singing in consensus integration tests, instead of using mocks
- fix issue in crypto components where private key bytes was not set
- N/A
=> Integration test consensus signing

storage/databaseremover/factory/customDatabaseRemoverCreator.go, storage/databaseremover/factory/customDatabaseRemoverCreator_test.go, storage/factory/pruningStorerFactory.go
- The config value `AccountsTrieCleanOldEpochsData` was not used 
- Added a factory function that creates either a custom or a disabled db remover, based on the above config value
1. should remove
- set an observer's configuration: `AccountsTrieCleanOldEpochsData` to `true` and `AccountsTrieSkipRemovalCustomPattern` to `%2`. When looking in the `db` directory, for epoch older than current - 4 (so if in epoch 8, from epoch 0 to epoch 4)  databases that are not divisible by 2 should not have `AccountsTrie` db for that epoch. Therefore: Epoch_0: should have AccountsTrie, Epoch_1: should not have AccountsTrie, and so on
2. should not remove
- set an observer's configuration `AccountsTrieCleanOldEpochsData` to `false`. In epoch 8, when checking the database dir, no `AccountsTrie` should have …
=> fix accounts trie remover config value

cmd/seednode/main.go, dataRetriever/resolvers/topicResolverSender/topicResolverSender.go, dataRetriever/txpool/memorytests/memory_test.go, factory/network/networkComponents.go, go.mod, go.sum, heartbeat/processor/directConnectionsProcessor.go, heartbeat/processor/directConnectionsProcessor_test.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, node/external/timemachine/fee/memoryFootprint/memory_test.go, p2p/constants.go, p2p/factory/factory.go, process/interceptors/factory/interceptedDirectConnectionInfoFactory_test.go, process/interceptors/processor/directConnectionInfoInterceptorProcessor_test.go, process/p2p/interceptedDirectConnectionInfo.go, process/p2p/interceptedDirectConnectionInfo_test.go, testscommon/components/components.go
-  some tests that computed the amount of memory consumed sometimes failed. This was due to the fact that unnecessary libp2p components were running due to the poor code decoupling
- integrated new p2p version
- removed code un-necessary dependency
- reverted some tests values
- half network test
=> Integrate new p2p repo version

process/block/preprocess/basePreProcess.go, process/block/preprocess/basePreProcess_test.go
- gasComputation component started to consume large amounts of time when the calls to `SetGasProvided` were done on a several hundreds of transactions and up. The time consumed was caused that each transaction hash from the miniblock was added as record in the map that was latter used to append each executed hash, causing exponential time of execution consumed.
- removed unnecessary gasComputation.Reset call from the basePreProcess.handleProcessTransactionInit call
- standard system tests
- half network tests, before and after the partial miniblock execution enable epoch
=> Remove unnecessary gasComputation.Reset call

go.mod, go.sum
- Previously, information about the _frozen_ or _wiped_ _amount_ was not present on the logs / events `ESDTFreeze` and `ESDTWipe`
- Related PR: https://github.com/ElrondNetwork/elrond-vm-common/pull/134
- Reference newest `vm-common v1.3.18`, which implements the fix:
- In the event / log `ESDTFreeze`, add the frozen amount as `topics[2]` (previously fixed to `0`).
- In the event / log `ESDTWipe`, add the wiped amount as `topics[2]` (previously fixed to `0`).
- Standard testing (including ESDT / NFT operations)
- Testing using `rosetta-cli` checker & ESDT support.
=> Integrate vm-common: v1.3.18

storage/clean/oldDatabaseCleaner.go, storage/disabled/storer.go, storage/disabled/storer_test.go
- oldDatabaseRemover relied on the fact that all storers return the correct oldest epoch and ones that don't have an epoch approach, they would have returned an error. However, a disabled Storer has been introduced recently and returned `0` as that value, with no error
- return `0` for the disabled storer
- db cleanup
=> Fix old database cleaner

node/external/logs/logsRepository.go, node/external/logs/logsRepository_test.go
- In some rare cases, right at the beginning of an epoch, `logs & events` of a transaction can we mistakenly saved in the storage associated with the previous epoch.
- In this PR, we attempt to load `logs & events` both from the requested epoch `N`, and from the epoch `N-1`.
- Regular testing
- `rosetta-cli` checker (with ESDT) against devnet (e.g. shard 0)
=> Workaround: get logs on a best-effort basis (handle epoch-change edge-case)

go.mod, go.sum
- Reference vm-common [v1.3.20](https://github.com/ElrondNetwork/elrond-vm-common/releases/tag/v1.3.20)
=> Reference vm-common v1.3.20

common/trie.go, common/trie_test.go, state/accountsDB.go, trie/depthFirstSync.go, trie/depthFirstSync_test.go, trie/doubleListSync.go, trie/doubleListSync_test.go, trie/patriciaMerkleTrie.go, trie/sync.go, trie/trieStorageManager.go, update/genesis/import.go
- There was an error when checking if a trie was empty based on it's root hash
- When checking if a trie is empty, also check if the root hash of the trie is equal to the empty trie root hash
=> Fix empty trie root hash

heartbeat/monitor/errors.go, heartbeat/monitor/heartbeatMessage.go, heartbeat/monitor/monitor.go, heartbeat/monitor/monitor_test.go
- after some **mainnet** node upgrades, the observed heartbeat status response randomly showed active or inactive nodes in the network. This was caused by the fact that the node returned all messages (inactive or active) regardless that the public key is now behind another pid
- made the heartbeat v2 monitor struct better filter-out inactive messages by using the following algorithm:
suppose that, for the same BLS public key we got `n` messages from `n` different pids:
1. if all stored messages show inactive nodes, only keep the latest message, remove the older ones, and put the value `0` on the `NumInstances` field from the `data.PubKeyHeartbeat` struct;
2. if all stored messages show only active nodes, sort the messages based on the `pid` (so that the response will be consistent on all …
=> Heartbeat v2 monitor better filtering

consensus/spos/bls/export_test.go, consensus/spos/bls/subroundEndRound.go, consensus/spos/bls/subroundEndRound_test.go, integrationTests/consensus/consensusSigning_test.go
- Error on creating the aggregated signature on leader was not treated accordingly. Since the sig share is not checked by each node separately, it can happen that an invalid format sig share is provided, so signature aggregation will fail
- handler invalid signers similar as in the verification case
- N/A
=> Pseudo slashing fixes

cmd/assessment/benchmarks/arwenBenchmark.go, epochStart/metachain/systemSCs_test.go, genesis/process/genesisBlockCreator_test.go, go.mod, go.sum, integrationTests/multiShard/hardFork/hardFork_test.go, integrationTests/state/stateTrieSync/stateTrieSync_test.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithTestWebServer.go, integrationTests/vm/arwen/arwenvm/mandosConverter/mandosConverter.go, integrationTests/vm/arwen/arwenvm/mandosConverter/mandosConverterUtils.go, integrationTests/vm/arwen/delegation/delegationSimulation_test.go, integrationTests/vm/arwen/erc20/erc20_test.go, integrationTests/vm/arwen/upgrades/upgrades_test.go, integrationTests/vm/testInitializer.go, integrationTests/vm/txsFee/scCalls_test.go, process/factory/metachain/vmContainerFactory_test.go, process/factory/shard/vmContainerFactory.go, process/factory/shard/vmContainerFactory_test.go, process/smartContract/builtInFunctions/factory_test.go, testscommon/components/components.go, vm/factory/systemSCFactory_test.go
This PR replaces `wasm-vm` with `wasm-vm-v1_4` and removes the reference to `wasm-vm` entirely.
The `rc/v1.4.0` branch of the must not reference `wasm-vm` without a version suffix just yet (the integration branch for that is work in progress).
=> Freeze legacy wasm-vm v1.4

storage/factory/pruningStorerFactory.go
- removed duplicated code
- removed duplicated code
=> Removed duplicated code

outport/process/alteredaccounts/alteredAccountsProvider.go, outport/process/alteredaccounts/alteredAccountsProvider_test.go
- Added an extra check for the Value field from a transaction when altered accounts are extracted   
=> extra check

.github/PULL_REQUEST_TEMPLATE.md
- the reference from PR template to the contributing guidelines was broken
- use absolute URL instead of relative
=> fix contributing URL

node/external/blockAPI/baseBlock.go
- during the latest changes, altered accounts provider used the tx value, and txs from the pool constructed when querying altered accounts did not have the value set (since it wasn't needed)
- set tx value
- receiver addresses should be returned in altered accounts endpoints
=> fix tx value for altered accounts tx pool

go.mod, go.sum, outport/process/alteredaccounts/alteredAccountsProvider.go, outport/process/alteredaccounts/alteredAccountsProvider_test.go
- Within the latest `elrond-go-core` integration, we replaced proto `MetaData` with `TokenMetaData` in altered accounts.
- Refactor code to work with the new struct
- Unit tests
=> FEAT: Use MetaData from outport

state/accountsDB.go, state/errors.go
- `ErrMissingTrie` is shadowing the original err.
- Add the original err message to `ErrMissingTrie`
- Normal test
=> Missing trie err fix

dataRetriever/factory/containers/export_test.go, dataRetriever/factory/containers/requestersContainer.go, dataRetriever/factory/containers/requestersContainer_test.go, dataRetriever/resolvers/topicResolverSender/topicResolverSender_test.go, dataRetriever/topicSender/topicRequestSender.go, dataRetriever/topicSender/topicRequestSender_test.go, testscommon/dataRetriever/requesterStub.go
- unittests only
- unittests only
- unittests only
**Notes for review** 
- tests from `topicRequestSender_test.go` are the same old tests from `topicResolverSender/topicResolverSender_test.go`, only changed the structure to use `t.Run`s
- tests from `requestersContainer_test.go` are more ore less same tests as in `resolversContainer_test.go`, but using `t.Run`s …
=> Unittests for topicRequestSender and requestersContainer

api/errors/errors.go, api/groups/blockGroup.go, go.mod, go.sum, node/external/blockAPI/baseBlock.go
- Removed `MetaData` from api responses, since it could not be consistently provided.
- This information is also available from logs, at each `NFTCreate` builtin function call.
- Removed `withMetaData` flag from `alteredAccounts`
- Check that for each altered accounts endpoint, `MetaData` information is no longer available
=> Remove withMetaData query param

epochStart/bootstrap/process.go, epochStart/bootstrap/sovereignChainProcess.go, epochStart/bootstrap/sovereignChainProcess_test.go, epochStart/bootstrap/storageProcess.go, epochStart/bootstrap/storageProcess_test.go, factory/bootstrap/bootstrapComponents.go, factory/bootstrap/bootstrapComponents_test.go, factory/consensus/consensusComponents.go, factory/consensus/consensusComponents_test.go, node/nodeRunner.go, process/errors.go, process/interface.go, process/sync/storageBootstrap/baseStorageBootstrapper.go, process/sync/storageBootstrap/metaStorageBootstrapper.go, process/sync/storageBootstrap/shardStorageBootstrapper.go, process/sync/storageBootstrap/sovereignChainBaseStorageBootstrapper.go, process/sync/storageBootstrap/sovereignChainBaseStorageBootstrapper_test.go, process/sync/storageBootstrap/sovereignChainShardStorageBootstrapper.go, process/sync/storageBootstrap/sovereignChainShardStorageBootstrapper_test.go, testscommon/components/components.go
- To be able to support the sovereign chain implementation the EpochStartBootstrap, StorageEpochStartBootstrap and StorageBootstrap components should be adapted to the new approach by making a new version and use as much as we can the common code used also in the regular chain (main chain)
- Added support for sovereign chain bootstrapper from storage and from epoch start
- Added support for all the factories needed for sovereign chain components (EpochStartBootstrap, StorageEpochStartBootstrap, StorageBootstrap, etc.)
- 
- 
- 
- …
=> Bootstrap from storage or from epoch start for sovereign chain

state/trackableDataTrie.go
- Taking the key into consideration when computing data size is backwards incompatible
- Revert some changes from previous PR
=> remove key size from total leaf size computation

consensus/interface.go, consensus/mock/peerBlacklistHandlerStub.go, factory/consensus/consensusComponents.go
- the peer blacklist handler's goroutine was hanging (the test `TestConsensusComponents_Close_ShouldWork` was failing)
- call the `Close()` function
- `TestConsensusComponents_Close_ShouldWork` should pass
=> fix peer blacklist handler closing

integrationTests/multiShard/block/interceptedHeadersSigVerification/interceptedHeadersSigVerification_test.go, integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go, integrationTests/node/heartbeatV2/heartbeatV2_test.go, integrationTests/nodesCoordinatorFactory.go, integrationTests/singleShard/block/consensusNotAchieved/consensusNotAchieved_test.go, integrationTests/singleShard/block/executingMiniblocks/executingMiniblocks_test.go, integrationTests/sync/basicSync/basicSync_test.go, integrationTests/testConsensusNode.go, integrationTests/testHeartbeatNode.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithCoordinator.go, integrationTests/testProcessorNodeWithMultisigner.go
- refactored nodes keys in integration tests
- refactored nodes keys in integration tests
- N/A
=> Refactored nodes keys in tests

common/hardfork/hardforkExclusionHandler.go, common/interface.go, factory/consensus/consensusComponents.go, factory/consensus/consensusComponents_test.go, go.mod, go.sum, integrationTests/consensus/consensus_test.go, integrationTests/factory/consensusComponents/consensusComponents_test.go, integrationTests/testSyncNode.go, node/nodeRunner.go, process/sync/argBootstrapper.go, process/sync/baseSync.go, process/sync/baseSync_test.go, process/sync/metablock.go, process/sync/metablock_test.go, process/sync/shardblock.go, process/sync/shardblock_test.go, testscommon/components/components.go, testscommon/hardforkExclusionHandlerStub.go
- integrate HardforkExclusionHandler into sync block in order to not allow rollback for rounds that are start of interval
- integrated HardforkExclusionHandler
- will be tested on feat branch
=> HardforkExclusionHandler into shouldAllowRollback

cmd/node/flags.go, common/constants.go, config/config.go, factory/crypto/cryptoComponents.go, factory/crypto/cryptoComponents_test.go, factory/crypto/export_test.go, factory/interface.go, factory/mock/keyLoaderStub.go, go.mod, go.sum, heartbeat/sender/multikeyHeartbeatSender.go, keysManagement/managedPeersHolder.go, node/nodeRunner.go, scripts/testnet/include/build.sh, scripts/testnet/start.sh, scripts/testnet/variables.sh
- added the possibility to load multiple private keys to be handled by the node
- added new .pem file flag
- modified the crypto factory to take into account this new flag and apply the newly handled keys. In this scenario, the node will autogenerate a public key for use in the normal operation (just as it does in the backup operation)
- system test with 4 observers, each on a different shard, allValidatorsKey.pem containing all private keys registered on the network, the chain should advance normally
- if …
=> Load private keys

consensus/interface.go, consensus/mock/consensusDataContainerMock.go, consensus/mock/mockTestInitializer.go, consensus/mock/signatureHandlerStub.go, consensus/signing/errors.go, consensus/signing/signing.go, consensus/signing/signing_test.go, consensus/spos/bls/blsSubroundsFactory.go, consensus/spos/bls/subroundBlock.go, consensus/spos/bls/subroundBlock_test.go, consensus/spos/bls/subroundEndRound.go, consensus/spos/bls/subroundEndRound_test.go, consensus/spos/bls/subroundSignature.go, consensus/spos/bls/subroundSignature_test.go, consensus/spos/consensusCore.go, consensus/spos/consensusCoreValidator.go, consensus/spos/consensusCoreValidator_test.go, consensus/spos/consensusCore_test.go, consensus/spos/interface.go, consensus/spos/subround.go, factory/consensus/consensusComponents.go
- refactored the private keys usage in consensus
- refactored the private keys usage in consensus
- N/A
=> Refactored private keys usage in consensus

node/metrics/metrics.go, state/accountsDB.go, state/accountsDB_test.go, state/peerAccountsDB.go
- Set snapshot status metrics as integers instead of bool strings
- Update the metric for snaphost status in progress, from `false/true` to `0/1`
- check the updated metrics in node/status route when snapshot is in progress:
- erd_accounts_snapshot_in_progress: 1 if the snapshot is in progress, 0 if it's not
- erd_peers_snapshot_in_progress: 1 if the snapshot is in progress, 0 if it's not
- if this is a `feat` branch merging, do …
=> use numeric instead of bool for snapshots in progress

go.mod, go.sum, node/node.go, node/nodeLoadAccounts.go, node/node_test.go, testscommon/esdtStorageHandlerStub.go
- for historical requests, `esdtStorageHandler.GetESDTNFTTokenOnDestination` would have not returned ok data, since the `esdtStorageHandler` uses a static _AccountsAdapter_ and it would have loaded the current system account instead of the historical one
- integrate new vm common with `GetESDTNFTTokenOnDestinationWithCustomSystemAccount` function
1. issue an SFT collection 
2. create an SFT, check `<node>/address/erd1alice/esdt` and it should return the created NFT. also, note down the `nonce` from `blockInfo`. Let's call it `block_nonce_0`
3. after a few blocks, add quantity to the same nonce, perform the same checks as previous and note down the `nonce` from `blockInfo`. Let's call it `block_nonce_1`. Also, check  `<node>/address/erd1alice/esdt?blockNonce=block_nonce_0` and it should …
=> EN-13529: get token with custom system account

dataRetriever/resolvers/topicResolverSender/topicResolverSender.go, dataRetriever/resolvers/topicResolverSender/topicResolverSender_test.go
- peers rating should be decreased when a request is made to a peer
- added DecreaseRating call
- TBD
=> Add missing call to DecreaseRating on peersRatingHandler

cmd/node/config/config.toml
- Now, the node does a trie pruning operation on each new committed block. This makes the trie history unavailable after ~10 consecutive final blocks are committed
- disable in-epoch trie pruning
- standard system test in which, after the upgrade, you pick an old block (>50 rounds old block) and query a get operation as follows:
```
http://<proxy>/address/<address>?blockNonce=<block_nonce>
```
- if this is a `feat` branch merging, …
=> Disable in-epoch trie pruning 

go.sum, process/interface.go, process/smartContract/hooks/blockChainHook.go, process/smartContract/hooks/blockChainHook_test.go, process/smartContract/hooks/counters/disabledCounter.go, process/smartContract/hooks/counters/usageCounter.go, process/smartContract/hooks/counters/usageCounter_test.go, process/smartContract/hooks/interface.go, process/smartContract/process.go, testscommon/blockChainHookCounterStub.go, testscommon/blockChainHookStub.go
- blockchain hook prints did not contain execution context such as the transaction hash and other helpful information
- refactor code to provide more context whenever blockchain counters needed to be output as log prints
- run a system testnet with the following log level `*:DEBUG,blockchainHookCounters:TRACE`, analyze the logs, should find trace logs that start with `blockchain hook counters` that contain the 3 counters values.
- …
=> Blockchainhook counters refactor

process/economics/builtInFunctionsCost.go, process/gasCost.go
fix missed gas computation
add the new builtin functions to the ComputeBuiltInCost
generate txs for each of the 3 builtin functions, execute them and check the gas used is according to the estimation.
=> add functions to ComputeBuiltInCost

go.mod, go.sum, outport/firehose/errors.go, outport/firehose/firehoseIndexer.go, outport/firehose/firehoseIndexer_test.go, testscommon/ioWriterStub.go
- Proto firehose block communication between elrond-go node and firehose node
- Added support for "dummy" block firehose console writing for firehose node reader. 
**NOTE:** Intentionally initialized internal marshaller of `firehoseIndexer` with `&GogoProtoMarshalizer` instead of passing a marshaller interface.
- Local testnet with firehose block ingestion process
- if this is a `feat` branch merging, do all satellite projects …
=> Send dummy firehose block

state/parsers/dataTrieLeafParser.go, state/parsers/dataTrieLeafParser_test.go
- When parsing a data trie leaf, if the leaf value was not migrated to the new version, the unmarshal should err. There are some cases in which the unmarshall does not err, but the data is still nil.
- After unmarshal, also check that the trieData is not empty.
- added unit test
=> Trie leaf data unmarshal

trie/patriciaMerkleTrie_test.go, trie/statistics/trieStatistics.go, trie/statistics/trieStatisticsCollector.go, trie/statistics/trieStatistics_test.go
- When printing trie stats, some fields are hard to read and not really useful (ex: numBranchesPerLevel, numExtensionsPerLevel, numLeavesPerLevel)
- Remove said fields, and replace them with totalNumBranches, totalNumExtensions, totalNumLeaves
=> refactor trie stats

epochStart/bootstrap/syncValidatorStatus.go, factory/bootstrap/shardingFactory.go, sharding/mock/nodesCoordinatorCacheMock.go, sharding/nodesCoordinator/errors.go, sharding/nodesCoordinator/indexHashedNodesCoordinator.go, sharding/nodesCoordinator/indexHashedNodesCoordinatorLite.go, sharding/nodesCoordinator/indexHashedNodesCoordinatorRegistry.go, sharding/nodesCoordinator/indexHashedNodesCoordinatorWithRater_test.go, sharding/nodesCoordinator/indexHashedNodesCoordinator_test.go, sharding/nodesCoordinator/interface.go, sharding/nodesCoordinator/shardingArgs.go
- Cacher for epoch nodes config, in order to keep more nodes configuration in a cacher if needed.
- add a separate cacher for epoch nodes config
- separate operation for getting nodes config
=> Epoch nodes config cacher

statusHandler/statusMetricsProvider.go, statusHandler/statusMetricsProvider_test.go
- `erd_rounds_passed_in_current_epoch` and `erd_nonces_passed_in_current_epoch` were not set when calling the Prometheus metrics endpoint
- compute their values for that endpoint as well
- query `<node>:<port>/node/metrics` and search for the 2 metrics. They should have the same value as the ones found at `<node>:<port>/node/status`
=> fix num rounds and nonces passed in epoch for prometheus

common/constants.go, dataRetriever/factory/resolverscontainer/metaResolversContainerFactory.go, dataRetriever/factory/resolverscontainer/metaResolversContainerFactory_test.go, dataRetriever/factory/resolverscontainer/shardResolversContainerFactory.go, dataRetriever/factory/resolverscontainer/shardResolversContainerFactory_test.go, epochStart/bootstrap/process.go, factory/consensus/consensusComponents.go, factory/processing/blockProcessorCreator_test.go, factory/state/stateComponents.go, genesis/process/genesisBlockCreator.go, genesis/process/genesisBlockCreator_test.go, integrationTests/state/stateTrie/stateTrie_test.go, integrationTests/state/stateTrieSync/stateTrieSync_test.go, integrationTests/testProcessorNode.go, node/nodeRunner.go, process/sync/baseSync.go, process/sync/interface.go, process/sync/metablock.go, process/sync/metablock_test.go, process/sync/shardblock.go, process/sync/shardblock_test.go, testscommon/components/components.go, testscommon/components/default.go, testscommon/storage/storerStub.go, trie/factory/trieCreator.go, trie/factory/trieFactoryArgs.go, update/genesis/import.go, update/genesis/import_test.go
- Duplicate constants for db identifier
- remove constants for peer and user accounts key
- use constant from dataRetriever storage units
- N/A
=> refactor to use storer ids for dataRetriever

consensus/spos/worker.go, consensus/spos/worker_test.go
- there were situations when the MetricReceivedProposedBlock was improperly computed
- fix MetricReceivedProposedBlock overflow by disallowing a negative value
- standard system test + system test without transactions 
=> Fix `MetricReceivedProposedBlock` overflow

go.mod, go.sum, outport/firehose/errors.go, outport/firehose/firehoseIndexer.go, outport/firehose/firehoseIndexerTxPool.go, outport/firehose/firehoseIndexerTxPool_test.go, outport/firehose/firehoseIndexer_test.go
- Include tx pool in firehose block
- Add support to parse tx pool and convert each interface to its proto message
- Local testnet + firehose ingestion process + tools to check firehose ingested blocks
=> Add tx pool to firehose block

testscommon/state/userAccountStub.go
- generating schema from proto not working due to invalid path
- fix included path in generator
- generate schemas, no error should be reported
=> fix path for generating proto schema

cmd/termui/provider/metricsProvider.go
- nodes without `https` would have not worked for termui
- allow both `http` and `https`
- start a termui instance built from the `rc/v1.4.0` branch - should **not** load upper data (node name, pub key, and so on)
- start a termui instance built from this branch -  - **should** load upper data (node name, pub key, and so on)
=> Fix termui node URL

scripts/testnet/variables.sh
- when running the internal testnets, the observers were not running with the DB lookup extension. It is useful to have them running with the DB lookup extension for testing & debugging purposes  
- set default DbLookupExtensions.Enabled = true on observers that are running using the internal testnet scripts
- start a local system testnet, the observers should be started in db-lookup-extension mode:
Logs like this one will appear:
```
WARN [2023-01-30 12:15:19.361] [main]               [/0/0/]        the node is in DB lookup extension mode! Will auto-set some config values DbLookupExtensions.Enabled = true 
```
Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check …
=> DB lookup extension enabled for observers running on local testnets

outport/firehose/firehoseIndexerTxPool.go, outport/firehose/firehoseIndexerTxPool_test.go
- Tx pool contains a `map<string, tx>` fore each tx/scr/reward, etc. Each `string` **key**  in map is defined as `string([]byte(...))`, which result in non human readible strings when being indexed in firehose, such as: 
```
"Transactions": {
"\ufffd\ufffd\u000eC\ufffd\ufffd\u001a\ufffd\ufffd\u000eZS!=\ufffd\ufffd\ufffdJ\ufffdaE\ufffd\ufffdE\\\ufffdm\ufffd\ufffd\ufffd\ufffd\ufffd": {
"Transaction": {
"nonce": 10,
```
- Refactor indexing process for each key string to be the hex encoded value of the hash. E.g.:
```
"Transactions": {
"e8f86c78622c609913fd1a445d65a31dda2ae79ac73bc678c6069e7eacdaafc5": {
"Transaction": {
"nonce": 10,
```
- Firehose integration tests
Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-man …
=> Use hex encoded hash in txs maps

integrationTests/testInitializer.go
- There were some integration tests that were randomly failing
- Add a delay after UpdateRound() (from integration tests) is called, allowing the round to be properly updated in the nodes
- No testing needed, changes were made only in integration tests.
=> add delay after UpdateRound in integration tests

integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
- After the integration tests in `StartInEpoch` were run, the `Static` db was not removed
- Remove the `Static` db after the tests are finished 
- No testing needed, no changes were made in productive code.
=> remove StartInEpoch integration test db

process/block/baseProcess.go, process/block/baseProcess_test.go, process/block/metablock.go, process/block/metablock_test.go, process/block/shardblock.go, process/block/shardblock_test.go, trie/branchNode.go, trie/extensionNode.go, trie/leafNode.go, trie/node.go, trie/node_test.go
- while processing scheduled transactions, the process status handler component is not notified
- added processStatusHandler control while processing scheduled transactions
- standard system test with scheduled transactions, after the upgrade we should be able to find the following succession of events: 
```
processStatusHandler.SetBusy reason = "shardProcessor.CreateBlock"
processStatusHandler.SetIdle
*** or ***
processStatusHandler.SetBusy reason = "baseProcessor.ProcessScheduledBlock"
processStatusHandler.SetIdle
processStatusHandler.SetBusy reason = "baseProcessor.ProcessScheduledBlock"
processStatusHandler.SetIdle
processStatusHandler.SetBusy reason = "shardProcessor.CommitBlock"
processStatusHandler.SetIdle
```
Based on the [Contributing …
=> Schedule processing control over the process status handler component

node/external/timemachine/fee/feeComputer.go, node/external/timemachine/fee/feeComputer_test.go, node/external/timemachine/fee/memoryFootprint/memory_test.go
- Concurrent requests for `GET transaction` - where transactions are in in epochs with different fee computation scheme - result in inconsistent computation of the API field `initiallyPaidFee`
- Regression introduced in https://github.com/multiversx/mx-chain-go/pull/4255.
- In API's fee computer, do not share `enableEpochsHandler` across different instances of `economicsData`.
- regular testing on internal testnets
- testing session on public testnet using rosetta-cli checker
- if this is a larger feature that probably needs more …
=> Fix inconsistent computation of "initiallyPaidFee" on concurrent requests

cmd/termui/view/termuic/termuiRenders/widgetsRender.go, cmd/termui/view/termuic/termuiRenders/widgetsRender_test.go
- termui logs window scrolled heretically when large log lines needed to be displayed
- minor fixes in termui
- 
- 
- 
=> Small termui fixes

cmd/node/main.go, config/configChecker.go, config/configChecker_test.go, config/errors.go
- In case of a wrong epoch configuration for staking v4, there was no protocol sanity check to signal it
- Added a config checker for stakingV4, which checks:
1. StakingV4 steps are in order
2. MaxNodesChangeEnableEpoch are changed correctly.
- For "soft configuration mistakes", a **warn** is thrown 
- Local testnet scripts
=> Protection check for stakingV4 configs

sharding/nodesCoordinator/indexHashedNodesCoordinator.go
- In the old version when there was a fix for `FixWaitingList` which was wrongfully using a `previousEpochConfig` for leaving nodes, there was a log.Warn in case of shard mismatch. The reason why this warn was not triggered when nodes were starting with previousConfig from epoch = 0 is because we never changed the number of shards. This warn was adapted to work with metablock start of epoch data which might not provide enough info and trigger unnecessary warnings.
- Remove warn
- 
- 
- 
- if this is a larger feature that probably …
=> FIX: Remove warn

cmd/node/config/config.toml, cmd/node/config/enableEpochs.toml
- compressed configs
- compressed configs
- 
- 
- 
=> v1.4.8-dev-config

node/external/transactionAPI/apiTransactionProcessor.go, node/external/transactionAPI/gasUsedAndFeeProcessor.go, node/external/transactionAPI/gasUsedAndFeeProcessor_test.go, outport/process/factory/check_test.go, outport/process/factory/outportDataProviderFactory.go, outport/process/transactionsfee/interface.go, outport/process/transactionsfee/transactionChecker.go, outport/process/transactionsfee/transactionsFeeProcessor.go, outport/process/transactionsfee/transactionsFeeProcessor_test.go
- Bug-fix the problem of how is calculated the `gasUsed` and `fee` fields for the transaction structure that is returned by the `/transction/${txHash}` endpoint and for the `outport` package
- In case of an ESDT Transfer ( fungible token transfer, nft transfer, or multi transfer) with smart contract calls the fee field will be set with initialPaidFee and the gasUsed field will be set with gasLimit of the transaction. This solution will solve the case when we have this kind of transaction and it fails (in that case these fields were incorrect).
- For a failed transaction with an ESDT transfer and SC call check if the `gasUsed` and `fee` fields are calculated correctly.
Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branch …
=> Fix gas used and fee

common/interface.go, integrationTests/state/stateTrieSync/stateTrieSync_test.go, testscommon/trie/trieStub.go, trie/branchNode.go, trie/branchNode_test.go, trie/extensionNode.go, trie/extensionNode_test.go, trie/interface.go, trie/leafNode.go, trie/patriciaMerkleTrie.go, trie/patriciaMerkleTrie_test.go
The GetNumNodes functionality had some edge cases. This functionality was **solely used in tests** so it can be safely removed. 
- removed GetNumNodes trie unused functionality
- standard system-test
=> Remove `GetNumNodes` trie functionality

go.mod, go.sum
=> Proper release for feat multikey

node/external/transactionAPI/gasUsedAndFeeProcessor.go, node/external/transactionAPI/gasUsedAndFeeProcessor_test.go, outport/process/transactionsfee/transactionsFeeProcessor.go, outport/process/transactionsfee/transactionsFeeProcessor_test.go
- Bug-fix the case when a smart contract result with a refund is generated but the receiver is not the sender of the initial transaction.  In this case, the `fee` and `gasUsed` was calculated based on a refund that never arrived at the sender of the transaction, which is wrong.
- Added an extra check that verifies if the receiver of the smart contract result with refund is the sender of the initial transaction. 
- Verify that for the case from above the `gasused` and `fee` fields are calculated correctly
- if this is a larger …
=> Bug-fix `gasUsed` and `fee` transasctionsFeeProcessor

node/node.go, node/node_test.go
- there were some inconsistencies between how several endpoints returned data when the account was not found 
- return empty responses instead of errors each time an account that does not exist is passed as input
**This PR brings breaking changes on the node's API level, so they should be communicated properly before reaching a release**
Call the following endpoints 2 ways: for a node running this branch and for a node running `feat/polaris-fixes`. Node with this branch should return empty responses, while the node with feat/polaris-fixes _could_ return errors (not in each case).
_these examples require that the used address does not exist or is in another shard_
- 127.0.0.1:8080/address/erd12fzhhrv4pnjflvsy0d7zpq54lz4fjuafqnarlwvspsz569zj4dfqlquphc
- …
=> always return empty responses when accounts are not found

cmd/node/config/config.toml, config/config.go, node/nodeRunner.go
- the delay before the node allows external (API) vm queries was fixed to 2 minutes
- extracted configuration value
- play around with the `VmQueryDelayAfterStartInSec` value and (re)start a node. after the number of seconds specified in the config, it should accept API VM Queries. Query example:
```
curl --request POST \
--url http://127.0.0.1:8080/vm-values/query \
--header 'Content-Type: application/json' \
--data '{
"scAddress": "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u",
"funcName": "getContractConfig"
}'
```
- was the PR targeted to the correct …
=> extracted configuration value for vm-queries delay

cmd/keygenerator/converter/pidPubkeyConverter.go, config/tomlConfig_test.go, go.mod, go.sum, integrationTests/consensus/consensus_test.go, node/external/transactionAPI/apiTransactionProcessor.go, node/external/transactionAPI/apiTransactionProcessor_test.go, node/node_test.go, outport/process/alteredaccounts/alteredAccountsProvider.go, outport/process/alteredaccounts/errors.go, process/smartContract/process.go, state/accountsDB.go, state/syncer/userAccountsSyncer.go
-fixes after review for feat/pubkey_converter
- 
- 
- 
- system test - #allin and #half with rc/v1.6.0
=> Fix after review pubkeyconverter

node/external/transactionAPI/unmarshaller.go
- missing fields in the transaction response for guarded transactions
- added the missing fields
- send guarded transactions and check for the fields on observer and proxy 
=> add extra fields on prepare transaction

process/transaction/interceptedTransaction.go, process/transaction/interceptedTransaction_test.go
- if a tx had an invalid guardian signature, one was not able to tell if the wrong signature is the tx's signature of the guardian's signature 
- wrap error
- 
- 
- 
=> wrap invalid guardian signature error

integrationTests/vm/delegation/delegationScenarios_test.go, integrationTests/vm/esdt/process/esdtProcess_test.go, integrationTests/vm/txsFee/validatorSC_test.go, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegation_test.go, vm/systemSmartContracts/esdt.go, vm/systemSmartContracts/validator.go, vm/systemSmartContracts/validator_test.go
To increase consistency in system smart contract we should return error on case of all user errors. Otherwise it is hard to make integrations of these functions into other SCs.
Return error when needed.
Test withdraw from a delegation contract when there is nothing to unBond. After flag is activated, it should return error.
=> Return err every time system vm

state/export_test.go, state/trackableDataTrie.go, state/trackableDataTrie_test.go
- Fix a case in which `Delete()` is called twice in a row for the same key
- Remove unnecessary code 
- Fix `MigrateDataTrieLeaves()` func. If the version that needs to be migrated is `AutoBalanceEnabled`, get the proper key.
=> fix for delete edgecase and remove some code

heartbeat/processor/export_test.go, heartbeat/processor/peerAuthenticationRequestsProcessor.go, heartbeat/processor/peerAuthenticationRequestsProcessor_test.go
- some unit tests for the peerAuthenticationRequestsProcessor component were seldom failing
- added new unit tests
- reworked tests that tested logic to work on a component that did not launched go routines
- minor production code refactoring
- when analyzing the logs, we should find prints like: 
```
received enough messages, closing peerAuthenticationRequestsProcessor go routine
```
or 
```
closing peerAuthenticationRequestsProcessor...
closing peerAuthenticationRequestsProcessor go routine
```
- if this is …
=> Fix seldom failing tests in hb v2

cmd/termui/view/termuic/termuiRenders/widgetsRender.go, factory/processing/processComponents.go, node/nodeRunner.go
- previously, one couldn't figure out if a node if full archive or not by looking at the termui window
- display a message if the node is in full archive mode
- by using this branch, connect via termui to a node that is a full archive and to one that is not. Termui should display accordingly
=> termui: display if the node is full archive

state/syncer/baseAccoutnsSyncer_test.go, state/syncer/export_test.go, state/syncer/userAccountsSyncer_test.go, state/syncer/validatorAccountsSyncer_test.go
- Add unit tests before making changes in trie sync process
- Added unit tests for state/syncer package
- N/A
=> unit tests for state/syncer

facade/initial/initialNodeFacade_test.go, facade/mock/nodeStub.go, facade/nodeFacade.go, facade/nodeFacade_test.go
- increase code coverage
- added unit tests on facade package
- tests only
=> Coverage for facade

factory/status/statusComponents.go
- fixed the indexer creation
- 
- 
- 
- 
- 
- 
=> Fixed the indexer creation

cmd/node/config/enableEpochs.toml
- change epoch in which autoBalanceDataTries is enabled
=> change epoch in which autoBalanceDataTries is enabled

process/guardian/guardedAccount.go, process/guardian/guardedAccount_test.go, process/transaction/baseProcess.go, process/transaction/baseProcess_test.go
Improvements for set guardian
- allow setting of pending guardian the active guardian - increases protection time 2x.
- reject txs with usernames from pending set guardian - simplifies checks before execution
=> Allow set same guardian

factory/processing/blockProcessorCreator.go, genesis/process/shardGenesisBlockCreator.go, integrationTests/singleShard/block/executingMiniblocks/executingMiniblocks_test.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, integrationTests/vm/testInitializer.go, integrationTests/vm/txsFee/relayedMoveBalance_test.go, integrationTests/vm/wasm/utils.go, integrationTests/vm/wasm/wasmvm/wasmVM_test.go, process/transaction/export_test.go, process/transaction/shardProcess.go, process/transaction/shardProcess_test.go
- It is harder now to figure out the status of a failed relayed transaction only by querying the REST API routes
- added logs for the non-executable relayed transactions
- standard system test + failed relayed v1 & v2 transactions. `signalError` logs should appear for those transactions
=> Logs for non-executable transactions

go.mod, go.sum, vm/systemSmartContracts/esdt.go, vm/systemSmartContracts/esdt_test.go
- Updated the version of mx-chain-vm-common` modules
- Bug-fix: fixed the log that is generated with the identifier `upgradeProperties`
- PR from the `mx-chain-vm-common`: https://github.com/multiversx/mx-chain-vm-common-go/pull/211
- Make a transaction with `SetGuardian` and check in the Elasticsearch database that the field `operation` is set.
- Do an `issue` ESDT transaction and check that properties `canUpgrade` and `canSetSpecialRole` are true in the log with the `upgradeProperties` identifier
- if this is a larger feature …
=> Update vm-common and `upgradeProperties` log

sharding/nodesCoordinator/indexHashedNodesCoordinator.go, sharding/nodesCoordinator/indexHashedNodesCoordinator_test.go
- When loading from storage, get from most recent loaded epoch nodes config
- N/A
=> handle nodes config from storage

cmd/node/config/gasSchedules/gasScheduleV1.toml, cmd/node/config/gasSchedules/gasScheduleV2.toml, cmd/node/config/gasSchedules/gasScheduleV3.toml, cmd/node/config/gasSchedules/gasScheduleV4.toml, cmd/node/config/gasSchedules/gasScheduleV5.toml, cmd/node/config/gasSchedules/gasScheduleV6.toml, cmd/node/config/gasSchedules/gasScheduleV7.toml, go.mod, go.sum, integrationTests/vm/testInitializer.go, integrationTests/vm/txsFee/dns_test.go, integrationTests/vm/txsFee/migrateDataTrie_test.go
=> Metadata endpoint

factory/processing/blockProcessorCreator_test.go, genesis/process/genesisBlockCreator_test.go, integrationTests/testInitializer.go, node/node_test.go, process/peer/process.go, process/peer/process_test.go, process/rewardTransaction/process_test.go, process/scToProtocol/stakingToPeer_test.go, process/sync/trieIterators/tokensSuppliesProcessor_test.go, process/sync/trieIterators/trieAccountsIterator_test.go, state/accounts/peerAccount.go, state/accounts/peerAccount_test.go, state/export_test.go, state/factory/accountCreator.go, state/interface.go, state/journalEntries.go, state/trackableDataTrie/export_test.go, state/trackableDataTrie/trackableDataTrie.go, state/trackableDataTrie/trackableDataTrie_test.go, testscommon/state/accountWrapperMock.go, update/genesis/common.go, vm/systemSmartContracts/eei_test.go, vm/systemSmartContracts/staking_test.go
- Move data trie tracker in a separate package, and remove NewEmptyPeerAccount()
=> Separate package for data trie tracker

common/interface.go, keysManagement/errors.go, keysManagement/interface.go, keysManagement/managedPeersMonitor.go, keysManagement/managedPeersMonitor_test.go
- new component needed to provided managed keys info
- created managedPeersMonitor
- will be tested with the full feat branch
=> Managed peers monitor

process/transaction/shardProcess_test.go
=> fix race in tests

cmd/node/config/external.toml, config/externalConfig.go, factory/status/export_test.go, factory/status/statusComponents.go, factory/status/statusComponents_test.go, outport/factory/hostDriverFactory.go, outport/factory/hostDriverFactory_test.go, outport/factory/outportFactory.go, outport/factory/outportFactory_test.go, testscommon/components/components.go
-  The configuration for the HostDriver has to support multiple instances.
- Extended the `external.toml` config file in order to have multiple instances of `HostDriversConfig`. 
- This change is needed because we want to have multiple host drivers on the same node. ( we need an instance of the host driver for the Elastic indexer and one instance for the Event notifier)
- Do a system test with multiple instances of the host driver on the same node. 
- if this is a larger feature that probably needs more than one PR, is there a …
=> Multiple instances HostDriver

cmd/node/config/enableEpochs.toml
- compressed flags after mainnet release
- compressed flags
=> Compressed flags

cmd/node/config/config.toml, cmd/node/flags.go, config/config.go, config/contextFlagsConfig.go, config/tomlConfig_test.go, dataRetriever/factory/storageRequestersContainer/args.go, dataRetriever/factory/storageRequestersContainer/metaRequestersContainerFactory.go, dataRetriever/factory/storageRequestersContainer/metaRequestersContainerFactory_test.go, dataRetriever/factory/storageRequestersContainer/shardRequestersContainerFactory.go, dataRetriever/factory/storageRequestersContainer/shardRequestersContainerFactory_test.go, epochStart/bootstrap/fromLocalStorage.go, epochStart/bootstrap/metaStorageHandler.go, epochStart/bootstrap/metaStorageHandler_test.go, epochStart/bootstrap/process.go, epochStart/bootstrap/process_test.go, epochStart/bootstrap/shardStorageHandler.go, epochStart/bootstrap/shardStorageHandler_test.go, epochStart/bootstrap/storageProcess.go, factory/data/dataComponents.go, factory/processing/processComponents.go, factory/state/stateComponents.go, integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go, integrationTests/realcomponents/processorRunner.go, node/nodeRunner.go, storage/factory/storageServiceFactory.go, trie/factory/trieCreator.go, trie/factory/trieCreator_test.go
- rc/v1.6.0 can not start a snapshot-less node by providing the config through config.toml
- put back snapshot-less config in config.toml
- standard system test in which we start a snapshot-less node using the following possibilities:
1. start the node with the flag `--snapshots-enabled=false`
2. start the node using the flag `--operation-mode snapshotless-observer`
3. start the node by altering the config.toml (either directly or using the override configs in prefs.toml) for `SnapshotsEnabled = false`
- if this is a larger feature …
=> Put back snapshot-less config in config.toml

.github/workflows/create_release.yml, cmd/node/main.go, docker/multiversx/Dockerfile, docker/termui/Dockerfile
- fixed go build commands
- fixed go build commands
- not required, non-production changes were made
=> Fixed go build commands

process/block/baseCrossNotarizer.go, process/block/baseProcess.go, process/block/interface.go, process/block/metablock.go, process/block/multiShardCrossNotarizer.go, process/block/shardblock.go, process/block/sovereignChainBlock.go, process/block/sovereignCrossNotarizer.go, process/block/sovereignCrossNotarizer_test.go
- There was some meta notarization on sovereign chain that introduced warnings at each block
- Extracted `getLastCrossNotarizedHeaders` func from `baseProcessor.go`, which was notarizing all shards+meta.
- Created a small base component (`baseBlockNotarizer`) used for  `getLastCrossNotarizedHeadersForShard`
- Created two small components that inherit `baseBlockNotarizer`: `multiShardCrossNotarizer` for regular chain + `sovereignShardCrossNotarizer` for sovereign chain
- 
- 
- 
- if this is a larger feature that probably needs more …
=> Sovereign cross notarizer

cmd/node/config/config.toml
- Enabled sharded storage feature on UserAccounts and PeerAccounts storers
- Set `ShardIDProviderType` and `NumShards` in config
- Standard testing procedure
=> Enable sharded storage for user accounts and peer accounts

process/smartContract/scQueryService.go, process/smartContract/scQueryService_test.go
when configuring maximum gas limit per query should set a reasonable value
add 300s worth of gas as maximum/default limit, when not explicitly set otherwise
Execute VM queries (for 0 limits on ShardMaxGasPerVmQuery and/or MetaMaxGasPerVmQuery) and check the reported used and remaining gas. Should add up to 300_000_000_000
=> set max gas per query to 300s equivalent

node/processingOnlyNode/configLoaders.go, node/processingOnlyNode/memoryComponents.go, node/processingOnlyNode/testOnlyProcessingNode.go, node/processingOnlyNode/testOnlyProcessingNode_test.go
- started work on the testOnlyProcessingNode
- 
- 
- 
- 
- 
- 
=> TestOnlyProcessingNode - part 1

node/chainSimulator/configLoaders.go, node/chainSimulator/coreComponents.go, node/chainSimulator/cryptoComponents.go, node/chainSimulator/disabled/antiflooder.go, node/chainSimulator/disabled/peerHonesty.go, node/chainSimulator/disabled/peersRatingMonitor.go, node/chainSimulator/interface.go, node/chainSimulator/memoryComponents.go, node/chainSimulator/networkComponents.go, node/chainSimulator/stateComponents.go, node/chainSimulator/statusComponents.go, node/chainSimulator/statusCoreComponents.go, node/chainSimulator/storageService.go, node/chainSimulator/syncedBroadcastNetwork.go, node/chainSimulator/syncedBroadcastNetwork_test.go, node/chainSimulator/syncedMessenger.go, node/chainSimulator/syncedMessenger_test.go, node/chainSimulator/testOnlyProcessingNode.go, node/chainSimulator/testOnlyProcessingNode_test.go
- renamed the package
- added networkComponents
- 
- 
- 
- 
- 
- 
=> Added network components in chain simulator

genesis/parsing/accountsParser.go, genesis/parsing/accountsParser_test.go, go.mod, go.sum
-  Changed the indexer version with one with some extra checks on the `tags` index 
-  PR from `mx-chain-es-indexer-go` module https://github.com/multiversx/mx-chain-es-indexer-go/pull/248
- 
=> Update indexer version

cmd/sovereignnode/incomingHeader/incomingHeaderProcessor.go, cmd/sovereignnode/incomingHeader/incomingHeaderProcessor_test.go, cmd/sovereignnode/incomingHeader/incomingSCRProcessor.go, cmd/sovereignnode/systemTestDemo/mockNotifier/notifier.go, dataRetriever/requestHandlers/sovereignRequestHandler.go, errors/errors.go, process/factory/interceptorscontainer/sovereignShardInterceptorsContainerFactory.go, process/interceptors/processor/sovereignHdrInterceptorProcessor.go, process/interceptors/processor/sovereignHdrInterceptorProcessor_test.go, process/interface.go, testscommon/sovereign/incomgHeaderSubscriberStub.go, testscommon/sovereignInterceptedExtendedHeaderDataStub.go
- Verify intercepted received extended header and save it
- In order to verify the received extended header, we use the incoming header processor. This will create incoming scrs + miniblocks from the received header + incoming events. If the hash of received data matches the computed one, then the proof is valid.
- Save will add incoming header once.
- 
- 
-  …
=> Verify + save received extended header

process/block/shardblock.go
- There were some edge cases in which a snapshot would start right before the node would reach the next epoch, so there were 2 snapshots in the same epoch.
- Get the right epoch when starting a snapshot from the epochStartTrigger
=> Fix snapshot in the wrong epoch

keysManagement/managedPeersHolder.go, keysManagement/managedPeersHolder_test.go
- fixed managed peers holder to avoid panics in case of a badly configured node where the identities are set but the actual .pem file containing the keys is not provided
- separated the curated & valid data map from the provided identities
- standard system test with multikey
- start a metachain node providing a named identity like
```
[[NamedIdentity]]
Identity = "test"
NodeName = "test"
BLSKeys = [
"<BLS1>",
"<BLS2>",
...
"<BLSn>"
]
```
where `<BLS1>`, `<BLS2>` ... `<BLSn>` are all BLS keys from the testnet in hex format
The node should sync and not panic.
- was the PR …
=> Fixed managedPeersHolder for badly configured node

cmd/seednode/main.go, common/constants.go, common/converters.go, common/converters_test.go, factory/network/networkComponents.go, factory/status/export_test.go, factory/status/statusComponentsHandler.go, factory/status/statusComponentsHandler_test.go, go.mod, go.sum, p2p/disabled/networkMessenger.go, p2p/interface.go, testscommon/p2pmocks/messengerStub.go
- using the same logger on all messenger components led to difficulties during debugging
- added setter for p2p debugger, as it could be optional and set later on from node
- added p2p metrics for full archive network
- system test with some nodes on full archive network
- on full archive nodes, `/node/p2pstatus` must have metrics ending with _full_archive, which should reflect the actual state of the network
- if this is a `feat` …
=> Added p2p debugger setter

dataRetriever/mock/peerListCreatorStub.go, dataRetriever/topicSender/topicRequestSender.go, dataRetriever/topicSender/topicRequestSender_test.go
- there might be a possibility when running a regular node, 
- add a fallback option.. if the requests sent on full archive network fail, try on the regular one
=> Added fallback on topicRequestSender in case requests on full archive nodes fail

node/chainSimulator/dataComponents.go, node/chainSimulator/processComponents.go, node/chainSimulator/syncedMessenger.go, node/chainSimulator/syncedMessenger_test.go, node/chainSimulator/testOnlyProcessingNode.go, node/chainSimulator/testOnlyProcessingNode_test.go, node/chainSimulator/testdata/genesisSmartContracts.json
- Process Components 
- Data Components
=> Data components and process components

examples/construction_test.go
- there was no example of how the hash should be computed when guardians fields are set
- added unit test
- n/a
=> tx hash test example with guardian

.github/workflows/create_release.yml
- create release workflow stopped working
- replace the usage of `hub` application with the official one (`gh`)
- create a draft release
=> chore: fixed create release workflow

dblookupext/historyRepository.go, dblookupext/miniblocksHandler.go, dblookupext/miniblocksHandler_test.go
- implemented `getMiniblockMetadataByMiniblockHash` and `getMiniblockMetadataByTxHash` in the `miniblocksHandler`
- identified parts in `historyRepository` that will change in the upcoming PRs
- 
- 
- 
- 
- 
- 
=> Implemented part 3 of the fix for db lookup extension and partial miniblocks

process/sync/storageBootstrap/baseStorageBootstrapper.go
- Get last epoch from metachain epoch start trigger info, instead of last header from shard boostrap info
- the issue was happening when shuffling out and moving to another shard 
- Standard testing procedure
=> get last epoch from epoch start trigger info

go.mod, go.sum
- when calling the `/address/:address/guardian-data`, the `guarded` bool property was not shown if it was false (json omitempty). 
- Reference mx-chain-core-go version that will not omit the field 
- core PR: https://github.com/multiversx/mx-chain-core-go/pull/271
- n/a
=> reference core version with removed omitempty for guarded api field

integrationTests/realcomponents/processorRunner_test.go, integrationTests/realcomponents/txsimulator/componentConstruction_test.go, node/chainSimulator/chainSimulator.go, node/chainSimulator/chainSimulator_test.go, node/chainSimulator/components/coreComponents.go, node/chainSimulator/components/manualRoundHandler.go, node/chainSimulator/components/testOnlyProcessingNode.go, node/chainSimulator/components/testOnlyProcessingNode_test.go, node/chainSimulator/configs/configs.go, node/chainSimulator/configs/configs_test.go, node/chainSimulator/interface.go, node/chainSimulator/process/processor.go, node/nodeRunner_test.go, process/sync/baseForkDetector.go, testscommon/realConfigsHandling.go
- added & integrated manual round handler
- 
- 
- 
- 
- 
- 
=> Added & integrated manual round handler

node/chainSimulator/chainSimulator.go, node/chainSimulator/chainSimulator_test.go, node/chainSimulator/components/bootstrapComponents.go, node/chainSimulator/components/closeHandler.go, node/chainSimulator/components/coreComponents.go, node/chainSimulator/components/dataComponents.go, node/chainSimulator/components/instantBroadcastMessenger.go, node/chainSimulator/components/memoryComponents.go, node/chainSimulator/components/networkComponents.go, node/chainSimulator/components/processComponents.go, node/chainSimulator/components/statusComponents.go, node/chainSimulator/components/statusCoreComponents.go, node/chainSimulator/components/storageService.go, node/chainSimulator/components/testOnlyProcessingNode.go, node/chainSimulator/configs/configs.go, node/chainSimulator/errors.go, node/chainSimulator/facade.go, node/chainSimulator/interface.go, node/chainSimulator/process/interface.go
- epoch change fixes
- started implementation for the chain simulator facade
- added & called Close on all inner components
- 
- 
- 
- 
- 
- 
=> Fixes for chain simulator

api/gin/webServer.go, api/gin/webServer_test.go
- the node can panic if it was started with `-rest-api-interface off`
- fixed web server closing when the web server is disabled by testing if the server is nil
- start a node with `-rest-api-interface off`. When the log print `application is now running` is displayed, stop the node with CTRL-C. Panic should not occur.
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside …
=> Fixed web server closing when the web server is disabled

epochStart/bootstrap/process_test.go, genesis/process/disabled/feeHandler.go, testscommon/cryptoMocks/signerStub.go
- bootstrap interceptors threw away SetGuardian transactions
- fixed the return value on `MaxGasPriceSetGuardian` method for the disabled fee handler
- standard system test, import-db testing
=> Fixed return value in the `MaxGasPriceSetGuardian` method on the disabled fee handler 

common/reflectcommon/structFieldsUpdate.go, common/reflectcommon/structFieldsUpdate_test.go
- There was a bug when trying to override the `Antiflood.NumConcurrentResolverJobs` config
- Treat the case for `int32` config entries
=> overridable configs fix

cmd/sovereignnode/config/sovereignConfig.toml, cmd/sovereignnode/go.mod, cmd/sovereignnode/go.sum, config/sovereignConfig.go, dataRetriever/dataPool/sovereign/outGoingOperationPool.go, dataRetriever/dataPool/sovereign/outGoingOperationPool_test.go, errors/errors.go, factory/processing/blockProcessorCreator.go, go.mod, go.sum, integrationTests/testProcessorNode.go, process/block/displayBlock.go, process/block/displayBlock_test.go, process/block/export_test.go, process/block/interface.go, process/block/sovereign/interface.go, process/block/sovereign/outgoingOperations.go, process/block/sovereign/outgoingOperations_test.go, process/block/sovereignChainBlock.go, process/block/sovereignChainBlock_test.go, testscommon/sovereign/outGoingOperationsPool.go, testscommon/sovereign/outgoingOperationsFormatterMock.go, testscommon/sovereign/outgoingOperationsFormatterStub.go, testscommon/transactionCoordinatorMock.go
- Added outgoing operations pool. This is a cache which stores outgoing txs data at their specified hash. Each entry in cache has an expiry time. We should `Delete` entries from this cache once the confirmation from the notifier is received that the outgoing operation has been sent to main chain. An unconfirmed operation is a tx data operation which has been stored in cache for longer than the time to wait for unconfirmed outgoing operations. The leader of the next round should check if there are any unconfirmed operations and try to resend them. [TBD] here a mechanism to check if the unconfirmed operations are truly missing or the leader is having trouble with his notifier and didn't receive the confirmation
- Integrated this pool in sovereign chain block processor.
Based on the …
=> Outgoing operations pool

node/chainSimulator/chainSimulator.go, node/chainSimulator/chainSimulator_test.go, node/chainSimulator/components/testOnlyProcessingNode.go, node/chainSimulator/components/testOnlyProcessingNode_test.go, node/chainSimulator/process/interface.go
- Extended  chain simulator with an extra function that can set state of an account
=> Extra endpoint `chan_simulator` SetState

README.md, api/gin/common_test.go, api/gin/webServer.go, api/mock/facadeStub.go, api/shared/interface.go, cmd/node/CLI.md, cmd/node/flags.go, cmd/seednode/CLI.md, cmd/seednode/api/api.go, cmd/seednode/main.go, config/config.go, config/contextFlagsConfig.go, facade/initial/initialNodeFacade.go, facade/initial/initialNodeFacade_test.go, facade/nodeFacade.go, facade/nodeFacade_test.go, go.mod, node/nodeRunner.go
- libp2p prometheus dashboards can be used for a useful overview over different metrics
- added new flag to start a new route `/debug/metrics/prometheus`
- updated readme with steps to start the dashboards
- standard system test + follow the [readme steps](https://github.com/multiversx/mx-chain-go/tree/prometheus_dashboards#running-p2p-prometheus-dashboards) …
=> Added new flag + readme for starting p2p prometheus dashboards

node/external/blockAPI/metaBlock.go, node/external/blockAPI/shardBlock.go
- rand seed and prev rand seed are missing from the apiBlock
- add randSeed and prevRandSeed on the apiBlock
- request blocks from the node and from the proxy and the randSeed and prevRandSeed fields should be populated
=> added randSeed and prevRandSeed on api blocks

outport/notifier/eventNotifier.go, outport/notifier/eventNotifier_test.go
- Handle notifier revert data with new data payload structure
- Test the following 2 scenarios on system tests that includes block reverts:
- HTTP integration: observer + notifer with old http integration enabled
- WebSocket integration: observer + notifier with WS integration enabled
- WebScoket integration is available only after upgrade
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside …
=> use new payload for revert in http integration

process/block/metablock.go, process/block/shardblock.go
- fixed forgotten mutex.Unlock calls
- 
- 
- 
- 
- 
- 
=> Fixed forgotten mutexes Unlock calls

keysManagement/managedPeersHolder.go, keysManagement/managedPeersHolder_test.go
- node will panic in multikey mode if a key from allValidatorsKeys.pem is defined in the NamedIdentities section
- make sure each and every peerInfo instance contains a not nil redundancy handler
- start a node in multikey mode. A BLS key from the set should be defined in the NamedIdentities section. A node without this fix will panic after bootstrapping.   …
=> Fixed managed peers holder

consensus/spos/bls/subroundStartRound.go, consensus/spos/bls/subroundStartRound_test.go
- in single-key operation mode, the redundancy machines can generate forks
- cancel start subround in single key redundancy mode
- single key redundancy tests
=> Temporary fix for the single-key redundancy system

consensus/spos/bls/subroundBlock.go, consensus/spos/bls/subroundStartRound.go, consensus/spos/bls/subroundStartRound_test.go
- multikey redundancy stopped working after merging this PR https://github.com/multiversx/mx-chain-go/pull/5808
- proper fix for redundancy 
- single-key & multi-key redundancy tests
=> Proper fix for redundancy

cmd/node/config/prefs.toml
- fixed comments in prefs.toml
- 
- 
- 
- not needed, non production code affected
=> Fixed comments in prefs.toml

cmd/logviewer/CLI.md, cmd/logviewer/main.go, cmd/logviewer/tls.go
- Load tls certificate into log viewer to be used when using the ws dialer
- Tested with a generated certificate from sovereign bridge tx server and it works
=> Load tls config into logviewer

cmd/node/config/enableEpochs.toml, cmd/node/main.go, config/configChecker.go, config/configChecker_test.go, config/errors.go, config/interface.go, node/nodeRunner.go, scripts/testnet/include/config.sh
- Remove enforced config protections
- Moved `SanityCheckEnableEpochsStakingV4` (now `sanityCheckEnableEpochsStakingV4`) inside `SanityCheckNodesConfig`
- Minor extra cleanings
- Local testnet
=> FIX: Remove enforced config protections

trie/patriciaMerkleTrie.go, trie/patriciaMerkleTrie_test.go
- put back mutex protection
- 
- 
- 
- 
- 
- 
=> Put back mutex protection

consensus/spos/errors.go, consensus/spos/worker.go, consensus/spos/worker_test.go
=> verify header hash

cmd/sovereignnode/config/sovereignConfig.toml, config/sovereignConfig.go, factory/processing/blockProcessorCreator.go, testscommon/components/configs.go, testscommon/generalConfig.go
-  Add back subscribed events for outgoing operations
- Local testnet
=> FIX: Add back subscribed events for outgoing operations

cmd/seednode/main.go, go.mod, go.sum, p2p/disabled/networkMessenger.go, testscommon/p2pmocks/messengerStub.go
- added protocol ID check in seeder for better debugging experience
- related PR: https://github.com/multiversx/mx-chain-communication-go/pull/47
- the seeder now displays a table like this:
```
INFO [2024-01-23 20:39:05.436]   peers info                               num known peers = 3 num connected peers = 2 
INFO [2024-01-23 20:39:05.436]   
+------------------------------------------------------------------------------------+--------------------+
| Connected peers                                                                    | Valid protocol ID? |
+------------------------------------------------------------------------------------+--------------------+
| /ip4/127.0.0.1/tcp/40938/p2p/16Uiu2HAm8YvJcudqcMHrSJkGds9KJN2fXr57Fohws1fSZ35kE8pi |     !!! no !!!     |
| …
```
=> Protocol ID check in seeder

consensus/spos/bls/subroundEndRound.go, process/block/baseProcess.go, process/block/baseProcess_test.go, process/block/metablock_test.go, process/block/shardblock_test.go, process/headerCheck/common.go, process/headerCheck/common_test.go
- fixed multikey backup step-in by filtering the consensus group that created the block by applying the bitmap. Without this, the backup node can not step in as it continuously resets the counters for the monitored keys 
- apply the bitmap filtering extracted in a common function for reusability reasons
- standard system-test
- multikey & singlekey backup scenarios
- if this is a `feat` branch merging, do all satellite projects …
=> Fix multikey backup step in

cmd/node/config/config.toml, cmd/node/config/enableEpochs.toml, cmd/sovereignnode/config/enableEpochs.toml, cmd/sovereignnode/go.mod, cmd/sovereignnode/go.sum, go.mod, go.sum
- MX-14985 task
- 
- 
- set IsPayableBySCEnableEpoch = 0
- 
- 
- 
- 
=> config param update

epochStart/metachain/auctionListDisplayer.go, epochStart/metachain/auctionListDisplayer_test.go, epochStart/metachain/auctionListSelector.go, epochStart/metachain/auctionListSelector_test.go, epochStart/metachain/auctionListSorting.go, epochStart/metachain/errors.go, epochStart/metachain/interface.go, epochStart/metachain/systemSCs_test.go, epochStart/metachain/tableDisplayer.go, factory/disabled/auctionListDisplayer.go, factory/processing/blockProcessorCreator.go, integrationTests/testProcessorNode.go, integrationTests/vm/staking/systemSCCreator.go, testscommon/tableDisplayerMock.go
- We use the same component `AuctionListSelector` for both computation at the end of the epoch and api calls simulation
- Since this component used to print a lot of data to the log, therefore causing increased storage needs, we needed to disable it for api calls
- Moved all storage expensive table displayers into a new component: `auctionListDisplayer`.
- This above mentioned displayer is used only for epoch start computation. For api component, we use a disabled one
- Run a system test with debug level, multiKey and enough nodes in network to always have the auction list filled
- After epoch 6 (when whole stakingV4 chain is enabled), we should periodically call `validator/auction` route and make sure that no table is printed
- Meanwhile, starting epoch 6, at each epoch change, we should …
=> Add auction list displayer component and disable it on api

process/block/preprocess/sovereignChainTransactions.go, process/block/preprocess/sovereignChainTransactions_test.go, process/block/preprocess/transactions.go, process/block/preprocess/transactionsV2.go
- Correction for transactions that should be added in the scheduled mini block
- 
- 
- `isTransactionEligibleForExecution` function should return the error
error => is not added in the miniblock and for some cases removed from txpool (e.g. InsufficientFee, LowerNonce)
no error => is added in the miniblock (including txs with InsufficientFunds)
- running sovereign node and sending bad transactions
- a full testing plan with transaction should be defined later
- 
- if this is a larger feature that probably needs more than one PR, is …
=> miniblocks transactions fixes and unit tests

scripts/testnet/include/config.sh, scripts/testnet/include/observers.sh, scripts/testnet/variables.sh
- with the deprecation of -no-key flag, the local testnets scripts would start the observers as multi key nodes
- fix scripts
- only scripts changes
=> Fix scripts for local testnet in multikey mode

api/groups/validatorGroup_test.go, common/dtos.go, integrationTests/chainSimulator/staking/delegation_test.go, integrationTests/chainSimulator/staking/stakeAndUnStake_test.go, process/peer/validatorsProviderAuction.go, process/peer/validatorsProvider_test.go
- Renamed auction list api response for auction nodes to nodes in order to avoid redundant naming
=> FIX: Rename auction list nodes to nodes

epochStart/metachain/legacySystemSCs.go, epochStart/metachain/systemSCs_test.go, epochStart/metachain/validators.go
- When staking new nodes from queue to auction list in `StakingV4Step1`, in some edge cases with queued inactive jailed validators, when sending them to auction (after they are unjailed), they would appear as duplicates when trying to sort them. This, however, would be fixed in nodes coordinator, therefore would not have any impact of the code. This is something that happens on existing code(before stakingV4) anyway
- However, starting stakingV4, we will delete such existing nodes(if found) and replace them with the new ones
- Initially found in this test `TestChainSimulator_FromQueueToAuctionList` as a `WARN`, from this pr: https://github.com/multiversx/mx-chain-go/pull/5937. Tested the fix with that integration test and it works
Based on the [Contributing …
=> FIX: Duplicated pub key in stakingV4

process/block/baseProcess.go, process/block/metablock.go, process/block/shardblock.go
- Configurable delay request block info `baseProcessor.go`
=> Base process configurable delay request block info

process/smartContract/processProxy/processProxy.go, process/smartContract/processProxy/processProxy_test.go, process/smartContract/processProxy/testProcessProxy.go
- using IsFlagEnabled could lead to an edge case where EpochConfirmed from enableEpochsHandler is called after processProxy's one
- replaced with IsFlagEnabledInEpoch
- standard system test + import-db, will be run on feat branch
=> Process proxy fix

dataRetriever/factory/dataPoolFactory.go, storage/factory/dbConfigHandler.go, storage/factory/export_test.go, storage/factory/persisterCreator.go, storage/factory/persisterCreator_test.go, storage/factory/persisterFactory.go, storage/factory/persisterFactory_test.go
- Use `UseTmpAsFilePath` db config field for all persisters
- Standard testing procedure
=> Persister tmp file path

cmd/node/flags.go, common/operationmodes/historicalBalances.go, common/operationmodes/historicalBalances_test.go, common/operationmodes/operationmodes.go, factory/api/apiResolverFactory.go, process/smartContract/scQueryService.go, process/smartContract/scQueryService_test.go
- In some cases, deep VM queries against old epochs caused subsequent VM queries on recent blocks to fail.
```
print("Causing the issue...")
do_contract_query(recent_block - 6 * 14400)
do_contract_query(recent_block - 5 * 14400)
do_contract_query(recent_block - 4 * 14400)
print("This will fail")
do_contract_query(recent_block)
print("Repairing the issue...")
do_contract_query(recent_block - 3 * 14400)
print("Now it will work")
do_contract_query(recent_block)
```
If observer is started in **deep-history mode**, perform deep VM queries, using `recreateTrieFromEpoch`. Otherwise, rely on `recreateTrie`. Most important work is done by https://github.com/multiversx/mx-chain-go/pull/6008.
- Regular testing
- VM queries stressing (default)
- VM queries against both old and new blocks (not only …
=> Deep VM queries: deep-history observer vs. regular observer

api/groups/transactionGroup.go, api/groups/transactionGroup_test.go, node/external/transactionAPI/apiTransactionProcessor.go, node/external/transactionAPI/apiTransactionProcessor_test.go, node/external/transactionAPI/fieldsHandler.go, node/external/transactionAPI/fieldsHandler_test.go
- missing fields in response of /transaction/pool by sender
- added new fields which can be requested: `guardian`, `guardiansignature`, `signature`, `sendershard`, `receivershard` and wildcard `*` which will return all fields as in the next picture
- will be tested with proxy branch [support_for_tx_pool_wild_card](https://github.com/multiversx/mx-chain-proxy-go/pull/432)
- standard system test + scenario:
- add 2 transactions in pool for a sender, one guarded and another one not guarded. Then check `/transaction/pool?by-sender=erd1....&fields=` with the new fields.
- also check that a combination of fields and wildcard is not possible. Eg fields=nonce,*
Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) …
=> Added missing fields on the transaction/pool by-sender request

consensus/spos/bls/sovereignSubRoundEnd.go, consensus/spos/bls/sovereignSubRoundEnd_test.go
- Unconfirmed operations were only resent by the next leader if there were also operations in the current block to be bridged 
- If there is no outgoing operation in the current block, leader should check for unconfirmed operations and resend them
- 
- 
- 
=> FIX [sovereign] Resend of unconfirmed operation by next leader if no current operation found

cmd/sovereignnode/config/sovereignConfig.toml, config/sovereignConfig.go, errors/errors.go, process/block/sovereignBlockProcessorFactory.go, process/block/sovereignChainBlock.go, process/block/sovereignChainBlock_test.go, testscommon/generalConfig.go
- SHA256 hasher needed for outgoing operations because SC can only use SHA256 hasher
- 
- 
- add `OperationsHasher` in sovereign config
- 
- 
- unit tests
- 
=> Mx 15248 outgoing ops hasher

genesis/process/genesisBlockCreator_test.go, genesis/process/sovereignGenesisBlockCreator.go, genesis/process/sovereignGenesisBlockCreator_test.go
- Removed createSovereignGenesisESDTTransfers to avoid double spending.
- Since we introduced sovereign accounts creator, initial esdt balances are directly set to trie into genesis processor, so there is no need to create initial cross shard esdt transfers, since that would double the balance from initial config. 
- Local testnet
=> FIX: Remove createSovereignGenesisESDTTransfers to avoid double spending

integrationTests/chainSimulator/staking/stakingProviderWithNodesinQueue_test.go, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/eei.go, vm/systemSmartContracts/stakingWaitingList.go, vm/systemSmartContracts/staking_test.go
Bugfix as nodes remain in undefined state from the delegation contract perspective after the activation of staking v4 and unStaking of nodes from queue
Called unStakeAtEndOfEpoch on delegation contracts to fix thee state of nodes.
Before activation of staking v4, create a delegation contract and add nodes to the queue. After the activation call reStakeUnStakedNodes and it should work …
=> fixed unstaked list on delegation when nodes are unstaked from queue

common/constants.go, dataRetriever/blockchain/blockchain.go, dataRetriever/blockchain/metachain.go, node/metrics/metrics.go, node/metrics/metrics_test.go, scripts/testnet/include/config.sh, scripts/testnet/variables.sh, statusHandler/persister/persistentHandler.go, statusHandler/statusMetricsProvider.go, statusHandler/statusMetricsProvider_test.go
- added block timestamp + scripts update for the round duration
- added the possibility to define the round duration in the local scripts (related PR: https://github.com/multiversx/mx-chain-deploy-go/pull/52) 
- 
- 
- 
- test that the proxy's API endpoint route `/network/status/0`, `/network/status/1` ... `/network/status/4294967295` returns the new field called `erd_block_timestamp` that matches the block's timestamp.
- if this is a larger feature that probably needs more than one PR, is there a `feat` …
=> Added block timestamp + scripts update for the round duration

common/constants.go, common/enablers/enableEpochsHandler.go, common/enablers/enableEpochsHandler_test.go, epochStart/metachain/legacySystemSCs.go, epochStart/metachain/systemSCs.go, epochStart/metachain/systemSCs_test.go, state/interface.go, state/validatorsInfoMap.go
- Possible backwards incompatibility issues
=> FIX: Possible backwards incompatibilities fixes

epochStart/dtos.go, epochStart/interface.go, epochStart/metachain/auctionListSelector.go, epochStart/metachain/stakingDataProvider.go, epochStart/metachain/systemSCs_test.go, integrationTests/chainSimulator/interface.go, integrationTests/chainSimulator/staking/stake/stakeAndUnStake_test.go, integrationTests/vm/staking/stakingV4_test.go, integrationTests/vm/staking/testMetaProcessorWithCustomNodesConfig.go, testscommon/stakingcommon/stakingDataProviderStub.go
- In case of leaving active nodes in epoch (waiting/eligible), as long as there leaving nodes per shard < number of active nodes && leaving nodes per shard  < number nodes to shuffle per shard, those will not be shuffled out, they can leave. If there are more nodes per shard that are leaving than the number of nodes to shuffle per shard, the remaining will be forced to stay
- Fix auction list selection algorithm to consider leaving active nodes and forced nodes to stay when computing number of avaiable slots to select qualified nodes.
- One easy starting point would be to do something similar to this test: `TestChainSimulator_UnStakeOneActiveNodeAndCheckAPIAuctionList`
Scenario 1: 
- Have every epoch auction list with enough nodes (let's say 8 qualified, 2 unqualified)
- Unstake 1 or more …
=> POC: Distribute to waiting from auction based on leaving nodes

epochStart/metachain/legacySystemSCs.go, factory/runType/sovereignRunTypeComponents.go, genesis/process/common/initialization.go, genesis/process/common/initialization_test.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/sovereignGenesisBlockCreator.go, genesis/process/sovereignGenesisBlockCreator_test.go, testscommon/state/accountWrapperMock.go
- Fix unknown async call error when a sc tries to call a meta chain sc address(like esdt issue)
- Reused init func for esdt sys accounts from epoch change flow
- Fixed sovereign blockchain pointers in run type components 
- 
=> [sovereign] Add system sc code data

cmd/sovereignnode/sovereignNodeRunner.go, dataRetriever/mock/shardRequestersContainerFactoryMock.go, factory/interface.go, factory/processing/processComponents.go, factory/processing/processComponents_test.go, factory/runType/runTypeComponents.go, factory/runType/runTypeComponentsHandler.go, factory/runType/runTypeComponentsHandler_test.go, factory/runType/sovereignRunTypeComponents.go, integrationTests/realcomponents/processorRunner.go, node/chainSimulator/components/processComponents.go, node/nodeRunner.go, testscommon/components/components.go, testscommon/dataRetriever/shardRequestersContainerFactoryMock.go, testscommon/factory/requestersContainerFactoryMock.go, testscommon/mainFactoryMocks/runTypeComponentStub.go
- refactor `RequesterContainerFactoryCreator`
- 
- 
- 
- 
- 
- 
- 
- 
=> refactor RequesterContainerFactoryCreator

.github/workflows/build_and_test.yml, .github/workflows/create_release.yml
Drop `macos-latest` runner (for some time, that's an M1, as well, but with less memory). For non-ARM64 runners, we could have used `macos-13`. 
However, for practicality, we'll only run the workflows on Ubuntu (AMD64) and MacOS (ARM64).
References:
- https://github.com/actions/runner-images/issues/9741
- https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
=> Adjust workflow runners (MacOS)

node/chainSimulator/chainSimulator.go, node/chainSimulator/chainSimulator_test.go, node/chainSimulator/components/testOnlyProcessingNode.go, node/chainSimulator/configs/configs.go, node/chainSimulator/process/interface.go, testscommon/chainSimulator/nodeHandlerMock.go
- Added a new method that will trigger a change of epoch 
=> `chain simulator` force change of epoch

epochStart/metachain/stakingDataProvider.go, epochStart/metachain/stakingDataProvider_test.go, process/peer/validatorsProvider.go, process/peer/validatorsProviderAuction.go, process/peer/validatorsProvider_test.go, vm/process/systemVM.go
=> add system vm critical section

node/chainSimulator/chainSimulator_test.go, node/chainSimulator/components/interface.go, node/chainSimulator/components/processComponents.go, node/chainSimulator/components/syncedTxsSender.go, node/chainSimulator/components/syncedTxsSender_test.go, node/chainSimulator/components/testOnlyProcessingNode.go, node/chainSimulator/components/testOnlyProcessingNode_test.go, node/chainSimulator/dtos/state.go
- the chain simulator uses the same component used by the regular node to broadcast the transactions. The default component contains an accumulator that gathers transactions for about 100 milliseconds and then dispatches them as a group of transactions. The dispatching mechanism uses a data packer to split the accumulated transactions into smaller packets (if required and if it is possible)
- renaming the `keys` to `pairs` (related to https://github.com/multiversx/mx-chain-go/pull/6179):
The endpoint `/address/:address?withKeys=true` is going to return something of this type:
```
type AccountResponse struct {
Address         string            `json:"address"`
Nonce           uint64            `json:"nonce"`
Balance         string            `json:"balance"`
Username        string …
```
=> Chain simulator custom transactions sender component

process/block/sovereignChainBlock.go, process/interface.go, process/peer/process.go, testscommon/validatorStatisticsProcessorStub.go
- When reverting state, the header was cast to a meta header
- Changed interfaces and `RevertState` in sovereign not to cast to meta header
- 
- 
- 
=> FIX: Revert state in sovereign

node/chainSimulator/chainSimulator.go
- Especially for deployed contracts
- 
- 
- 
- 
- 
- 
=> FIX: Destination shard id in chain simulator for meta chain addresses

cmd/sovereignnode/chainSimulator/sovereignChainSimulator.go, cmd/sovereignnode/chainSimulator/tests/bridge/bridge_test.go, cmd/sovereignnode/chainSimulator/tests/bridge/common.go, process/block/preprocess/basePreProcess.go, process/block/sovereignChainBlock.go, process/coordinator/process.go
- When setting outgoing mb after whole processing is done (which contain outgoing operations),  there are some extra checks that can cause the chain to halt. Mainly, we were missing some saved txs for the outgoing tx hashes, which were not found and also failed gas limit checks
-  Since we weren't saving outgoing operations anyway (especially the data inside time), I think it's better to save it in the storage as a "dummy" tx with the outGoingTxData that is used by the bridge service to format txs for main chain.
- 
- 
- 
- if this …
=> FIX: Outgoing op tx hash

epochStart/metachain/common.go, epochStart/metachain/legacySystemSCs.go, epochStart/metachain/systemSCs.go, factory/processing/processComponents_test.go, genesis/mock/coreComponentsMock.go, genesis/process/argGenesisBlockCreator.go, genesis/process/common/initialization.go, genesis/process/genesisBlockCreator.go, genesis/process/genesisBlockCreator_test.go, genesis/process/shardGenesisBlockCreator.go, genesis/process/sovereignGenesisBlockCreator.go, genesis/process/sovereignGenesisBlockCreator_test.go, genesis/process/vmNodesCoord.go, testscommon/genesisMocks/runTypeComponentsStub.go
- If we start a sovereign chain with all enable epochs on 0, some system sc init execution that happen at the end of epoch are not executed. 
- In sovereign genesis processing, we will init system sc contract funcs(delegation + governance) by default
- Moved some code from system sc in the common genesis package to be used by sov genesis block creator
- 
- 
-  …
=> FIX: System sc end of epoch init for genesis block on sovereign

integrationTests/chainSimulator/staking/jail/jail_test.go, integrationTests/chainSimulator/staking/stake/simpleStake_test.go, integrationTests/chainSimulator/staking/stake/stakeAndUnStake_test.go, integrationTests/chainSimulator/staking/stakingProvider/delegation_test.go, integrationTests/chainSimulator/staking/stakingProvider/stakingProviderWithNodesinQueue_test.go, integrationTests/chainSimulator/vm/esdtImprovements_test.go, node/chainSimulator/chainSimulator_test.go, node/chainSimulator/components/cryptoComponents_test.go, node/chainSimulator/components/processComponents.go
- chain simulator used a disabled white list data verifier that returns true on IsWhitelisted method, thus the transactions sent through chain simulator would have never been checked
- use other implementation of disabled white list data verifier
- chain simulator only, no test needed
=> ChainSimulator: verify tx on send

cmd/node/config/enableEpochs.toml, common/constants.go, common/enablers/enableEpochsHandler.go, common/enablers/enableEpochsHandler_test.go, config/epochConfig.go, config/tomlConfig_test.go, integrationTests/chainSimulator/relayedTx/relayedTx_test.go, integrationTests/multiShard/relayedTx/common.go, integrationTests/testProcessorNode.go, integrationTests/vm/txsFee/multiShard/relayedMoveBalance_test.go, integrationTests/vm/txsFee/relayedBuiltInFunctions_test.go, integrationTests/vm/txsFee/relayedESDT_test.go, integrationTests/vm/txsFee/relayedScCalls_test.go, integrationTests/vm/txsFee/relayedScDeploy_test.go, node/metrics/metrics.go, node/metrics/metrics_test.go, process/transaction/baseProcess.go, process/transaction/metaProcess.go, process/transaction/shardProcess.go, process/transaction/shardProcess_test.go, sharding/mock/enableEpochsHandlerMock.go
- the fix for move balance should actually be fix for base cost
- updated the fix to also cover other inner txs than move balance
- will be verified on feat branch
=> Rename FixRelayedMoveBalanceFlag to FixRelayedBaseCostFlag + proper fix

process/common.go
- The function `DisplayProcessTxDetails` is called in a few places during transactions processing. Its main concern is to display some data by means of Log.Trace(). In this regard, it performs some computation, which takes some non-negligible time (analyzed with _pprof_).
- Skip the computations performed by  `DisplayProcessTxDetails` if it should display nothing, given the current log level.
- Standard testing.
- if this is a …
=> Optimize "DisplayProcessTxDetails": Early exit if log level is not TRACE

epochStart/metachain/sovereignValidatorInfoCreatorFactory.go, epochStart/metachain/sovereignValidatorInfoCreatorFactory_test.go, epochStart/metachain/sovereignValidators.go, epochStart/metachain/sovereignValidators_test.go, epochStart/metachain/validatorInfoCreatorFactory.go, epochStart/metachain/validatorInfoCreatorFactory_test.go, epochStart/metachain/validators.go, errors/errors.go, factory/interface.go, factory/processing/blockProcessorCreator.go, factory/processing/processComponents.go, factory/processing/processComponents_test.go, factory/runType/runTypeComponents.go, factory/runType/runTypeComponentsHandler.go, factory/runType/runTypeComponentsHandler_test.go, factory/runType/sovereignRunTypeComponents.go, integrationTests/testProcessorNode.go, process/block/preprocess/validatorInfoPreProcessor.go, process/block/sovereignChainBlock.go, testscommon/components/components.go, testscommon/factory/validatorInfoCreatorFactoryMock.go, testscommon/mainFactoryMocks/runTypeComponentStub.go
- Save validator info data for peer miniblocks in sovereign chain block processing part
- No need to broadcast data for epoch start peer mbs and intercept it to be added in pool
- When creating validator infos, we will save them directly in pool inside `sovereignValidatorInfoCreator`, which will be called at processing epoch start block level in `sovereignChainBlock`
- 
- 
- 
- if this is a `feat` branch merging, do all satellite …
=> [sovereign] Save validators info shard data epoch change

cmd/node/config/enableEpochs.toml, common/constants.go, common/enablers/enableEpochsHandler.go, common/enablers/enableEpochsHandler_test.go, config/epochConfig.go, config/tomlConfig_test.go, go.mod, go.sum, node/metrics/metrics.go, node/metrics/metrics_test.go, statusHandler/statusMetricsProvider.go, statusHandler/statusMetricsProvider_test.go
=> Multi transfer execute by user flag

integrationTests/chainSimulator/vm/esdtImprovements_test.go, vm/systemSmartContracts/esdt.go
- Fix missing role in singular roles check
- Added integration test
- register dynamic token --> try to set `ESDTRoleNFTUpdate` role multiple times
=> Dynamic roles singular

go.mod, go.sum
=> even newer wasmer

.github/workflows/build_and_test.yml, .github/workflows/create_release.yml, go.mod, go.sum
=> Merge master into rc17next1 2024.08.08

.github/workflows/docker-keygenerator.yaml
- Building the Docker image for keygenerator on each pull request is not necessary.
- Removed the pull request trigger from the GitHub Actions workflow, leaving only the manual workflow_dispatch trigger active.
- 
- 
- 
=> Keygen workflow remove pull request action trigger

integrationTests/chainSimulator/relayedTx/relayedTx_test.go, process/transaction/export_test.go, process/transaction/shardProcess.go
- when multiple inner txs fail with the same error(non executable), only one scr will be generated due to all scrs having the same hash
- improved return message on scr in order to reflect which inner tx failed, resulting in different hashes each time
- standard system test + test relayed v3 with multiple inner txs from the same sender with higher/lower nonce …
=> fixed missing scrs when multiple inner tx fail with the same error, caused by hash collision

cmd/node/CLI.md, cmd/node/config/lightClientP2P.toml, cmd/node/config/prefs.toml, cmd/node/flags.go, cmd/node/main.go, common/constants.go, common/generics.go, config/config.go, config/prefsConfig.go, errors/errors.go, factory/network/networkComponents.go, factory/network/networkComponentsHandler.go, factory/network/networkComponents_test.go, integrationTests/factory/componentsHelper.go, integrationTests/factory/constants.go, integrationTests/realcomponents/processorRunner.go, node/nodeRunner.go, p2p/constants.go, testscommon/components/components.go
- Light clients will connect on this additional network messenger.
- Similar to the full archive network, another one has been added for the light client suppliers to connect to.
- Start a seednode with mvx-light-client protocol ID.
- Start a node with the InitialPeerList in lightClientP2P.toml set from the seednode you just started.
- Connection should work, add more nodes if needed.  …
=> New p2p network messenger for the light clients and suppliers.

scripts/testnet/include/config.sh, scripts/testnet/prerequisites.sh, scripts/testnet/sovereignBridge/config/common.snippets.sh
- `NFTs` tab in explorer was not working
- 
- 
- Need to run the tool to update indices at startup, if elasticsearch is enabled
- 
- 
- 
- 
- 
=> elasticsearch indices update at startup

go.mod, go.sum
=> crypto ei signature hooks errors

go.mod, go.sum
=> new vm go tag

epochStart/bootstrap/baseStorageHandler.go, epochStart/bootstrap/bootStrapSovereignShardProcessor.go, epochStart/bootstrap/bootStrapSovereignShardProcessor_test.go, epochStart/bootstrap/interface.go, epochStart/bootstrap/metaStorageHandler.go, epochStart/bootstrap/shardSovereignStorageHandler.go, epochStart/bootstrap/shardSovereignStorageHandler_test.go, epochStart/bootstrap/shardStorageHandler.go
- Sovereign shard storage handler for bootstrap
- Used internal `sovereignShardStorageHandler` constructor to be used in `sovereignBootStrapShardProcessor` for saving bootstrap data.
- `SaveDataToStorage` is a bit of combination of both `shardStorageHandler` & `metaStorageHandler`, but more inspired by meta one. Please careful review here
- 
- 
- 
- if this is a `feat` branch merging, do all satellite projects have a proper tag …
=> [sovereign] Shard Storage handler

cmd/sovereignnode/chainSimulator/tests/processBlock/cleanupHeaders_test.go, process/block/sovereignChainBlock.go
- The same first dummy cross header is added in the block tracker until a valid cross chain header was received
- 
- 
- Only if there's a new cross chain header processed then call the save function
- 
- 
- 
- 
- 
=> cross header notarization fix

go.mod, go.sum, integrationTests/chainSimulator/vm/esdtImprovements_test.go
- If the metaData of a dynamic token is updated by an address which does not have the actual token in it's balance, the update works as expected, but the nonce field is not set, so it will be 0.
- In the case described above, set the nonce field with the actual nonce of the token
- Add more integration tests
- Normal test
=> update vm common version and add integration tests

vm/systemSmartContracts/governance.go, vm/systemSmartContracts/governance_test.go
=> MX-15031: Add cancel method before voting start

process/block/metrics.go, process/block/shardblock.go, process/block/sovereignChainBlock.go
- Save missing metrics for committed sovereign block
- Added cross metric for main chain notarized header, similar to the one from meta chain on mainnet
- 
- 
- 
```
/ 20241002182609
// http://127.0.0.1:10000/network/status
{
"data": {
"status": {
"erd_block_timestamp": 1727882769,
"erd_cross_check_block_height": "mainChain 0",
"erd_current_round": 451,
"erd_epoch_number": 20,
"erd_highest_final_nonce": 450,
"erd_nonce": 451,
"erd_nonce_at_epoch_start": 440,
"erd_nonces_passed_in_current_epoch": 11,
"erd_round_at_epoch_start": 440,
"erd_rounds_passed_in_current_epoch": 11,
"erd_rounds_per_epoch": 21
}
},
"error": "",
"code": "successful"
}
```
Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR …
=> [sovereign] Save metrics for committed block

cmd/sovereignnode/chainSimulator/tests/epochChange/epochChange_test.go, integrationTests/chainSimulator/staking/common.go, integrationTests/chainSimulator/staking/stake/stakeAndUnStake_test.go
- Check vm query staked bls key status for staked nodes in integration tests for sovereign
- 
- 
- 
- 
- 
- 
=> [sovereign] Extend staked node tests

integrationTests/chainSimulator/vm/esdtImprovements_test.go
- There are some flows that have not been tested yet
- Add more testing scenarios
- No testing needed, changes made only in testing files
=> add more integration tests

node/external/transactionAPI/apiTransactionProcessor.go, node/external/transactionAPI/gasUsedAndFeeProcessor.go, node/external/transactionAPI/gasUsedAndFeeProcessor_test.go, node/external/transactionAPI/testData/relayedV1CreateNewDelegationContract.json, outport/process/transactionsfee/transactionsFeeProcessor.go
- node api does not take into account the latest fix for base cost of relayed when computing fees with refund
- proper fix
- system test + scenarios
=> fix gasUsed and fee for relayed v1 and v2

cmd/node/config/external.toml, go.mod, go.sum, node/chainSimulator/components/memoryComponents.go, outport/factory/hostDriverFactory_test.go, outport/factory/outportFactory_test.go, testscommon/components/components.go
- Updated the version of mx-chain-communication-go
- PR from 'mx-chain-communication-go': https://github.com/multiversx/mx-chain-communication-go/pull/59
- Check If node with  'HostDriver' enabled is working correctly 
=> new version of mx-chain-comm-go

process/block/sovereign/incomingHeader/extendedHeaderProcessor.go, process/block/sovereign/incomingHeader/incomingHeaderProcessor.go
- request headers go routine is requesting headers which should actually be in the pool already
- 
- 
- first `addSCRsToPool`, then `addExtendedHeaderToPool`
- 
- 
- 
- 
- 
=> fix request incoming SCRs

process/common.go, process/common_test.go
- Utility function to get extended header from storage
- 
- 
- 
- 
- 
- 
=> [sovereign] Get extended header from storage

cmd/node/config/external.toml, cmd/sovereignnode/config/sovereignConfig.toml, cmd/sovereignnode/go.mod, cmd/sovereignnode/go.sum, cmd/sovereignnode/systemTestDemo/mockNotifier/vars.go, go.mod, go.sum, outport/factory/hostDriverFactory_test.go, outport/factory/outportFactory_test.go, scripts/testnet/sovereignBridge/observer/deployObserver.sh, scripts/testnet/sovereignBridge/observer/shard-observer, testscommon/components/components.go
- sovereign could not connect to testnet observer because mx-communication-go needs to be updated
- 
- 
- update dependency mx-communication-go
- fix in configs (similar to [this](https://github.com/multiversx/mx-chain-go/pull/6550/files))
- 
- 
- 
- 
=> updated communication-go dependency

process/block/sovereignChainBlock.go
- ProcessBlock metrics sometimes returned pointer error because were using go routines
- 
- 
- use metrics without go routine
- 
- 
- 
- 
- 
=> fix metrics on ProcessBlock

factory/vm/sovereignVmContainerShardCreator_test.go, factory/vm/vmContainerShardCreator_test.go
- Skip tests related to VM 1.4 for arm64 architecture
- 
- 
- 
- 
- 
- 
- 
- 
=> Skip tests for arm64 architecture

node/external/transactionAPI/apiTransactionProcessor.go
- SilentEncode prints a Warn log due to empty guardian address. The proper fix should be inside SilentEncode method, a simple check if len of pkBytes is 0 to return an empty string. Will be fixed in a next release.
- added a length check for guardian address to avoid SilentEncode on empty string
- standard system test, call either /transaction/pool/by-sender with some txs in pool, either /transaction/pool and check for warn like: `bech32PubkeyConverter.SilentEncode       hex buff =  error = wrong size when encoding address, expected length 32, received 0`
- was the PR …
=> fix spamming warnings from apiTransactionProcessor

cmd/sovereignnode/chainSimulator/tests/esdt/issueSc_test.go, cmd/sovereignnode/chainSimulator/tests/processBlock/cleanupHeaders_test.go, cmd/sovereignnode/chainSimulator/tests/processBlock/incomingHeader_test.go, cmd/sovereignnode/notifier/notifierBootstrapper.go, cmd/sovereignnode/notifier/notifierBootstrapper_test.go, cmd/sovereignnode/systemTestDemo/mockNotifier/notifier.go, common/enablers/enableEpochsHandler.go, process/block/baseProcess.go, process/block/sovereignChainBlock.go, process/sync/baseForkDetector.go, process/track/baseBlockTrack.go, process/track/blockProcessor.go, process/track/sovereignChainShardBlockTrack.go, process/track/sovereignChainShardBlockTrack_test.go
- Several bugs
- Fixed notifier bootstrapper to use a confidence threshold for synced times before subscribing to receive data. This is because the sync mechanism can sometimes send "false positives" 
- Fixed cleanup of notarized headers for cross shard. There was a very tricky bug, which would delete notarized mainchain headers instead of self chain headers
- 
- 
- 
- if this is a `feat` branch merging, do all satellite projects …
=> [sovereign] Bugfix notifier bootstrapper + cleanup notarized headers

epochStart/bootstrap/bootStrapSovereignShardProcessor.go, epochStart/bootstrap/bootStrapSovereignShardProcessor_test.go, epochStart/bootstrap/common.go, epochStart/bootstrap/disabled/disabledAccountsAdapter.go, epochStart/bootstrap/disabled/disabledAccountsAdapter_test.go, epochStart/bootstrap/factory/epochStartInterceptorsContainerFactory.go, epochStart/bootstrap/factory/epochStartInterceptorsContainerFactory_test.go, epochStart/bootstrap/interface.go, epochStart/bootstrap/process.go, epochStart/bootstrap/process_test.go
- When starting a node in epoch, we create args for interceptors using disabled components
- One of the disabled component, was the accounts db, which returned a nil acount, which was later being used, causing nil pointer dereference.
- Injected accounts creator from runTypeComps into disabled epoch start accounts db to return dummy/empty accounts
- 
- 
-  …
=> [sovereign] FIX: disabled accounts db in epoch start interceptor

factory/disabled/txProcessor.go, go.mod, go.sum, process/block/preprocess/accountStateProvider.go, process/block/preprocess/accountStateProvider_test.go, process/block/preprocess/basePreProcess.go, process/block/preprocess/interfaces.go, process/block/preprocess/selectionSession.go, process/block/preprocess/selectionSession_test.go, process/block/preprocess/sortedTransactionsProvider.go, process/block/preprocess/transactions.go, process/interface.go, process/transaction/baseProcess.go, process/transaction/baseProcess_test.go, process/transaction/export_test.go, storage/txcache/txcache.go, testscommon/txProcessorMock.go, testscommon/txProcessorStub.go
- This is an improvement upon https://github.com/multiversx/mx-chain-go/pull/6603.
- We should have no / as little as possible not-executable transactions in the bulk of selected transactions.
- https://github.com/multiversx/mx-chain-storage-go/pull/58
- Inform selection about not-executable transactions related to guardians, through exporting & using the `VerifyGuardian` function.
- Standard testing
- Send not-executable transactions (related to guardians). Inspect the logs and assert they aren't selected.
- if this is a larger …
=> Mempool: handle not-executable transactions related to guardians

go.mod, go.sum, integrationTests/singleShard/block/executingMiniblocks/executingMiniblocks_test.go, process/block/preprocess/selectionSession.go, process/block/preprocess/selectionSession_test.go, process/block/preprocess/transactions.go
- This is an improvement upon https://github.com/multiversx/mx-chain-go/pull/6603.
- We should have no / as little as possible not-executable transactions in the bulk of selected transactions.
- https://github.com/multiversx/mx-chain-storage-go/pull/59
- Inform selection about the value transferred within a transaction, so that it can stop selecting transactions from a sender that consumes all the balance (no more balance remaining for fees).
- Standard testing
- Craft sequences of transactions that also hold not-executable ones (balance consumed by the first of them).
- was …
=> Mempool: completely handle fees and transferred balances within "detectWillFeeExceedBalance()"

dataRetriever/factory/dataPoolFactory.go, dataRetriever/txpool/argShardedTxPool.go, dataRetriever/txpool/interface.go, dataRetriever/txpool/memorytests/memory_test.go, dataRetriever/txpool/mempoolHost.go, dataRetriever/txpool/mempoolHost_test.go, dataRetriever/txpool/shardedTxPool.go, dataRetriever/txpool/shardedTxPool_test.go, go.mod, go.sum, node/external/transactionAPI/apiTransactionProcessor_test.go, process/block/preprocess/selectionSession.go, process/block/preprocess/selectionSession_test.go, process/block/preprocess/transactions.go, storage/txcache/txcache.go, storage/txcache/txcache_test.go, testscommon/dataRetriever/poolFactory.go, testscommon/dataRetriever/poolsHolderMock.go, testscommon/txcachemocks/mempoolHostMock.go
- https://github.com/multiversx/mx-chain-go/pull/6637#discussion_r1861863598
- Parsing the data field of `MultiESDTNFTTransfer` transactions in order to recover transfers of the native currency incurs a non-negligible performance cost. 
- https://github.com/multiversx/mx-chain-storage-go/pull/60
- Compute `TransferredValue` when adding the transaction in the mempool (just like we do for `Fee`). Use the information at selection time.
- Move logic from `SelectionSession.GetTransferredValue()` to `MempoolHost.GetTransferredValue()`.
- Refactor dependencies of the `shardedTxPool` class.
- Standard testing
Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the …
=> Mempool optimization: on transaction addition, call "GetTransferredValue" and retain its value

cmd/node/config/config.toml, go.mod, go.sum
- When adding transactions in the mempool, the addition is subject to the so-called "sender constraints". Historically, the parameters that guide the constraints were [these](https://github.com/multiversx/mx-chain-mainnet-config/blob/v1.8.4.0/config.toml#L389).
- However, since, for some time, the interceptors apply [this constraint](https://docs.multiversx.com/integrators/creating-transactions/#issue-too-many-transactions-from-the-same-account), it's reasonable to adjust the "sender constraints", as well.
- https://github.com/multiversx/mx-chain-storage-go/pull/64
- `Adjust TxDataPool.SizePerSender` to a lower value.
- Standard testing.
Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author …
=> Mempool: adjust sender constraints

go.mod, go.sum, process/constants.go
- Since the selection flow does not include not-executable transactions anymore, we can use a lower `maxNum` when selecting transactions (optimization).
- Adjust constant `TxCacheSelectionMaxNumTxs` from 50k to 30k.
- https://github.com/multiversx/mx-chain-storage-go/pull/65
- Standard & heavy testing. 
=> Mempool: lower "maxNum" when selecting transactions

api/groups/networkGroup.go, node/node.go, node/node_test.go
- Add custom handling for NonFungibleESDT and NonFungibleESDTv2
- Observer and Proxy testing for "/network/esdt/non-fungible-tokens" endpoint - it should list all non fungible tokens
=> Fix get non fungible tokens list

common/interface.go, integrationTests/vm/txsFee/migrateDataTrie_test.go, trie/branchNode.go, trie/branchNode_test.go, trie/extensionNode.go, trie/extensionNode_test.go, trie/interface.go, trie/leafNode.go, trie/leafNode_test.go, trie/patriciaMerkleTrie.go, trie/patriciaMerkleTrie_test.go, trie/trieBatchManager/trieBatchManager.go, trie/trieBatchManager/trieBatchManager_test.go, trie/trieChangesBatch/trieChangesBatch.go, trie/trieChangesBatch/trieChangesBatch_test.go
- All the trie changes are added to a batch before being added to the trie. When the batch is commited to the trie, the changes are added one by one. 
- In order to reduce the time spent on saving the changes from the batch to the trie, add all the batched data to the trie in one go. 
- The next step will be to add the data to the trie using goroutines …
=> add batched changes to trie

node/external/transactionAPI/apiTransactionProcessor.go, node/external/transactionAPI/apiTransactionProcessor_test.go, node/external/transactionAPI/fieldsHandler.go, node/external/transactionAPI/fieldsHandler_test.go
- if hash is not explicitly provided, it is not returned in response
- when requesting with fields=*, senderShard and receiverShard are always 0
- fix the fields
- standard system test + add some cross shard txs in the pool. Check:
- /transaction/pool?fields=* returns proper shards for sender and receiver. 
- /transaction/pool?by-sender="sender"&fields="*" returns proper shards
- /transaction/pool?by-sender="sender"&fields=sender returns txHash as well(same for all combinations of fields)
- if this is a larger feature that probably …
=> Fix transaction/pool endpoint issues

common/interface.go, common/modifiedHashes.go, common/modifiedHashes_test.go, trie/branchNode.go, trie/branchNode_test.go, trie/errors.go, trie/extensionNode.go, trie/extensionNode_test.go, trie/goroutinesManager.go, trie/goroutinesManager_test.go, trie/interface.go, trie/leafNode.go, trie/leafNode_test.go, trie/mock/throttlerStub.go, trie/node.go, trie/node_test.go, trie/patriciaMerkleTrie.go
- All the trie changes are put in a batch. When a commit occurs, the changes batch is added to the trie, but the changes are done in serial. 
- When the changes from the batch need to be added to the trie, use goroutines where possible in order to speed up the update of the trie 
=> update trie on goroutines

consensus/spos/bls/v2/export_test.go, consensus/spos/bls/v2/subroundEndRound.go, consensus/spos/bls/v2/subroundEndRound_test.go, consensus/spos/worker.go, factory/interface.go, testscommon/consensus/sposWorkerMock.go
=> Subround endround v2 tests

process/headerCheck/headerSignatureVerify.go
- leader sig should not be removed while checking the header signature
- avoid removing the leader signature
=> Fix header verification after equivalent proofs

cmd/sovereignnode/chainSimulator/sovereignChainSimulator.go, cmd/sovereignnode/go.mod, cmd/sovereignnode/go.sum, factory/api/apiResolverFactory_test.go, factory/block/sovereignShardHeaderFactory.go, factory/block/sovereignShardHeaderFactory_test.go, factory/bootstrap/bootstrapComponents.go, factory/bootstrap/bootstrapComponents_test.go, factory/interface.go, factory/processing/processComponents_test.go, factory/runType/runTypeComponents.go, factory/runType/runTypeComponentsHandler.go, factory/runType/runTypeComponentsHandler_test.go, factory/runType/sovereignRunTypeComponents.go, genesis/process/argGenesisBlockCreator.go, genesis/process/genesisBlockCreator.go, genesis/process/sovereignGenesisBlockCreator.go, genesis/process/sovereignGenesisBlockCreator_test.go, go.mod, go.sum, process/block/sovereignChainBlock.go, testscommon/components/components.go, testscommon/components/configs.go, testscommon/genesisMocks/runTypeComponentsStub.go, testscommon/mainFactoryMocks/runTypeComponentStub.go
- Backwards compatibility issues for other sovereign chains if we change the header or if internal `Header` is changed on mainnet. 
- Sovereign header version factory
- 
- 
- 
=> [sovereign] Header version factory

factory/disabled/incomingHeaderProcessor.go, factory/processing/processComponents.go, factory/processing/processComponents_test.go, integrationTests/realcomponents/processorRunner.go, node/nodeRunner.go, testscommon/components/components.go
- Clean incoming header processor argument and checks
- 
- 
- 
- 
- 
- 
=> [sovereign] Clean incoming header processor argument and checks

dataRetriever/txpool/memorytests/memory_test.go, go.mod, go.sum
- 
- 
- 
- https://github.com/multiversx/mx-chain-storage-go/pull/67
- 
- 
- 
- 
- 
=> Mempool: handle relayed V3 transactions in selection

integrationTests/chainSimulator/relayedTx/relayedTx_test.go, process/dataValidators/txValidator.go, process/dataValidators/txValidator_test.go
- relayed txs v3 with sender account not-existent are rejected by interceptors, despite the zero value of transaction
- allow relayed txs v3 with new senders, in case of zero value transactions
=> Accept relayed tx v3 with sender account non-existent

cmd/node/factory/interface.go, consensus/broadcast/delayedBroadcast.go, consensus/interface.go, consensus/spos/bls/v1/subroundBlock.go, consensus/spos/bls/v2/subroundBlock.go, consensus/spos/errors.go, consensus/spos/interface.go, consensus/spos/worker.go, dataRetriever/dataPool/proofsCache/proofsPool.go, epochStart/bootstrap/disabled/disabledHeaderSigVerifier.go, fallback/headerValidator.go, integrationTests/consensus/consensusSigning_test.go, process/block/baseProcess.go, process/block/baseProcess_test.go, process/block/interceptedBlocks/common.go, process/block/interceptedBlocks/interceptedBlockHeader.go, process/block/interceptedBlocks/interceptedBlockHeader_test.go, process/block/interceptedBlocks/interceptedMetaBlockHeader.go, process/errors.go, process/headerCheck/common.go, process/headerCheck/errors.go, process/headerCheck/headerSignatureVerify.go, process/headerCheck/headerSignatureVerify_test.go, process/interface.go, process/peer/process.go, testscommon/consensus/headerSigVerifierStub.go, testscommon/fallbackHeaderValidatorStub.go
- The proof verification (aggregated signature) with equivalent proofs is for the unaltered header, so it also needs to be verified on the unaltered header
- Add more safety and integrity checks
- Leader signature is not removed from the header before verifying the proof aggregated signature
- Make sure new header fields (proof related) are validated for both before activation - throw an error if the new fields are present, and after activation - throw an error if the fields are not present
- Unit tests
- Regular system test with transitioning from old to new consensus will be done on the feat branch
Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the …
=> Fixes header sig verification

storage/pruning/fullHistoryPruningStorer.go, storage/pruning/fullHistoryPruningStorer_test.go, storage/pruning/pruningStorer.go
=> Merge rc spica patch rv3 into feat rv3 2024.12.18

consensus/spos/bls/v2/subroundEndRound.go, consensus/spos/worker.go
- Do not wait for signatures if proof already received
- small refactorings and checks
- TBD
=> Subround endround v2 fixes

integrationTests/chainSimulator/relayedTx/relayedTx_test.go, process/transaction/shardProcess.go
- missing receipt for move balance intra shard in case of refund
- compute the txHash as before
=> Fix receipts hash mismatch

integrationTests/chainSimulator/relayedTx/relayedTx_test.go, node/external/transactionAPI/apiTransactionProcessor.go, node/external/transactionAPI/apiTransactionProcessor_test.go, process/constants.go
- Some Node API clients are interested into a precise value of `tx.ProcessingTypeOnSource` and `tx.ProcessingTypeOnDestination` (in the context of GET transaction).
- Do not override the aforementioned fields when the transaction is relayed V3.
- Standard testing.
=> On Node API, adjust processing type for relayed V3

api/groups/networkGroup_test.go, common/constants.go, node/chainSimulator/components/nodeFacade.go, node/nodeRunner.go, statusHandler/statusMetricsProvider.go, statusHandler/statusMetricsProvider_test.go
- new metric similar with erd_extra_gas_limit_guarded_tx might be needed for relayed tx
- added erd_extra_gas_limit_relayed_tx
- will be tested with feat branch
=> new metric for extra relayed tx gas limit

integrationTests/chainSimulator/relayedTx/relayedTx_test.go, process/smartContract/processorV2/processV2.go, process/transaction/baseProcess.go, process/transaction/shardProcess.go
- txs v3 relayed by one of the parties do not consume the fee 
- fixed this edge case by only loading the account once if the relayer is one of the participants
- with feat branch + scenario
=> fix relayed v3 with relayer one of the participants leading to free txs

node/external/transactionAPI/gasUsedAndFeeProcessor.go, outport/process/transactionsfee/transactionChecker.go, outport/process/transactionsfee/transactionsFeeProcessor.go, outport/process/transactionsfee/transactionsFeeProcessor_test.go
- the fee fomr indexer was not the correct one
- outport fee handling needs special treatment for relayed v3, similar as for transaction api of the node
- with feat branch, comparison between gateway and explorer/api results
=> fixed the computed fee for outport for relayed v3

node/external/transactionAPI/gasUsedAndFeeProcessor.go, node/external/transactionAPI/gasUsedAndFeeProcessor_test.go, node/external/transactionAPI/testData/relayedV3WithMultipleRefunds.json
- if more than one refund scrs are generated for a tx, only one is considered while computing the fee field on node api
- take into account all refund scrs for node api
- with feat branch, send a tx that generate multiple refunds 
=> count all refunds if more than one scr exists

genesis/process/disabled/feeHandler.go, go.mod, go.sum, outport/mock/economicsDataMock.go, outport/process/interface.go, outport/process/transactionsfee/interface.go, outport/process/transactionsfee/transactionsFeeProcessor.go, outport/process/transactionsfee/transactionsFeeProcessor_test.go, process/economics/economicsData.go, process/interface.go, testscommon/economicsmocks/economicsDataHandlerStub.go, testscommon/economicsmocks/economicsHandlerMock.go
- Implemented the part compute fee and gas used in case of multiple smart contract results with refund value
- Changed the version of `mx-chain-core-go`: https://github.com/multiversx/mx-chain-core-go/pull/345
- Changed the version of `mx-chain-es-indexer-go`: https://github.com/multiversx/mx-chain-es-indexer-go/pull/319
- 
- Ensure gas used and the fee is calculated correctly 
- if this is a `feat` branch merging, do all satellite …
=> Multiple smart contract results with refund

process/block/baseProcess.go
=> fix missing runlock

cmd/node/config/config.toml, config/config.go, dataRetriever/dataPool/proofsCache/proofsPool.go, dataRetriever/dataPool/proofsCache/proofsPool_test.go, dataRetriever/factory/dataPoolFactory.go, integrationTests/testProcessorNode.go, process/block/baseProcess.go, process/block/baseProcess_test.go, testscommon/dataRetriever/poolFactory.go, testscommon/dataRetriever/poolsHolderMock.go
- Add cleanup delta for proofs pool
- TBD
=> Proofs pool cleanup delta

trie/branchNode.go, trie/branchNode_test.go, trie/extensionNode.go, trie/extensionNode_test.go, trie/interface.go, trie/leafNode.go, trie/leafNode_test.go, trie/node.go, trie/node_test.go, trie/patriciaMerkleTrie.go, trie/sync.go, trie/sync_test.go, trie/trieStorageManager.go
- There were some unnecessary trie node encode operations
- Remove unnecessary encode operation from `collectStats` and `commitSnapshot`
=> remove unnecessary trie node encode operations and remove unused code

common/common.go, consensus/chronology/chronology.go, consensus/spos/bls/v2/subroundBlock.go, go.mod, go.sum, process/block/baseProcess.go, process/block/shardblock.go, process/sync/baseForkDetector.go, process/track/blockProcessor.go
=> Fix transition block

common/common.go
=> Improved VerifyProofAgainstHeader with extra check on IsStartOfEpoch field

process/block/baseProcess.go, process/block/metablock.go, process/block/shardblock.go, process/errors.go, process/track/blockProcessor.go
=> more fixes on the notarization part

dataRetriever/dataPool/proofsCache/proofsPool.go, process/block/baseProcess.go
=> cosmetic changes

consensus/spos/bls/v2/subroundEndRound.go, consensus/spos/bls/v2/subroundEndRound_test.go, process/sync/baseForkDetector.go, process/sync/metaForkDetector.go, process/sync/shardForkDetector.go
- During testing the shard nodes falsely detects from time to time that metachain is falling behind with notarization
- Fork detector should be updated with the final blocks based on the new rules
- Consensus subround EndRound needs to be updated to commit the block only once the proof is stored, otherwise the fork detector would wrongly compute the last notarized blocks
- 
- if this is a `feat` branch merging, do all satellite …
=> Fix shard stuck

common/common.go, process/block/metablock.go, process/common.go
=> fix sync on meta

cmd/node/config/enableEpochs.toml, go.mod, go.sum
=> Merge master into rc barnard 2025.01.29

integrationTests/chainSimulator/interface.go
=> chain simulator interface update

common/interface.go, genesis/process/memoryComponents.go, integrationTests/benchmarks/loadFromTrie_test.go, integrationTests/state/stateTrie/stateTrie_test.go, integrationTests/state/stateTrieSync/stateTrieSync_test.go, state/accountsDB.go, state/accountsDB_test.go, state/peerAccountsDB_test.go, state/storagePruningManager/storagePruningManager_test.go, state/syncer/baseAccountsSyncer.go, state/trackableDataTrie/trackableDataTrie.go, state/trackableDataTrie/trackableDataTrie_test.go, testscommon/trie/trieStub.go, trie/baseIterator.go, trie/branchNode_test.go, trie/depthFirstSync_test.go, trie/doubleListSync_test.go, trie/extensionNode_test.go, trie/factory/trieCreator.go, trie/goroutinesManager.go, trie/goroutinesManager_test.go, trie/leafNode_test.go, trie/patriciaMerkleTrie.go, trie/patriciaMerkleTrie_test.go, trie/sync_test.go, trie/trieBatchManager/trieBatchManager.go, trie/trieBatchManager/trieBatchManager_test.go, trie/trieChangesBatch/trieChangesBatch.go, trie/trieChangesBatch/trieChangesBatch_test.go
- Missing log prints for new functionality
- Add logging for `goroutinesManager` and for `trieBatchManager`
=> add logging for trie goroutines and batch

cmd/sovereignnode/chainSimulator/sovereignChainSimulator_test.go, integrationTests/chainSimulator/testing.go, node/chainSimulator/chainSimulator_test.go, node/chainSimulator/sovereignChainSimulator.go
=> sovereign chain simulator updates

common/common.go, consensus/interface.go, process/block/interceptedBlocks/common.go, process/headerCheck/headerSignatureVerify.go, process/headerCheck/headerSignatureVerify_test.go
=> add header verification unit tests

integrationTests/chainSimulator/mempool/mempool_test.go, integrationTests/chainSimulator/mempool/testutils_test.go, integrationTests/vm/wasm/queries/queries_test.go
- Some long tests were failing at times (flaky).
- Increase some sleep times, to allow test transactions to fully propagate / reach mempool.
Changes were verified by running the tests in question in a loop:
```
while go clean -testcache && go test ./...; do sleep 1; done
```
- No additional testing is needed.
=> Fix some long tests

epochStart/shardchain/trigger.go, factory/consensus/consensusComponents.go, factory/mock/forkDetectorMock.go, integrationTests/mock/forkDetectorStub.go, integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go, node/mock/forkDetectorMock.go, process/interface.go, process/mock/forkDetectorMock.go, process/sync/baseForkDetector.go, process/sync/interface.go, process/sync/storageBootstrap/baseStorageBootstrapper.go, process/sync/storageBootstrap/baseStorageBootstrapper_test.go, process/sync/storageBootstrap/metaStorageBootstrapper.go, process/sync/storageBootstrap/shardStorageBootstrapper.go, process/sync/storageBootstrap/shardStorageBootstrapper_test.go, testscommon/processMocks/forkDetectorStub.go
- bootstrapping after shuffling to other shards with equivalent proofs does not always succeed
- after applying the previously stored block, if this block has proofs, set the fork detector correspondingly.
- 
=> set fork detector checkpoints on bootstrapper applyBlock

cmd/node/config/enableEpochs.toml, cmd/node/config/gasSchedules/gasScheduleV1.toml, cmd/node/config/gasSchedules/gasScheduleV2.toml, cmd/node/config/gasSchedules/gasScheduleV3.toml, cmd/node/config/gasSchedules/gasScheduleV4.toml, cmd/node/config/gasSchedules/gasScheduleV5.toml, cmd/node/config/gasSchedules/gasScheduleV6.toml, cmd/node/config/gasSchedules/gasScheduleV7.toml, cmd/node/config/gasSchedules/gasScheduleV8.toml, common/constants.go, common/enablers/enableEpochsHandler.go, config/epochConfig.go, go.mod, go.sum
- Integrate new version of VM
- Added new VM hook (managedGetAllTransfersCallValue)
- Added new VM hook (managedGetCodeHash)
- Masked errors from libraries (that should remain internal to the VM) with activation epoch
- https://github.com/multiversx/mx-chain-vm-go/pull/895
- https://github.com/multiversx/mx-chain-vm-go/pull/898
- https://github.com/multiversx/mx-chain-vm-go/pull/897 …
=> vm integration for get all transfers value hook, get code hash hook and internal errors masking

consensus/chronology/chronology.go, consensus/interface.go, consensus/round/round.go, consensus/spos/bls/proxy/subroundsHandler.go, consensus/spos/consensusState.go, consensus/spos/interface.go, consensus/spos/worker.go, factory/interface.go, factory/mock/rounderMock.go, integrationTests/mock/roundHandlerMock.go, node/chainSimulator/components/manualRoundHandler.go, node/mock/rounderMock.go, process/mock/rounderMock.go, testscommon/consensus/consensusStateMock.go, testscommon/consensus/rounderMock.go, testscommon/consensus/sposWorkerMock.go, testscommon/roundHandlerMock.go
=> Consensus transition speedup

cmd/node/config/enableEpochs.toml, common/constants.go, common/enablers/enableEpochsHandler.go, common/enablers/enableEpochsHandler_test.go, config/epochConfig.go, config/tomlConfig_test.go, go.mod, go.sum, node/metrics/metrics.go, node/metrics/metrics_test.go, statusHandler/statusMetricsProvider.go, statusHandler/statusMetricsProvider_test.go
- Integrate new VM with backtransfer OPCODE improvements/fixes
- https://github.com/multiversx/mx-chain-vm-go/pull/899
=> vm integration for backtransfers improvements

process/block/baseProcess.go, process/block/metablock.go, process/block/shardblock.go
=> fix writing on channel when a block is requested in order to attest the current one

process/block/interceptedBlocks/common.go, process/block/interceptedBlocks/common_test.go, process/block/interceptedBlocks/interceptedMetaBlockHeader_test.go
- Adapt meta header interceptor to check shard data proof only on metachain nodes
- On shard nodes we don't need to have these additional checks, if there is a proof for the received metachain we can conclude that it reached consensus
- TBD
=> check shard data only on meta nodes in interceptor

storage/pruning/pruningStorer.go
- Add state statistics for `SearchFirst` operation in PrunningStorer
- TBD
=> add state statistics for search first

consensus/spos/bls/v2/export_test.go, consensus/spos/bls/v2/subroundEndRound.go, consensus/spos/bls/v2/subroundEndRound_test.go
- Check if multi-key and if not, return single key when getting proof sender
- TBD
=> Subround endround equivalent proofs unit tests

state/accountsDB.go, state/accountsDB_test.go, state/journalEntries.go, state/stateChanges/collector.go, state/stateChanges/collector_test.go, state/trackableDataTrie/trackableDataTrie.go
- State changes collector should not return err if snapshot ID number if higher than number of collected state changes, it should just set snapshot ID index to last collected state change
- to be tested with feature branch
=> fix state changes collector index out of bounds

consensus/spos/bls/proxy/subroundsHandler_test.go, consensus/spos/bls/v2/export_test.go, consensus/spos/bls/v2/subroundEndRound.go, consensus/spos/bls/v2/subroundEndRound_test.go, consensus/spos/bls/v2/subroundStartRound.go, consensus/spos/consensusCore.go, consensus/spos/consensusCoreValidator.go, consensus/spos/consensusCoreValidator_test.go, consensus/spos/consensusCore_test.go, consensus/spos/errors.go, consensus/spos/interface.go, consensus/spos/invalidSignersCache.go, consensus/spos/invalidSignersCache_test.go, consensus/spos/worker.go, consensus/spos/worker_test.go, factory/consensus/consensusComponents.go, factory/consensus/consensusComponents_test.go, factory/interface.go, testscommon/consensus/invalidSignersCacheMock.go, testscommon/consensus/mockTestInitializer.go, testscommon/consensus/sposWorkerMock.go
- as now all participants can aggregate signatures and send final info, the network might get flooded with the invalid signers messages
- added a mechanism similar to equivalent proofs to avoid further broadcast in case of known invalid signers message
- with rc branch
=> Invalid signers cache

consensus/spos/bls/v2/errors.go, consensus/spos/bls/v2/export_test.go, consensus/spos/bls/v2/subroundEndRound.go, consensus/spos/bls/v2/subroundEndRound_test.go
- if a node has too many invalid signatures to fall beyond threshold, it will simply wait for a proof
- wait for proof or more signatures
- with rc and invalid signers
=> Recursive call to doEndRoundJobByNode in order to wait more signatures

go.mod, go.sum, integrationTests/vm/esdt/forwarderMock.go, integrationTests/vm/esdt/localFuncs/localEsdtNft.go
- Integrate new version of VM with the new transfer and execute and return error hook.
- https://github.com/multiversx/mx-chain-vm-go/pull/907
=> integrate transfer and execute with return error

cmd/node/config/config.toml, config/config.go, dataRetriever/dataPool/proofsCache/export_test.go, dataRetriever/dataPool/proofsCache/proofsBucket.go, dataRetriever/dataPool/proofsCache/proofsCache.go, dataRetriever/dataPool/proofsCache/proofsCache_bench_test.go, dataRetriever/dataPool/proofsCache/proofsCache_test.go, dataRetriever/dataPool/proofsCache/proofsPool.go, dataRetriever/dataPool/proofsCache/proofsPool_test.go, dataRetriever/factory/dataPoolFactory.go, integrationTests/testProcessorNode.go, process/block/baseProcess_test.go, testscommon/dataRetriever/poolFactory.go, testscommon/dataRetriever/poolsHolderMock.go
- Remove sort operation when adding to pool
- Added more unit tests to proofsCache
- to be tested with feat branch
=> Proofs pool improvements

epochStart/bootstrap/disabled/disabledAccountsAdapter.go, factory/processing/blockProcessorCreator.go, genesis/process/shardGenesisBlockCreator.go, go.mod, go.sum, integrationTests/testProcessorNode.go, integrationTests/vm/wasm/utils.go, process/rewardTransaction/process.go, process/rewardTransaction/process_test.go, process/smartContract/process.go, process/smartContract/processorV2/processV2.go, process/transactionEvaluator/simulationAccountsDB.go, state/accountsDB.go, state/accountsDBApi.go, state/accountsDBApiWithHistory.go, state/accountsDB_test.go, state/disabled/disabledStateChangesCollector.go, state/interface.go, state/journalEntries.go, state/stateChanges/collector.go, state/stateChanges/collector_test.go, state/stateChanges/dataAnalysisCollector.go, state/trackableDataTrie/trackableDataTrie.go, testscommon/state/accountsAdapterStub.go, testscommon/state/stateChangesCollectorStub.go
- The feature had multiple bugs
- Multiple fixes
=> state changes fixes

consensus/spos/bls/v2/export_test.go, consensus/spos/bls/v2/subroundBlock.go, consensus/spos/bls/v2/subroundEndRound.go
- multikey backups do not propose blocks when they should
- fixed early exit in subroundBlock in order to allow backups to propose block
- small fix also on invalid signatures propagation to use the proper sender for multikey as well
- with rc
=> fixed backups not proposing block in multikey mode

process/block/interceptedBlocks/common.go, process/block/shardblock.go
- Use current commited shard header in finalized state for outport driver
- With feat branch
=> fix shard header finalized state

trie/extensionNode.go, trie/extensionNode_test.go
- There is an edgecase when inserting in an extension node
- Fix edgecase
- Add unit test
- Import db
=> add fix and unit test

trie/branchNode.go, trie/branchNode_test.go, trie/extensionNode.go, trie/extensionNode_test.go, trie/leafNode.go, trie/node.pb.go, trie/node.proto, trie/node_test.go
- `EncodedChildren`/`EncodedChild` trie node field's name is misleading
- Rename EncodedChildren to `ChildrenHashes` & `EncodedChild` to `ChildHash`
=> rename EncodedChildren to ChildrenHashes

consensus/spos/bls/v2/errors.go, consensus/spos/bls/v2/subroundEndRound.go, consensus/spos/bls/v2/subroundEndRound_test.go
- Remove unnecessary propagation of equivalent consensus proofs
- Avoid propagating own proofs when another proof already received and propagated
- regular system test & network bandwidth consumption checks
=> Equivalent proofs propagation optimisation

state/stateAccesses/collector_test.go
- added unit tests for merging state accesses for same account
- 
- 
- 
- 
- 
- 
- 
- 
=> unit tests for merging same account accesses

cmd/node/config/config.toml
- with request for proofs the BaseMessagesPerInterval is too low
- double the BaseMessagesPerInterval
- let a full history node reset and let it resync as fast as possible
=> increased BaseMessagesPerInterval

trie/export_test.go, trie/keyBuilder/keyBuilder.go, trie/keyBuilder/keyBuilder_test.go, trie/leafNode.go, trie/node.go, trie/node_test.go, trie/patriciaMerkleTrie.go, trie/patriciaMerkleTrie_test.go, trie/trieChangesBatch/trieChangesBatch.go, trie/trieChangesBatch/trieChangesBatch_test.go
- The keys that are saved in the batch are saved as `hex`. This means that the keys occupy two times as much space
- Save keys as bytes instead of hex inside the batcher, and convert to hex only when inserting in the trie
=> save keys as bytes instead of hex

trie/baseIterator.go, trie/baseNode.go, trie/branchNode.go, trie/branchNode_test.go, trie/depthFirstSync.go, trie/doubleListSync.go, trie/errors.go, trie/export_test.go, trie/extensionNode.go, trie/extensionNode_test.go, trie/interface.go, trie/leafNode.go, trie/leafNode_test.go, trie/node.go, trie/node_test.go, trie/patriciaMerkleTrie.go, trie/patriciaMerkleTrie_test.go, trie/rootManager.go, trie/rootManager_test.go, trie/sync.go, trie/sync_test.go, trie/trieNodesHandler.go, trie/trieNodesHandler_test.go, trie/trieStorageManager.go
- Each trie node saves it's own hash. But intermediary nodes also save the hash for each child. This means that some hashes are duplicated in memory. 
- Remove the `hash` field from each trie node. When that hash is needed, it can be accessed from the parent node. 
- The trie insert/delete now happens in batches. Because of this we can compute the hash for each trie node when a batch is commited to the trie, thus removing the need to traverse the trie and compute the rootHash when it is needed.
- if this …
=> remove hash from trie nodes and use hash from parent nodes

common/interface.go, trie/baseIterator.go, trie/baseNode.go, trie/branchNode.go, trie/branchNode_test.go, trie/depthFirstSync.go, trie/doubleListSync.go, trie/export_test.go, trie/extensionNode.go, trie/extensionNode_test.go, trie/interface.go, trie/leafNode.go, trie/leafNode_test.go, trie/node.go, trie/node_extension.go, trie/node_test.go, trie/patriciaMerkleTrie.go, trie/proofVerifier.go, trie/sync.go, trie/sync_test.go, trie/trieStorageManager.go
- Each trie node hold a pointer to the marshaller and one to the hasher. These will use extra memory.
- Remove the pointers to the marshaller and hasher for all trie nodes. Instead, pass these as arguments.
- Group the `marshaller`, `hasher` and `trieStorage` in another component. These are usually used together, so it will make the code more readable by passing a single component instead of three.
- if …
=> remove hasher and marshaller pointers from the trie nodes

.github/workflows/code-coverage.yml
Fix upload of code coverage metrics to https://app.codecov.io/gh/multiversx/mx-chain-go.
=> Fix code coverage upload

integrationTests/chainSimulator/staking/stake/stakeAndUnStake_test.go
=> fixing tests with unbond

codecov.yml
- For some reason, for `rc/barnard`, some test files aren't excluded from the code coverage report:
- https://app.codecov.io/gh/multiversx/mx-chain-go/tree/rc%2Fbarnard
- Though, they are excluded from the report on `master`:
- https://app.codecov.io/gh/multiversx/mx-chain-go/tree/master
- Report of this PR:
- https://app.codecov.io/gh/multiversx/mx-chain-go/tree/fix-codecov-06-16
- Explicitly exclude some Go modules from the code coverage report, by adjusting `codecov.yml`.
- No testing necessary.
- if this is a larger feature …
=> Fix codecov config (exclude files)

txcache/trackedBlock.go, txcache/trackedBlock_test.go
- solved a **TODO** related to [this comment](https://github.com/multiversx/mx-chain-go/pull/7080#discussion_r2174380195)
- avoid double search in map by **checking if the sender is also the fee payer** and accumulate in its breadcrumb
- added a unit test for this case
=> optimize compile breadcrumb flow

consensus/round/round.go, consensus/round/round_test.go
- fix round index check for supernova round activation
- add more unit tests for concurrency operations
- System test with genesis time way ahead (more than supernova round activation negative)
=> fix round index activation check

api/groups/validatorGroup_test.go, api/middleware/sourceThrottler.go, cmd/termui/view/termuic/processCloser.go, common/statistics/stateStatistics.go, dataRetriever/provider/miniBlocks.go, node/chainSimulator/components/testOnlyProcessingNode.go, process/block/preprocess/transactions.go, process/block/shardblock.go, process/coordinator/process.go, process/economics/gasConfigHandler.go, process/mock/coreComponentsMock.go, process/smartContract/processorV2/vmOutputAccountsProcessor.go, process/sync/baseSync.go, process/sync/storageBootstrap/metricsLoader/loadPersistentMetrics.go, process/transaction/metaProcess.go, sharding/nodesCoordinator/hashValidatorShuffler.go, state/accountsDB.go, state/journalEntries.go, storage/pruning/export_test.go, testscommon/blockChainHookStub.go, trie/export_test.go, update/sync/syncHeaders.go
Several community PRs pinpoint mismatches between structure or function descriptions and their actual names:
-  chore: fix some function names in comment #7072 
-  chore: make struct comments match struct names #6239 
-  chore: fix some comments #6329 
- make struct and func comments match their name
- 
- 
- 
=> Change struct and func description to match struct/function names

consensus/spos/consensusState.go, consensus/spos/roundConsensus.go, consensus/spos/roundConsensus_test.go
- Add missing mutex protection on round consensus methods
- System tests with restarts
=> fix missing mutex protection in round state

process/common.go, process/common_test.go, process/errors.go
- the common method `UnmarshallHeader` from processing should be updated for header v3
- updated method
- with rc
=> Update UnmarshallHeader method for v3

dataRetriever/requestHandlers/requestHandler.go, dataRetriever/requestHandlers/requestHandler_test.go, epochStart/bootstrap/process.go, genesis/process/disabled/disabled_test.go, genesis/process/disabled/requestHandler.go, integrationTests/resolvers/transactions/transactionsRequest_test.go, integrationTests/singleShard/transaction/interceptedResolvedTx/interceptedResolvedTx_test.go, process/factory/metachain/preProcessorsContainerFactory.go, process/factory/shard/preProcessorsContainerFactory.go, process/interface.go, testscommon/dataRetriever/equivalentProofRequesterStub.go, testscommon/requestHandlerStub.go, update/interface.go, update/sync/syncTransactions.go
- This pull request refactors the request handler interface by renaming RequestTransaction to RequestTransactions and adds new epoch-specific request methods. The main changes focus on improving method naming consistency and adding support for epoch-specific data requests.
- Renamed RequestTransaction to RequestTransactions across all implementations and interfaces
- Added new *ForEpoch variants for all request methods to support epoch-specific requests
- Updated timeout constant in bootstrap process from 2 to 5 minutes
- 
- 
- 
- …
=> Request handler refactor

factory/processing/txSimulatorProcessComponents.go, integrationTests/chainSimulator/simulate/simulate_test.go
- This PR addresses an issue with the /transaction/cost endpoint, which failed when handling relayed v3 transactions — specifically when the sender had no EGLD balance. The current behavior incorrectly simulates the transaction execution, causing invalid cost estimations in certain relayed transaction flows.
- Replaced the existing smart contract processor component with one that accurately simulates relayed transaction execution.
1.	Call /transaction/cost with a v3 relayed transaction where the sender has zero EGLD.
2.	Confirm that the cost estimation completes successfully and returns a valid gas cost.
3.	Ensure existing non-relayed flows remain unaffected.
Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-manage …
=> Fixes tx cost endpoint

update/sync/syncEpochStartShardHeaders_test.go
- Fixed **TestSyncEpochStartShardHeader_ProofsBeforeHeaderShouldWork** by increasing timeout.
=> Supernova TxPool: Fixed Failing Tests

txcache/autoClean.go, txcache/eviction.go, txcache/interface.go, txcache/selectionTracker.go, txcache/transactionsTracker.go, txcache/transactionsTracker_test.go, txcache/txByHashMap.go, txcache/txByHashMap_test.go, txcache/txCache.go
- Solved some TODOs.
- moved the check of the transaction **outside of txByHashMap.**
- create a method in the transactionsTracker that **returns untracked txs.** 
- added some unit tests, removed some TODO comments.
- added method for **getting all of the tracked blocks** using a copy of the map.
=> Supernova TxPool Part2: Check Tracked Txs Fixes
