cmd/node/main.go, core/trimmers.go, core/trimmers_test.go, dataRetriever/requestHandlers/requestHandler.go, node/defineOptions.go, node/node.go, process/block/baseProcess.go, process/block/baseProcess_test.go, process/block/export_test.go, process/block/interceptors/metachainHeaderInterceptor.go, process/block/interceptors/metachainHeaderInterceptor_test.go, process/block/metablock.go, process/block/metablock_test.go, process/block/preprocess/transactions.go, process/block/shardblock.go, process/block/shardblock_test.go, process/constants.go, process/errors.go, process/sync/baseSync.go, process/sync/basicForkDetector.go, process/sync/basicForkDetector_test.go, process/sync/errors.go, process/sync/export_test.go, process/sync/metablock.go, process/sync/metablock_test.go, process/sync/shardblock.go, process/sync/shardblock_test.go
=> Feat vm economics merge with master

data/trie/branchNode.go, data/trie/branchNode_test.go, data/trie/patriciaMerkleTrie.go, dataRetriever/resolvers/topicResolverSender/export_test.go, dataRetriever/resolvers/topicResolverSender/topicResolverSender.go, dataRetriever/resolvers/topicResolverSender/topicResolverSender_test.go, p2p/libp2p/directSender.go, p2p/libp2p/export_test.go, p2p/libp2p/mutexHolder.go, p2p/libp2p/mutexHolder_test.go, p2p/libp2p/netMessenger.go, p2p/p2p.go
Merged master into feat/vm-and-economics without changes
=> Merged feat/vm and economics update 07072019

p2p/memp2p/memp2p.go, p2p/memp2p/memp2p_network.go, p2p/memp2p/memp2p_test.go
Fixes a couple of race conditions in the MemP2P mock.
=> Fix data race conditions

Makefile
Add a Makefile to the project, useful for running custom test groups.
E. g.
* `make test-short` runs `go test -short -count=1 ./...`
* `make test-race` runs `go test -short -count=1 -race ./...`
For cleaning up:
* `make clean-test` the test cache
* `make clean` will clean the test cache and the build
* `make build` will build the entire `elrond-go` project
=> New makefile

integrationTests/node/heartbeat_test.go, integrationTests/testInitializer.go, node/heartbeat/hearbeatMessageInfo.go, node/heartbeat/heartbeat.go, node/heartbeat/monitor.go, node/heartbeat/monitor_test.go, node/heartbeat/sender.go
added integration test and unit test for heartbeat sender and monitor
changed how the signature is done on heartbeat messages
all heartbeat status values are updated when a new message is being received
=> En 3542 fix heartbeat is active

process/errors.go, process/interceptors/common.go, process/interceptors/common_test.go, process/interceptors/multiDataInterceptor.go, process/interceptors/multiDataInterceptor_test.go, process/interceptors/singleDataInterceptor.go, process/interceptors/singleDataInterceptor_test.go, process/interface.go, process/mock/interceptedDataFactoryStub.go, process/mock/interceptedDataStub.go, process/mock/interceptorProcessorStub.go, process/mock/interceptorThrottlerStub.go
added new interceptor implementations
=> added new interceptor implementations

cmd/node/factory/structs.go, cmd/node/main.go, core/genesis/genesisBlockCreator.go, node/node.go, node/node_test.go
remove from main.go  CreateShardGenesisBlock and CreateMetaGenesisBlock and set in structs.go GenesisHeader and GenesisHeaderHash
=> EN-2890 : remove second generation of the genesis block

cmd/node/factory/structs.go, cmd/node/main.go, node/defineOptions.go, node/node.go, sharding/nodesSetup.go, sharding/nodesSetup_test.go
fixed bug that could not generate bulk transactions
refactored some structs.go methods
removed isMetachainActive
=> fixed bug that could not generate bulk transactions

integrationTests/longTests/storage_test.go, integrationTests/testStorage.go
refactor integration tests for storage
=> EN-3347 : refactor integration tests for storage and move in longTests

core/statistics/resourceMonitor.go
added some stats info in resourceMonitor
=> En 3834 observers out of mem add stats

node/nodeTesting.go, node/nodeTesting_test.go
generate bulk transactions func does not check data pools anymore
=> generate bulk transaction func does not care about the tx pool size

statusHandler/appStatusFacade_test.go, statusHandler/prometheusHandler_test.go
updated test for prometheusHandler in order to support go1.13
cleanup in appStatusFacade_test
=> updated test for prometheusHandler in order to support go1.13

cmd/node/main.go, core/constants.go, core/statistics/machine/memStatistics.go, statusHandler/presenter/systemLoadsGetters.go, statusHandler/presenter/systemLoadsGetters_test.go
Added a new metric for system memory usage + renaming of older ones
=> EN-4100: memory metrics update

core/logger/redirectStderrDarwin.go
Fixed redirect of the std err on darwin os
=> Fix redirect stderr darwin

process/common_test.go
modify test to work all the time
=> EN-4105 : fix test to work all the time

cmd/node/main.go, statusHandler/view/termuic/termuiConsole.go, statusHandler/view/termuic/termuiRenders/widgetsRender.go
Fixed bugs:
- [invalid key] appeared instead of public key for signing
- log list did not update when resizing
- random characters which appeared would have remained so a periodic cleanup was added
Please test on all operating systems
=> EN-4112: Termui bug fixes

cmd/node/config/config.toml, node/heartbeat/monitor.go
removed heartbeat storage when serving a rest API request
=> removed heartbeat storage when serving a rest API request

cmd/node/factory/structs.go, core/address.go, process/factory/metachain/feeHandler.go, process/factory/metachain/intermediateProcessorsContainerFactory.go, process/factory/metachain/intermediateProcessorsContainerFactory_test.go, process/factory/metachain/preProcessorsContainerFactory.go, process/factory/metachain/preProcessorsContainerFactory_test.go, process/smartContract/process.go
Factories and tx Cooridnator creation for metachain
=> En 4444/processor factories and tx coordinator metachain

data/trie/branchNode.go, data/trie/branchNode_test.go, data/trie/errors.go, data/trie/extensionNode.go, data/trie/extensionNode_test.go, data/trie/leafNode.go, data/trie/leafNode_test.go, data/trie/node.go, data/trie/node_test.go, data/trie/patriciaMerkleTrie.go, data/trie/patriciaMerkleTrie_test.go, go.mod, go.sum
Create snapshot and delete old snapshots on goroutines.
=> En 4496 trie snapshot optimization

process/block/preprocess/intermediateResults.go
fixing generation of txInfo for smart contract results. special case being the empty address.
=> Bugfix / generation of txInfo for smart contract results. special case

core/indexer/elasticsearch.go
Log more information from elastic search.
Fix problem with goroutine in for instruction.
=> EN-4684 Elastic search improve (log more infromation)

cmd/node/main.go, display/converters.go, process/sync/baseSync.go
added the possibility to output on stdout plain, uncolored text
removed ellipsis character when displaying []byte as hex as it might cause some display issues
corrected a small bug in process after receiving a new nonce on base sync
=> added the possibility to output on stdout plain, uncolored text

cmd/node/config/config.toml, cmd/node/main.go, facade/elrondNodeFacade.go
fixed bug that cause seldom application freeze on startup
added log.trace prints on main file for easier future debugging sessions
optimized signal waiting go routine on main
removed with-ui flag
removed log folder creation
removed unused config.toml setting
=> fixed bug that cause seldom application freeze on startup

cmd/node/factory/structs.go, data/trie/branchNode.go, data/trie/branchNode_test.go, data/trie/extensionNode.go, data/trie/extensionNode_test.go, data/trie/interceptedNode.go, data/trie/interceptedNode_test.go, data/trie/iterator.go, data/trie/leafNode.go, data/trie/leafNode_test.go, data/trie/node.go, data/trie/node_test.go, data/trie/patriciaMerkleTrie.go, data/trie/sync.go, data/trie/sync_test.go, integrationTests/multiShard/smartContract/testInitializer.go, integrationTests/testProcessorNode.go, process/factory/metachain/interceptorsContainerFactory.go, process/factory/metachain/interceptorsContainerFactory_test.go, process/factory/shard/interceptorsContainerFactory.go, process/factory/shard/interceptorsContainerFactory_test.go, process/interceptors/factory/argInterceptedDataFactory.go, process/interceptors/factory/interceptedMetaHeaderDataFactory_test.go, process/interceptors/factory/interceptedTrieNodeDataFactory.go, process/interceptors/factory/interceptedTrieNodeDataFactory_test.go
=> refactor trie

cmd/node/factory/interface.go, cmd/node/factory/structs.go, cmd/node/main.go, epochStart/errors.go, epochStart/interface.go, epochStart/metachain/trigger.go, epochStart/metachain/trigger_test.go, epochStart/mock/epochStartNotifierStub.go, epochStart/notifier/common.go, epochStart/notifier/epochStartSubscriptionHandler.go, epochStart/notifier/epochStartSubscriptionHandler_test.go, epochStart/notifier/export_test.go, epochStart/shardchain/trigger.go, epochStart/shardchain/trigger_test.go, integrationTests/consensus/testInitializer.go, integrationTests/mock/epochStartNotifierStub.go, integrationTests/testProcessorNode.go
implemented a notifier mechanism which will trigger all the registered handlers when a new epoch is started
=> EN-5150: epoch start notifier

core/check/ifNil.go, core/check/ifNil_test.go
=> En 5237 check if nil reflect

integrationTests/p2p/networkSharding/networkSharding_test.go
added more time on integrated test
=> Fix network sharding integration test

consensus/spos/errors.go, consensus/spos/worker.go, consensus/spos/worker_test.go, process/sync/baseForkDetector.go
* Fixed problem when nodes are entered in sync mode because of a probable highest nonce set by a proposed block
=> Rc bon fix probable highest nonce

integrationTests/node/heartbeat_test.go
Fixed a heartbeat integration test because of a missing function on a stub.
=> fixed heartbeat integration test

integrationTests/multiShard/block/executingRewardMiniblocks_test.go, integrationTests/testProcessorNode.go, process/block/preprocess/transactions.go
=> En 5272 fix computation of fee txs when gas limit is reached to rc

integrationTests/singleShard/block/executingMiniblocksSc_test.go, integrationTests/singleShard/block/executingMiniblocks_test.go, integrationTests/testInitializer.go, integrationTests/testP2PNode.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithMultisigner.go, integrationTests/testSyncNode.go, p2p/errors.go, p2p/libp2p/discovery/hostDecorator.go, p2p/libp2p/discovery/hostDecorator_test.go, p2p/libp2p/discovery/kadDhtDiscoverer.go
Add a new host decorator, able to limit the connection attempts
done by  KAD discovery
=> En 5138  Discovery connections count limit

consensus/message.go, consensus/message_test.go, consensus/spos/bls/subroundSignature.go, consensus/spos/bls/subroundSignature_test.go, consensus/spos/bn/subroundBitmap.go, consensus/spos/bn/subroundBitmap_test.go, consensus/spos/bn/subroundCommitment.go, consensus/spos/bn/subroundCommitmentHash.go, consensus/spos/bn/subroundCommitmentHash_test.go, consensus/spos/bn/subroundCommitment_test.go, consensus/spos/bn/subroundSignature.go, consensus/spos/bn/subroundSignature_test.go, consensus/spos/commonSubround/subroundBlock.go, consensus/spos/commonSubround/subroundBlock_test.go, consensus/spos/worker_test.go
removed ConsensusMessage.Timestamp unused field
=> removed ConsensusMessage.Timestamp unused field

cmd/node/main.go
changed the nodesCoordinator to work without rating
=> Hack nodes coordinator without rating

p2p/libp2p/networksharding/kadSharder.go
fixed display of bad params error when prioBits is 0
=> fixed display of bad params error when prioBits is 0

cmd/node/config/config.toml, cmd/node/main.go, config/config.go
Removed Network ID configuration and flag because it is not used anymore anywhere
=> remove network ID config and flag

data/trie/trieStorageManager.go, epochStart/metachain/pendingMiniBlocks.go
fixed some calls to lock and unlock
=> fixed some calls to Lock and Unlock

cmd/logviewer/main.go, cmd/logviewer/testing/main.go, logger/commonConverters.go, logger/logOutputSubject.go
added milliseconds when displaying a log line
=> Milliseconds in log lines

storage/leveldb/leveldb.go, storage/leveldb/leveldbSerial.go
autoclosing persisters when GC tries to collect the persister instance
=> autoclosing persisters when GC tries to collect the persister instance

integrationTests/mock/blockTrackerStub.go, integrationTests/multiShard/block/edgecases_test.go, node/mock/blockTrackerStub.go, process/block/baseProcess.go, process/block/metablock.go, process/block/metablock_test.go, process/block/shardblock.go, process/block/shardblock_test.go, process/common.go, process/interface.go, process/mock/blockTrackerMock.go, process/rewardTransaction/process.go, process/smartContract/process.go, process/throttle/block.go, process/track/baseBlockTrack.go, process/track/baseBlockTrack_test.go, process/track/export_test.go, process/transaction/metaProcess.go, process/transaction/shardProcess.go
- Fixed cleaning problem from block tracker
- Fixed memory leak problem in block throttle
=> Fix-block-tracker-cleaning-problem

api/node/routes.go, cmd/node/main.go, integrationTests/multiShard/block/interceptedBlocks_test.go
- closing messenger instance in the main function
- added placeholder to insert test code
- added a new integration test for intercepted meta headers
=> - closing messenger instance in the main function

process/interceptors/multiDataInterceptor.go, process/interceptors/singleDataInterceptor.go
added more info on existing prints
=> added more info to existing prints

cmd/node/main.go, sharding/nodesSetup.go, sharding/nodesSetup_test.go
=> remove num-of-nodes option

p2p/libp2p/netMessenger.go, p2p/libp2p/peersOnChannel.go, scripts/testnet/include/nodes.sh
changed refresh topic peers interval values
updated nodes.sh
=> changed refresh topic peers interval values

cmd/node/factory/structs.go, process/constants.go, process/interface.go, process/track/argBlockProcessor.go, process/track/argBlockTrack.go, process/track/baseBlockTrack.go, process/track/blockProcessor.go, process/track/blockProcessor_test.go, process/track/errors.go, process/track/export_test.go, process/track/metaBlockTrack.go, process/track/shardBlockTrack.go
Fixed an edge case when node not requests next cross header if nothing new would be received because of an epoch change
=> Fixed an edge case when node not requests next cross header

dataRetriever/factory/resolverscontainer/baseResolversContainerFactory.go, dataRetriever/factory/resolverscontainer/metaResolversContainerFactory.go, dataRetriever/factory/resolverscontainer/metaResolversContainerFactory_test.go, dataRetriever/factory/resolverscontainer/shardResolversContainerFactory.go, dataRetriever/factory/resolverscontainer/shardResolversContainerFactory_test.go, p2p/libp2p/netMessenger.go, p2p/libp2p/netMessenger_test.go
removed pubsub topic creation for resolvers
=> removed pubsub topic creation for resolvers

cmd/node/factory/structs.go, epochStart/interface.go, epochStart/metachain/pendingMiniBlocks.go, epochStart/metachain/pendingMiniBlocks_test.go, integrationTests/mock/pendingMiniBlocksHandlerStub.go, node/mock/pendingMiniBlocksHandlerStub.go, process/block/pendingMb/pendingMiniBlocks.go, process/block/pendingMb/pendingMiniBlocks_test.go, process/interface.go, process/mock/pendingMiniBlocksHandlerStub.go
* Fixed counting of pending miniblocks created from meta to shards at the end of each epoch (rewards miniblocks)
=> Fix counting of pending miniblocks

crypto/signing/mcl/suiteBLS12_381.go
=> fix mcl import

integrationTests/multiShard/endOfEpoch/executingEpochChange_test.go
skipped TestEpochChangeWithNodesShufflingAndRater
=> skipped TestEpochChangeWithNodesShufflingAndRater

epochStart/interface.go, epochStart/metachain/trigger.go, epochStart/shardchain/trigger.go, epochStart/shardchain/trigger_test.go, process/block/interceptedBlocks/interceptedMetaBlockHeader.go, process/block/metablock.go, process/block/preprocess/smartContractResults_test.go, process/block/preprocess/transactions.go, process/block/preprocess/transactions_test.go, process/block/shardblock.go, process/interface.go
make it easier to search in local pool.
epoch trigger - subscribe to notifier
shardBlock - do not delete in add
metaBlock - do not delete in add
=> epoch trigger - sort metaheaders according to nonce.

integrationTests/state/stateTrie/stateTrie_test.go
Fix TestRollbackBlockAndCheckThatPruningIsCancelledOnAccountsTrie that sometimes fails on TC.
=> Fix failing test

.travis.yml
Invoke `make arwen` during Travis build.
=> Generate Arwen's binary on Travis

cmd/node/config/config.toml, integrationTests/testProcessorNode.go, process/block/baseProcess.go, process/block/metablock.go, process/block/shardblock.go, scripts/testnet/include/config.sh, scripts/testnet/variables.sh
enabled bech32 on addresses, removed a golang ci bot issue, updated testnet scripts
=> enabled bech32 on addresses

integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go, integrationTests/multiShard/smartContract/scCallingSC_test.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithStateCheckpointModulus.go
this branch fixes 2 integration tests (one that affects `development` branch and one that affects `logs-and-events` branch)
=> Fix integration tests

epochStart/genesis/genesisBlockCreator.go
make all metachain nodes call staking at genesis in same order
=> Fix different root hash genesis

storage/leveldb/common.go, storage/leveldb/leveldb.go, storage/leveldb/leveldbSerial.go, storage/leveldb/leveldb_test.go
added a call to leveldb subsystem to recover the db file in case there is an error opening the existing file
=> Automatic recover of corrupted DB file

epochStart/shardchain/trigger.go, epochStart/shardchain/trigger_test.go
revert state to block in epoch trigger should search for the first epoch start block he can find.
=> Bug fix/revert state to block if no block inepoch

integrationTests/vm/arwen/arwenVM/arwenVM_test.go, integrationTests/vm/testInitializer.go
Integration test to force SC processing and trie
=> Integration test to force SC processing and trie

integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, integrationTests/vm/esdt/esdtProcess_test.go, integrationTests/vm/systemVM/stakingSC_test.go, process/block/preprocess/gasComputation.go, process/smartContract/builtInFunctions/esdtTransfer.go, process/smartContract/process.go, process/smartContract/vmInput.go, vm/factory/systemSCFactory.go, vm/gasCost.go, vm/interface.go, vm/mock/systemEIStub.go, vm/systemSmartContracts/auction.go, vm/systemSmartContracts/eei.go, vm/systemSmartContracts/eei_test.go, vm/systemSmartContracts/esdt.go, vm/systemSmartContracts/esdt_test.go
Added integration test.
Fixed gas consumed fee computation for current shard.
Eliminated useless smart contract results.
Fixed treating the error of an asyncCall.
=> En 6125/esdt integration test

integrationTests/vm/systemVM/stakingSC_test.go, vm/systemSmartContracts/auction.go, vm/systemSmartContracts/auction_test.go, vm/systemSmartContracts/staking.go
fixed cases of stake-unstake-stake.
fixed cases of stake-unstake-unbond-stake
fixed cases of stake-unstake-stake-claim
=> En 6287/staking auction improvements

cmd/node/config/api.toml
enable the route which returns the cost of a transaction
=> enable transaction cost route

cmd/node/config/config.toml
=> fixed start in epoch config

heartbeat/process/sender.go
Update node type that is displayed in termUI
=> update node type

cmd/node/main.go, sharding/indexHashedNodesCoordinator.go, vm/systemSmartContracts/auction.go
=> Fix antiflood

core/constants.go, process/mock/peerAccountHandlerMock.go, process/peer/export_test.go, process/peer/process.go, process/peer/process_test.go, sharding/indexHashedNodesCoordinator.go, sharding/indexHashedNodesCoordinatorWithRater.go, sharding/indexHashedNodesCoordinatorWithRater_test.go
added "jailed" nodes list in order to display these in the explorer
=> jailed nodes list

api/network/routes.go, statusHandler/statusMetricsProvider.go
added `erd_latest_tag_software_version` metric to the network config endpoint
=> added software version metric to network config endpoint

dataRetriever/txpool/README.md, storage/txcache/score.go
https://github.com/ElrondNetwork/elrond-go/tree/pool%2B%2Bdocs/dataRetriever/txpool
=> TxPool documentation (readme)

core/indexer/common.go, core/indexer/elasticsearchDatabase.go, core/indexer/elasticsearchDatabaseClient.go, core/indexer/elasticsearchDatabase_test.go, core/indexer/interface.go, core/indexer/queries.go, core/mock/databaseWriterMock.go, vm/systemSmartContracts/staking.go
`Bug`: Status of transactions that are indexed in elasticserach database remains Pending because cross shard transactions was indexed first by the observer from destination shard and after that was indexed again by  the observer from source shard. This happens because observer from source shard was behind. 
`Fix` : Before index a transaction an extra check was added to verify if transaction exists in database.
This bug also occurs when mini-blocks are indexed
=> Check if txs and mbs exists in es

vm/systemSmartContracts/auction.go, vm/systemSmartContracts/auction_test.go
added verification and check that only the validator can unJail his own nodes.
=> En 6804/un jail only validator

debug/p2p/export_test.go, debug/p2p/p2pDebugger_test.go
- fixed race conditions in p2p debugger unit tests
=> Fix p2p debugger unit tests

consensus/broadcast/delayedBroadcast.go
Improved logging for now to help narrow down on the issue of odd length on header hash hex representation.
=> odd length hash

core/indexer/constants.go
Reduced the number of requests to elastic search database.
=> reduced the number of request to elastic search

docker/elrond/Dockerfile, docker/seednode/Dockerfile
include Docker builder pattern (multi-stage builds)
golang base container
start with Entrypoint
Elrond Node:
remove network specific configs
TODO: remove version dependencies for arwen-wasm-vm
=> prepare elrond and seednode dockerfiles

data/mock/dataTrieTrackerStub.go, data/state/accountsDB.go, data/state/export_test.go, data/state/interface.go, data/state/trackableDataTrie.go, data/state/trackableDataTrie_test.go, data/trie/trieStorageManager.go, process/mock/dataTrieTrackerStub.go
Remove unused code from state package and change some log levels.
=> remove unused code

cmd/node/config/economics.toml, cmd/node/factory/structs.go, cmd/node/main.go, config/economicsConfig.go, data/block/metaBlock.pb.go, epochStart/errors.go, epochStart/metachain/economics.go, epochStart/metachain/economics_test.go, epochStart/mock/rewardsHandlerStub.go, genesis/process/genesisBlockCreator_test.go, integrationTests/testProcessorNode.go, process/block/displayMetaBlock.go, process/economics/economicsData.go, process/economics/economicsData_test.go, process/errors.go, process/factory/metachain/vmContainerFactory_test.go, process/interface.go, process/mock/rewardsHandlerMock.go, process/peer/process_test.go, vm/interface.go, vm/mock/validatorSettingsStub.go, vm/systemSmartContracts/auction.go
implementation of new economics
=> En 7072/economics final

cmd/node/config/config.toml
This branch contains only the change in caches number of items from the debug-leveldb-serial branch
=> cmd: resize storer caches

cmd/node/config/p2p.toml, cmd/seednode/config/p2p.toml, config/p2pConfig.go, factory/networkComponents_test.go, integrationTests/p2p/networkSharding/networkSharding_test.go, integrationTests/p2p/peerDisconnecting/peerDisconnecting_test.go, integrationTests/p2p/peerDiscovery/kadDht/peerDiscovery_test.go, integrationTests/testInitializer.go, p2p/example/libp2p/autodiscovery/main.go, p2p/libp2p/discovery/continuousKadDhtDiscoverer.go, p2p/libp2p/discovery/continuousKadDhtDiscoverer_test.go, p2p/libp2p/discovery/factory/peerDiscovererFactory.go, p2p/libp2p/netMessenger_test.go
- renamed the RandezVous option to ProtocolID
=> ProtocolID instead of randezvous

Makefile, cmd/CLI.md.sh, cmd/keygenerator/CLI.md, cmd/logviewer/CLI.md, cmd/node/CLI.md, cmd/seednode/CLI.md, cmd/termui/CLI.md
Results:
- https://github.com/ElrondNetwork/elrond-go/blob/cli-readme/cmd/node/CLI.md
- https://github.com/ElrondNetwork/elrond-go/blob/cli-readme/cmd/seednode/CLI.md
- https://github.com/ElrondNetwork/elrond-go/blob/cli-readme/cmd/termui/CLI.md
- https://github.com/ElrondNetwork/elrond-go/blob/cli-readme/cmd/keygenerator/CLI.md
- https://github.com/ElrondNetwork/elrond-go/blob/cli-readme/cmd/logviewer/CLI.md
=> Auto generate Markdown files for CLI

integrationTests/p2p/networkSharding/networkSharding_test.go, integrationTests/testP2PNode.go
- fixed the network sharding test that was caused by not instantiating the peerSignatureHandler component
- added a new protection in the network sharding test
=> Fixed network sharding test

cmd/node/config/config.toml, process/block/baseProcess_test.go, process/block/metablock.go, process/constants.go, process/track/baseBlockTrack.go, process/track/baseBlockTrack_test.go, process/track/blockProcessor_test.go
* Tuned up some constants to improve catch up speed
* Adjusted some miniblocks parameters
=> Tuned up some constants to improve catch up speed

cmd/node/factory/structs.go, genesis/process/intermediate/standardDelegationProcessor.go
- making arwen in-process for genesis
- added prints for time duration for the verify section
=> Hotfix for delegation SC when delegating 1400 nodes

cmd/node/factory/structs.go, genesis/process/intermediate/standardDelegationProcessor.go
Release 2020.07.22 1 for v1.0.146
=> Release 2020.07.22 1

cmd/node/factory/structs.go, cmd/node/main.go
- save genesis blocks in nonce-hash storers
=> Save genesis in nonce hash storer

cmd/node/config/economics.toml
- added more digits in inflation settings
=> Update inflation with more digits

scripts/testnet/include/config.sh, scripts/testnet/variables.sh
Adapted testnet's script to use the output directory of file generator
=> adapted testnet's script to new filegen

cmd/node/config/systemSmartContractsConfig.toml
- updated MaxNumberOfNodesForStake to the mainnet value in order to better test the new branches
=> Update max staking nodes

integrationTests/multiShard/transaction/interceptedResolvedBulkTx/interceptedResolvedBulkTx_test.go
- fixed test by lowering the number of nodes per shard
=> Fix tx routing test

node/nodeTransactions.go, node/nodeTransactions_test.go
Fix status of a smart contract deploy transaction. A smart contract deploy is always intra-shard.
=> Fix status of a smart contract deploy transaction

process/smartContract/process.go, process/transaction/shardProcess.go
fix backward compatibility of tx gas consumption in case of invalid txs
=> fix backward compatibility of tx gas consumption in case of invalid txs

integrationTests/multiShard/relayedTx/edgecases/edgecases_test.go, integrationTests/multiShard/relayedTx/relayedTx_test.go
- temporary skipped relayed txs tests
=> Temp skip relayed tests

epochStart/metachain/rewards.go
- added debug prints for reward miniblock mismatch
=> Added debug prints for reward transaction mismatch

cmd/node/config/economics.toml, cmd/node/config/systemSmartContractsConfig.toml
- changed ERD naming in configs to eGLD
- reduced the minimum stake value
=> Updated configs

.github/workflows/deployment.yml, docker/keygenerator/Dockerfile
Build & push docker image for keygenerator as well.
=> Docker for keygenerator

cmd/node/config/ratings.toml
updated decreaseRating step to **4*** increaseratingStep
=> updated ratings.toml comments

cmd/node/config/config.toml, cmd/node/config/ratings.toml, cmd/node/config/systemSmartContractsConfig.toml
- config for testing the upgrade process
=> Config test upgrade

integrationTests/frontend/staking/staking_test.go, integrationTests/frontend/staking/testdata/key.pem, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, process/unsigned/interceptedUnsignedTransaction.go
- added integration test that proves that a staking transaction with real BLS signature will work. Test data will be provided from the frontend testing process.
=> Integration test on staking process with real BLS signed values

cmd/node/config/ratings.toml, cmd/node/config/systemSmartContractsConfig.toml, go.mod, go.sum, process/smartContract/process.go
Resolves issues with backward compatibility. Uses flags where code changed.
=> New-arwen-backward-compatible

integrationTests/multiShard/endOfEpoch/epochStartChangeWithContinuousTransactionsInMultiShardedEnvironment/epochStartChangeWithContinuousTransactionsInMultiShardedEnvironment_test.go, integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go, integrationTests/multiShard/hardFork/hardFork_test.go, integrationTests/multiShard/relayedTx/relayedTx_test.go, integrationTests/multiShard/smartContract/scCallingSC_test.go, integrationTests/state/stateTrie/stateTrie_test.go, integrationTests/testInitializer.go, integrationTests/vm/esdt/esdtProcess_test.go, integrationTests/vm/systemVM/stakingSC_test.go
- fixed transaction dispatching in integration tests
=> Fixed transaction dispatching in integration tests

cmd/node/factory/structsStatusHandlers.go, cmd/termui/main.go, statusHandler/errors.go, statusHandler/factory/viewsFactory.go, statusHandler/factory/viewsFactory_test.go, statusHandler/presenter/chainInfoGetters.go, statusHandler/presenter/chainInfoGetters_test.go, statusHandler/view/interface.go, statusHandler/view/termuic/interface.go, statusHandler/view/termuic/termuiConsole.go, statusHandler/view/termuic/termuiRenders/widgetsRender.go
- made the termui interface refresh faster than on second
- fixed the termui estimations on blocks/second and time to a complete sync
=> Fix termui sync status

cmd/node/main.go, core/indexer/dataIndexerArgs.go, core/indexer/elasticProcessor.go, core/indexer/elasticProcessor_test.go, core/indexer/factory/indexerFactory.go, core/indexer/factory/indexerFactory_test.go, core/indexer/processTransactions.go, core/indexer/processTransactions_test.go
- removed the shard coordinator injection in indexer
=> Removed unnecessary dependency in indexer

vm/systemSmartContracts/delegation.go
implemented view functions for delegation system smart contract
=> EN-8065/View-functions-for-system-delegation-sc

vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegationManager.go, vm/systemSmartContracts/delegationManager_test.go, vm/systemSmartContracts/delegation_test.go
1. There were added some TODOs with questions about the correctness of the code execution for some edge cases
2. There were done some small code modifications (method renaming, errors handling/returning, wrong log info, etc)
3. There were found some few issues and had also been proposed an implementation for their fixes (added TODOs describing the reason behind of the new code proposal)
=> Delegation system SC - Audit

cmd/node/main.go, factory/cryptoComponents.go, factory/cryptoComponents_test.go
- fixed turbo import-db turbo mode by injecting the correct sign verifier in vm container
=> EN 8192 Fix import-DB turbo mode

core/indexer/elasticClientCommon.go, core/indexer/elasticProcessor.go, core/indexer/elasticProcessor_test.go
Fix backwards compatibility problem with observers that index data in elasticsearch database.
=> fix backwards compatibility problem with elastic search observers

cmd/node/flags.go, epochStart/bootstrap/epochStartMetaBlockProcessor.go, epochStart/bootstrap/process.go, epochStart/bootstrap/storageEpochStartMetaBlockProcessor.go, epochStart/bootstrap/storageEpochStartMetaBlockProcessor_test.go, epochStart/bootstrap/storageProcess.go, epochStart/bootstrap/storageProcess_test.go, epochStart/bootstrap/syncValidatorStatus.go, errors/errors.go, factory/bootstrapComponents.go, factory/processComponents.go, process/block/shardblock.go, storage/leveldb/leveldb.go, storage/leveldb/leveldbSerial.go
- implemented start in epoch in import-db process
=> EN 8232 new storage bootstrap component

dataRetriever/mock/trieStorageManagerStub.go, dataRetriever/storageResolvers/trieNodeResolver_test.go, epochStart/bootstrap/epochStartMetaBlockProcessor.go, epochStart/bootstrap/process.go, epochStart/bootstrap/storageEpochStartMetaBlockProcessor.go, epochStart/bootstrap/storageEpochStartMetaBlockProcessor_test.go, epochStart/bootstrap/storageProcess.go, epochStart/bootstrap/storageProcess_test.go, epochStart/metachain/economics_test.go, epochStart/mock/economicsHandlerStub.go, epochStart/mock/interceptedDataStub.go, factory/bootstrapComponents.go
- added storage epoch start bootstrap unit tests
=> EN 8234 add unit tests

dataRetriever/factory/resolverscontainer/args.go, dataRetriever/factory/resolverscontainer/baseResolversContainerFactory.go, dataRetriever/factory/resolverscontainer/metaResolversContainerFactory.go, dataRetriever/factory/resolverscontainer/shardResolversContainerFactory.go, dataRetriever/resolvers/baseFullHistoryResolver.go, dataRetriever/resolvers/baseSimpleResolver.go, dataRetriever/resolvers/baseStorageResolverFactory.go, dataRetriever/resolvers/headerResolver.go, dataRetriever/resolvers/interface.go, dataRetriever/resolvers/miniblockResolver.go, dataRetriever/resolvers/miniblockResolver_test.go, dataRetriever/resolvers/transactionResolver.go, factory/processComponents.go
- changed the resolvers so they can be used by the full history nodes by taking into account the provided epoch value
=> En 7444 sync from genesis resolvers

core/indexer/dataDispatcher.go, core/indexer/dataDispatcher_test.go
Try to index all the items that are in the `dataDispatcher` queue when method `Close` is called.
=> Try to write all the items from  the queue when method Close is called

cmd/node/main.go, debug/resolver/interceptorResolver.go, epochStart/interface.go, epochStart/metachain/economics_test.go, epochStart/metachain/trigger.go, epochStart/metachain/trigger_test.go, epochStart/shardchain/trigger.go, integrationTests/mock/endOfEpochTriggerStub.go, integrationTests/multiShard/hardFork/hardFork_test.go, integrationTests/testP2PNode.go, integrationTests/testProcessorNode.go, node/mock/endOfEpochTriggerStub.go, update/errors.go, update/factory/exportHandlerFactory.go, update/interface.go, update/mock/epochHandlerStub.go, update/mock/roundHandlerStub.go, update/trigger/export_test.go, update/trigger/trigger.go, update/trigger/trigger_test.go
- made the hardfork trigger broadcast the early start of epoch round as to avoid async setting that can give unpredictable results
=> Hardfork fixes 2020.12.02

data/interface.go, data/syncer/baseAccountsSyncer.go, data/syncer/userAccountsSyncer.go, data/syncer/validatorAccountsSyncer.go, data/trie/errors.go, data/trie/statistics/trieSyncStatistics.go, data/trie/statistics/trieSyncStatistics_test.go, data/trie/sync.go, data/trie/sync_test.go, integrationTests/state/stateTrieSync/stateTrieSync_test.go, update/sync/coordinator.go, update/sync/syncAccountsDBs.go
- added sync tries progress information prints
=> Sync tries progress

core/constants.go, core/parsers/errors.go, node/errors.go, node/external/nodeApiResolver.go, p2p/libp2p/netMessenger.go, process/block/baseProcess.go
=> Linter fixes for Goland 2020.3 for feat/soft-restart

examples/address_test.go, examples/blsSigning_test.go
Added address examples:
-bech32 to hex
-hex to bech32
-shard ID computation
Added bls signing example
=> added example tests for addresses and bls signing

integrationTests/vm/arwen/badcontracts/badcontracts_test.go, integrationTests/vm/arwen/delegation/delegation_test.go, process/smartContract/process.go, vm/systemSmartContracts/validator.go
=> cleanup unused function

cmd/node/config/config.toml, cmd/node/config/systemSmartContractsConfig.toml
=> Fixed enable epochs in configs

integrationTests/vm/arwen/arwenVM/arwenVM_test.go, integrationTests/vm/arwen/arwenVM/gasSchedule_test.go, integrationTests/vm/arwen/delegation/delegation_test.go, integrationTests/vm/arwen/wasmer/wasmer_test.go, integrationTests/vm/mockVM/vmDeploy/vmDeploy_test.go, integrationTests/vm/mockVM/vmGet/vmGet_test.go, integrationTests/vm/mockVM/vmRunContract/vmRunContract_test.go, integrationTests/vm/testInitializer.go, integrationTests/vm/txsFee/backwardsCompatibility_test.go, integrationTests/vm/txsFee/builtInFunctions_test.go, integrationTests/vm/txsFee/moveBalance_test.go, integrationTests/vm/txsFee/multiShard/builtInFunctions_test.go, integrationTests/vm/txsFee/multiShard/moveBalance_test.go, integrationTests/vm/txsFee/multiShard/relayedBuiltInFunctions_test.go, integrationTests/vm/txsFee/multiShard/relayedMoveBalance_test.go, integrationTests/vm/txsFee/multiShard/relayedScDeploy_test.go, integrationTests/vm/txsFee/multiShard/relayedTxScCalls_test.go, integrationTests/vm/txsFee/multiShard/scCalls_test.go, integrationTests/vm/txsFee/relayedBuiltInFunctions_test.go, integrationTests/vm/txsFee/relayedMoveBalance_test.go, integrationTests/vm/txsFee/relayedScCalls_test.go, integrationTests/vm/txsFee/relayedScDeploy_test.go, integrationTests/vm/txsFee/scCalls_test.go, integrationTests/vm/txsFee/scDeploy_test.go, integrationTests/vm/txsFee/utils/utils.go, process/smartContract/testUtils.go, process/transaction/shardProcess.go, process/transaction/shardProcess_test.go
- fixed a backwards compatibility issue when computing transaction fee
=> Fixed backwards compatibility new issue

storage/factory/openStorage.go, storage/factory/openStorage_test.go, storage/storageUnit/storageunit.go, storage/storageUnit/storageunit_test.go
removed persister creation from short tests
=> removed persister creation test from short tests - took 50 seconds each

integrationTests/vm/delegation/delegationScenarios_test.go
* Added delegation system SC integration test complex scenario
=> System delegation SC scenarios

cmd/node/factory/structs.go, epochStart/interface.go, epochStart/metachain/stakingDataProvider.go, epochStart/metachain/systemSCs.go, epochStart/metachain/systemSCs_test.go, epochStart/mock/stakingDataProviderStub.go, integrationTests/testProcessorNode.go, integrationTests/vm/delegation/delegationScenarios_test.go, process/smartContract/process.go, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegation_test.go, vm/systemSmartContracts/staking.go, vm/systemSmartContracts/validator.go, vm/systemSmartContracts/validator_test.go
added function to redelegate rewards
added function to call unStake at end of epoch in case of system delegation smart contracts.
added function reStakeUnStakedNodes
=> reDelegate-rewards

vm/systemSmartContracts/staking.go
- fixed the wrong error return when trying to unstake an already unstaked node at end of epoch
=> More fixes for unqualified nodes

epochStart/metachain/systemSCs_test.go
- added test for the unqualified node situation
=> Test for unqualified nodes

epochStart/metachain/economics.go, epochStart/metachain/economics_test.go
unit tests for rewards with different inflation rates and acc fees and devfees
=> acc fees greater than inflation and zero inflation tests

cmd/node/main.go, core/constants.go, statusHandler/statusMetricsProvider.go, statusHandler/statusMetricsProvider_test.go
Added **rewards top up gradient value** in api route `/network/config`
=> added gradient value in network config api route

api/block/routes.go, api/block/routes_test.go, api/mock/facade.go, core/dblookupext/factory/historyRepositoryFactory_test.go, core/mock/chainStorerMock.go, fallback/headerValidator_test.go, vm/errors.go, vm/factory/readOnlySCContainer_test.go, vm/process/messageSigVerifier.go, vm/process/messageSigVerifier_test.go
Improved code coverage for different packages / files.
No system tests needed
=> unit tests for un-tested files

cmd/node/main.go, core/constants.go, statusHandler/statusMetricsProvider.go, statusHandler/statusMetricsProvider_test.go
Added **top up factor** in the api route `/network/config`
=> added top up factor in network config api route

examples/address_test.go
- added deploy SC address in examples
=> Example contract deploy sc address

integrationTests/vm/esdt/esdtProcess_test.go
Add integration tests in which a SC calls another SC using ESDT, but the second SC returns an error. All state changes should be reverted.
=> esdt async call tests

cmd/node/config/gasSchedules/gasScheduleV2.toml, vm/systemSmartContracts/staking.go, vm/systemSmartContracts/staking_test.go, vm/systemSmartContracts/validator.go, vm/systemSmartContracts/validator_test.go
new possibility to stake nodes after unstake
=> allow-stake-node-after-unstake

integrationTests/node/getAccount/getAccount_test.go, integrationTests/state/genesisState/genesisState_test.go, integrationTests/state/stateExecTransaction/stateExecTransaction_test.go, integrationTests/state/stateTrie/stateTrie_test.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithStateCheckpointModulus.go, integrationTests/testSyncNode.go, integrationTests/vm/arwen/delegation/delegationSimulation_test.go, vm/systemSmartContracts/validator.go
- added integration test for stake delegation simulation with time printing
=> Delegation stake simulation

process/smartContract/process.go
small improvement of return message
=> small-improvement-of-return-message

scripts/testnet/include/config.sh, scripts/testnet/variables.sh
=> Fixed local testnet scripts

cmd/node/factory/structs.go, process/block/argProcessor.go, process/block/metablock.go
=> bwd-fix/order-of-processing-meta

update/sync/syncHeadersByHash.go, update/sync/syncMiniBlocks.go
- Added missing `continue` statements on for loops
=> update/sync: add missing continue

update/sync/syncHeadersByHash.go
Make code a little less verbose.
=> update/sync: combine locks

p2p/libp2p/directSender.go, p2p/libp2p/directSender_test.go
- fixed unit test
- removed useless import aliases
- renaming (fixed typos)
=> External fixes

epochStart/metachain/stakingDataProvider.go, go.mod, go.sum, process/factory/shard/vmContainerFactory.go
=> use-flag-for-arwen-constructor

cmd/node/config/gasSchedules/gasScheduleV1.toml, cmd/node/config/gasSchedules/gasScheduleV2.toml, go.mod, go.sum, process/factory/metachain/vmContainerFactory_test.go, process/smartContract/builtInFunctions/factory_test.go, process/transaction/transactionCostEstimator_test.go, vm/gasCost.go, vm/systemSmartContracts/defaults/gasMap.go
- Integrated new Arwen binary v1.0.1
=> Integrate arwen v1.0.1

data/state/accountsDB_test.go, data/state/export_test.go
Add a benchmark for getCodeEntry from accountsDB.
=> GetCode benchmark

cmd/assessment/hostParameters/hostParametersGetter.go, cmd/assessment/hostParameters/hostParametersGetter_test.go, cmd/assessment/main.go
- added new tool's boilerplate code + hosts parameters info
The tool requirements are:
- display anonymized host data
- run several SC benchmarks and display the host's result
=> Assessment tool binary preparation

process/smartContract/process.go, process/sync/storageBootstrap/baseStorageBootstrapper.go, vm/systemSmartContracts/governance.go
- fixed all log.LogIfError calls to contain an odd number of arguments so the messages will be displayed properly
=> Fixed LogIfError usage

cmd/node/factory/structs.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, integrationTests/testProcessorNode.go, integrationTests/vm/testInitializer.go, process/block/preprocess/gasComputation.go, process/block/preprocess/gasConsumption_test.go, process/smartContract/builtInFunctions/saveUserName.go
Optimized gas computation using new transaction type handler
=> improved gas computation using new tx type handler

core/constants.go, process/block/preprocess/transactions.go, process/coordinator/process.go
* Fixed max block size reached situation when more than one scr is generated
=> Fix max block size reached when more than one scr is generated

process/block/preprocess/gasComputation.go, process/block/preprocess/gasConsumption_test.go
Early exit for smart contract results and low gas limit transactions.
Added unit tests.
=> fix gas computation on edge case

process/block/preprocess/transactions_test.go
* Added unit test for max block size reached edge case
=> Unit test max block size reached

go.mod, go.sum, integrationTests/mock/intermediateTransactionHandlerMock.go, integrationTests/vm/arwen/arwenVM/arwenVM_test.go, integrationTests/vm/testInitializer.go, process/smartContract/testUtils.go
new arwen with fixed memory leakage
=> new arwen with fixed memory leakage

api/api.go, api/block/routes.go, api/block/routes_test.go, api/mock/facade.go, data/api/apiBlock.go, facade/interface.go, facade/mock/nodeStub.go, facade/nodeFacade.go, integrationTests/api/transaction_test.go, integrationTests/interface.go, integrationTests/mock/statusMetricsStub.go, integrationTests/testProcessorNodeWithTestWebServer.go, node/blockAPI/interface.go, node/blockAPI/metaBlock.go, node/blockAPI/shardBlock.go, node/nodeBlocks.go, node/nodeBlocks_test.go
- added web server test processor node
- API small refactor to apply Dependency Inversion Principle
- add integration test that prove backwards compatibility on gas cost route
=> Web server integration test + api small refactor

process/block/preprocess/gasComputation.go, process/block/preprocess/gasConsumption_test.go
Improved gas computation on relayed tx
=> New arwen release

.github/workflows/golangci-lint.yml
make the linter require changes only to the new code + removed log colors
=> updated golangci lint action

cmd/assessment/benchmarks/arwenBenchmark.go, cmd/assessment/benchmarks/coordinator.go, cmd/assessment/benchmarks/coordinator_test.go, cmd/assessment/benchmarks/delegationBenchmark.go, cmd/assessment/benchmarks/erc20Benchmark.go, cmd/assessment/benchmarks/errors.go, cmd/assessment/benchmarks/factory/interface.go, cmd/assessment/benchmarks/factory/runner.go, cmd/assessment/benchmarks/results.go, cmd/assessment/benchmarks/results_test.go, cmd/assessment/hostParameters/hostInfo.go, cmd/assessment/hostParameters/hostInfo_test.go, cmd/assessment/hostParameters/hostParametersGetter.go, cmd/assessment/hostParameters/hostParametersGetter_test.go, cmd/assessment/main.go
- added csv output for host info and benchmarks results
=> Assessment tool output csv feature

docker/elrond/Dockerfile, docker/keygenerator/Dockerfile, docker/seednode/Dockerfile
Update go version from docker images
=> update docker images go version

process/smartContract/process.go, process/smartContract/process_test.go
no built in func call in case of meta
=> no built in func call in case of meta

go.mod, go.sum
- updated 2 dependency versions
- related to #2794 #2796
=> Dependancy updates

data/trie/evictionWaitingList/evictionWaitingList_test.go
Fixed bad test detected by  code coverage tool
=> Fix bad test detected by code cov tool

Makefile, heartbeat/componentHandler/heartbeatHandler_test.go
- fixed a flaky code coverage unit test
=> Fixed heartbeat unit test for code coverage tool

consensus/spos/bls/subroundEndRound.go, factory/blockProcessorCreator.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, integrationTests/testProcessorNode.go, process/block/baseProcess_test.go, process/block/shardblock_test.go, process/coordinator/process.go, process/coordinator/process_test.go
* Refactored transaction coordinator with arguments
=> Refactor transaction coordinator with arguments

heartbeat/componentHandler/heartbeatHandler_test.go
- fixed a flaky code coverage test
=> Fix flaky test

cmd/node/config/config.toml
- postponed the MaxNodesChangeEnableEpoch.EpochEnable value with 1 epoch
=> Change configs

go.sum
=> Fixed go.sum

epochStart/metachain/systemSCs.go, epochStart/metachain/systemSCs_test.go, vm/systemSmartContracts/validator.go
fixed the scenario of unstaking a node at end of epoch from the waiting list
=> Fix unStake from waiting at end of epoch

node/node_test.go
=> Fixed flaky code coverage unit test

cmd/node/factory/structsStatusHandlers.go, core/computers.go, data/blockchain/baseBlockchain.go, epochStart/bootstrap/process.go, epochStart/metachain/rewardsV2_test.go, factory/blockProcessorCreator.go, factory/statusComponents_test.go, integrationTests/api/transaction_test.go, integrationTests/factory/bootstrapComponents/bootstrapComponents_test.go, node/node.go, node/nodeRunner.go, node/nodeTransactions.go, node/nodeTransactions_test.go, process/coordinator/process_test.go, process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go, storage/txcache/score.go, storage/txcache/wrappedTransaction.go
fix some linter issues
give more time for test to pass libp2p module init.
=> linter issues fix

vm/systemSmartContracts/validator_test.go
=> Unit tests for min unstake value

epochStart/metachain/systemSCs_test.go, integrationTests/vm/systemVM/stakingSC_test.go, integrationTests/vm/testInitializer.go, integrationTests/vm/txsFee/validatorSC_test.go, vm/factory/systemSCFactory.go, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegation_test.go, vm/systemSmartContracts/validator.go, vm/systemSmartContracts/validator_test.go
- Fixed the minimum unstake value
=> updated min unstake value in validator sc

integrationTests/vm/esdt/esdtLocalFunsSC_test.go, integrationTests/vm/esdt/esdtNFTSCs_test.go, integrationTests/vm/esdt/esdtNft_test.go, process/smartContract/builtInFunctions/esdtNFTCreateRoleTransfer.go, testscommon/txDataBuilder/builder.go
transfer create role integration test
=> tNFT Transfer create role integration test

api/address/routes.go, facade/nodeFacade_test.go, integrationTests/vm/esdt/esdtRoles_test.go, node/node_test.go, process/coordinator/transactionType_test.go, process/smartContract/builtInFunctions/changeOwnerAddress_test.go, process/smartContract/builtInFunctions/esdtNFTCreateRoleTransfer_test.go, process/smartContract/builtInFunctions/esdtNFTCreate_test.go, process/smartContract/builtInFunctions/factory_test.go, process/smartContract/builtInFunctions/keyValueStorage_test.go, process/smartContract/hooks/blockChainHook_test.go
Fixed golang-ci linter issues and increased code coverage
=> Linter fixes and code coverage for feat/eip-esdt-local-mint

vm/systemSmartContracts/staking.go, vm/systemSmartContracts/staking_test.go
Improved waiting list view function. returned the bls keys, the reward addresses and the register nonce
=> Improve waiting list view func

cmd/node/main.go, factory/dtos.go, factory/stateComponents.go, integrationTests/testProcessorNodeWithTestWebServer.go, node/node.go, node/node_test.go, node/options.go, node/options_test.go, node/stakeValuesProcessor/errors.go, node/stakeValuesProcessor/stakeValuesHandlerFactory.go, node/stakeValuesProcessor/stakeValuesHandlerFactory_test.go, node/stakeValuesProcessor/stakeValuesProcessor.go, node/stakeValuesProcessor/stakeValuesProcessor_test.go
Bugfix: change mechanism how the `total-staked` value and the `top-up` value is calculated
=> fix network economics API route

go.mod, go.sum
=> New arwen after improvements

go.mod, go.sum
reference proper arwen version
=> reference new arwen 1.2.2

integrationTests/vm/esdt/esdtProcess_test.go
Return to alice the issue price on async callback error
=> Asynccallback treat error

cmd/node/config/config.toml, vm/systemSmartContracts/esdt.go
- Fixed ESDT owner comparison in functions
=> Fixed esdt owner

go.mod, go.sum
=> Arwen 1.2.5

cmd/node/config/config.toml, cmd/node/config/systemSmartContractsConfig.toml
=> Compressed activation flags

cmd/node/config/config.toml
- changed activation flags for ESDT & fixes
=> Changed activation flags for ESDT & fixes

epochStart/metachain/stakingDataProvider.go
initialize ownerStats for unstaked nodes at end of epoch
=> epochStart: initialize ownerStats for unstaked at eoe

go.mod, go.sum
=> arwen 1.2.7

vm/mock/hasherStub.go, vm/systemSmartContracts/esdt.go, vm/systemSmartContracts/esdt_test.go
ensure the token randomness length in all cases
=> ensure the token randomness length in all cases

data/trie/patriciaMerkleTrie.go, statusHandler/presenter/chainInfoGetters.go, storage/pruning/fullHistoryPruningStorer_test.go, storage/pruning/pruningStorer.go, storage/pruning/pruningStorer_test.go
=> Linters fixes for feat/full-history-nodes

vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegationManager.go, vm/systemSmartContracts/validator.go
merge validator data to delegation
=> En 9636/merge validator to delegation

process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go, process/interceptors/baseDataInterceptor.go, process/interceptors/baseDataInterceptor_test.go, process/interceptors/multiDataInterceptor.go, process/interceptors/multiDataInterceptor_test.go, process/interceptors/singleDataInterceptor.go, process/interceptors/singleDataInterceptor_test.go, update/factory/fullSyncInterceptors.go
- refactored interceptors implementation for better code reuse
=> Interceptors refactor

process/constants.go
* Increased max number of headers to whitelist in advance
=> Changed max num of headers to whitelist in advance

vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegationManager_test.go, vm/systemSmartContracts/delegation_test.go, vm/systemSmartContracts/staking.go, vm/systemSmartContracts/staking_test.go, vm/systemSmartContracts/validator.go, vm/systemSmartContracts/validator_test.go
added a set of unit tests for validator to delegation functionality
=> En 9637/unit tests validator to delegation

integrationTests/frontend/staking/staking_test.go, integrationTests/testInitializer.go, integrationTests/vm/systemVM/stakingSC_test.go
=> Reduced duplicated code in the validator to delegation integration tests

api/address/routes.go, api/address/routes_test.go
Added an extra field `developerReward` in the API route `/address/:addr`
=> Developer reward field

process/errors.go, process/interceptors/peerHeartbeatInterceptor.go, process/interceptors/peerHeartbeatInterceptor_test.go, process/interface.go, process/mock/interceptedDataStub.go, process/mock/interceptedPeerHeartbeatStub.go, process/mock/peerHeartbeatProcessorStub.go
- new peer heartbeat interceptor implementation
=> EN 9565 peer heartbeat interceptor

integrationTests/multiShard/validatorToDelegation/validatorToDelegation_test.go
=> linter fix on test

Makefile, api/shared/shared.go, consensus/spos/bls/subroundBlock_test.go, crypto/signing/multisig/pubkeys.go, dataRetriever/dataPool/headersCache/headersPool_test.go, epochStart/bootstrap/process_test.go, integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithStateCheckpointModulus.go, integrationTests/testSyncNode.go, storage/bloom/bloom.go, storage/bloom/bloom_test.go
Added in the Makefile command "make lint" that will run` golangci linter.`
This command will check if the `golangci linter` is installed ( in case of not installed, will install the latest tag of the `golangci linter`) and after that will run the linter.
=> added command "make lint"

integrationTests/multiShard/validatorToDelegation/validatorToDelegation_test.go, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegationManager.go, vm/systemSmartContracts/delegationManager_test.go, vm/systemSmartContracts/delegation_test.go, vm/systemSmartContracts/staking.go, vm/systemSmartContracts/staking_test.go
Implemented merge function with whitelisted address
=> Merge with whitelisted address

epochStart/metachain/systemSCs_test.go
- covered the always jailed fix with unit tests
=> - covered the always jailed fix with unit tests

cmd/node/config/config.toml, cmd/node/factory/structs.go, config/config.go, epochStart/metachain/systemSCs.go, epochStart/metachain/systemSCs_test.go, vm/systemSmartContracts/staking.go
Add check if node is jailed in validator statistics
=> Add-check-if-node-is-jailed-in-VS

data/state/accountsDB.go, data/trie/branchNode.go, data/trie/branchNode_test.go, data/trie/extensionNode.go, data/trie/extensionNode_test.go, data/trie/interface.go, data/trie/leafNode.go, data/trie/leafNode_test.go, data/trie/node_test.go, data/trie/patriciaMerkleTrie.go, data/trie/sync_test.go, data/trie/trieStorageManager.go
Refactor trie insert and commit in preparation for the trie checkpoint optimizations.
=> Refactor trie insert and commit

cmd/node/metrics/metrics.go, core/constants.go, node/nodeTransactions.go, node/nodeTransactions_test.go, statusHandler/statusMetricsProvider.go, statusHandler/statusMetricsProvider_test.go
Set the source and the the destination shard of a transaction when is returned from the pool.
=> Add mising fields /transaction/:hash

epochStart/metachain/rewardsV2.go, epochStart/metachain/rewardsV2_test.go
added unit tests for validation of rewards on v2 and rewards on v3.5
=> En 9713 rewards unit tests

go.mod, go.sum
Use the latest indexer commit that works with the latest version of kibana
This PR will fix the issue https://github.com/ElrondNetwork/elrond-go/issues/3101
=> latest indexer latest kibana version

data/block/blockV2.go, data/block/blockV2_test.go, data/block/block_test.go, data/block/metaBlock_test.go, factory/block/metaHeaderFactory_test.go, factory/block/shardHeaderFactory_test.go, process/block/metablock_test.go, process/block/shardblock_test.go
more unit tests sc execution added
=> En 10102 unit tests sc execution

cmd/assessment/benchmarks/erc20Benchmark.go, cmd/node/config/config.toml, config/config.go, config/tomlConfig_test.go, factory/apiResolverFactory.go, factory/processComponents.go, genesis/process/genesisBlockCreator_test.go, integrationTests/multiShard/hardFork/hardFork_test.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, integrationTests/vm/arwen/arwenvm/arwenVM_test.go, integrationTests/vm/arwen/arwenvm/gasSchedule_test.go, integrationTests/vm/arwen/arwenvm/testRunner.go, integrationTests/vm/arwen/delegation/delegation_test.go, integrationTests/vm/arwen/utils.go, integrationTests/vm/testInitializer.go, process/factory/shard/errors.go, process/factory/shard/vmContainerFactory.go, process/factory/shard/vmContainerFactory_test.go, testscommon/generalConfig.go
=> Removed Arwen OOP

Makefile, cmd/assessment/benchmarks/erc20Benchmark.go, cmd/node/config/config.toml, cmd/node/factory/structs.go, cmd/node/main.go, config/config.go, config/tomlConfig_test.go, genesis/process/genesisBlockCreator_test.go, integrationTests/multiShard/hardFork/hardFork_test.go, integrationTests/testInitializer.go, integrationTests/testProcessorNode.go, integrationTests/vm/arwen/arwenVM/arwenVM_test.go, integrationTests/vm/arwen/arwenVM/gasSchedule_test.go, integrationTests/vm/arwen/arwenVM/testRunner.go, integrationTests/vm/arwen/delegation/delegation_test.go, integrationTests/vm/arwen/utils.go, integrationTests/vm/testInitializer.go, process/factory/shard/vmContainerFactory.go, process/factory/shard/vmContainerFactory_test.go
=> Removed Arwen OOP option

go.mod, go.sum
Updated Arwen to version v1.3.15
=> Update Arwen version to v1.3.15

.github/workflows/create_release.yml
Fixed the create release workflow
=> fixed create release workflow

cmd/node/main.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithStateCheckpointModulus.go, integrationTests/testSyncNode.go, integrationTests/vm/arwen/utils.go, integrationTests/vm/mockVM/vmGet/vmGet_test.go, integrationTests/vm/testInitializer.go, process/smartContract/scQueryService.go, process/smartContract/scQueryService_test.go
=> Added lock for sc query

go.mod, go.sum
=> Arwen 1.3.16

cmd/node/config/config.toml, dataRetriever/resolvers/topicResolverSender/topicResolverSender.go, factory/networkComponentsHandler_test.go, heartbeat/process/messageProcessor_test.go, p2p/libp2p/connectionMonitor/libp2pConnectionMonitorSimple_test.go, p2p/libp2p/export_test.go, p2p/libp2p/netMessenger_test.go
Aligned the remained TODOs + additional unit tests
=> [preferred peers] unit tests + todos aligning

docker/elrond/Dockerfile
Fix docker image to work with the latest arwen.
=> Fix docker image

Makefile
- added `-short` flag for the code coverage run
=> Code cov fixes

Makefile, cmd/node/config/config.toml, consensus/spos/bls/subroundBlock_test.go, epochStart/bootstrap/process_test.go, heartbeat/mock/shardCoordinatorMock.go, integrationTests/multiShard/endOfEpoch/common.go, integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go, integrationTests/multiShard/hardFork/hardFork_test.go, integrationTests/multisig/blsMultisig_test.go, integrationTests/state/stateTrie/stateTrie_test.go, integrationTests/testProcessorNode.go, integrationTests/testProcessorNodeWithStateCheckpointModulus.go, integrationTests/testSyncNode.go, node/mock/shardCoordinatorMock.go, process/factory/shard/vmContainerFactory.go, process/peer/process.go, process/smartContract/process_test.go, process/transaction/baseProcess.go
- linter fixes
- code cov now runs the tests in short mode
=> Linter fixes

cmd/node/main.go
- override health records params during import-db
=> Override health records params during import-db

cmd/seednode/main.go
- fixed messenger creation in seednode app
=> Fix seednode

cmd/assessment/main.go, cmd/node/main.go, core/machineID.go, core/machineID_test.go, data/trie/node.go, data/trie/node_extension.go, data/trie/node_test.go
- added test point
- extracted in a function the machine ID computation
=> Test resync trie when get node from db fails

epochStart/bootstrap/process.go
close triechunksprocessor on bootstrap
=> close triechunksprocessor on bootstrap

go.mod, go.sum
=> new vm-common

cmd/assessment/benchmarks/coordinator.go, cmd/assessment/benchmarks/coordinator_test.go, cmd/assessment/benchmarks/results.go, cmd/assessment/main.go
- added final result print in assessment tool
=> Final result in assessment tool

epochStart/metachain/systemSCs.go, p2p/libp2p/netMessenger.go, vm/systemSmartContracts/esdt.go
- fixed full history prints & misc prints
=> Dev full archive connect/disconnect fixes

go.mod, go.sum
This PR updates dependency on Arwen v1.3.25.
=> Update Arwen with hotfix

data/block/miniBlockHeader.go, data/blockchain/blockchain.go, data/interface.go, epochStart/bootstrap/process.go, epochStart/metachain/epochStartData.go, epochStart/shardchain/trigger.go, process/block/metablock.go, process/block/shardblock.go, process/common.go, process/peer/process.go, process/sync/shardblock.go, process/track/baseBlockTrack.go, process/track/metaBlockTrack.go, process/track/shardBlockTrack.go, testscommon/headerHandlerStub.go
* Replaced cast to *block.Header with ShardHeaderHandler interface
=> Replace cast to block header with ShardHeaderHandler interface

factory/stateComponents.go, state/storagePruningManager/evictionWaitingList/benchmark_test.go, state/storagePruningManager/evictionWaitingList/memoryEvictionWaitingList.go, state/storagePruningManager/evictionWaitingList/memoryEvictionWaitingList_test.go
- fix linter issues on feat/import-db-trie-fixes
=> Fix linter issues

cmd/node/config/api.toml
- fixed formatting in api.toml file
=> Fixed formatting in api.toml

go.mod, go.sum
- new arwen v1.3.28 that fixes a backwards compatibility issue
=> Arwen v1.3.28

cmd/node/config/gasSchedules/gasScheduleV1.toml, cmd/node/config/gasSchedules/gasScheduleV2.toml, cmd/node/config/gasSchedules/gasScheduleV3.toml
Updated existing gas maps with the right (tested) values
=> update gas Schedules

cmd/node/config/external.toml
Added in the indexer config the new indexes .
=> New indexer indexes

node/esdtTokensFilters.go, node/node.go
- use polymorphism instead of function pointers
=> Use polymorphism in EN-10559-all-esdt-roles

.github/workflows/create_release.yml
- removed arwen make call from the release workflow
Release successfully made, as can be seen here: https://github.com/ElrondNetwork/elrond-go/actions/runs/1127255870
=> Removed Arwen make call in the release workflow

cmd/node/config/gasSchedules/gasScheduleV1.toml, cmd/node/config/gasSchedules/gasScheduleV2.toml, cmd/node/config/gasSchedules/gasScheduleV3.toml, go.mod, go.sum, vm/systemSmartContracts/esdt.go
New esdt roles
Integrate new arwen
Add gas costs for new APIs
=> New esdt roles, integrate arwen

consensus/spos/worker.go, go.mod, go.sum, integrationTests/testInitializer.go, node/node.go, storage/factory/pruningStorerFactory.go, storage/leveldb/leveldbSerial.go, trie/node.go, trie/trieStorageManager.go
- fixed oom by closing the snapshot db's used in snapshot process
- minor code changes around some log prints
- refactored pruningStorerFactory.go so it does not use slice pointers
- bump gin version to v1.7.4
=> Fix OOM exceptions

trie/node_extension.go
=> Fixed trie node test point

cmd/node/config/gasSchedules/gasScheduleV1.toml, cmd/node/config/gasSchedules/gasScheduleV2.toml, cmd/node/config/gasSchedules/gasScheduleV3.toml, go.mod, go.sum
new gas cost - new arwen release
=> Integrate new arwen 1.4.8

process/peer/process.go
set decrease leader log from trace to debug
=> set decrease proposer log to debug from trace

process/economics/economicsData.go, process/economics/economicsData_test.go
- Bug-fix: fixed the edge case when computed transaction fee was negative
=> Fix edge case negative fee 

dblookupext/esdtSupply/logsProcessor.go, dblookupext/esdtSupply/logsProcessor_test.go
Bug-fix
-- fixed how the key for an NFT is created.
=> Bug fix token supply 

dblookupext/esdtSupply/logsProcessor.go
Bug-fix: Fix revert condition to work as expected.
=> Fix revert condition

api/gin/webServer.go, api/groups/addressGroup.go, api/groups/blockGroup.go, api/groups/hardforkGroup.go, api/groups/networkGroup.go, api/groups/nodeGroup.go, api/groups/proofGroup.go, api/groups/transactionGroup.go, api/groups/validatorGroup.go, api/groups/vmValuesGroup.go, api/shared/interface.go, facade/disabled/disabledNodeFacade.go, node/nodeRunner.go
integrated the new routes handler + adapted the switchable facade mechanism
=> integrate new routes handler

go.mod, go.sum
=> New arwen 1.4.10

process/smartContract/process.go
fix backward compatibility issue
=> Backward compatibility fix on Transfer And Exec

go.mod, go.sum
=> arwen 1.4.11

testscommon/goroutines/filter.go
- added ntp go routine exception in integration tests
=> Ntp go routine exception

go.mod, go.sum
=> new vm common and arwen

cmd/termui/presenter/chainInfoGetters.go, cmd/termui/presenter/chainInfoGetters_test.go, cmd/termui/view/termuic/termuiRenders/widgetsRender.go
- fixed termui remaining epoch time
=> Fixed termui remaining time metric

cmd/node/config/enableEpochs.toml, config/epochConfig.go, config/tomlConfig_test.go, factory/apiResolverFactory.go, factory/blockProcessorCreator.go, go.mod, go.sum, integrationTests/multiShard/smartContract/polynetworkbridge/bridge_test.go, integrationTests/vm/esdt/process/esdtProcess_test.go, node/esdtTokensFilters.go, node/node.go, node/nodeRunner.go, node/node_test.go, process/smartContract/builtInFunctions/factory.go, vm/systemSmartContracts/esdt.go, vm/systemSmartContracts/esdt.pb.go, vm/systemSmartContracts/esdt_test.go, vm/systemSmartContracts/proto/esdt.proto
=> Create nft on multiple shards

go.mod, go.sum
vmcommon 1.2.1
Test:
MultiTransferESDT with only one token cross shard between 2 users.
https://testnet-explorer.elrond.com/transactions/e8b10bf940a7b0dfa9703140430420928a87467a7d004e35e9cdd7a3a0f64c60
=> vmcommon 1.2.1

cmd/node/config/enableEpochs.toml, cmd/termui/presenter/chainInfoGetters.go, cmd/termui/presenter/chainInfoGetters_test.go, cmd/termui/view/termuic/termuiRenders/widgetsRender.go, config/epochConfig.go, config/tomlConfig_test.go, factory/apiResolverFactory.go, factory/blockProcessorCreator.go, go.mod, go.sum, integrationTests/multiShard/smartContract/polynetworkbridge/bridge_test.go, integrationTests/vm/esdt/process/esdtProcess_test.go, node/esdtTokensFilters.go, node/node.go, node/nodeRunner.go, node/node_test.go, process/smartContract/builtInFunctions/factory.go, vm/systemSmartContracts/esdt.go, vm/systemSmartContracts/esdt.pb.go, vm/systemSmartContracts/esdt_test.go, vm/systemSmartContracts/logs.go, vm/systemSmartContracts/proto/esdt.proto
merge development into `feat/web-server-refactor`
=> Merge development into feat/web-server-refactor

cmd/node/config/enableEpochs.toml, config/epochConfig.go, config/tomlConfig_test.go, genesis/process/shardGenesisBlockCreator.go, node/nodeRunner.go, process/smartContract/process.go, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegation_test.go
Master optimization delegation - compute rewards
=> Master optimization delegation

cmd/node/config/enableEpochs.toml, config/epochConfig.go, config/tomlConfig_test.go, factory/blockProcessorCreator.go, genesis/process/metaGenesisBlockCreator.go, genesis/process/shardGenesisBlockCreator.go, go.mod, go.sum, integrationTests/testProcessorNode.go, node/nodeRunner.go, process/errors.go, process/smartContract/process.go, process/smartContract/process_test.go
arwen 1.4.14 and scr size invariant check
=> arwen 1.4.14 and scr size invariant check

docker/elrond/Dockerfile
- Removed arwen build from the elrond node Docker image
=> Remove arwen build from docker image

cmd/node/config/enableEpochs.toml
- compressed configs for development branch
=> Compressed configs for development branch

cmd/node/flags.go
- completely disabled checkpointing in import-db process
=> Disabled checkpointing in import-db

process/block/export_test.go, process/block/shardblock.go, process/block/shardblock_test.go, process/peer/process.go
* Fixed missing trigger from epoch start meta block
=> Fix missing trigger from meta block epoch start

storage/pruning/pruningStorer.go
Small refactor for the pruning storer Get().
=> Refactor Get() from pruningStorer

storage/pruning/fullHistoryPruningStorer.go, storage/pruning/fullHistoryPruningStorer_test.go, storage/pruning/pruningStorer.go
=> Master with storer fixes

common/constants.go, factory/statusComponents.go, go.mod, go.sum, integrationTests/vm/testIndexer.go, outport/errors.go, outport/factory/outportFactory.go, outport/factory/outportFactory_test.go, outport/interface.go, outport/mock/driverStub.go, outport/outport.go, outport/outport_test.go
- new outport driver interface
- made the outport handler wait for all drivers to return nil error on each function
=> New outport driver interface - take 2

process/block/preprocess/transactionsV2_test.go, process/block/preprocess/transactions_test.go
=> Unit tests for transactions V2

go.mod, go.sum, process/smartContract/process.go
=> Fix backwd comp store cost

integrationTests/mock/intermediateTransactionHandlerMock.go, process/block/postprocess/basePostProcess.go, process/coordinator/process.go, process/interface.go, process/mock/intermProcessorStub.go, process/mock/intermediateTransactionHandlerMock.go
=> revert-fees-from-SCRs

go.mod, go.sum
=> new backward comp try

p2p/libp2p/netMessenger_test.go
=> Fixed p2p unit test

common/constants.go, state/accountsDB.go, trie/trieStorageManager.go
Reverts ElrondNetwork/elrond-go#3623
=> Revert "No snapshot after start in epoch"

go.mod, go.sum, integrationTests/vm/testIndexer.go
=> Fix indexer mappings

integrationTests/vm/testIndexer.go, integrationTests/vm/txsFee/multiESDTTransfer_test.go, integrationTests/vm/txsFee/scCalls_test.go
fix assessment tool for master-with-latest-indexer-v1.2.36
=> fix assessment tool build

storage/pruning/pruningStorer.go, storage/pruning/pruningStorer_test.go, testscommon/snapshotPruningStorerMock.go, testscommon/trie/snapshotPruningStorerStub.go, trie/interface.go, trie/snapshotTrieStorageManager.go, trie/snapshotTrieStorageManager_test.go
When a snapshot is in progress, try and get the needed values from cache first.
=> get from cache when taking snapshot

go.mod, go.sum, process/block/preprocess/gasComputation.go
=> Arwen 1.4.34

dblookupext/esdtSupply/esdtSuppliesProcessor.go, dblookupext/esdtSupply/esdtSuppliesProcessor_test.go, dblookupext/esdtSupply/logsProcessor.go, dblookupext/esdtSupply/logsProcessor_test.go
- fixed panic in logs processor
=> Fixed panic in logs processor

go.mod, go.sum
=> vmcommon 1.2.10

process/block/baseProcess_test.go, process/block/preprocess/scheduledTxsExecution_test.go
added unit tests for newly added methods for scheduled with invalid blocks
=> added unit tests for new methods for scheduled

cmd/node/config/config.toml, cmd/node/config/enableEpochs.toml
- temporary disable scheduled txs feature
=> Temporary disable scheduled txs feature

go.mod, go.sum
New vmcommon check froze on collection
=> New vmcommon check froze on collection

sharding/networksharding/export_test.go, sharding/networksharding/peerShardMapper.go, sharding/networksharding/peerShardMapper_test.go
- added prints for the pid <-> BLS PK mapping
=> Prints for the pid <-> BLS PK mapping

process/smartContract/hooks/blockChainHook_test.go
- fixed data race condition in blockchain hook unit tests
=> Fixed data race condition in blockchain hook unit tests

README.md, process/rating/peerHonesty/peerHonesty_test.go
- fixed golang minimum version
- fixed race condition in `TestP2pPeerHonesty_Close` test
=> Update readme.md + fixed race condition in unit test

go.mod, go.sum
=> Indexer v1.1.35

epochStart/metachain/systemSCs_test.go, storage/leveldb/leveldbSerial.go
Improved the destroying of the level db storers
=> LevelDB storer Destroy improvements

go.mod, go.sum
- This new vm-common will generate logs and events for ESDT built in functions like `ESDTWipe`, `ESDTSetRoles` etc
=> Latest vm-common v1.2.12

cmd/node/config/gasSchedules/gasScheduleV1.toml, cmd/node/config/gasSchedules/gasScheduleV2.toml, cmd/node/config/gasSchedules/gasScheduleV3.toml, cmd/node/config/gasSchedules/gasScheduleV4.toml, cmd/node/config/gasSchedules/gasScheduleV5.toml, go.mod, go.sum
=> arwen v1.4.34 rc2

common/logging/fileLogging_test.go, epochStart/metachain/systemSCs_test.go, go.mod, go.sum, integrationTests/longTests/storage/storagePutRemove_test.go, integrationTests/multiShard/hardFork/hardFork_test.go, integrationTests/state/stateTrieSync/stateTrieSync_test.go, storage/factory/directoryhandler/directoryReader_test.go, storage/leveldb/leveldbSerial_test.go, storage/leveldb/leveldb_test.go, storage/pruning/fullHistoryPruningStorer_test.go, storage/pruning/pruningStorer_test.go, storage/storageUnit/storageunit_test.go, trie/doubleListSync_test.go, trie/interceptedNode_test.go, trie/iterator_test.go, trie/patriciaMerkleTrie_test.go, trie/trieStorageManager_test.go, update/genesis/export_test.go, update/trigger/importStartHandler_test.go
=> Master to scheduled 02 25 v2

go.mod, go.sum
=> vm 1.4.34-rc6

go.mod, go.sum, integrationTests/resolvers/smartContractsResults/scrs_test.go, integrationTests/resolvers/testInitializer.go, p2p/libp2p/directSender.go, p2p/libp2p/netMessenger.go, p2p/libp2p/netMessenger_test.go
=> P2P data limit change

genesis/process/genesisBlockCreator_test.go, genesis/process/shardGenesisBlockCreator.go, process/block/postprocess/intermediateResults.go, process/smartContract/process.go, process/transaction/baseProcess.go
=> backward compatibility multishard

factory/apiResolverFactory.go, integrationTests/testProcessorNodeWithTestWebServer.go, integrationTests/vm/testInitializer.go, integrationTests/vm/txsFee/txCostEstimator_test.go, process/smartContract/process.go, process/smartContract/process_test.go, process/transaction/transactionCostEstimator.go, process/transaction/transactionCostEstimator_test.go
change too much gas provided message
=> change too much gas provided message

go.mod, go.sum, process/sync/baseSync.go, process/sync/baseSync_test.go, testscommon/headerHandlerStub.go
This PR allows rollback of final block to allow re-processing if it holds scheduled mini blocks
=> Rollback final block with scheduled

process/block/preprocess/basePreProcess.go, process/block/preprocess/smartContractResults.go, process/block/preprocess/smartContractResults_test.go, process/block/preprocess/transactions.go, process/block/preprocess/transactions_test.go, process/block/shardblock.go
- fixed the epoch activation in transactions pre-processors
=> Fixed the epoch activation in transactions pre-processors

epochStart/bootstrap/startInEpochScheduled.go, epochStart/bootstrap/startInEpochScheduled_test.go, process/block/preprocess/scheduledTxsExecution.go, process/block/preprocess/scheduledTxsExecution_test.go, process/block/preprocess/transactions.go, process/block/preprocess/transactions_test.go, testscommon/genericMocks/chainStorerMock.go, testscommon/shardedDataCacheNotifierMock.go
- fix invalid scheduled tx on epoch start
- fixed transaction restore in cache
- added unit tests
=> fix invalid scheduled tx on epoch start

epochStart/bootstrap/baseStorageHandler.go, epochStart/bootstrap/process.go, epochStart/bootstrap/process_test.go, node/nodeRunner.go, process/block/pendingMb/export_test.go, process/block/pendingMb/pendingMiniBlocks.go, process/block/pendingMb/pendingMiniBlocks_test.go
- fix pending miniblocks handling & loading on bootstrap
=> Fix pending miniblocks handling & loading on bootstrap

heartbeat/monitor/monitor_test.go, p2p/libp2p/export_test.go, p2p/libp2p/netMessenger.go, p2p/libp2p/netMessenger_test.go
- added more checks for ConnectionTopic on netMessenger
- fixed monitor_test causing random fails
=> Fix topic error

go.mod, go.sum
reference new logger, `v1.0.7`
=> use logger v1.0.7

go.mod, go.sum
- Latest version of the indexer `v1.1.38` ( this indexer contains some fixes for the schedule execution transactions)
=> Indexer v1.1.38

.github/workflows/golangci-lint.yml, Makefile
=> Golang ci linter fixes

go.mod, go.sum, vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/logs.go, vm/systemSmartContracts/logs_test.go
- Fixed the delegation system smart contract logs
=> Fix system delegation smart contract logs

cmd/node/config/config.toml, cmd/node/config/economics.toml, cmd/node/config/enableEpochs.toml
=> Master with compressed flags

go.mod, go.sum
- Latest version of the indexer v1.1.40
=> Master with indexer v1.1.40

go.mod, go.sum
=> backwd-comp-vm

factory/consensusComponents.go, integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go, process/mock/blockTrackerMock.go, process/mock/bootstrapStorerMock.go, process/sync/storageBootstrap/baseStorageBootstrapper.go, process/sync/storageBootstrap/baseStorageBootstrapper_test.go, process/sync/storageBootstrap/metaStorageBootstrapper.go, process/sync/storageBootstrap/shardStorageBootstrapper.go, process/sync/storageBootstrap/shardStorageBootstrapper_test.go
- added epoch notifier in storage bootstrapper and called after the load blocks call has completed
- added unit tests in sync/storageBootstrapper area
=> Epoch notifier in storage bootstrap

epochStart/bootstrap/shardStorageHandler.go, epochStart/bootstrap/shardStorageHandler_test.go, epochStart/metachain/epochStartData_test.go, go.sum, process/block/baseProcess_test.go, process/block/displayBlock_test.go, process/block/export_test.go, process/block/metablock.go, process/block/preprocess/basePreProcess.go, process/block/preprocess/rewardTxPreProcessor.go, process/block/preprocess/smartContractResults.go, process/block/preprocess/transactions.go, process/block/preprocess/transactions_test.go, process/block/processedMb/processedMiniBlocks.go, process/block/processedMb/processedMiniBlocks_test.go, process/block/shardblock.go, process/block/shardblock_test.go, process/coordinator/process.go
* Added unit tests for feat/partial-mb-execution
=> Unit tests for feat partial mb execution

go.mod, go.sum, testscommon/headerHandlerStub.go
* Changed elrond-go-core reference
=> Fix elrond-go-core reference for feat/partial-mb-execution

dblookupext/esdtSupply/esdtSuppliesProcessor_test.go, dblookupext/esdtSupply/logsProcessor.go, testscommon/genericMocks/storerMock.go
- fixed the code that computes the total amount to be added to minted/burnt/supply field of an ESDT token. 
- added unit tests for reverting logs with mint/burn
- refactoring
=> fix esdt total supply endpoint

genesis/process/disabled/feeHandler.go, process/block/postprocess/feeHandler.go, process/block/postprocess/feeHandler_test.go, process/interface.go, process/mock/feeAccumulatorStub.go, process/transaction/export_test.go, process/transaction/shardProcess.go, process/transaction/shardProcess_test.go, testscommon/unsignedTxHandlerStub.go
add a mapping between originaltx and usertx for relayed tx to help with reverting fees
=> usertx accumulated fees revert

.github/workflows/golangci-lint.yml, vm/systemSmartContracts/liquidStaking.go
activate golangci linter for PRs towards feature branches (`feat/*`)
=> add golangci linter for feat branches PRs

process/common.go, process/rewardTransaction/process.go, process/smartContract/process.go, process/transaction/metaProcess.go, process/transaction/shardProcess.go
added txHash in executing transaction print
added internal vm errors as log
=> added internal vm errors as log

go.mod, go.sum, process/smartContract/testScProcessor.go
=> indexer v1.1.41

heartbeat/processor/peerAuthenticationRequestsProcessor.go, heartbeat/processor/peerAuthenticationRequestsProcessor_test.go
Added missing check on MinPeersThreshold which does not allow values bigger than 100%
=> Missing arg check

go.mod, go.sum
=> vm-1.4.34.rc8

cmd/termui/presenter/common.go
removed some function that were not used anymore
=> remove unused code inside termui app

state/storagePruningManager/storagePruningManager.go, trie/patriciaMerkleTrie.go
When pruning or recreating trie, do not log err if DB is closing
=> Refactor pruning error print

common/constants.go, dataRetriever/errors.go, dataRetriever/resolvers/validatorInfoResolver.go, dataRetriever/resolvers/validatorInfoResolver_test.go, process/errors.go, process/interceptors/factory/interceptedValidatorInfoDataFactory.go, process/interceptors/factory/interceptedValidatorInfoDataFactory_test.go, process/interceptors/processor/interface.go, process/interceptors/processor/validatorInfoInterceptorProcessor.go, process/interceptors/processor/validatorInfoInterceptorProcessor_test.go, process/interface.go, process/peer/constants.go, process/peer/interceptedValidatorInfo.go, process/peer/interceptedValidatorInfo_test.go, process/peer/validatorsProvider_test.go, testscommon/marshalizerStub.go
- Added interceptedValidatorInfo, interceptedValidatorInfoDataFactory, validatorInfoInterceptorProcessor, validatorInfoResolver
=> Interceptor + Resolver

vm/interface.go, vm/mock/systemEIStub.go, vm/process/systemVM.go, vm/systemSmartContracts/eei.go
create vmOutput if error on system vm
=> create vmOutput if error on system vm

examples/address_test.go
- in `address_test` from examples, added the system account address
=> added system account address in examples

.github/workflows/create_release.yml, cmd/termui/presenter/common.go, cmd/termui/view/termuic/termuiRenders/widgetsRender.go, consensus/spos/bls/subroundBlock_test.go, vm/interface.go, vm/mock/systemEIStub.go, vm/process/systemVM.go, vm/systemSmartContracts/eei.go
- update master -> rc/2022-may
- linter fixes on commit https://github.com/ElrondNetwork/elrond-go/pull/4077/commits/f12e872ee99039b2aaf086d348accb60b354268c
=> Update master rc 2022 may

integrationTests/testProcessorNode.go
- Fix broken integration test because of missed activation epoch
=> FIX: Broken test

go.mod, go.sum
=> indexer v1.2.30

cmd/node/config/enableEpochs.toml
=> Compressed configs

cmd/node/main.go
Reverts security advisory "test fix"
=> Revert "Fix"

cmd/node/flags.go
- added a new flag to set a custom value when the health records start triggering pprof files
- removed the custom changes whenever an import-db process starts
Testing scenario: start a testnet, take a node, stop it, and start it with these 2 custom flags: `-use-health-service -memory-usage-to-create-profiles 1073741824` which translates to: create health records, but alter the value to 1GB.
grep the log to the following string: `setting a new value for the memoryUsageToCreateProfiles option` and you should be able to check that the new value was set correctly (the default one from the config is ~2.25GB)
Also, check that health records are to be created in the `health-records` directory and contains files with the filenames in the following format: `mem__20220621124307__1_xx_GB.pprof`
=> Health records changes

cmd/node/config/enableEpochs.toml
=> v1.3.28 dev configs

go.mod, go.sum, process/guardian/disabled/disabledGuardedAccount.go, process/guardian/guardedAccount.go, process/guardian/guardedAccount_test.go, process/interface.go, testscommon/guardianMocks/guardianAccountHandlerStub.go
this PR cleans the account guardians, leaving only the active one.
=> clean not active guardians

go.mod, go.sum
=> Indexer v1.2.34 rc june

consensus/interface.go, consensus/mock/messengerStub.go, p2p/libp2p/netMessenger.go, p2p/libp2p/netMessenger_test.go, p2p/mock/messageProcessorMock.go, p2p/p2p.go, testscommon/p2pmocks/messengerStub.go
- added support for the multisigner in network messenger
=> Multisigner: added support in network messenger

cmd/node/flags.go, config/contextFlagsConfig.go, epochStart/bootstrap/process.go, epochStart/bootstrap/process_test.go, factory/bootstrapComponents.go, factory/bootstrapComponents_test.go, integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go, node/nodeRunner.go
- added `force-start-from-network` flag
=> Added force-start-from-network flag

cmd/node/config/enableEpochs.toml
=> Compressed flags

go.mod, go.sum, process/smartContract/hooks/blockChainHook.go, process/smartContract/hooks/blockChainHook_test.go, process/smartContract/hooks/export_test.go
=> Clean aot cache if activation

go.mod, go.sum
=> Indexer with fixes

dblookupext/errors.go, dblookupext/eventsHashesByTxHashIndex.go, dblookupext/historyRepository.go, dblookupext/historyRepository_test.go, errors/closingError.go, errors/closingError_test.go, errors/errors.go, heartbeat/monitor/monitor.go, heartbeat/monitor/monitor_test.go, state/accountsDB.go, state/storagePruningManager/storagePruningManager.go, storage/errors.go, storage/leveldb/leveldb.go, storage/leveldb/leveldbSerial.go, storage/leveldb/leveldbSerial_test.go, storage/leveldb/leveldb_test.go, storage/leveldb/serialActions.go, storage/pruning/pruningStorer.go, storage/pruning/triePruningStorer.go, storage/pruning/triePruningStorer_test.go, trie/patriciaMerkleTrie.go, trie/snapshotTrieStorageManager.go, trie/trieStorageManager.go
- fixed prints when fetching old/unnecessary hb v2 messages + cache cleanup
- better handling when logging errors in historyRepository, removed some duplicated code
=> [FIX]Print fixes for rc/2022-july

consensus/spos/bls/subroundEndRound.go
- fix linter issue: remove unused function  
- N/A
=> Fix linter issue: remove unused function

cmd/node/config/config.toml, config/config.go, factory/coreComponents_test.go, factory/networkComponents_test.go, factory/processComponents.go, factory/stateComponents_test.go, process/block/poolsCleaner/basePoolsCleaner.go, process/block/poolsCleaner/miniBlocksPoolsCleaner.go, process/block/poolsCleaner/miniBlocksPoolsCleaner_test.go, process/block/poolsCleaner/txsPoolsCleaner.go, process/block/poolsCleaner/txsPoolsCleaner_test.go, process/constants.go, testscommon/generalConfig.go
=> Merge dev into feat enable epochs

common/statistics/resourceMonitor.go
- check the load of the node 
- added more logging for CPU and MEMORY
- run normal tests and look in the logs
=> added more cpu and memory logging

cmd/node/config/enableEpochs.toml, common/enablers/enableEpochsHandler.go, common/enablers/epochFlags.go, common/interface.go, config/epochConfig.go, config/tomlConfig_test.go, integrationTests/vm/delegation/delegationScenarios_test.go, node/nodeRunner.go, process/factory/metachain/vmContainerFactory.go, sharding/mock/enableEpochsHandlerMock.go, testscommon/enableEpochsHandlerStub.go, vm/errors.go, vm/systemSmartContracts/delegationManager_test.go, vm/systemSmartContracts/delegation_test.go, vm/systemSmartContracts/eei.go, vm/systemSmartContracts/eei_test.go, vm/systemSmartContracts/esdt_test.go, vm/systemSmartContracts/stakingWithWaiting_test.go, vm/systemSmartContracts/staking_test.go, vm/systemSmartContracts/validator_test.go
- Merge `development` branch into `feat/altered-accounts`
=> Merge dev into altered

p2p/libp2p/peersOnChannel_test.go
- Fix one unit test
- test seldom fails
- TC long & short tests
=> Fix peer on channel test

.github/workflows/build_and_test.yml, .github/workflows/code-coverage.yml, .github/workflows/create_release.yml, .github/workflows/deploy-docker.yml, .github/workflows/deployment.yml, .github/workflows/golangci-lint.yml, cmd/node/config/config.toml, cmd/node/config/enableEpochs.toml, factory/bootstrapComponents.go, process/guardedtx/guardedTxVerifier.go, process/guardedtx/guardedTxVerifier_test.go, process/guardian/guardedAccount.go, process/guardian/guardedAccount_test.go, process/interface.go, process/mock/interceptedTxHandlerStub.go, process/transaction/interceptedTransaction.go, testscommon/interceptedTxMocks/InterceptedUnsignedTxHandlerStub.go, testscommon/interceptedTxMocks/interceptedTxStub.go
This PR contains some fixes for the freeze account feature, found during testing.
Guardian signature needs to be verified over the json marshalled transaction not on the gogo proto marshalled tx.
send guarded txs, signed by the previously set guardian on a frozen account, and check that the transaction is executed
=> Freeze account fixes

process/peer/constants.go
- Fixed linter issue
- 
- 
- 
- 
- 
- 
- 
-
=> Fix linter issue in feat/refactor-peers-mbs

process/guardedtx/guardedTxVerifier_test.go, process/guardian/guardedAccount.go, process/interceptors/singleDataInterceptor.go
merge mutex fix (single interceptor) to feat freeze account
=> Merge rc july mutex fix freezeacc

process/transaction/interceptedTransaction.go
=> process: remove unused field

api/errors/errors.go, api/groups/addressGroup.go, api/groups/addressGroup_test.go, api/mock/facadeStub.go, api/shared/interface.go, cmd/node/config/api.toml, facade/initial/initialNodeFacade.go, facade/interface.go, facade/mock/nodeStub.go, facade/nodeFacade.go, facade/nodeFacade_test.go, integrationTests/interface.go, integrationTests/testProcessorNodeWithTestWebServer.go, node/node.go, node/node_test.go
=> Dev to rc v1.4.0 2022.09.07

cmd/node/flags.go, config/contextFlagsConfig.go, factory/consensusComponents.go, factory/stateComponents.go, node/nodeRunner.go, state/accountsDB.go, state/accountsDB_test.go, state/export_test.go, state/peerAccountsDB.go
=> Update hb fixes 2022.09.07

cmd/node/config/gasSchedules/gasScheduleV6.toml
- Update latest gas schedule config for freeze account and guardian
- standard system testing
=> Updated lastest gasSchedule with freeze account and guardian fields

process/block/preprocess/export.go, process/block/preprocess/smartContractResults_test.go, process/block/preprocess/transactions.go, process/block/preprocess/transactionsV2.go, process/block/preprocess/transactions_test.go
=> Exported new functions for txPreprocess - prepared for sovereign chain

dataRetriever/requestHandlers/requestHandler.go, dataRetriever/resolvers/peerAuthenticationResolver.go, dataRetriever/resolvers/peerAuthenticationResolver_test.go
=> Merge rc july into rc 1.4.0 11.09.2022

examples/construction_test.go, go.mod, go.sum, integrationTests/multiShard/relayedTx/common.go, integrationTests/multiShard/transaction/txRouting/txRouting_test.go, integrationTests/multiShard/txScenarios/common.go, integrationTests/singleShard/transaction/interceptedBulkTx/interceptedBulkTx_test.go, integrationTests/singleShard/transaction/interceptedResolvedTx/interceptedResolvedTx_test.go, integrationTests/testInitializer.go, integrationTests/testNetwork.go, node/nodeTesting.go, process/transaction/interceptedTransaction.go
- Refactor get signing data for transaction and move sign with hash check in elrond-go-core
- Refactor in elrond-go after elrond-go-core changes
- standard all-in system test
=> Refactor GetDataForSigning for transaction

cmd/node/config/enableEpochs.toml
=> Merge master rc v1.4.0

cmd/node/config/enableEpochs.toml, consensus/spos/bls/blsWorker.go, consensus/spos/bls/blsWorker_test.go, consensus/spos/bls/export_test.go, consensus/spos/consensusMessageValidator.go, consensus/spos/consensusMessageValidator_test.go, consensus/spos/constants.go, consensus/spos/interface.go, consensus/spos/worker.go, consensus/spos/worker_test.go
- merge
- merge
- already tested
=> Merge rc v1.4.0 feat p2p separate repo

cmd/node/config/config.toml, common/statistics/resourceMonitor.go, integrationTests/state/stateTrieSync/stateTrieSync_test.go, integrationTests/testProcessorNode.go, node/nodeRunner.go, process/block/preprocess/basePreProcess.go, process/block/preprocess/basePreProcess_test.go, process/block/preprocess/gasComputation.go, process/interceptors/factory/interceptedTrieNodeDataFactory.go, process/interceptors/factory/interceptedTrieNodeDataFactory_test.go, state/syncer/baseAccountsSyncer.go, trie/branchNode_test.go, trie/depthFirstSync.go, trie/depthFirstSync_test.go, trie/doubleListSync.go, trie/extensionNode_test.go, trie/interceptedNode.go, trie/interceptedNode_test.go, trie/leafNode_test.go, trie/sync.go, trie/syncCreator.go, trie/syncCreator_test.go, trie/sync_test.go, trie/trieNodesHandler.go, trie/trieNodesHandler_test.go
=> Merge master rc v1.4.0 2022.10.03

cmd/node/config/config.toml, cmd/node/config/enableEpochs.toml, common/statistics/resourceMonitor.go, integrationTests/state/stateTrieSync/stateTrieSync_test.go, integrationTests/testProcessorNode.go, node/nodeRunner.go, process/block/preprocess/basePreProcess.go, process/block/preprocess/basePreProcess_test.go, process/block/preprocess/gasComputation.go, process/interceptors/factory/interceptedTrieNodeDataFactory.go, process/interceptors/factory/interceptedTrieNodeDataFactory_test.go, state/syncer/baseAccountsSyncer.go, trie/branchNode_test.go, trie/depthFirstSync.go, trie/depthFirstSync_test.go, trie/doubleListSync.go, trie/extensionNode_test.go, trie/interceptedNode.go, trie/interceptedNode_test.go, trie/leafNode_test.go, trie/sync.go, trie/syncCreator.go, trie/syncCreator_test.go, trie/sync_test.go, trie/trieNodesHandler.go, trie/trieNodesHandler_test.go
Merge master into `feat/rosetta`.
=> Merge master into feast/rosetta (2022-10-04)

go.mod, go.sum
- Reference `vm-common v1.3.15-rosetta1`
=> Reference vm-common v1.3.15-rosetta1.

consensus/spos/bls/subroundSignature.go, factory/consensus/consensusComponents.go, factory/crypto/cryptoComponents.go, factory/crypto/cryptoComponentsHandler.go, factory/crypto/errors.go, factory/crypto/signatureHolder.go, factory/crypto/signatureHolder_test.go, factory/interface.go, factory/mock/cryptoComponentsMock.go, integrationTests/consensus/consensusSigning_test.go, integrationTests/consensus/consensus_test.go, integrationTests/mock/cryptoComponentsStub.go, integrationTests/testConsensusNode.go, node/mock/factory/cryptoComponentsStub.go, testscommon/components/default.go
=> Merge optimize consensus sig into pseudo slashing

cmd/node/config/enableEpochs.toml, common/enablers/enableEpochsHandler.go, common/enablers/enableEpochsHandler_test.go, common/enablers/epochFlags.go, common/interface.go, config/epochConfig.go, config/tomlConfig_test.go, factory/api/apiResolverFactory.go, genesis/process/shardGenesisBlockCreator.go, go.mod, go.sum, node/nodeRunner.go, sharding/mock/enableEpochsHandlerMock.go, state/accountsDBApi.go, state/accountsDB_test.go, storage/clean/oldDatabaseCleaner.go, storage/disabled/storer.go, storage/disabled/storer_test.go, testscommon/enableEpochsHandlerStub.go
- merge
- merge
- old NFT token test
=> Update master rc/v1.4.0 - 2022.10.06

common/constants.go, factory/heartbeatV2Components.go, heartbeat/interface.go, heartbeat/monitor/crossShardPeerTopicNotifier.go, heartbeat/monitor/crossShardPeerTopicNotifier_test.go, integrationTests/testHeartbeatNode.go, p2p/errors.go, p2p/libp2p/export_test.go, p2p/libp2p/netMessenger.go, p2p/libp2p/netMessenger_test.go, p2p/mock/peerTopicNotifierStub.go, p2p/p2p.go, testscommon/p2pmocks/messengerStub.go
- added cross shard peer topic notifier
=> Added cross shard peer topic notifier

node/external/logs/logsRepository.go, node/external/logs/logsRepository_test.go
- Merge feat/rosetta into v1.4.0
=> Merge feat/rosetta into v1.4.0 (2022-10-10)

state/accountsDB.go
=> Merge refactor get all leaves into unit tests

integrationTests/multiShard/smartContract/polynetworkbridge/bridge_test.go, integrationTests/testInitializer.go, integrationTests/vm/esdt/process/esdtProcess_test.go, process/factory/shard/vmContainerFactory.go, process/smartContract/process.go, process/smartContract/vmInput.go
Some tests need flags which do not exists in vm 1.5 and in sc processor v2. Resolved these tests and found some backward compatibility issues on sc processor v1 - reverted code to match the one from rc/1.4.0
Reverted code to smartcontract processor from rc/1.4.0 branch
- 
- 
-
=> Make tests with vm 1.4

process/smartContract/processProxy/processProxy.go, process/smartContract/processProxy/testProcessProxy.go
=> separated test proxy process from production one

process/smartContract/processProxy/processProxy.go, process/smartContract/processProxy/processProxy_test.go
- minor fixes on sc processor proxy
- added unit tests for the sc processor proxy, minor fixes and 1 TODO
- N/A
=> Added unit tests for processProxy

process/smartContract/processorV2/failureContext.go, process/smartContract/processorV2/processV2.go, process/smartContract/processorV2/process_test.go
Existing tx processing failure mechanism is encompassed in ProcessIfError(). This code was scattered everywhere and there was also the risk of double calling it.
Refactor of the failure processing calling code, by moving it as high as possible in the calling hierarchy.
Existing unit tests cover the error scenarios and their pass guarantees a correct refactor.
=> error processing refactor

consensus/mock/consensusDataContainerMock.go, consensus/spos/bls/subroundEndRound.go, consensus/spos/bls/subroundEndRound_test.go, consensus/spos/consensusCore.go, consensus/spos/interface.go
=> Merge pseudo slashing consensus into blacklist invalid singers

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
- there were unclear instructions for branches management
- added guidelines on how branches should be used
- only text/approach review
=> Change contributing and pr template

process/txsimulator/txSimulator.go, process/txsimulator/txSimulator_test.go
- removes a data concurrency issue on the transaction simulator
- fixed concurrency issues on the transaction simulator
- internal system test
=> Fixed transaction simulator data concurrency issue

cmd/node/config/enableEpochs.toml
- compressed configs
- compressed configs
=> Compressed configs for v1.3.44-dev-config

vm/systemSmartContracts/delegation.go, vm/systemSmartContracts/delegation_test.go, vm/systemSmartContracts/logs.go, vm/systemSmartContracts/logs_test.go
=> Merge rc into feat nodes synced on hb 2022.10.27 2

factory/processing/processComponents.go, go.mod, go.sum, outport/outport.go, outport/process/alteredaccounts/alteredAccountsProvider.go, outport/process/alteredaccounts/alteredAccountsProvider_test.go, outport/process/alteredaccounts/shared/shared.go, outport/process/alteredaccounts/tokensProcessor.go, outport/process/outportDataProvider.go, testscommon/state/accountWrapperMock.go
- Added extra fields in the altered accounts structure that are needed on the elastic indexer side
- Updated `elrond-go-core` module
=> New fields altered account

genesis/parsing/accountsParser.go
- Removed unused function which caused linter errors
- 
- 
=> FIX: Delete unused func
