multiversx/mx-chain-go

- .github/PULL_REQUEST_TEMPLATE.md
- merge `master` into `rc/v1.4.`0
- merge
- no need
> Merge master rc v1 4 0 nov7

- go.mod
- go.sum
> Proper p2p release

- consensus/mock/alarmSchedulerStub.go
- consensus/mock/watchdogMock.go
- consensus/signing/errors.go
- consensus/spos/bls/blsSubroundsFactory.go
- fixed linter issues
- fixed linter issues
- N/A
> Linter fixes on consensus pkg

- cmd/node/flags.go
> Merge rc in feat altered 11

- cmd/node/config/prefs.toml
- cmd/node/flags.go
- cmd/node/main.go
- common/operationmodes/operationmodes.go
- common/operationmodes/operationmodes_test.go
- common/reflectcommon/structFieldsUpdate.go
- config/overridableConfig/configOverriding.go
- config/overridableConfig/configOverriding_test.go
- config/prefsConfig.go
- outport/process/alteredaccounts/alteredAccountsProvider.go
> Merge rc in feat altered 11 11

- config/config.go
- dataRetriever/errors.go
- dataRetriever/factory/containers/requestersContainer.go
- dataRetriever/factory/requestersContainer/args.go
- dataRetriever/factory/requestersContainer/baseRequestersContainerFactory.go
- dataRetriever/factory/requestersContainer/export_test.go
- dataRetriever/factory/requestersContainer/metaRequestersContainerFactory.go
- dataRetriever/factory/requestersContainer/metaRequestersContainerFactory_test.go
- dataRetriever/factory/requestersContainer/shardRequestersContainerFactory.go
- dataRetriever/factory/requestersContainer/shardRequestersContainerFactory_test.go
- dataRetriever/interface.go
- dataRetriever/requestHandlers/requesters/baseRequester.go
- dataRetriever/requestHandlers/requesters/baseRequester_test.go
- dataRetriever/requestHandlers/requesters/headerRequester_test.go
- dataRetriever/requestHandlers/requesters/requesters_test.go
- dataRetriever/resolvers/topicResolverSender/topicResolverSender.go
- dataRetriever/topicSender/baseTopicSender.go
- dataRetriever/topicSender/topicRequestSender.go
- dataRetriever/topicSender/topicRequestSender_test.go
- new containers are needed for requesters
- add containers, factories and topic sender
- to be tested when feat branch is ready
**Note for review:** One who reviews should compare `requesterscontainer` package with `resolverscontainer` one, as the code was more or less moved. Didn't remove the logic from `resolverscontainer` yet in order to avoid enormous PRs, will be done in further ones. Same note for `requestersContainer.go`, which is almost the same with `resolversContainer.go`. Left a todo in order to generalize this container and reduce it to a single component used in both requesters and resolvers.
Based on the [Contributing Guidelines](https://github.com/ElrondNetwork/elrond-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the …
> Requesters containers

- consensus/spos/bls/subroundEndRound.go
> fix consensus message pubkey in log trace

- process/block/preprocess/basePreProcess.go
- improve SCR lookup in smartcontract preprocessor
- improve SCR lookup in smartcontract preprocessor by using the SearchFirstData method
- system test
> Improve SCR lookup in smartcontract preprocessor

- factory/crypto/cryptoComponents.go
- scripts/testnet/include/config.sh
- scripts/testnet/include/validators.sh
- scripts/testnet/variables.sh
- update testnet scripts to support multikey
- updated scripts
- multikey testnet
> Update testnet scripts for multikey

- consensus/blacklist/blacklist.go
- consensus/message.proto
- consensus/spos/bls/subroundEndRound.go
- Fixes after review on feat branch https://github.com/ElrondNetwork/elrond-go/pull/4467
- fix indentation
- use timer in blacklist component
- N/A
> fixes after review: fix indentation + use timer in blacklist

- cmd/node/config/config.toml
- cmd/node/flags.go
- config/config.go
- factory/status/statusComponents.go
- outport/factory/outportFactory.go
- outport/firehose/errors.go
- outport/firehose/firehoseIndexer.go
- Added config flag for enabling firehose
- Added config flag + initial implementation. This initial implementation is compatible with [first firehose version](https://github.com/ElrondNetwork/firehose-multiversx) 
- Tested with local testnet + firehose blocks ingestion process
> En 13511 add firehose enabled flag

- factory/processing/blockProcessorCreator.go
- factory/processing/blockProcessorCreator_test.go
- factory/processing/export_test.go
- factory/processing/processComponents.go
- factory/processing/processComponents_test.go
- genesis/errors.go
- genesis/process/disabled/scheduledTxsExecutionHandler.go
- genesis/process/shardGenesisBlockCreator.go
- process/block/sovereignblock.go
* Refactor and add more fixes for feat/chain-go-sdk
* Created instance for sovereign chain block processor
* Refactored usage of scheduled txs execution disabled component in sovereign chain
* Fixed some methods from scheduled txs execution handler disabled component used in sovereign chain 
- 
- 
- 
> Refactor and more fixes for feat/chain-go-sdk

- process/errors.go
- process/interface.go
- process/rating/ratingsData.go
- process/rating/ratingsData_test.go
- sharding/chainParametersHolder.go
- sharding/chainParametersHolder_test.go
- sharding/errors.go
- sharding/interface.go
- sharding/nodesSetup.go
- sharding/nodesSetup_test.go
- testscommon/shardingmock/chainParametersHolderMock.go
- testscommon/shardingmock/chainParametersHolderStub.go
- part 2 of the consensus group size changes
- fix older TODOs
- refactoring & improvements
- 
- 
- 
> En 13432 consensus group size changes part 2

- cmd/node/config/config.toml
- disabled flag
- disabled flag
> Disabled trie pruning on `master`

- go.mod
- go.sum
- outport/firehose/errors.go
- outport/firehose/firehoseIndexer.go
- outport/firehose/firehoseIndexer_test.go
- Integrate block body and altered accounts into firehose block
- Integrate block body and altered accounts into firehose block
- Local testnet + firehose ingestion process + scripts and tools
> Firehose block body integration

- process/guardian/guardedAccount.go
- process/guardian/guardedAccount_test.go
- missing mut locks
- add rlock
- will be tested with feat branch
> Add missing mut locks

- examples/tokenKeys_test.go
- helper tests (commonly used in debugging) like these were not committed
- add examples on how to handle storage keys of tokens
- n/a
> added tokens keys test examples

- integrationTests/vm/testInitializer.go
- integrationTests/vm/txsFee/freezeAccounts_test.go
- integrationTests/vm/txsFee/guardAccount_test.go
- process/errors.go
- process/transaction/baseProcess.go
- process/transaction/baseProcess_test.go
- added semi-integration tests
- added semi-integration tests for different scenarios
- 
- 
- 
> Added semi-integration tests for freeze accounts feature

- examples/tokenKeys_test.go
> Update feat rebranding 2023.01.16

- go.mod
- go.sum
This PR updates the dependency on the VM v1.4 with a fixed version.
> Fix VM memory leak

- vm/systemSmartContracts/governance.go
- vm/systemSmartContracts/governance_test.go
Added new view functions for governance
> View funcs governance

- epochStart/bootstrap/process.go
- epochStart/bootstrap/process_test.go
- epochStart/bootstrap/shardStorageHandler.go
- epochStart/bootstrap/shardStorageHandler_test.go
- epochStart/bootstrap/startInEpochScheduled.go
- epochStart/bootstrap/startInEpochScheduled_test.go
- epochStart/bootstrap/types/scheduledDataSyncerTypes.go
- go.mod
- go.sum
- integrationTests/multiShard/endOfEpoch/startInEpoch/startInEpoch_test.go
- outport/notifier/eventNotifier.go
- outport/notifier/eventNotifier_test.go
- testscommon/scheduledDataSyncer/dataSyncerStub.go
- vm/systemSmartContracts/delegation.go
- vm/systemSmartContracts/logs.go
- vm/systemSmartContracts/logs_test.go
> Merge rc v1.4.0 into feat chain go sdk 30.01.2023

- .github/ISSUE_TEMPLATE/question.yml
- common/constants.go
- examples/tokenKeys_test.go
- integrationTests/factory/bootstrapComponents/bootstrapComponents_test.go
- integrationTests/factory/componentsHelper.go
- integrationTests/factory/consensusComponents/consensusComponents_test.go
- integrationTests/factory/constants.go
- integrationTests/factory/coreComponents/coreComponents_test.go
- integrationTests/factory/cryptoComponents/cryptoComponents_test.go
- integrationTests/factory/dataComponents/dataComponents_test.go
- integrationTests/factory/heartbeatComponents/heartbeatComponents_test.go
- integrationTests/factory/networkComponents/networkComponents_test.go
- integrationTests/factory/processComponents/processComponents_test.go
- integrationTests/factory/stateComponents/stateComponents_test.go
- integrationTests/factory/statusComponents/statusComponents_test.go
- integrationTests/factory/statusCoreComponents/statusCoreComponents_test.go
- integrationTests/vm/esdt/process/esdtProcess_test.go
- integrationTests/vm/txsFee/scCalls_test.go
- process/smartContract/process_test.go
- vm/process/systemVM.go
- vm/process/systemVM_test.go
- further rebranding work
- minor integration tests refactoring
- further rebranding work
- minor integration tests refactoring
> Further rebranding work

- .github/ISSUE_TEMPLATE/question.yml
- common/constants.go
- examples/tokenKeys_test.go
- integrationTests/factory/bootstrapComponents/bootstrapComponents_test.go
- integrationTests/factory/componentsHelper.go
- integrationTests/factory/consensusComponents/consensusComponents_test.go
- integrationTests/factory/constants.go
- integrationTests/factory/coreComponents/coreComponents_test.go
- integrationTests/factory/cryptoComponents/cryptoComponents_test.go
- integrationTests/factory/dataComponents/dataComponents_test.go
- integrationTests/factory/heartbeatComponents/heartbeatComponents_test.go
- integrationTests/factory/networkComponents/networkComponents_test.go
- integrationTests/factory/processComponents/processComponents_test.go
- integrationTests/factory/stateComponents/stateComponents_test.go
- integrationTests/factory/statusComponents/statusComponents_test.go
- integrationTests/factory/statusCoreComponents/statusCoreComponents_test.go
- integrationTests/vm/esdt/process/esdtProcess_test.go
- integrationTests/vm/txsFee/scCalls_test.go
- process/smartContract/process_test.go
- vm/process/systemVM.go
- vm/process/systemVM_test.go
> Merge rc v1.4.0 into feat chain go sdk 30.01.2023 2

- docker/termui/Dockerfile
> Merge master 2023.02.01

- docker/termui/Dockerfile
- go.mod
- go.sum
- node/external/timemachine/fee/feeComputer.go
- node/external/timemachine/fee/feeComputer_test.go
- node/external/timemachine/fee/interface.go
- node/external/transactionAPI/apiTransactionProcessor.go
- node/external/transactionAPI/apiTransactionProcessor_test.go
- node/external/transactionAPI/gasUsedAndFeeProcessor.go
- node/external/transactionAPI/gasUsedAndFeeProcessor_test.go
- node/external/transactionAPI/interface.go
- process/block/metablock.go
- process/peer/process.go
- testscommon/feeComputerStub.go
merge from v1.4
merge from v1.4
- 
> Merge v14 to v15 0102

- update/sync/syncTransactions_test.go
- unit test failing due to timing
- fix timing dependency
-
> fix arbitrary failing test

- integrationTests/multiShard/smartContract/scCallingSC_test.go
- integrationTests/testConsensusNode.go
- fixing failing test
- fixed failing test
- N/A
> Fix seldom failing integration tests

- integrationTests/multiShard/smartContract/scCallingSC_test.go
- integrationTests/testConsensusNode.go
- integrationTests/testInitializer.go
> Merge rc v1.4.0 into feat chain go sdk 03.02.2023

- cmd/node/config/external.toml
- go.mod
- go.sum
- Changed the version of the `mx-chain-es-indexer-go` module
- The new version of the indexer module will create a new Elasticseach index where will be saved information about the fungible tokens and 'collections'.
- PR from the `mx-chain-es-indexer-go` repository: https://github.com/multiversx/mx-chain-es-indexer-go/pull/190
- Create all types of tokens `FungibleESDT`, `NonFungibleESDT`, `SemiFungibleESDT`, and `MetaESDT` and check in information about these tokens are saved in the `esdts` index from the Elasticsearch database. 
- …
> change indexer

- storage/database/shardIDProvider.go
- storage/database/shardedPersister.go
- storage/database/shardedPersister_test.go
- some fixes required for the benchmarks
- use serial db & fix the running context for the benchmarks 
- 
> use serialdb, & some refactoring

- cmd/node/config/config.toml
- cmd/node/config/enableEpochs.toml
> Merge master feat polaris 2023.02.17

- cmd/node/config/config.toml
- cmd/node/config/enableEpochs.toml
> Merge master rc v1.5.0 2023.02.17

- README.md
- Added a new badge for the repository contributors
> Contributors badge

- README.md
> Update master polaris fixes 2023.02.23

- consensus/constants.go
- consensus/spos/bls/blsSubroundsFactory.go
- consensus/spos/bls/blsSubroundsFactory_test.go
- consensus/spos/bls/export_test.go
- consensus/spos/bls/subroundBlockV2_test.go
- consensus/spos/bls/subroundEndRound.go
- consensus/spos/bls/subroundEndRoundV2.go
- consensus/spos/bls/subroundEndRoundV2_test.go
- consensus/spos/bls/subroundSignature.go
- consensus/spos/bls/subroundSignatureV2.go
- consensus/spos/bls/subroundSignatureV2_test.go
- consensus/spos/sposFactory/sposFactory.go
- consensus/spos/sposFactory/sposFactory_test.go
- errors/errors.go
- factory/consensus/consensusComponents.go
- factory/consensus/consensusComponentsHandler_test.go
- factory/consensus/consensusComponents_test.go
- go.mod
- go.sum
- integrationTests/consensus/consensus_test.go
- node/nodeRunner.go
- node/sovereignNodeRunner.go
- process/block/baseProcess.go
- process/block/interface.go
- process/block/sovereignblock.go
- process/common.go
- process/errors.go
- testscommon/components/components.go
- Fixed signing and checking aggregate signature on consensus flow for sovereign chain
- 
- 
- 
- 
- 
- 
> Bugfixing and stabilization for sovereign chain

- README.md
> Update rc v1.5.0 2023.02.23

- integrationTests/vm/txsFee/guardAccount_test.go
- added new semi-integration test
- refactoring in guarded accounts semi-integration tests
- added a complex scenario as a semi-integration test
- N/A
> Added complex scenario semi-integration test for guarded accounts feat

- integrationTests/consensus/consensusSigning_test.go
- integrationTests/consensus/consensus_test.go
- added consensus test for consensus model v2
- 
- 
- 
- 
- 
- 
> Aded consensus integration tests for consensus model v2

- common/interface.go
- integrationTests/state/stateTrieSync/stateTrieSync_test.go
- node/external/transactionAPI/apiTransactionProcessor.go
- node/external/transactionAPI/gasUsedAndFeeProcessor.go
- node/external/transactionAPI/gasUsedAndFeeProcessor_test.go
- outport/process/factory/check_test.go
- outport/process/factory/outportDataProviderFactory.go
- outport/process/transactionsfee/interface.go
- outport/process/transactionsfee/transactionChecker.go
- outport/process/transactionsfee/transactionsFeeProcessor.go
- outport/process/transactionsfee/transactionsFeeProcessor_test.go
- testscommon/trie/trieStub.go
- trie/branchNode.go
- trie/branchNode_test.go
- trie/extensionNode.go
- trie/extensionNode_test.go
- trie/interface.go
- trie/leafNode.go
- trie/patriciaMerkleTrie.go
- trie/patriciaMerkleTrie_test.go
> Merge polaris fixes rc v1.5.0 2023.02.28

- go.mod
- go.sum
> Update polaris fixes rc v1.5.0 2023.03.09

- cmd/node/config/config.toml
- config/config.go
- node/nodeRunner.go
> Merge rc v1.6.0 into feat consensus model v2 14.03.2023

- go.mod
- go.sum
- node/node.go
- node/node_test.go
- vm/systemSmartContracts/esdt.go
> Update master rc v1.5.0 2023.03.20

- state/accountsDB_test.go
> add unit tests

- integrationTests/vm/txsFee/migrateDataTrie_test.go
- testscommon/integrationtests/factory.go
- Add tests for migrateDataTrie built in function
> add migrateDataTrie semi integration tests

- factory/api/apiResolverFactory_test.go
- factory/bootstrap/bootstrapComponentsHandler_test.go
- factory/bootstrap/bootstrapComponents_test.go
- factory/consensus/consensusComponentsHandler_test.go
- factory/consensus/consensusComponents_test.go
- factory/core/coreComponentsHandler_test.go
- factory/core/coreComponents_test.go
- factory/crypto/cryptoComponentsHandler_test.go
- factory/crypto/cryptoComponents_test.go
- factory/crypto/multiSignerContainer_test.go
- factory/data/dataComponentsHandler_test.go
- factory/data/dataComponents_test.go
- factory/network/networkComponentsHandler_test.go
- factory/network/networkComponents_test.go
- factory/processing/blockProcessorCreator_test.go
- factory/processing/processComponentsHandler_test.go
- factory/processing/processComponents_test.go
- factory/state/stateComponentsHandler_test.go
- factory/state/stateComponents_test.go
- factory/status/statusComponentsHandler_test.go
- factory/status/statusComponents_test.go
- factory/statusCore/statusCoreComponentsHandler_test.go
- factory/statusCore/statusCoreComponents_test.go
- genesis/process/genesisBlockCreator_test.go
- code coverage was wrongly computed
- removed t.Skip from tests
- N/A - no production code affected
> Removed t.Skip from unit tests

- cmd/node/config/enableEpochs.toml
- compressed configs
- 
- 
- 
- 
- 
- 
> v1.4.14-dev-config

- cmd/node/config/external.toml
- config/externalConfig.go
- factory/status/statusComponents.go
- outport/notifier/eventNotifier.go
- testscommon/components/components.go
- Add custom marshaller for notifier driver
- Marshaller type from config
- N/A
> add marshaller type for notifier to external config

- api/groups/transactionGroup_test.go
- go.mod
- go.sum
> updated mx-chain-core-go to latest

- process/transaction/metaProcess.go
- process/transaction/metaProcess_test.go
> Merge master in rc/1.5.0

- factory/processing/blockProcessorCreator.go
- outport/process/outportDataProvider.go
- process/block/preprocess/transactions.go
- process/common.go
-  Bug-fixes transaction execution order component.
- Fixed some problems with the transaction execution order component.
- 
- 
- 
> Fixes transaction execution order

- state/trackableDataTrie.go
- Remove duplicated code: get from trie on RetrieveValue() and getOldValue()
> Remove duplicated code in trackable data trie

- api/groups/blockGroup.go
- api/groups/blockGroup_test.go
- api/groups/hardforkGroup_test.go
- api/groups/internalGroup_test.go
- cmd/termui/view/termuic/termuiRenders/widgetsRender.go
- heartbeat/processor/export_test.go
- heartbeat/processor/peerAuthenticationRequestsProcessor.go
- heartbeat/processor/peerAuthenticationRequestsProcessor_test.go
- node/nodeRunner.go
> Merge rc 1.6.0 into sharded persister

- testscommon/trie/snapshotPruningStorerStub.go
- trie/dfsIterator_test.go
- trie/factory/trieCreator_test.go
- trie/keyBuilder/disabledKeyBuilder_test.go
- trie/snapshotTrieStorageManager_test.go
- trie/statistics/trieStatisticsCollector_test.go
- trie/statistics/trieStatistics_test.go
- trie/storageMarker/trieStorageMarker_test.go
- trie/syncTrieStorageManager_test.go
- trie/sync_test.go
- trie/trieNodesHandler_test.go
- trie/trieStorageManagerInEpoch_test.go
- trie/trieStorageManagerWithoutCheckpoints_test.go
- trie/trieStorageManagerWithoutSnapshot_test.go
- trie/trieStorageManager_test.go
- update/container/accountDBSyncers_test.go
- update/container/export_test.go
- update/container/trieSyncers_test.go
- increase code coverage
- added unit tests for trie package + some on update package
- unit tests only
> Coverage for: trie

- state/accountsDB_test.go
> fix race condition in test

- cmd/node/config/enableEpochs.toml
- common/enablers/enableEpochsHandler.go
- common/enablers/enableEpochsHandler_test.go
- common/enablers/epochFlags.go
- common/interface.go
- config/epochConfig.go
- config/tomlConfig_test.go
- integrationTests/multiShard/relayedTx/edgecases/edgecases_test.go
- process/transaction/baseProcess.go
- process/transaction/export_test.go
- process/transaction/shardProcess.go
- process/transaction/shardProcess_test.go
- sharding/mock/enableEpochsHandlerMock.go
- testscommon/enableEpochsHandlerStub.go
Fix for the finding in guardian competition where the guarded leaked wallet could have miss transactions.
> Move guardian checks

- common/enablers/epochFlags.go
- config/epochConfig.go
- integrationTests/multiShard/relayedTx/edgecases/edgecases_test.go
- integrationTests/vm/txsFee/relayedAsyncCall_test.go
- integrationTests/vm/txsFee/relayedBuiltInFunctions_test.go
- integrationTests/vm/txsFee/relayedMoveBalance_test.go
- integrationTests/vm/txsFee/relayedScCalls_test.go
> Merge master rc/v1.5.0 2023.05.29

- go.mod
- go.sum
- Updated the version of `mx-chain-es-indexer-go` module
- The new version of  `mx-chain-es-indexer-go` module adds some extra checks for some fields. 
- Check if the explorer works correctly
> Integrate new indexer with extra checks

- go.mod
- go.sum
-  Merge
- `mx-chain-es-indexer-go` release: https://github.com/multiversx/mx-chain-es-indexer-go/releases/tag/v1.3.18
> Merge master in rc/v1.5.0

- go.mod
- go.sum
update vmcommon version for argscheck
update go.mod
regular system test with set guardian calls
> Update vmcommon argscheck

- cmd/node/config/enableEpochs.toml
- compressed configs
- 
- 
- 
- 
- 
- 
> Compressed configs for v1.4.18

- cmd/node/config/enableEpochs.toml
> Merge master rc v1.5.0 2023.06.21

- epochStart/metachain/systemSCs.go
- epochStart/metachain/systemSCs_test.go
- errors/errors.go
- After the refactor, an if condition was wrongly written
- Change the if condition. 
- Added a unit test which should pass with the old code, should fail with the code after the refactor, and should pass after this fix
- Will be tested in the feat branch
> add test for stakingToValidatorStatistics

- process/block/shardblock.go
- missing member initialization causing panic
- added initialization
- will be tested with feat branch
> Fix managed peers holder initialization

- api/groups/nodeGroup.go
- api/groups/nodeGroup_test.go
- api/mock/facadeStub.go
- api/shared/interface.go
- cmd/node/config/api.toml
- common/interface.go
- facade/initial/initialNodeFacade.go
- facade/interface.go
- facade/mock/apiResolverStub.go
- facade/nodeFacade.go
- integrationTests/interface.go
- integrationTests/testProcessorNodeWithTestWebServer.go
- keysManagement/managedPeersMonitor.go
- keysManagement/managedPeersMonitor_test.go
- node/external/nodeApiResolver.go
- node/external/nodeApiResolver_test.go
- testscommon/managedPeersMonitorStub.go
- missing endpoint for all managed keys
- added /managed-keys endpoint
> All managed keys endpoint

- cmd/node/config/external.toml
- config/externalConfig.go
- factory/status/export_test.go
- factory/status/statusComponents.go
- factory/status/statusComponents_test.go
- outport/factory/hostDriverFactory.go
- outport/factory/hostDriverFactory_test.go
- outport/factory/outportFactory.go
- outport/factory/outportFactory_test.go
- testscommon/components/components.go
> Merge rc/v1.6.0 in feat/state refactor 30jun

- process/transaction/shardProcess_test.go
- fixed race condition in test
- fixed race condition in test
- not required
> Fixed race condition in test

- cmd/node/config/enableEpochs.toml
> Merge master feat go 1205 2023.07.07

- cmd/seednode/main.go
- factory/network/networkComponents.go
- go.mod
- go.sum
- p2p/constants.go
- update dep with latest changes
- 
- 
- 
- 
- 
- 
> Updated mx-chain-communication-go with NetworkType

- go.mod
- go.sum
> update mx chain communication go

- go.mod
- go.sum
- Added a new version of the `mx-chain-es-indexer-go` with extra checks
- PR from the `mx-chain-es-indexer-go`:https://github.com/multiversx/mx-chain-es-indexer-go/pull/237
- System test
> indexer with extra checks

- go.mod
- go.sum
> Merge master go 1.20.5 2023.07.20

- go.mod
- go.sum
> Update mx-chain-communication-go tag

- scripts/testnet/include/config.sh
- missing copy toml file
- added copy instruction
- scripts only
> Copy fullArchiveP2P.toml

- cmd/sovereignnode/go.mod
- cmd/sovereignnode/go.sum
- factory/processing/blockProcessorCreator.go
- factory/processing/txSimulatorProcessComponents.go
- genesis/process/shardGenesisBlockCreator.go
- integrationTests/testProcessorNode.go
- process/smartContract/process.go
- process/smartContract/processorV2/errors.go
- process/smartContract/processorV2/factory.go
- process/smartContract/processorV2/processV2.go
- process/smartContract/processorV2/sovereignSCProcess.go
- process/smartContract/scrCommon/common.go
- process/smartContract/scrCommon/interface.go
- process/smartContract/testScProcessor.go
- Since scr processor v2 was introduced, adjusted sovereign scr processor to use the new component
- Moved sov scr proc to another package and refactored
- Small file/structure refactor
- System test with mock notifier works
> Sovereign scr proccessor v2

- epochStart/bootstrap/storageProcess_test.go
- some tests failed
- fix tests
- no testing needed, just unit test setup problems
> fixed race condition

- epochStart/bootstrap/storageProcess_test.go
> Merge chain go sdk to refactor aug 7

- .github/workflows/build_and_test.yml
- .github/workflows/check-cli-md.yml
- .github/workflows/code-coverage.yml
- .github/workflows/create_release.yml
- .github/workflows/golangci-lint.yml
- docker/keygenerator/Dockerfile
- docker/multiversx/Dockerfile
- docker/seednode/Dockerfile
- docker/termui/Dockerfile
- go.mod
- go.sum
> update libp2p version

- dataRetriever/topicSender/topicResolverSender_test.go
- data race in tests
- fix data race in tests
- test code only
> fix data race in tests

- .github/workflows/build_and_test.yml
- .github/workflows/check-cli-md.yml
- .github/workflows/code-coverage.yml
- .github/workflows/create_release.yml
- .github/workflows/golangci-lint.yml
- cmd/node/config/enableEpochs.toml
- cmd/node/main.go
- dataRetriever/topicSender/topicResolverSender_test.go
- docker/keygenerator/Dockerfile
- docker/node/Dockerfile
- docker/seednode/Dockerfile
- docker/termui/Dockerfile
> Merge rc160 into feat vmquery with coord 2023.08.25

- .github/workflows/build_and_test.yml
- .github/workflows/check-cli-md.yml
- .github/workflows/code-coverage.yml
- .github/workflows/create_release.yml
- .github/workflows/golangci-lint.yml
- cmd/node/config/enableEpochs.toml
- cmd/node/main.go
- dataRetriever/topicSender/topicResolverSender_test.go
- docker/keygenerator/Dockerfile
- docker/node/Dockerfile
- docker/seednode/Dockerfile
- docker/termui/Dockerfile
> Merge in feat logs

- cmd/sovereignnode/go.mod
- cmd/sovereignnode/go.sum
- cmd/sovereignnode/systemTestDemo/go.mod
- cmd/sovereignnode/systemTestDemo/go.sum
- consensus/spos/sposFactory/sposFactory.go
- dataRetriever/requestHandlers/requestHandler.go
- factory/bootstrap/bootstrapComponents.go
- factory/bootstrap/shardingFactory.go
- factory/consensus/consensusComponents.go
- factory/data/dataComponents.go
- factory/processing/blockProcessorCreator.go
- factory/processing/processComponents.go
- genesis/parsing/accountsParser.go
- genesis/parsing/smartContractParser.go
- genesis/process/genesisBlockCreator.go
- go.mod
- go.sum
- heartbeat/monitor/crossShardPeerTopicNotifier.go
- process/block/baseProcess.go
- process/block/interceptedBlocks/common.go
- process/block/interceptedBlocks/interceptedMiniblock.go
- process/block/sovereignChainBlock.go
- process/headerCheck/headerSignatureVerify.go
- process/rating/ratingsData.go
- sharding/multiShardCoordinator.go
- sharding/nodesCoordinator/common.go
- sharding/nodesCoordinator/indexHashedNodesCoordinator.go
- sharding/nodesSetup.go
- update/genesis/export.go
> Sovereign shard coordinator

- errors/errors.go
- factory/interface.go
- factory/processing/interface.go
- factory/processing/processComponents.go
- factory/runType/runTypeComponents.go
- factory/runType/runTypeComponentsHandler.go
- factory/runType/sovereignRunTypeComponents.go
- factory/runType/sovereignRunTypeComponents_test.go
- process/block/preprocess/interfaces.go
- process/interface.go
- storage/factory/shardAdditionalStorageServiceFactory.go
- storage/factory/shardAdditionalStorageServiceFactory_test.go
- storage/factory/sovereignAdditionalStorageServiceFactory.go
- storage/factory/sovereignAdditionalStorageServiceFactory_test.go
- storage/factory/storageServiceFactory.go
- this was the last place where the chainRunType was actively used
- creation of two different versions of StorageServiceCreators for normal and sovereign mode
- #allIn
> added additionalStorageService

- epochStart/errors.go
- epochStart/metachain/baseRewards.go
- epochStart/metachain/baseRewards_test.go
- epochStart/metachain/rewardsV2.go
- factory/processing/blockProcessorCreator.go
- integrationTests/testProcessorNode.go
- outport/process/outportDataProvider.go
> add rewards transaction ordering on rewards creation in metachain

- node/processingOnlyNode/coreComponents.go
- node/processingOnlyNode/storageService.go
- node/processingOnlyNode/testOnlyProcessingNode.go
- node/processingOnlyNode/testOnlyProcessingNode_test.go
> initialize core components

- cmd/sovereignnode/go.mod
- cmd/sovereignnode/go.sum
- cmd/sovereignnode/incomingHeader/errors.go
- cmd/sovereignnode/incomingHeader/extendedHeaderProcessor.go
- cmd/sovereignnode/incomingHeader/incomingHeaderProcessor.go
- cmd/sovereignnode/incomingHeader/incomingHeaderProcessor_test.go
- go.mod
- go.sum
- node/external/blockAPI/baseBlock.go
- node/external/blockAPI/blockArgs.go
- When receiving incoming header and creating extended headers, we will save incoming events as well. These events will be used to verify/validate the proof of created incoming miniblocks
- 
- 
- 
- 
- 
- 
> Save incoming events on extended header

- cmd/sovereignnode/sovereignNodeRunner.go
- errors/errors.go
- factory/processing/processComponents.go
- factory/processing/processComponents_test.go
- integrationTests/realcomponents/processorRunner.go
- node/nodeRunner.go
- process/block/interceptedBlocks/sovereignInterceptedExtendedShardHeader.go
- process/block/interceptedBlocks/sovereignInterceptedExtendedShardHeader_test.go
- process/factory/interceptorscontainer/args.go
- process/factory/interceptorscontainer/interface.go
- process/factory/interceptorscontainer/shardInterceptorsContainerFactoryCreator.go
- process/factory/interceptorscontainer/shardInterceptorsContainerFactoryCreator_test.go
- process/factory/interceptorscontainer/shardInterceptorsContainerFactory_test.go
- process/factory/interceptorscontainer/sovereignShardInterceptorsContainerFactory.go
- process/factory/interceptorscontainer/sovereignShardInterceptorsContainerFactoryCreator.go
- process/factory/interceptorscontainer/sovereignShardInterceptorsContainerFactoryCreator_test.go
- process/factory/interceptorscontainer/sovereignShardInterceptorsContainerFactory_test.go
- process/interceptors/factory/sovereignInterceptedExtendedShardHeaderFactory.go
- process/interceptors/factory/sovereignInterceptedExtendedShardHeaderFactory_test.go
- process/interceptors/processor/sovereignHdrInterceptorProcessor.go
- process/interface.go
- testscommon/components/components.go
- testscommon/sovereign/incomgHeaderSubscriberStub.go
- Sovereign shard interceptors container factory
- Implemented it + injected factories
- 
- 
- 
> Sovereign shard interceptors container factory 

- dataRetriever/requestHandlers/sovereignRequestHandler.go
- dataRetriever/requestHandlers/sovereignRequestHandler_test.go
- Implement sovereign extended header request handler
- 
- 
- 
- 
- 
- 
> Implement sovereign extended header request handler

- dataRetriever/factory/dataPoolFactory.go
- dataRetriever/txpool/shardedTxPool.go
- dataRetriever/txpool/shardedTxPool_test.go
- after latest fixes, the structure was not castable anymore
- updated the registration process
> Fixed tx removal from inner tx pool

- dblookupext/hashToEpochIndex.go
- dblookupext/miniblocksHandler.go
- dblookupext/miniblocksHandler_test.go
- testscommon/genericMocks/storerMock.go
- added blockReverted functionality + tests
- 
- 
- 
- 
- 
- 
> Fixing hyperblock partial mb handling part2

- common/constants.go
- integrationTests/resolvers/transactions/transactionsRequest_test.go
- integrationTests/singleShard/transaction/interceptedBulkTx/interceptedBulkTx_test.go
- integrationTests/testProcessorNode.go
- integrationTests/vm/esdt/process/esdtProcess_test.go
- changed constant, adapted tests
- 
- 
- 
- 
- 
- 
> Changed `MaxTxNonceDeltaAllowed` constant

- cmd/sovereignnode/incomingHeader/errors.go
- cmd/sovereignnode/incomingHeader/incomingHeaderProcessor.go
- cmd/sovereignnode/incomingHeader/incomingHeaderProcessor_test.go
- cmd/sovereignnode/incomingHeader/incomingSCRProcessor.go
- cmd/sovereignnode/systemTestDemo/mockNotifier/notifier.go
- Added gas cost + function call with args according to latest doc regarding bridge operations
- 
- 
- 
- 
- 
- 
> Extend events data with function call + args + gas limit

- scripts/generators/mockGenerator.sh
> stubGenerator -> mockGenerator

- epochStart/metachain/systemSCs_test.go
- factory/api/apiResolverFactory.go
- factory/processing/blockProcessorCreator_test.go
- factory/state/stateComponents.go
- genesis/process/memoryComponents.go
- integrationTests/state/stateTrie/stateTrie_test.go
- integrationTests/testInitializer.go
- state/accountsDB.go
- state/accountsDB_test.go
- state/disabled/disabledSnapshotsManager.go
- state/errors.go
- state/factory/accountsAdapterAPICreator_test.go
- state/peerAccountsDB.go
- state/peerAccountsDB_test.go
- state/storagePruningManager/storagePruningManager_test.go
- testscommon/integrationtests/factory.go
- testscommon/state/snapshotsManagerStub.go
- update/genesis/import.go
> Merge rc 1.7.0 into refactor nodes coordinator

- .github/workflows/create_release.yml
- fixed create_release.yml
- 
- 
- 
- 
- 
- 
> Fixed create release workflow file

- process/errors.go
- process/smartContract/processorV2/process_test.go
- process/smartContract/processorV2/vmInputV2.go
> Check Async Args no panic

- cmd/node/config/fullArchiveP2P.toml
- cmd/node/config/p2p.toml
- cmd/seednode/config/p2p.toml
- config/tomlConfig_test.go
- go.mod
- go.sum
- integrationTests/p2p/networkSharding-hbv2/networkSharding_test.go
- integrationTests/testInitializer.go
- p2p/config/config.go
- p2p/constants.go
- testscommon/components/components.go
- integrated p2p resource limiter configs in order to have better control on the seednodes during their connection acceptance processes.
- 
- 
- 
- standard system-test
- half-half system test
- high seeder load in a separate network
> Add resource limiter config

- cmd/sovereignnode/config/sovereignConfig.toml
- config/sovereignConfig.go
- errors/errors.go
- factory/processing/blockProcessorCreator.go
- integrationTests/testProcessorNode.go
- process/block/sovereign/errors.go
- process/block/sovereign/interface.go
- process/block/sovereign/outgoingOperations.go
- process/block/sovereign/outgoingOperationsFactory.go
- process/block/sovereign/outgoingOperations_test.go
- process/block/sovereignChainBlock.go
- process/block/sovereignChainBlock_test.go
- testscommon/components/configs.go
- testscommon/generalConfig.go
- testscommon/sovereign/outgoingOperationsFormatterStub.go
- Added `OutgoingOperationsFormatter` which collects relevant outgoing events for bridge from the logs and creates an outgoing data that needs to be signed by validators to bridge tokens
- 
- 
- 
- 
- 
- 
> Mx 14670 collect outgoing sovereign logs

- node/chainSimulator/components/nodeFacade.go
- node/chainSimulator/components/statusComponents.go
- node/chainSimulator/components/testOnlyProcessingNode.go
- Enable VM queries
- Set `erd_probable_highest_nonce` metric
> Allow VM queries

- node/chainSimulator/chainSimulator.go
- node/chainSimulator/chainSimulator_test.go
- node/chainSimulator/components/cryptoComponents.go
- node/chainSimulator/components/testOnlyProcessingNode.go
- Option to disable transaction signature verification
> [chain_simulator] Bypass transaction signature

- go.mod
- go.sum
> new vm 1.5.21

- node/chainSimulator/chainSimulator.go
- node/chainSimulator/components/testOnlyProcessingNode.go
- node/chainSimulator/process/interface.go
- node/chainSimulator/process/processor.go
- Set round metric
- Added mutex for the blocks generation part
> Bug-fixes and improvments

- dataRetriever/factory/dataPoolFactory.go
- epochStart/metachain/systemSCs_test.go
- genesis/process/genesisBlockCreator.go
- go.mod
- go.sum
- process/smartContract/hooks/blockChainHook.go
- storage/factory/persisterCreator.go
- storage/factory/storageServiceFactory.go
- storage/interface.go
- storage/storageunit/storageunit.go
- storage/storageunit/storageunit_test.go
- testscommon/dataRetriever/poolFactory.go
- update/factory/dataTrieFactory.go
- update/factory/exportHandlerFactory.go
- User persister factory for static storers creation
> Use sharded persister for static storers

- cmd/node/config/systemSmartContractsConfig.toml
- vm/systemSmartContracts/governance.go
- vm/systemSmartContracts/governance_test.go
- minor governance fixes required found while writing the documentation
- 
- 
- 
- 
- 
- 
> Governance fixes

- node/chainSimulator/chainSimulator.go
- node/chainSimulator/chainSimulator_test.go
- node/chainSimulator/components/testOnlyProcessingNode.go
- node/chainSimulator/components/testOnlyProcessingNode_test.go
- node/chainSimulator/dtos/state.go
- node/chainSimulator/process/interface.go
- node/external/timemachine/fee/memoryFootprint/memory_test.go
- set the entire state on an account 
> Set entire state of an account

- storage/factory/dbConfigHandler.go
- storage/factory/dbConfigHandler_test.go
- storage/factory/export_test.go
- fixed dbConfigHandler to accommodate different DB configs
- fixed dbConfigHandler to accommodate different DB configs
- special test for epoch 1 degradation check
> Fixed dbConfigHandler to accommodate different DB configs

- go.mod
- go.sum
> new vm 1.5.23

- trie/branchNode.go
- trie/branchNode_test.go
- trie/extensionNode.go
- trie/extensionNode_test.go
- trie/node.go
- trie/node_test.go
- trie/trieStorageManager.go
- trie/trieStorageManager_test.go
- Mx 14854 merge rc 1 7 into staking v4 10 jan 2024
> Mx 14854 merge rc 1 7 into staking v4 10 jan 2024

- genesis/process/sovereignGenesisBlockCreator.go
- genesis/process/sovereignGenesisBlockCreator_test.go
- MX-14968 task
- refactor for file `genesis/process/sovereignGenesisBlockCreator.go`
- 
- init system account function add
- 
- 
-
- 
> initSystemAccount new function

- cmd/node/config/enableEpochs.toml
- common/enablers/enableEpochsHandler.go
- common/enablers/enableEpochsHandler_test.go
- common/enablers/epochFlags.go
- common/interface.go
- config/epochConfig.go
- config/tomlConfig_test.go
- go.mod
- go.sum
- sharding/mock/enableEpochsHandlerMock.go
- testscommon/enableEpochsHandlerMock/enableEpochsHandlerStub.go
- new vm common
- 
- 
- 
- 
- 
- 
> New vm common

- cmd/node/config/enableEpochs.toml
- common/enablers/enableEpochsHandler.go
- common/enablers/enableEpochsHandler_test.go
- common/enablers/epochFlags.go
- common/interface.go
- config/epochConfig.go
- config/tomlConfig_test.go
- go.mod
- go.sum
- sharding/mock/enableEpochsHandlerMock.go
- testscommon/enableEpochsHandlerMock/enableEpochsHandlerStub.go
> Update master rc sirius patch 2 2023.01.17

- factory/api/apiResolverFactory.go
- factory/api/apiResolverFactory_test.go
- factory/api/export_test.go
- MX-14961 task
- refactor for file `factory/api/apiResolverFactory.go`
- 
- refactor function createScQueryElement
- 
- 
- running main node
- 
> apiResolverFactory refactor

- cmd/sovereignnode/sovereignNodeRunner.go
- factory/api/apiResolverFactory.go
- factory/api/apiResolverFactory_test.go
- factory/errors.go
- integrationTests/testProcessorNodeWithTestWebServer.go
- node/nodeRunner.go
- node/trieIterators/factory/delegatedListHandlerFactory.go
- node/trieIterators/factory/delegatedListHandlerFactory_test.go
- node/trieIterators/factory/directStakedListHandlerFactory.go
- node/trieIterators/factory/directStakedListHandlerFactory_test.go
- node/trieIterators/factory/interface.go
- node/trieIterators/factory/sovereignDelegatedListHandlerFactory.go
- node/trieIterators/factory/sovereignDelegatedListHandlerFactory_test.go
- node/trieIterators/factory/sovereignDirectStakedListHandlerFactory.go
- node/trieIterators/factory/sovereignDirectStakedListHandlerFactory_test.go
- node/trieIterators/factory/sovereignStakeValuesHandlerFactory.go
- node/trieIterators/factory/sovereignStakeValuesHandlerFactory_test.go
- node/trieIterators/factory/stakeValuesHandlerFactory.go
- node/trieIterators/factory/stakeValuesHandlerFactory_test.go
- MX-14950 task
- refactor for files `node/trieIterators/factory/delegatedListHandlerFactory.go` & `node/trieIterators/factory/stakeValuesHandlerFactory.go`
- 
- Refactor some components
- 
- 
- running main node
- 
> refactor sovereign components

- consensus/spos/bls/subroundEndRound.go
- process/block/baseProcess.go
- process/block/baseProcess_test.go
- process/block/metablock_test.go
- process/block/shardblock_test.go
- process/headerCheck/common.go
- process/headerCheck/common_test.go
> Update sirius patch 2 rc v1.7.0 2024.01.31

- node/chainSimulator/chainSimulator.go
- node/chainSimulator/chainSimulator_test.go
- node/chainSimulator/components/coreComponents.go
- node/chainSimulator/components/cryptoComponents.go
- node/chainSimulator/components/manualRoundHandler.go
- node/chainSimulator/components/testOnlyProcessingNode.go
- node/chainSimulator/configs/configs.go
- node/chainSimulator/dtos/validators.go
- node/chainSimulator/process/processor.go
- Initial round
- Added a new endpoint to extend the list of the managed validators' keys.
> Initial round

- consensus/spos/bls/subroundEndRound.go
- process/block/baseProcess.go
- process/block/baseProcess_test.go
- process/block/metablock_test.go
- process/block/shardblock_test.go
- process/headerCheck/common.go
- process/headerCheck/common_test.go
> Merge rc v1.7.0 feat staking v4 2024.02.01

- node/chainSimulator/chainSimulator.go
- node/chainSimulator/components/testOnlyProcessingNode_test.go
- node/chainSimulator/configs/configs.go
- node/chainSimulator/configs/configs_test.go
- changed the chain simulator to use less config pointers
- 
- 
- 
- 
- 
- 
> Changed the chain simulator to use less config pointers

- cmd/node/config/config.toml
- cmd/node/config/systemSmartContractsConfig.toml
- config/config.go
- config/systemSmartContractsConfig.go
- epochStart/metachain/auctionListSelector.go
- epochStart/metachain/auctionListSelector_test.go
- epochStart/metachain/errors.go
- epochStart/metachain/systemSCs_test.go
- factory/processing/blockProcessorCreator.go
- factory/processing/processComponents_test.go
- genesis/process/genesisBlockCreator_test.go
- integrationTests/multiShard/hardFork/hardFork_test.go
- integrationTests/testInitializer.go
- integrationTests/testProcessorNode.go
- integrationTests/vm/staking/systemSCCreator.go
- integrationTests/vm/testInitializer.go
- node/nodeRunner_test.go
- process/factory/metachain/vmContainerFactory_test.go
- testscommon/components/components.go
- testscommon/generalConfig.go
- vm/errors.go
- vm/factory/systemSCFactory_test.go
- vm/systemSmartContracts/esdt.go
- vm/systemSmartContracts/esdt_test.go
- Delete unused delegation ticker(from obsolete liquid staking)
- Treat overflow cases when computing number qualified of nodes
- Set max number of iterations cap in soft auction config
- Moved `SoftAuctionConfig` from `config.toml` to `systemSmartContractsConfig.toml`
> StakingV4 bugfixes

- sharding/nodesCoordinator/indexHashedNodesCoordinator.go
> FIX: Leaving node in previous config staking v4

- node/chainSimulator/chainSimulator_test.go
- node/chainSimulator/interface.go
> fix unit test

- config/configChecker_test.go
- System test config like scenario for sanity checks
> System test config like scenario for sanity checks

- integrationTests/chainSimulator/interface.go
- integrationTests/chainSimulator/staking/delegation_test.go
- integrationTests/chainSimulator/staking/stakeAndUnStake_test.go
- node/chainSimulator/chainSimulator.go
- node/chainSimulator/configs/configs.go
- process/interface.go
- process/peer/validatorsProvider.go
- testscommon/stakingcommon/validatorsProviderStub.go
> Staking ph4 delegation scenario 10

- process/block/preprocess/sovereignChainTransactions.go
- process/block/preprocess/sovereignChainTransactions_test.go
- process/block/preprocess/transactions.go
- process/block/preprocess/transactionsV2.go
- branch needed to merge `feat/chain-sdk-go` into `feat/demo-refactor`
- 
- 
- 
- 
- 
- 
- 
- 
> Merge sovereign into demo refactor

- integrationTests/chainSimulator/staking/delegation_test.go
- integrationTests/chainSimulator/staking/stakeAndUnStake_test.go
- node/chainSimulator/chainSimulator.go
- node/chainSimulator/chainSimulator_test.go
> Call chainSimulator.Close on all occasions to avoid resource leaks

- integrationTests/chainSimulator/interface.go
- integrationTests/chainSimulator/staking/delegation_test.go
- integrationTests/chainSimulator/staking/jail_test.go
- node/chainSimulator/chainSimulator.go
- node/chainSimulator/dtos/wallet.go
- small refactor in chain simulator
- 
- 
- 
- 
- 
- 
> Small refactor in chain simulator

- integrationTests/chainSimulator/interface.go
- integrationTests/chainSimulator/staking/delegation_test.go
- integrationTests/chainSimulator/staking/jail_test.go
- integrationTests/chainSimulator/staking/stakeAndUnStake_test.go
- node/chainSimulator/chainSimulator.go
- node/chainSimulator/configs/configs.go
- node/chainSimulator/process/processor.go
> Jail UnJail scenario

- integrationTests/chainSimulator/staking/delegation_test.go
> FIX: Unit tests

- cmd/node/config/config.toml
- config/config.go
- epochStart/shardchain/trigger.go
- factory/processing/processComponents.go
- node/chainSimulator/chainSimulator.go
- node/chainSimulator/configs/configs.go
- Moved the hard-coded wait duration from the epoch start trigger in `config.toml` file
> Configurable epoch change delay

- cmd/node/config/config.toml
- config/config.go
- epochStart/shardchain/trigger.go
- factory/processing/processComponents.go
- node/chainSimulator/configs/configs.go
- Merge `rc/v1.7.0` in `feat/staking-v4`
> Merge rc 7 in feat staking

- integrationTests/chainSimulator/staking/jail_test.go
- integrationTests/chainSimulator/staking/simpleStake_test.go
- node/chainSimulator/chainSimulator.go
- node/chainSimulator/configs/configs.go
- node/chainSimulator/send_and_execute.go
> Staking v4 - scenario nr 2

- integrationTests/chainSimulator/staking/stakeAndUnStake_test.go
> Scenerios 4 5 6 staking v4

- epochStart/metachain/legacySystemSCs.go
> Proper DelegationSmartContractFlag flag

- epochStart/metachain/systemSCs.go
> proper flag for GovernanceFlagInSpecificEpochOnly

- node/chainSimulator/components/bootstrapComponents.go
- node/chainSimulator/components/bootstrapComponents_test.go
- node/chainSimulator/components/coreComponents.go
- node/chainSimulator/components/coreComponents_test.go
- node/chainSimulator/components/cryptoComponents.go
- node/chainSimulator/components/cryptoComponents_test.go
- more coverage needed
- bootstrapComponentsHolder tests 
- tests only
> More chain simulator tests

- cmd/node/config/config.toml
- config/config.go
- epochStart/bootstrap/process.go
- epochStart/metachain/epochStartData.go
- factory/processing/processComponents.go
- genesis/process/argGenesisBlockCreator.go
- genesis/process/genesisBlockCreator.go
- node/chainSimulator/chainSimulator.go
- node/chainSimulator/chainSimulator_test.go
- node/chainSimulator/components/manualRoundHandler.go
- node/chainSimulator/components/processComponents.go
- node/chainSimulator/components/testOnlyProcessingNode.go
- node/chainSimulator/configs/configs.go
- node/chainSimulator/process/processor.go
- Added an option to set the genesis epoch
- Added an option in chain simulator to provide an initial nonce
- Extended the `config.toml` file with the GenesisEpoch parameter
- Extended the chain simulator with and option to provide an initial nonce
- Ensure the internal testnet is working properly.
> Genesis epoch

- factory/api/apiResolverFactory_test.go
- factory/processing/processComponents_test.go
- factory/state/stateComponentsHandler_test.go
- factory/state/stateComponents_test.go
- node/chainSimulator/components/dataComponents.go
- node/chainSimulator/components/dataComponents_test.go
- node/chainSimulator/components/instantBroadcastMessenger_test.go
- node/chainSimulator/components/manualRoundHandler_test.go
- node/chainSimulator/components/memoryComponents.go
- node/chainSimulator/components/memoryComponents_test.go
- node/chainSimulator/components/networkComponents.go
- node/chainSimulator/components/networkComponents_test.go
- node/chainSimulator/components/processComponents.go
- node/chainSimulator/components/processComponents_test.go
- testscommon/components/components.go
- increase chain simulator code coverage
- more coverage
- tests only
> More chain simulator tests part 2

- node/chainSimulator/components/api/fixedAPIInterface_test.go
- node/chainSimulator/components/api/freeAPIInterface_test.go
- node/chainSimulator/components/api/noApiInterface_test.go
- node/chainSimulator/components/closeHandler_test.go
- node/chainSimulator/components/stateComponents.go
- node/chainSimulator/components/stateComponents_test.go
- node/chainSimulator/components/statusComponents.go
- node/chainSimulator/components/statusComponents_test.go
- node/chainSimulator/components/statusCoreComponents.go
- node/chainSimulator/components/statusCoreComponents_test.go
- node/chainSimulator/components/storageService_test.go
- node/chainSimulator/facade_test.go
- testscommon/chainSimulator/chainSimulatorMock.go
- testscommon/generalConfig.go
- chain simulator coverage
- added more tests
- tests only
> More chain simulator tests part 3

- node/chainSimulator/components/syncedBroadcastNetwork.go
- node/chainSimulator/components/syncedBroadcastNetwork_test.go
> Fixed chain simulator's synced messenger to prepare the Peer field in the message

- factory/api/apiResolverFactory.go
- process/smartContract/scQueryService.go
- process/smartContract/scQueryService_test.go
> Handled vm queries in snapshotless mode

- go.mod
- go.sum
> Update to use latest storage version

- cmd/node/flags.go
- common/operationmodes/historicalBalances.go
- common/operationmodes/historicalBalances_test.go
- common/operationmodes/operationmodes.go
- factory/api/apiResolverFactory.go
- process/smartContract/scQueryService.go
- process/smartContract/scQueryService_test.go
> Merge rc v1.6.next1 rc v1.7.0 2024.03.05

- errors/errors.go
- process/transaction/sovereignProcess.go
- state/accounts/esdtAsBalance.go
- state/accounts/sovereignAccount.go
- state/accounts/sovereignAccount_test.go
- state/factory/sovereignAccountCreator.go
- state/factory/sovereignAccountCreator_test.go
- state/interface.go
> Esdt as gas token

- dataRetriever/factory/storageRequestersContainer/baseRequestersContainerFactory.go
- process/smartContract/scQueryService.go
- process/transaction/metaProcess.go
> Fix linter issues by removing unused methods

- errors/errors.go
- state/accounts/esdtAsBalance_test.go
- state/accounts/sovereignAccount.go
- state/accounts/sovereignAccount_test.go
- state/factory/sovereignAccountCreator.go
- state/factory/sovereignAccountCreator_test.go
- testscommon/sovereign/esdtAsBalanceHandlerMock.go
- Unit tests for https://github.com/multiversx/mx-chain-go/pull/5994
> ESDT native payment unit tests

- node/customConfigsDarwinArm64.go
- node/customConfigsDarwinArm64_test.go
- node/customConfigsDefault.go
- node/customConfigsDefault_test.go
- node/nodeRunner.go
- process/factory/shard/vmConfigPatching.go
- process/factory/shard/vmConfigPatching_darwin_arm64.go.go
- process/factory/shard/vmContainerFactory.go
- added config tweaks to support darwin & arm64 arch + unit tests
- 
- 
- 
- 
- 
- 
> Apple arm64 custom configs

- integrationTests/state/stateTrie/stateTrie_test.go
- integrationTests/state/stateTrieSync/stateTrieSync_test.go
- state/syncer/userAccountsSyncer.go
> Trie sync without code leaf updates

- sharding/nodesCoordinator/hashValidatorShuffler.go
> FIX: Warn for too low waiting list to debug

- api/errors/errors.go
- api/groups/transactionGroup.go
- api/groups/transactionGroup_test.go
- process/transaction/interceptedTransaction.go
- process/transaction/interceptedTransaction_test.go
- invalid checks for relayed v3 recursive
- proper checks
> added api check for recursive relayed v3 + fixed interceptor

- process/smartContract/scQueryService.go
- fixed linter issue
- 
- 
- 
- 
- 
- 
> Fixed linter issue

- node/chainSimulator/configs/configs.go
- node/customConfigsArm64.go
- node/customConfigsArm64_test.go
- node/customConfigsDefault.go
- node/customConfigsDefault_test.go
- node/nodeRunner.go
- applied custom arch config tweaks on the chain simulator
- 
- 
- 
- 
- 
- 
> Applied custom arch config tweaks on the chain simulator

- consensus/spos/bls/sovereignSubRoundEnd.go
- consensus/spos/bls/sovereignSubRoundEnd_test.go
> Merge feat sov into feat esdt native

- docker/node/Dockerfile
- scripts/docker-testnet/README.md
- scripts/docker-testnet/build.sh
- scripts/docker-testnet/clean.sh
- scripts/docker-testnet/functions.sh
- scripts/docker-testnet/setup.sh
- scripts/docker-testnet/start.sh
- scripts/docker-testnet/stop.sh
- scripts/docker-testnet/variables.sh
> Merge master into rc170 2024.03.27

- epochStart/metachain/legacySystemSCs.go
- state/interface.go
- state/validatorsInfoMap.go
> fix backwards compatibility issues in legacySystemSCs

- cmd/node/config/prefs.toml
- cmd/sovereignnode/config/prefs.toml
- scripts/testnet/include/config.sh
- override config 
- 
- 
- 
- 
- 
- 
- 
- 
> override config for WasmVMVersions

- epochStart/metachain/legacySystemSCs.go
- factory/runType/sovereignRunTypeComponents.go
- genesis/process/common/initialization.go
- genesis/process/common/initialization_test.go
- genesis/process/metaGenesisBlockCreator.go
- genesis/process/sovereignGenesisBlockCreator.go
- genesis/process/sovereignGenesisBlockCreator_test.go
- testscommon/state/accountWrapperMock.go
> Update sdk benchmarks from sdk apr 23

- cmd/sovereignnode/sovereignNodeRunner.go
- factory/interface.go
- factory/processing/processComponents.go
- factory/processing/processComponents_test.go
- factory/runType/runTypeComponents.go
- factory/runType/runTypeComponentsHandler.go
- factory/runType/runTypeComponentsHandler_test.go
- factory/runType/sovereignRunTypeComponents.go
- integrationTests/realcomponents/processorRunner.go
- node/chainSimulator/components/processComponents.go
- node/nodeRunner.go
- testscommon/components/components.go
- testscommon/factory/interceptorsContainerFactoryMock.go
- testscommon/mainFactoryMocks/runTypeComponentStub.go
- testscommon/shardInterceptorsContainerFactoryMock.go
- refactor `InterceptorsContainerFactoryCreator`
- 
- 
- 
- 
- 
- 
- 
- 
> refactor InterceptorsContainerFactoryCreator

- cmd/sovereignnode/sovereignNodeRunner.go
- factory/interface.go
- factory/processing/blockProcessorCreator.go
- factory/processing/processComponents.go
- factory/processing/processComponents_test.go
- factory/runType/runTypeComponents.go
- factory/runType/runTypeComponentsHandler.go
- factory/runType/runTypeComponentsHandler_test.go
- factory/runType/sovereignRunTypeComponents.go
- genesis/process/argGenesisBlockCreator.go
- genesis/process/genesisBlockCreator.go
- genesis/process/genesisBlockCreator_test.go
- genesis/process/metaGenesisBlockCreator.go
- genesis/process/shardGenesisBlockCreator.go
- integrationTests/multiShard/hardFork/hardFork_test.go
- integrationTests/realcomponents/processorRunner.go
- integrationTests/testInitializer.go
- node/chainSimulator/components/processComponents.go
- node/nodeRunner.go
- testscommon/components/components.go
- testscommon/factory/txPreProcessorFactoryMock.go
- testscommon/mainFactoryMocks/runTypeComponentStub.go
- refactor `TxPreProcessorCreator`
- 
- 
- 
- 
- 
- 
- 
- 
> refactor TxPreProcessorCreator

- cmd/sovereignnode/sovereignNodeRunner.go
- factory/interface.go
- factory/processing/interface.go
- factory/processing/processComponents.go
- factory/processing/processComponentsHandler_test.go
- factory/processing/processComponents_test.go
- factory/runType/runTypeComponents.go
- factory/runType/runTypeComponentsHandler.go
- factory/runType/runTypeComponentsHandler_test.go
- factory/runType/sovereignRunTypeComponents.go
- genesis/process/genesisMetaBlockChecker.go
- genesis/process/genesisMetaBlockChecker_test.go
- genesis/process/interface.go
- genesis/process/sovereignGenesisMetaBlockChecker.go
- genesis/process/sovereignGenesisMetaBlockChecker_test.go
- integrationTests/realcomponents/processorRunner.go
- integrationTests/testInitializer.go
- integrationTests/testProcessorNode.go
- node/chainSimulator/components/processComponents.go
- node/nodeRunner.go
- testscommon/components/components.go
- testscommon/factory/genesisMetaBlockCheckerMock.go
- testscommon/mainFactoryMocks/runTypeComponentStub.go
- refactor `GenesisMetaBlockChecker`
- 
- 
- 
- 
- 
- 
- 
- 
> refactor GenesisMetaBlockChecker

- factory/processing/processComponentsHandler_test.go
- node/chainSimulator/components/processComponents_test.go
- process/transaction/relayedTxV3Processor_test.go
- process/transaction/shardProcess_test.go
> Extra tests and coverage for relayed v3 with multiple inner transactions

- cmd/sovereignnode/go.mod
- cmd/sovereignnode/go.sum
- go.mod
- go.sum
> Fix ES Indexer go.mod

- cmd/sovereignnode/config/prefs.toml
- cmd/sovereignnode/go.mod
- cmd/sovereignnode/go.sum
- epochStart/metachain/legacySystemSCs.go
- factory/runType/sovereignRunTypeComponents.go
- genesis/process/common/initialization.go
- genesis/process/common/initialization_test.go
- genesis/process/metaGenesisBlockCreator.go
- genesis/process/sovereignGenesisBlockCreator.go
- genesis/process/sovereignGenesisBlockCreator_test.go
- go.mod
- go.sum
- scripts/testnet/include/config.sh
- testscommon/state/accountWrapperMock.go
- merge PR
- 
- 
- 
- 
- 
- 
- 
- 
> Merge sovereign into refactor

- cmd/node/config/enableEpochs.toml
- cmd/node/config/systemSmartContractsConfig.toml
- aligned configs with the mainnet
- compressed flags
- 
- 
- 
> v1.7.10 dev config

- integrationTests/testProcessorNode.go
- testscommon/generalConfig.go
- Fix long tests for Sovereign
- 
- 
- 
- 
- 
- 
- 
- 
> Fix long tests for Sovereign

- genesis/parsing/accountsParser.go
> Linter fix

- factory/vm/sovereignVmContainerShardCreator.go
- Fix missing piece for sovereign vm container
- 
- 
- 
- 
- 
- 
- 
- 
> Fix sovereign vm container

- cmd/sovereignnode/go.mod
- cmd/sovereignnode/go.sum
- go.mod
- go.sum
- vm/systemSmartContracts/eei.go
- Fix issue token from sc
- Copied the fixes from here: https://github.com/multiversx/mx-chain-go/compare/2bb8ca7...7aff054
- 
- 
- 
- 
- 
- 
- 
> Fix issue token from sc

- consensus/spos/bls/subroundBlockV2.go
- consensus/spos/bls/subroundSignature.go
- scripts/testnet/include/validators.sh
- scripts/testnet/variables.sh
> multikey on sovereign test

- scripts/testnet/variables.sh
> Temporary change for demo

- cmd/sovereignnode/sovereignNodeRunner.go
- Fix sovereign validators indexing at genesis  
> fix validators indexing

- epochStart/metachain/stakingDataProvider.go
- epochStart/metachain/stakingDataProvider_test.go
- process/peer/validatorsProvider.go
- process/peer/validatorsProviderAuction.go
- process/peer/validatorsProvider_test.go
> Validator stats fixes

- cmd/sovereignnode/go.mod
- cmd/sovereignnode/go.sum
- go.mod
- go.sum
- Fix esdt transfer role from vm-common by Robert
- 
- 
- 
- 
- 
- 
- 
- 
> Fix esdt transfer role from vm-common

- scripts/testnet/variables.sh
- Fix duplicate round duration config
- 
- 
- 
- 
- 
- 
- 
- 
> Fix duplicate round duration variable in config

- integrationTests/chainSimulator/common.go
- integrationTests/chainSimulator/interface.go
- integrationTests/chainSimulator/staking/common.go
- integrationTests/chainSimulator/staking/jail/jail_test.go
- integrationTests/chainSimulator/staking/stake/simpleStake_test.go
- integrationTests/chainSimulator/staking/stake/stakeAndUnStake_test.go
- integrationTests/chainSimulator/staking/stakingProvider/delegation_test.go
- integrationTests/chainSimulator/staking/stakingProvider/stakingProviderWithNodesinQueue_test.go
- integrationTests/chainSimulator/testing.go
- node/chainSimulator/chainSimulator.go
- node/chainSimulator/chainSimulator_test.go
- node/chainSimulator/errors.go
- node/chainSimulator/errors/errors.go
- refactor for chain simulator tests to be more general (and to work better with sovereign chain simulator)
- 
- 
- 
- 
- 
- 
- 
- 
> Chain simulator tests refactor

- integrationTests/chainSimulator/common.go
- integrationTests/chainSimulator/interface.go
- integrationTests/chainSimulator/staking/common.go
- integrationTests/chainSimulator/staking/jail/jail_test.go
- integrationTests/chainSimulator/staking/stake/simpleStake_test.go
- integrationTests/chainSimulator/staking/stake/stakeAndUnStake_test.go
- integrationTests/chainSimulator/staking/stakingProvider/delegation_test.go
- integrationTests/chainSimulator/staking/stakingProvider/stakingProviderWithNodesinQueue_test.go
- integrationTests/chainSimulator/testing.go
- node/chainSimulator/chainSimulator.go
- node/chainSimulator/chainSimulator_test.go
- node/chainSimulator/errors.go
- node/chainSimulator/errors/errors.go
> Update feat chain simulator 30.05

- go.mod
- go.sum
> updated es indexer

- integrationTests/multiShard/relayedTx/relayedTxV2_test.go
> fix TestRelayedTransactionV2InMultiShardEnvironmentWithSmartContractTX

- go.mod
- go.sum
- integrationTests/multiShard/relayedTx/relayedTxV2_test.go
- node/chainSimulator/chainSimulator.go
- node/chainSimulator/chainSimulator_test.go
- node/chainSimulator/components/interface.go
- node/chainSimulator/components/processComponents.go
- node/chainSimulator/components/syncedTxsSender.go
- node/chainSimulator/components/syncedTxsSender_test.go
- node/chainSimulator/components/testOnlyProcessingNode.go
- node/chainSimulator/components/testOnlyProcessingNode_test.go
- node/chainSimulator/configs/configs.go
- node/chainSimulator/dtos/state.go
- node/chainSimulator/process/interface.go
- testscommon/chainSimulator/nodeHandlerMock.go
> Merge rc 1 7 next 1 into feat esdt prefix 4 jun 2024

- scripts/testnet/sovereignBridge/pyScripts/address_convert.py
- scripts/testnet/sovereignBridge/pyScripts/address_shard.py
- scripts/testnet/sovereignBridge/pyScripts/compute_contract_address.py
- Python bridge scripts update with python package `multiversx-sdk`
- 
- 
- 
- 
- 
- 
- 
- 
> Python bridge scripts update with new dependency

- genesis/process/argGenesisBlockCreator.go
- genesis/process/genesisBlockCreator.go
- genesis/process/genesisBlockCreator_test.go
- genesis/process/metaGenesisBlockCreator.go
- process/interface.go
- testscommon/genesisMocks/runTypeComponentsStub.go
> Fix sovereign modularity issues for genesis meta block creation

- factory/interface.go
- factory/processing/processComponents.go
- factory/processing/processComponents_test.go
- factory/runType/runTypeComponents.go
- factory/runType/runTypeComponentsHandler.go
- factory/runType/runTypeComponentsHandler_test.go
- factory/runType/sovereignRunTypeComponents.go
- genesis/checking/interface.go
- genesis/checking/nodesSetupChecker.go
- genesis/checking/nodesSetupCheckerFactory.go
- genesis/checking/nodesSetupCheckerFactory_test.go
- genesis/checking/nodesSetupChecker_test.go
- testscommon/components/components.go
- testscommon/mainFactoryMocks/runTypeComponentStub.go
> Fix sovereign modularity issues for nodes setup checker

- cmd/sovereignnode/config/enableEpochs.toml
> FIX: Enable epochs

- integrationTests/chainSimulator/relayedTx/relayedTx_test.go
- integrationTests/chainSimulator/staking/jail/jail_test.go
- integrationTests/chainSimulator/staking/stake/simpleStake_test.go
- integrationTests/chainSimulator/staking/stake/stakeAndUnStake_test.go
- integrationTests/chainSimulator/staking/stakingProvider/delegation_test.go
- integrationTests/chainSimulator/staking/stakingProvider/stakingProviderWithNodesinQueue_test.go
- integrationTests/chainSimulator/vm/esdtImprovements_test.go
- node/chainSimulator/chainSimulator_test.go
- node/chainSimulator/components/cryptoComponents_test.go
- node/chainSimulator/components/processComponents.go
> Merge rc 17next1 into feat relayedv3 2024.06.19

- integrationTests/chainSimulator/vm/esdtImprovements_test.go
> add more testing scenarios

- integrationTests/chainSimulator/vm/esdtImprovements_test.go
> Merge rc17next1 into feat relayedv3 2024.06.20

- integrationTests/chainSimulator/vm/esdtImprovements_test.go
- vm/systemSmartContracts/esdt.go
- Fix non fungible esdt v2 dynamic token type on `registerDynamic`
- Do not allow registering dynamic for fungible token
- Chain simulator integration tests for `registerDynamic` and `registerAndSetAllRolesDynamic` functions
- Test scenarios for `registerDynamic` and `registerAndSetAllRolesDynamic` functions
> ESDT improvements integration tests part2 + fixes

- .github/workflows/deploy-docker.yaml
- .github/workflows/docker-keygenerator.yaml
- Create a workflow for building keygenerator docker image and pushing it to DockerHub
- 
- 
- 
- 
- 
- 
- 
- 
> Added action for building keygenerator docker images

- process/transaction/shardProcess.go
> fixed processTxFee for inner tx after base cost fix

- cmd/node/config/enableEpochs.toml
- compressed flags
- compressed flags
> v1.7.13 dev config

- go.mod
- go.sum
> updated core-go

- factory/disabled/txCoordinator.go
- factory/processing/processComponents.go
- integrationTests/mock/intermediateTransactionHandlerMock.go
- integrationTests/mock/transactionCoordinatorMock.go
- process/block/baseProcess.go
- process/block/postprocess/basePostProcess.go
- process/block/postprocess/basePostProcess_test.go
- process/block/postprocess/intermediateResults.go
- process/block/postprocess/intermediateResults_test.go
- process/block/postprocess/oneMBPostProcessor.go
- process/block/postprocess/oneMBPostProcessor_test.go
- process/block/preprocess/basePreProcess.go
- process/block/preprocess/basePreProcess_test.go
- process/block/preprocess/rewardTxPreProcessor.go
- process/block/preprocess/smartContractResults.go
- process/block/preprocess/transactions.go
- process/coordinator/process.go
- process/coordinator/process_test.go
- process/interface.go
- process/mock/intermProcessorStub.go
- process/mock/intermediateTransactionHandlerMock.go
- process/smartContract/process.go
- process/smartContract/process_test.go
- process/smartContract/processorV2/processV2.go
- process/smartContract/processorV2/process_test.go
- process/transaction/shardProcess.go
- process/transaction/shardProcess_test.go
- testscommon/preProcessorExecutionInfoHandlerMock.go
- testscommon/transactionCoordinatorMock.go
- update/mock/transactionCoordinatorMock.go
> Merge rc 17next1 into feat relayedv3 2024.07.04

- integrationTests/chainSimulator/relayedTx/relayedTx_test.go
- process/transaction/shardProcess.go
- process/transaction/shardProcess_test.go
- integration test needed to confirm gas consumption on non-executable inner txs
- added more integration tests
- small fix on failed logs append
> Added more integration tests for non-executable inner tx + small fix on logs append

- integrationTests/chainSimulator/esdt/issue_test.go
> FIX: Linter unused var

- cmd/node/config/gasSchedules/gasScheduleV1.toml
- cmd/node/config/gasSchedules/gasScheduleV2.toml
- cmd/node/config/gasSchedules/gasScheduleV3.toml
- cmd/node/config/gasSchedules/gasScheduleV4.toml
- cmd/node/config/gasSchedules/gasScheduleV5.toml
- cmd/node/config/gasSchedules/gasScheduleV6.toml
- cmd/node/config/gasSchedules/gasScheduleV7.toml
- cmd/node/config/gasSchedules/gasScheduleV8.toml
- go.mod
- go.sum
> updated mx-chain-vm-go to latest rc/v1.7.next1

- process/smartContract/processorV2/vmInputV2.go
- vm/systemSmartContracts/esdt.go
- update vm-go as per #6022 
- 
- 
- 
> Proper update of vm-go

- trie/branchNode.go
- trie/branchNode_test.go
- trie/extensionNode_test.go
- trie/leafNode_test.go
> update trie from batch tests

- cmd/node/config/enableEpochs.toml
- common/constants.go
- common/enablers/enableEpochsHandler.go
- config/epochConfig.go
- process/common.go
- process/scToProtocol/stakingToPeer.go
- state/interface.go
> Merge rc17next1 into feat relayedv3 2024.07.19

- integrationTests/vm/testInitializer.go
> fixed tests by using real FailedTxLogsAccumulator

- docker/node/Dockerfile
- docker/termui/Dockerfile
- Added step to create directories `lib_amd64` and `lib_arm64`.
- Added `TARGETARCH` environment variable in the Docker build context, for conditional copying of required files for target architecture.
- 
- 
- 
- 
- 
- 
> fix node/termui dockerfiles

- integrationTests/chainSimulator/bridge/common.go
- integrationTests/chainSimulator/common.go
- integrationTests/chainSimulator/esdt/issue_test.go
- integrationTests/chainSimulator/relayedTx/relayedTx_test.go
- integrationTests/chainSimulator/staking/jail/jail_test.go
- integrationTests/chainSimulator/staking/stake/simpleStake_test.go
- integrationTests/chainSimulator/staking/stake/stakeAndUnStake_test.go
- integrationTests/chainSimulator/staking/stakingProvider/delegation_test.go
- integrationTests/chainSimulator/staking/stakingProvider/stakingProviderWithNodesinQueue_test.go
- integrationTests/chainSimulator/testing.go
- integrationTests/chainSimulator/vm/egldMultiTransfer_test.go
- integrationTests/chainSimulator/vm/esdtImprovements_test.go
- integrationTests/chainSimulator/vm/esdtTokens_test.go
- node/chainSimulator/chainSimulator_test.go
- node/chainSimulator/components/processComponents.go
- node/chainSimulator/components/statusComponents.go
- node/chainSimulator/components/statusComponents_test.go
- node/chainSimulator/components/testOnlyProcessingNode.go
- vm/systemSmartContracts/esdt.go
> Merge rc 1 7 next into esdt prefix 1 aug 2024

- .github/workflows/build_and_test.yml
- .github/workflows/create_release.yml
- go.mod
- go.sum
> new-faster-wasmer

- .github/workflows/build_and_test.yml
- .github/workflows/create_release.yml
- go.mod
- go.sum
- integrationTests/chainSimulator/vm/esdtImprovements_test.go
- vm/systemSmartContracts/esdt.go
> Merge rc 1 7 next into esdt prefix 12 aug 2024

- process/block/preprocess/transactionsV2.go
> Switch log level to trace for tractions.processTransaction log

- consensus/broadcast/delayedBroadcast.go
- consensus/broadcast/delayedBroadcast_test.go
- consensus/broadcast/export.go
- consensus/broadcast/interface.go
- consensus/broadcast/metaChainMessenger.go
- consensus/broadcast/shardChainMessenger.go
- consensus/broadcast/shared/types.go
- consensus/mock/delayedBroadcasterMock.go
> fix cyclic import

- consensus/broadcast/commonMessenger.go
- consensus/broadcast/delayedBroadcast.go
- consensus/broadcast/delayedBroadcast_test.go
- consensus/broadcast/errors.go
- consensus/broadcast/export.go
- consensus/broadcast/interface.go
- consensus/broadcast/metaChainMessenger.go
- consensus/broadcast/metaChainMessenger_test.go
- consensus/broadcast/shardChainMessenger.go
- consensus/broadcast/shardChainMessenger_test.go
- consensus/broadcast/shared/types.go
- consensus/mock/delayedBroadcasterMock.go
- consensus/spos/sposFactory/sposFactory.go
- creating a mock for unit testing the broadcast component
- 
- 
- mock for delayedBroadcaster
- 
- 
- 
- 
- 
> Delayed broadcaster mock

- consensus/broadcast/shardChainMessenger_test.go
- consensus/spos/bls/export_test.go
- consensus/spos/bls/subroundStartRound_test.go
- testscommon/outport/outportStub.go
- testscommon/shardingMocks/nodesCoordinatorStub.go
- increasing code coverage in consensus
- 
- 
- unit tests
- 
- 
- 
- 
- 
> increase coverage for subroundStartRound

- go.mod
- go.sum
- Upgraded the version of the mx-chain-es-indexer-go
- Changed the version of mx-chain-es-indexer-go: https://github.com/multiversx/mx-chain-es-indexer-go/pull/293 
> latest indexer version

- cmd/sovereignnode/chainSimulator/tests/epochChange/epochChange_test.go
- process/smartContract/hooks/sovereignBlockChainHookFactory.go
> FIX: Max trie store operations read by using disabled counter

- consensus/spos/bls/errors.go
- consensus/spos/bls/export_test.go
- consensus/spos/bls/subroundSignature.go
- consensus/spos/bls/subroundSignature_test.go
- used goroutines for the signature in multikey mode
- 
- 
- goroutines for doSignatureJobForManagedKeys
- unit tests
- 
- 
- 
- 
> Multikey goroutines

- consensus/spos/bls/blsSubroundsFactory.go
- consensus/spos/bls/blsSubroundsFactory_test.go
- consensus/spos/bls/export_test.go
- consensus/spos/bls/subroundSignature.go
- consensus/spos/bls/subroundSignature_test.go
- consensus/spos/errors.go
- consensus/spos/sposFactory/sposFactory.go
- consensus/spos/sposFactory/sposFactory_test.go
- factory/consensus/consensusComponents.go
- added a throttler for the multikey goroutines signature
- initialization of signature subround and bls subround
- unit tests
- management of goroutines in multikey signature
- regular system test 
> throttler-management

- consensus/spos/bls/benchmark_test.go
- consensus/spos/bls/blsWorker_test.go
- consensus/spos/bls/subroundSignature_test.go
- benchmark test
- added a new benchmark_test file
- added a new consensusState init function for using 400 keys
- smoke and unit tests
> Benchmark test

- consensus/spos/consensusMessageValidator.go
- consensus/spos/consensusMessageValidator_test.go
- adapt final info message check
-
> Adapt final info message check

- sharding/errors.go
- sharding/mock/pubkeyConverterMock.go
- sharding/nodesCoordinator/common_test.go
- sharding/nodesSetup_test.go
- sharding/oneShardCoordinator_test.go
- increase coverage for some sharding components
- 
- 
- added new unit tests
- 
- 
- 
- 
- 
> increase coverage for nodesSetup

- go.mod
- go.sum
- integrationTests/chainSimulator/vm/egldMultiTransfer_test.go
- integrationTests/chainSimulator/vm/esdtImprovements_test.go
- integrationTests/chainSimulator/vm/esdtTokens_test.go
- There are some edgecases that are not tested
- Add more testing scenarios for the dynamic NFTs
- Small fix for the case that a dynamic token is updated in a shard in which the token is not present
- Normal testing
> add testing scenarios and update go mod

- cmd/sovereignnode/go.mod
- cmd/sovereignnode/go.sum
- go.mod
- go.sum
- API route /address/ADDRESS/collections didn't work
- 
- 
- Update in indexer
- 
- 
- 
- 
- 
> indexer dependency update

- dataRetriever/factory/requestersContainer/sovereignShardRequesterContainerFactory_test.go
- dataRetriever/factory/resolverscontainer/sovereignShardResolversContainerFactory_test.go
- process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go
- process/factory/interceptorscontainer/metaInterceptorsContainerFactory.go
- process/factory/interceptorscontainer/shardInterceptorsContainerFactory.go
- process/factory/interceptorscontainer/sovereignShardInterceptorsContainerFactory.go
- process/factory/interceptorscontainer/sovereignShardInterceptorsContainerFactory_test.go
- Sovereign shard interceptors container factory
- 
- 
- 
- 
- 
- 
> Sovereign shard interceptors container factory

- cmd/sovereignnode/chainSimulator/tests/processBlock/cleanupHeaders_test.go
- cmd/sovereignnode/chainSimulator/tests/processBlock/incomingHeader_test.go
- cmd/sovereignnode/go.mod
- cmd/sovereignnode/go.sum
- epochStart/bootstrap/fromLocalStorage.go
- epochStart/bootstrap/interface.go
- epochStart/bootstrap/process.go
- epochStart/bootstrap/process_test.go
- epochStart/bootstrap/sovereignChainProcess.go
- epochStart/bootstrap/sovereignChainProcess_test.go
- go.mod
- go.sum
- process/block/sovereignChainBlock.go
- sharding/nodesCoordinator/errors.go
- sharding/nodesCoordinator/indexHashedNodesCoordinator.go
- sharding/nodesCoordinator/indexHashedNodesCoordinatorRegistry.go
- sharding/nodesCoordinator/interface.go
- sharding/nodesCoordinator/numberOfShardsComputer.go
- sharding/nodesCoordinator/numberOfShardsComputer_test.go
- sharding/nodesCoordinator/sovereignIndexHashedNodesCoordinator.go
- sharding/nodesCoordinator/sovereignNumberOfShardsComputer.go
- sharding/nodesCoordinator/sovereignNumberOfShardsComputer_test.go
> Merge feat sovereign into feat sovereign stabilize sync

- consensus/spos/bls/subroundBlock.go
- consensus/spos/bls/subroundEndRound.go
- header can be broadcast during subround block with the equivalent proofs
- implement needed changes
- will be tested with feat branch
> Broadcast header on subroundBlock, on the shard_meta topic

- go.mod
- go.sum
- Updated proto structure in dependencies.
- Bump mx-chain-core-go version in go.mod
- Usual unit tests and PR checks should suffice.
> bump mx-chain-core go version.

- consensus/spos/bls/blsSubroundsFactory.go
- consensus/spos/bls/export_test.go
- consensus/spos/bls/subroundBlock.go
- consensus/spos/bls/subroundBlock_test.go
- consensus/spos/bls/subroundEndRound.go
- consensus/spos/bls/subroundSignature.go
- with the new implementation, headers being sent on headers topic, a new callback must be registered on headers pool so consensus components are updated
- added new handler and registered it
> Register consensus received header handler

- epochStart/bootstrap/bootStrapShardProcessor.go
- epochStart/bootstrap/bootStrapSovereignShardProcessor.go
- epochStart/bootstrap/bootStrapSovereignShardProcessor_test.go
- epochStart/bootstrap/epochStartMetaBlockProcessor.go
- epochStart/bootstrap/epochStartSovereignBlockProcessor.go
- epochStart/bootstrap/epochStartSovereignBlockProcessor_test.go
- epochStart/bootstrap/interface.go
- epochStart/bootstrap/process.go
- Sovereign epoch start block processor
- 
- 
- 
- 
- 
- 
> [sovereign] Epoch start block processor

- process/receiptslog/errors.go
- process/receiptslog/interface.go
- process/receiptslog/receiptsManager.go
- process/receiptslog/receiptsManagerCreator.go
- process/receiptslog/trieInteractor.go
- process/receiptslog/trieInteractor_test.go
- process/receiptslog/trieRecreate.go
- trie/baseIterator.go
- trie/branchNode.go
- trie/extensionNode.go
- trie/interface.go
- trie/leafNode.go
- trie/nodeTypes.go
-  Added receipt data trie
- Implemented the part where receipt data trie is saved in storage
> [lite-client] receipt data trie

- dataRetriever/factory/requestersContainer/baseRequestersContainerFactory.go
- dataRetriever/factory/requestersContainer/sovereignShardRequesterContainerFactory.go
- dataRetriever/factory/requestersContainer/sovereignShardRequesterContainerFactory_test.go
- dataRetriever/factory/resolverscontainer/baseResolversContainerFactory.go
- dataRetriever/factory/resolverscontainer/metaResolversContainerFactory.go
- dataRetriever/factory/resolverscontainer/shardResolversContainerFactory.go
- dataRetriever/factory/resolverscontainer/sovereignShardResolversContainerFactory.go
- dataRetriever/factory/resolverscontainer/sovereignShardResolversContainerFactory_test.go
- dataRetriever/requestHandlers/baseRequest.go
- dataRetriever/requestHandlers/baseSovereignRequester.go
- dataRetriever/requestHandlers/interface.go
- dataRetriever/requestHandlers/requestHandler.go
- dataRetriever/requestHandlers/sovereignRequestHandler_test.go
- epochStart/bootstrap/bootStrapSovereignShardProcessor_test.go
- process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go
- process/factory/interceptorscontainer/metaInterceptorsContainerFactory.go
- process/factory/interceptorscontainer/shardInterceptorsContainerFactory.go
- process/factory/interceptorscontainer/sovereignShardInterceptorsContainerFactory.go
- process/factory/interceptorscontainer/sovereignShardInterceptorsContainerFactory_test.go
- Fix validator info topic for requests intra shard
- 
- 
- 
- 
- 
- 
> [sovereign] Fix validator info topic for requests intra shard

- go.mod
- go.sum
> upgrade wasmer executor version

- epochStart/bootstrap/syncEpochStartMeta.go
- epochStart/bootstrap/syncEpochStartSovereign.go
- process/block/sovereignChainBlock.go
- Critical bugfix for sovereign chain block process
- Create shard interceptor when syncing blocks instead of meta
- 
- 
- 
- 
- 
- 
> [sovereign] FIX: Sovereign chain block processing

- cmd/node/config/enableEpochs.toml
- common/constants.go
- common/enablers/enableEpochsHandler.go
- common/enablers/enableEpochsHandler_test.go
- config/epochConfig.go
- config/tomlConfig_test.go
- node/metrics/metrics.go
- node/metrics/metrics_test.go
- statusHandler/statusMetricsProvider.go
- statusHandler/statusMetricsProvider_test.go
- vm/systemSmartContracts/delegation.go
- vm/systemSmartContracts/delegation_test.go
> Claim rewards with call value should err

- cmd/sovereignnode/chainSimulator/tests/processBlock/cleanupHeaders_test.go
- process/block/sovereignChainBlock.go
- scripts/testnet/include/config.sh
- scripts/testnet/prerequisites.sh
- scripts/testnet/sovereignBridge/config/common.snippets.sh
> Merge feat sovereign into feat stabilize sov 2 oct 2024

- cmd/node/config/systemSmartContractsConfig.toml
- config/systemSmartContractsConfig.go
- vm/systemSmartContracts/delegation.go
- vm/systemSmartContracts/delegation_test.go
> increaseFee with 30 epoch cooldown

- .github/workflows/build_and_test.yml
- .github/workflows/create_release.yml
- .github/workflows/docker-keygenerator.yaml
Bring changes of https://github.com/multiversx/mx-chain-go/pull/6487.
> Optimize GitHub workflows

- epochStart/errors.go
- epochStart/metachain/sovereignTrigger.go
- epochStart/metachain/sovereignTrigger_test.go
- epochStart/metachain/trigger_test.go
- epochStart/mock/validatorInfoSyncerStub.go
- factory/epochStartTrigger/sovereignEpochStartTriggerFactory.go
> [sovereign] Update data pool on sovereign trigger upon receiving epoch start header

- cmd/sovereignnode/sovereignNodeRunner.go
- factory/status/common.go
- factory/status/export_test.go
- factory/status/statusComponents.go
- factory/status/statusComponents_test.go
- process/block/metablock.go
- process/block/metrics.go
- process/block/sovereignChainBlock.go
-  index validator ratings at each `CommitBlock` if outport driver is attached
- `SaveValidatorsPubKeys` at each epoch change event detected
- 
- 
- 
- 
- 
- 
> [sovereign] indexValidatorsRatingIfNeeded

- process/block/sovereignChainBlock.go
> [sovereign] FIX: Save metrics panic

- cmd/sovereignnode/chainSimulator/sovereignChainSimulator.go
- cmd/sovereignnode/chainSimulator/tests/basic/basic_sc_adder_test.go
- cmd/sovereignnode/chainSimulator/tests/bridge/bridge_test.go
- cmd/sovereignnode/chainSimulator/tests/bridge/common.go
- cmd/sovereignnode/chainSimulator/tests/epochChange/epochChange_test.go
- cmd/sovereignnode/chainSimulator/tests/esdt/issueNft_test.go
- cmd/sovereignnode/chainSimulator/tests/esdt/issueSc_test.go
- cmd/sovereignnode/chainSimulator/tests/esdt/issueSft_test.go
- cmd/sovereignnode/chainSimulator/tests/esdt/issue_test.go
- integrationTests/chainSimulator/common.go
- integrationTests/chainSimulator/staking/common.go
- integrationTests/chainSimulator/staking/stake/stakeAndUnStake_test.go
- Some updates for tests after esdt-prefix merge
- 
- 
- 
- 
- 
- 
- 
- 
> chain simulator tests updates after merge

- cmd/sovereignnode/dataCodec/dataCodec.go
- Fix type for Amount and Royalties to match the types from SC framework ([docs](https://docs.multiversx.com/developers/developer-reference/sc-api-functions#get_esdt_token_data) here)
- 
- 
- 
- 
- 
- 
- 
- 
> data codec fix for amount and royalties

- go.mod
- go.sum
- integrationTests/chainSimulator/vm/esdtImprovements_test.go
> Merge rc 1 7 next into esdt prefix 16 oct

- .github/workflows/build_and_run_chain_simulator_and_execute_system_test.yml
> fix for workflow

- cmd/sovereignnode/systemTestDemo/mockNotifier/disabledGRPCServer.go
- cmd/sovereignnode/systemTestDemo/mockNotifier/disabledMockGRPCServer.go
- cmd/sovereignnode/systemTestDemo/mockNotifier/flags.go
- cmd/sovereignnode/systemTestDemo/mockNotifier/interface.go
- cmd/sovereignnode/systemTestDemo/mockNotifier/notifier.go
- cmd/sovereignnode/systemTestDemo/mockNotifier/vars.go
> logs update in mock notifier

- epochStart/bootstrap/bootStrapShardProcessor.go
- epochStart/bootstrap/bootStrapSovereignShardProcessor.go
- epochStart/bootstrap/bootStrapSovereignShardProcessor_test.go
- epochStart/bootstrap/interface.go
- epochStart/bootstrap/process.go
- update/sync/errors.go
- update/sync/extendedHeaderRequester.go
- update/sync/extendedHeaderRequester_test.go
- update/sync/interface.go
- update/sync/metaChainHeaderRequester.go
- update/sync/metaHeaderRequester.go
- update/sync/metaHeaderRequester_test.go
- update/sync/syncHeadersByHash.go
- update/sync/syncHeadersByHash_test.go
- Sync extended header by hash when bootstrapping from last finalized cross chain header
- Inject `CrossHeaderRequester` interface into `syncHeadersByHash.go` to request extended/meta headers
- 
- 
- 
> [sovereign] Cross header requester meta/extended

- cmd/sovereignnode/go.mod
- cmd/sovereignnode/go.sum
- go.mod
- go.sum
> Update go dependencies

- cmd/sovereignnode/go.mod
> Update mx-chain-go dependency

- integrationTests/chainSimulator/bridge/esdtSafe_test.go
- integrationTests/chainSimulator/common.go
- integrationTests/chainSimulator/esdt/issue_test.go
- 
- 
- 
- Little refactor for some functions to work in sovereign chain simulator
- 
- 
- 
- 
- 
> Refactor register functions to be usable in sovereign chain simulator

- cmd/node/config/economics.toml
- config/economicsConfig.go
- config/tomlConfig_test.go
- genesis/process/disabled/feeHandler.go
- integrationTests/chainSimulator/relayedTx/relayedTx_test.go
- integrationTests/chainSimulator/staking/stake/stakeAndUnStake_test.go
- integrationTests/chainSimulator/staking/stakingProvider/delegation_test.go
- integrationTests/testProcessorNode.go
- integrationTests/vm/testInitializer.go
- integrationTests/vm/wasm/utils.go
- node/chainSimulator/components/coreComponents_test.go
- process/economics/economicsData.go
- process/economics/economicsData_test.go
- process/economics/export_test.go
- process/economics/gasConfigHandler.go
- process/economics/testEconomicsData.go
- process/errors.go
- process/factory/metachain/vmContainerFactory_test.go
- process/interface.go
- process/peer/process_test.go
- process/smartContract/process_test.go
- process/smartContract/processorV2/processV2.go
- process/smartContract/processorV2/process_test.go
- testscommon/components/configs.go
- testscommon/economicsConfig.go
- testscommon/economicsmocks/economicsDataHandlerStub.go
- testscommon/economicsmocks/economicsHandlerMock.go
- testscommon/stakingcommon/stakingCommon.go
> Barnard to deleg 14 11

- cmd/node/config/economics.toml
- config/economicsConfig.go
- config/tomlConfig_test.go
- genesis/process/disabled/feeHandler.go
- integrationTests/chainSimulator/relayedTx/relayedTx_test.go
- integrationTests/chainSimulator/staking/stake/stakeAndUnStake_test.go
- integrationTests/chainSimulator/staking/stakingProvider/delegation_test.go
- integrationTests/testProcessorNode.go
- integrationTests/vm/testInitializer.go
- integrationTests/vm/wasm/utils.go
- node/chainSimulator/components/coreComponents_test.go
- process/economics/economicsData.go
- process/economics/economicsData_test.go
- process/economics/export_test.go
- process/economics/gasConfigHandler.go
- process/economics/testEconomicsData.go
- process/errors.go
- process/factory/metachain/vmContainerFactory_test.go
- process/interface.go
- process/peer/process_test.go
- process/smartContract/process_test.go
- process/smartContract/processorV2/processV2.go
- process/smartContract/processorV2/process_test.go
- testscommon/components/configs.go
- testscommon/economicsConfig.go
- testscommon/economicsmocks/economicsDataHandlerStub.go
- testscommon/economicsmocks/economicsHandlerMock.go
- testscommon/stakingcommon/stakingCommon.go
> Barnard governance 14 11

- cmd/sovereignnode/config/sovereignConfig.toml
> FIX: Comment

- go.mod
- go.sum
- integrationTests/chainSimulator/bridge/bridgeAndTransfer_test.go
- integrationTests/chainSimulator/bridge/esdtSafe_test.go
- integrationTests/chainSimulator/bridge/executeAndBurn_test.go
- integrationTests/chainSimulator/bridge/simpleEsdt_test.go
- 
- 
- 
- Update token id in all bridge chain simulator tests
- vm-common (feat/esdt-prefix-integration) and core-go (main) packages update
- 
- 
- 
- 
> updated token ids and go.mod

- cmd/sovereignnode/go.mod
- cmd/sovereignnode/go.sum
- go.mod
- go.sum
- integrationTests/chainSimulator/bridge/bridgeAndTransfer_test.go
- integrationTests/chainSimulator/bridge/esdtSafe_test.go
- integrationTests/chainSimulator/bridge/executeAndBurn_test.go
- integrationTests/chainSimulator/bridge/simpleEsdt_test.go
- merge PR
- 
- 
- core-go (feat/sovereign)
- vm-common (feat/sovereign)
- 
- sovereignnode/chainSimulator tests passed
- 
- 
> Merge esdt prefix into sovereign 20 nov

- consensus/broadcast/delayedBroadcast.go
- FIX: Concurrent access in delayedBroadcast.go using mutex
- 
- 
- 
- 
- 
- 
- 
- 
> FIX: Concurrent access in delayedBroadcast.go using mutex

- process/block/baseProcess.go
- process/block/metablock.go
- process/block/sovereignChainBlock.go
- Block commit for epoch start analysis and fixes
- call `markSnapshotDoneInPeerAccounts`
- create base func `commitEpochStart` for sovereign&meta
- 
- 
- 
> [sovereign] Block commit epoch start fixes

- process/smartContract/processorV2/processV2.go
> use proper prevTxHash in case of relayed v1 and v2

- go.mod
- go.sum
> Proper tag for storage go

- state/stateChanges/collector.go
- state/stateChanges/collector_test.go
- Fix storer check on collector Store function
- To be tested with the feat branch
> Fix state changes collector store check

- consensus/spos/bls/v2/subroundEndRound.go
- go.mod
- go.sum
- process/block/interceptedBlocks/interceptedEquivalentProof.go
- process/sync/baseSync.go
- process/sync/metablock_test.go
- process/sync/shardblock_test.go
- Check proof if first block after activation on sync process
- Integrate using round for header proof
- To be tested with feat branch
> Check proof on activation block sync

- node/chainSimulator/chainSimulator.go
- node/chainSimulator/components/syncedMessenger.go
- Chain simulator fixes
- 
- 
- 
- 
- 
- 
> fix chain simulator

- cmd/sovereignnode/config/prefs.toml
- scripts/testnet/sovereignBridge/config/common.snippets.sh
> DestinationShardAsObserver default "0"

- process/block/metablock.go
- process/errors.go
> complete shardData.Epoch

- process/block/metablock.go
> fix epoch check on shard data only after activation

- process/block/metablock.go
> early exist for shard data that should not have prev proof

- go.mod
- go.sum
- Changed the version of mx-chain-es-indexer-go module
- PR from mx-chain-es-indexer-go module:  https://github.com/multiversx/mx-chain-es-indexer-go/pull/324
- Ensure indexing is working in case of rollback with scheduled executed minbicloks
> Fix indexer

- cmd/node/config/enableEpochs.toml
- compress flags to align with mainnet
- compressed relayed v3 flag
- standard system test with upgrade from this one
> Flags compression

- epochStart/bootstrap/epochStartMetaBlockProcessor.go
- factory/bootstrap/bootstrapComponents.go
> fixed sync issues

- cmd/node/config/config.toml
- consensus/spos/bls/v2/subroundBlock.go
> fix config for shard nodes

- process/block/baseProcess.go
- process/block/metablock.go
- process/block/shardblock.go
- process/track/baseBlockTrack.go
> proper fix for meta sync

- cmd/node/config/enableEpochs.toml
> Merge master into rc andromeda 2025.01.30

- cmd/node/config/config.toml
- config/config.go
- config/tomlConfig_test.go
- consensus/broadcast/commonMessenger.go
- consensus/broadcast/delayedBroadcast.go
- consensus/broadcast/delayedBroadcast_test.go
- consensus/broadcast/interface.go
- consensus/broadcast/metaChainMessenger.go
- consensus/broadcast/metaChainMessenger_test.go
- consensus/broadcast/shardChainMessenger.go
- consensus/broadcast/shardChainMessenger_test.go
- consensus/interface.go
- consensus/spos/sposFactory/sposFactory.go
- consensus/spos/sposFactory/sposFactory_test.go
- factory/consensus/consensusComponents.go
- integrationTests/testProcessorNode.go
- node/chainSimulator/components/testOnlyProcessingNode.go
- testscommon/consensus/broadcastMessangerMock.go
- testscommon/consensus/delayedBroadcasterMock.go
> Cleanup delayed broadcast of proofs

- common/common.go
- consensus/interface.go
- process/block/interceptedBlocks/common.go
- process/headerCheck/headerSignatureVerify.go
- process/headerCheck/headerSignatureVerify_test.go
> fix wrong size bitmap error on transition block

- trie/factory/trieCreator.go
- trie/trieBatchManager/trieBatchManager.go
> small logging fixes

- common/common.go
- process/block/interceptedBlocks/common.go
- process/headerCheck/headerSignatureVerify.go
> reverted a previous commit leading to improper epoch usage for header verification

- process/block/metablock.go
- process/block/shardblock.go
> better handling of missing attesting headers

- node/chainSimulator/chainSimulator.go
- node/chainSimulator/chainSimulator_test.go
- node/chainSimulator/components/storageService.go
- node/chainSimulator/components/storageService_test.go
- node/chainSimulator/components/testOnlyProcessingNode.go
- Option to provide the trie storage
> Load trie from storage chain simulator

- node/chainSimulator/benchmarks_test.go
-  Added the file with benchmarks of transactions execution ( move balance, esdt transfer and swap )
> Benchmark file

- consensus/spos/bls/v2/subroundEndRound.go
> skip signatures check for observers

- process/sync/baseSync.go
> Extra log on sync block

- consensus/spos/bls/v2/subroundEndRound.go
> fix for "accumulated fees do not match" due to concurrent commit and scheduled processing

- process/track/argBlockProcessor.go
- process/track/blockProcessor.go
- process/track/blockProcessor_test.go
- process/track/metaBlockTrack.go
- process/track/shardBlockTrack.go
> when no block received, try removing the first requested block

- factory/processing/processComponents.go
- integrationTests/testProcessorNodeWithMultisigner.go
- process/headerCheck/headerSignatureVerify.go
- process/headerCheck/headerSignatureVerify_test.go
> Add proof to pool on transition

- consensus/spos/bls/v2/subroundBlock_test.go
> fix linter issue in tests

- consensus/spos/bls/v2/subroundBlock.go
> add process block stopwatch

- common/common.go
- factory/processing/processComponents.go
- process/track/argBlockProcessor.go
- process/track/argBlockTrack.go
- process/track/blockProcessor.go
- process/track/metaBlockTrack.go
- process/track/shardBlockTrack.go
> fix import-db

- cmd/sovereignnode/go.mod
- cmd/sovereignnode/go.sum
- go.mod
- go.sum
- process/block/export_test.go
- process/block/sovereign/interface.go
- process/block/sovereign/outgoingOperations.go
- process/block/sovereignChainBlock.go
- process/block/sovereignChainBlock_test.go
- testscommon/sovereign/outgoingOperationsFormatterMock.go
- Prepare node to create outgoing bridge data with type and add necessary interface definitions and setup for change validator set
- 
- 
- 
- 
- 
- 
> [sovereign] Create outgoing bridge data with type

- process/headerCheck/headerSignatureVerify.go
> Fix Andromeda import db

- node/external/blockAPI/baseBlock.go
> get bitmap and signature from proof for api block

- vm/systemSmartContracts/governance.pb.go
> regenerated governance.proto

- process/block/export_test.go
- process/block/metablock.go
- process/block/metablock_test.go
- process/block/shardblock.go
> fixed area not protected by mutex + tests

- process/headerCheck/headerSignatureVerify_test.go
- process/interceptors/processor/equivalentProofsInterceptorProcessor_test.go
> Andromeda increase coverage part4

- process/block/metablock.go
- Update meta block last header hash in finalized outport
- TBD
> Outport finalized state updates

- consensus/spos/bls/v2/subroundEndRound.go
- consensus/spos/bls/v2/subroundEndRound_test.go
- fix leader metrics todo
- removed todo and guarded to be called only for leader
- with rc
> Fix metrics for leader todo

- integrationTests/chainSimulator/staking/stakingProvider/delegation_test.go
- node/chainSimulator/chainSimulator_test.go
- process/block/interceptedBlocks/interceptedBlockHeader.go
- process/block/interceptedBlocks/interceptedEquivalentProof.go
- process/block/metablock.go
- process/sync/baseSync.go
> Remove Todo's Andromeda

- cmd/node/config/config.toml
- cmd/node/config/enableEpochs.toml
- cmd/node/config/enableRounds.toml
- Some test setup issues were detected within our internal tests.
- E enable VM 1.5 in epoch 0.
- Enable relayed V1 & V2 (legacy) in epoch 0.
- Regular all-in test.
> Optimize startup for internal testnets

- cmd/node/config/ratings.toml
- config/ratingsConfig.go
- factory/statusCore/statusCoreComponents.go
- factory/statusCore/statusCoreComponents_test.go
- integrationTests/testProcessorNode.go
- node/chainSimulator/components/coreComponents_test.go
- node/chainSimulator/components/statusCoreComponents_test.go
- node/chainSimulator/configs/configs.go
- node/metrics/metrics.go
- node/metrics/metrics_test.go
- process/errors.go
- process/interface.go
- process/mock/ratingsInfoMock.go
- process/rating/ratingsData.go
- process/rating/ratingsData_test.go
- testscommon/components/configs.go
- testscommon/ratingsInfoMock.go
- new ratings config is needed after activation
- updated ratingsData to handle multiple epochs for ratings
- with rc
> Ratings config per epoch

- cmd/node/config/economics.toml
> minor config compression

- consensus/spos/bls/v2/errors.go
- consensus/spos/bls/v2/export_test.go
- consensus/spos/bls/v2/subroundEndRound.go
- consensus/spos/bls/v2/subroundEndRound_test.go
> more tests for sendProof

- process/mock/raterMock.go
- process/peer/process.go
- process/peer/process_test.go
- no need to check the signed blocks threshold after equivalent proofs activation
- early exit
- with rc
> Remove signed blocks threshold

- go.mod
- go.sum
- state/accountsDB_test.go
- There was a missing unit test for a fixed edgecase
- Add missing unit test
> add unit test for revert fix, and update go mod

- integrationTests/consensus/consensus_test.go
- integrationTests/testConsensusNode.go
- integrationTests/testFullNode.go
- Fix multi key integration test
- Add multi key integration test with equivalent proofs
- TBD with rc branch
> fix keys management max rounds of inactivity

- cmd/node/config/enableEpochs.toml
- common/constants.go
- common/enablers/enableEpochsHandler.go
- common/enablers/enableEpochsHandler_test.go
- config/epochConfig.go
- config/tomlConfig_test.go
- go.mod
- go.sum
- integrationTests/vm/delegation/delegationScenarios_test.go
- node/metrics/metrics.go
- node/metrics/metrics_test.go
- statusHandler/statusMetricsProvider.go
- statusHandler/statusMetricsProvider_test.go
- vm/systemSmartContracts/delegation.go
- vm/systemSmartContracts/delegation_test.go
> Merge rc/barnard in feat/trie mutex refactor 25 mar

- process/block/interceptedBlocks/common.go
> add log on shard header prev proof verification

- consensus/spos/bls/blsWorker.go
- consensus/spos/export_test.go
- consensus/spos/interface.go
- consensus/spos/worker.go
- consensus/spos/worker_test.go
- process/block/interceptedBlocks/interceptedMetaBlockHeader.go
> store early consensus headers for execution

- scripts/testnet/include/config.sh
- round duration from variables.sh is not taken into consideration
- update round duration from the variables.sh
- run a local testnet with a different round time
> updated config.sh to take into consideration the round duration

- process/block/interceptedBlocks/common.go
> Check proof only if not nil

- integrationTests/chainSimulator/staking/jail/jail_test.go
- node/chainSimulator/process/processor.go
- Fixes chain simulator implementation andromeda
> Fixes chain simulator

- node/chainSimulator/chainSimulator.go
> Revert chain simulator delay

- integrationTests/testProcessorNode.go
- integrationTests/testSyncNode.go
- Fix integration tests
- TDB with feat branch
> fix fields checker integration tests referencies

- consensus/spos/worker.go
- process/block/baseProcess.go
> remove header from pool on revert

- .github/workflows/build_and_run_chain_simulator_and_execute_system_test.yml
> Fix gh action to support parallel execution and better test trigger from comments when running integration tests

- integrationTests/consensus/consensusSigning_test.go
- exclude invalid signers nodes from nonce check
- N/A
> Exclude invalid signers nodes from nonce check

- .github/workflows/build_and_run_chain_simulator_and_execute_system_test.yml
- consensus/spos/worker.go
- node/chainSimulator/chainSimulator.go
- node/chainSimulator/components/testOnlyProcessingNode.go
- node/chainSimulator/process/interface.go
- node/chainSimulator/process/processor.go
- process/block/baseProcess.go
- testscommon/chainSimulator/nodeHandlerMock.go
> Merge rc andromeda into feat patch2 2025.04.16

- common/proofs.go
- integrationTests/sync/basicSync/basicSync_test.go
- integrationTests/testInitializer.go
- integrationTests/testProcessorNode.go
- process/block/baseProcess.go
- process/sync/baseForkDetector.go
- process/sync/baseSync.go
- process/sync/metaForkDetector.go
- process/sync/shardForkDetector.go
- process/track/baseBlockTrack.go
> handle genesis nonce

- process/block/baseProcess.go
- process/block/export_test.go
- process/block/metablock.go
- process/block/shardblock.go
> fix shard nodes panicking while requesting epoch start meta proof

- process/sync/baseSync.go
- check proof hash when getting from pool by nonce
- to be tested with feat branch
> Fix checking proof by nonce from pool

- dataRetriever/factory/resolverscontainer/metaResolversContainerFactory.go
- dataRetriever/factory/resolverscontainer/shardResolversContainerFactory.go
- dataRetriever/factory/storageRequestersContainer/metaRequestersContainerFactory.go
- dataRetriever/factory/storageRequestersContainer/shardRequestersContainerFactory.go
- dataRetriever/resolvers/equivalentProofsResolver.go
- dataRetriever/resolvers/equivalentProofsResolver_test.go
- epochStart/bootstrap/baseStorageHandler.go
- factory/processing/processComponents.go
- node/external/blockAPI/internalBlock.go
- node/external/blockAPI/shardBlock.go
- process/block/baseProcess.go
- process/block/metablock.go
- process/common.go
- process/sync/shardblock.go
- process/sync/storageBootstrap/metaStorageBootstrapper.go
- process/sync/storageBootstrap/shardStorageBootstrapper.go
- process/txstatus/txStatusComputer.go
- storage/factory/storageServiceFactory.go
> append shard id for shard hdr nonce hash data unit

- process/sync/baseSync.go
- process/sync/interface.go
> do not request proofs if not needed

- common/common.go
- common/errors.go
- dataRetriever/errors.go
- dataRetriever/factory/storageRequestersContainer/baseRequestersContainerFactory.go
- dataRetriever/factory/storageRequestersContainer/metaRequestersContainerFactory.go
- dataRetriever/factory/storageRequestersContainer/metaRequestersContainerFactory_test.go
- dataRetriever/factory/storageRequestersContainer/shardRequestersContainerFactory.go
- dataRetriever/factory/storageRequestersContainer/shardRequestersContainerFactory_test.go
- dataRetriever/requestHandlers/requestHandler.go
- dataRetriever/resolvers/equivalentProofsResolver.go
- dataRetriever/storageRequesters/equivalentProofsRequester.go
- dataRetriever/storageRequesters/equivalentProofsRequester_test.go
> storage equivalentProofsRequester

- dataRetriever/errors.go
- dataRetriever/factory/requestersContainer/args.go
- dataRetriever/factory/requestersContainer/baseRequestersContainerFactory.go
- dataRetriever/factory/requestersContainer/metaRequestersContainerFactory.go
- dataRetriever/factory/requestersContainer/shardRequestersContainerFactory.go
- dataRetriever/factory/requestersContainer/shardRequestersContainerFactory_test.go
- dataRetriever/factory/storageRequestersContainer/baseRequestersContainerFactory.go
- dataRetriever/requestHandlers/requesters/equivalentProofsRequester.go
- dataRetriever/requestHandlers/requesters/requesters_test.go
- dataRetriever/storageRequesters/equivalentProofsRequester.go
- dataRetriever/storageRequesters/equivalentProofsRequester_test.go
- epochStart/bootstrap/process.go
- factory/processing/processComponents.go
- integrationTests/testHeartbeatNode.go
- integrationTests/testProcessorNode.go
> skip proofs request if epoch is not ok

- consensus/spos/bls/v2/subroundSignature.go
- consensus/spos/bls/v2/subroundSignature_test.go
- sometimes signature is sent even though proof is already received
- skip signature broadcast if proof exists
- with rc
> skip signature broadcast if proof already received

- consensus/spos/worker.go
- do no handle "future header to process" if received for other shard
- To be tested with the feature branch
> check for header shard when received in consensus worker

- go.mod
- go.sum
> proper tags on deps

- consensus/spos/roundConsensus.go
> Fix double rlock

- cmd/node/config/config.toml
- cmd/node/config/enableEpochs.toml
- cmd/node/config/ratings.toml
> Compressed flags after Andromeda

- cmd/node/config/config.toml
- cmd/node/config/enableEpochs.toml
- cmd/node/config/ratings.toml
- consensus/spos/roundConsensus.go
> Master into mempool supernova

- update/sync/syncEpochStartShardHeaders.go
- update/sync/syncEpochStartShardHeaders_test.go
> unit tests

- update/sync/syncEpochStartShardHeaders.go
- update/sync/syncEpochStartShardHeaders_test.go
> Barnard to gov 29 may

- .github/workflows/code-coverage.yml
> Fix codecov for Barnard

- .github/workflows/build_and_run_chain_simulator_and_execute_system_test.yml
- .github/workflows/check-cli-md.yml
- .github/workflows/code-coverage.yml
- .github/workflows/docker-keygenerator.yaml
- api/groups/addressGroup.go
- api/groups/addressGroup_test.go
- go.mod
- go.sum
- node/node.go
- node/node_test.go
- sonar-project.properties
> Merge barnard into feat timestamp ms

- cmd/node/config/enableEpochs.toml
- common/constants.go
- common/enablers/enableEpochsHandler.go
- common/enablers/enableEpochsHandler_test.go
- config/epochConfig.go
- config/tomlConfig_test.go
- Add supernova activation flag
- To be tested with the feature branch
> Add supernova activation flag

- cmd/node/config/config.toml
- cmd/node/config/ratings.toml
> config update as per master

- cmd/node/config/enableEpochs.toml
- common/constants.go
- common/enablers/enableEpochsHandler.go
- common/enablers/enableEpochsHandler_test.go
- config/epochConfig.go
- config/tomlConfig_test.go
- go.mod
- go.sum
- node/metrics/metrics.go
- node/metrics/metrics_test.go
- statusHandler/statusMetricsProvider.go
- statusHandler/statusMetricsProvider_test.go
> fix get balance opcode

- go.mod
- go.sum
> proper tag

- integrationTests/chainSimulator/mempool/mempool_test.go
- added some integration tests for the mempool selection
- integration tests for nonce gaps cases
- 
- 
- 
- 
- 
- 
- 
> mempool integration tests

- cmd/node/config/config.toml
- common/constants.go
- config/config.go
- debug/factory/interceptorDebuggerFactory.go
- debug/factory/interceptorDebuggerFactory_test.go
- debug/factory/interface.go
- debug/handler/broadcastDebug.go
- debug/handler/broadcastDebug_test.go
- debug/handler/disabledBroadcastDebugHandler.go
- debug/handler/disabledInterceptorDebugHandler.go
- debug/handler/interceptorDebugHandler.go
- debug/handler/interceptorDebugHandler_test.go
- debug/handler/interface.go
- epochStart/mock/coreComponentsMock.go
- integrationTests/testFullNode.go
- integrationTests/testProcessorNode.go
- node/chainSimulator/components/testOnlyProcessingNode.go
- node/nodeDebugFactory/interceptedDebugHandler.go
- node/nodeDebugFactory/interceptedDebugHandler_test.go
- node/nodeHelper.go
- p2p/constants.go
- process/interceptors/baseDataInterceptor.go
- process/interceptors/baseDataInterceptor_test.go
- process/interceptors/multiDataInterceptor.go
- process/interceptors/singleDataInterceptor.go
- process/interface.go
- process/mock/coreComponentsMock.go
- process/mock/interceptedDebugHandlerStub.go
- update/factory/exportHandlerFactory.go
> Merge supernova into feat async exec 2025.07.15

- .github/workflows/build_and_run_chain_simulator_and_execute_system_test.yml
- cmd/node/config/enableEpochs.toml
- common/constants.go
- common/enablers/enableEpochsHandler.go
- common/enablers/enableEpochsHandler_test.go
- config/epochConfig.go
- config/tomlConfig_test.go
- go.mod
- go.sum
- integrationTests/chainSimulator/staking/stakingProvider/delegation_test.go
- node/metrics/metrics.go
- node/metrics/metrics_test.go
- statusHandler/statusMetricsProvider.go
- statusHandler/statusMetricsProvider_test.go
- vm/errors.go
- vm/systemSmartContracts/governance.go
- vm/systemSmartContracts/governance_test.go
> Merge barnard into supernova

- .github/workflows/create_release.yml
- cmd/node/config/economics.toml
- cmd/node/config/enableEpochs.toml
- integrationTests/chainSimulator/relayedTx/relayedTx_test.go
> Merge master into rc supernova 2025.07.21

- process/missingData/misingDataResolver.go
- process/missingData/missingDataResolver_test.go
> add missing data request/resolve blocking

- process/sync/baseForkDetector.go
- process/sync/metaForkDetector_test.go
> fix genesis check before supernova

- consensus/chronology/chronology.go
- consensus/chronology/chronology_test.go
- Handler transition for chronology number of rounds to wait before an alarms
- TBD
> Handling for chronology watchdog alarm for supernova

- cmd/node/config/config.toml
- config/config.go
> Adapt supernova round related configs

- consensus/spos/consensusMessageValidator.go
- consensus/spos/consensusState.go
- consensus/spos/consensusState_test.go
- consensus/spos/worker_test.go
- add missing mutex locks in consensus state
- System test with custom restarts
> fix consensus state missing mutex locks

- cmd/node/config/config.toml
> Disable broadcast transaction statistics

- integrationTests/vm/txsFee/multiShard/relayedMoveBalance_test.go
- node/nodeTesting.go
- process/block/postprocess/oneMBPostProcessor.go
- process/block/preprocess/basePreProcess.go
- process/block/preprocess/export_test.go
- process/block/preprocess/gasComputation.go
- process/block/preprocess/gasTracker_test.go
- process/block/preprocess/interfaces.go
- process/block/preprocess/rewardTxPreProcessor.go
- process/block/preprocess/rewardTxPreProcessor_test.go
- process/block/preprocess/scheduledTxsExecution.go
- process/block/preprocess/smartContractResults.go
- process/block/preprocess/smartContractResults_test.go
- process/block/preprocess/transactions.go
- process/block/preprocess/transactionsV2.go
- process/block/preprocess/transactionsV2_test.go
- process/block/preprocess/transactions_test.go
- process/block/preprocess/txsForBlock.go
- process/block/preprocess/txsForBlock_test.go
- process/block/preprocess/validatorInfoPreProcessor.go
- process/block/preprocess/validatorInfoPreProcessor_test.go
- process/errors.go
- process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go
- process/factory/shard/preProcessorsContainerFactory.go
- process/transaction/interceptedTransaction_test.go
- refactoring existing code, to be extracted into a sub component and used in both proposal and execution.
- txs for block should be extracted into a component. 
- the proposal of a block and the verification of the proposal will make use of this component, as well as the execution of a proposal (they need separate instances, not sharing the same one between proposal and execution)
- the extracted subcomponent will be tested on the old flows (importDB and regular system tests for consensus)
- adding unit tests covering the component
- was the PR targeted to the correct …
> refactor txs for block in preprocessors

- dataRetriever/resolvers/epochproviders/arithmeticEpochProvider.go
- dataRetriever/resolvers/epochproviders/arithmeticEpochProvider_test.go
- dataRetriever/resolvers/epochproviders/export_test.go
- handling arithmetic epoch provider transition to supernova
- to be tested with feature branch
> Handling arithmetic epoch provider transition

- epochStart/metachain/trigger.go
- integrationTests/consensus/consensusSigning_test.go
- integrationTests/consensus/consensus_test.go
- integrationTests/testFullNode.go
> Merge supernova into sub second round

- node/node.go
- process/dataValidators/txValidator.go
- process/dataValidators/txValidator_test.go
- process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go
- update/factory/fullSyncInterceptors.go
> extra guardian check

- epochStart/metachain/trigger.go
- integrationTests/consensus/consensusSigning_test.go
- integrationTests/consensus/consensus_test.go
- integrationTests/testFullNode.go
- integrationTests/testInitializer.go
- integrationTests/testProcessorNode.go
- node/node.go
- process/dataValidators/txValidator.go
- process/dataValidators/txValidator_test.go
- process/factory/interceptorscontainer/baseInterceptorsContainerFactory.go
- update/factory/fullSyncInterceptors.go
- Updating feat/mempool-supernova with rc/supernova 
> RC/supernova into feat/mempool-supernova

- cmd/node/config/economics.toml
- config/economicsConfig.go
- process/block/gasConsumption.go
- process/block/gasConsumption_test.go
- process/errors.go
- process/interface.go
- a new component is needed to handle the max gas limits, as this will be completely used at block creation time, with no further estimation
- implement a new component that keeps track of the gas consumed throughout tx selection process
> Gas consumption

- dataRetriever/interface.go
- dataRetriever/shardedData/shardedData.go
- dataRetriever/txpool/interface.go
- dataRetriever/txpool/shardedTxPool.go
- dataRetriever/txpool/shardedTxPool_test.go
- process/block/preprocess/interfaces.go
- process/block/preprocess/transactions.go
- process/block/preprocess/transactions_test.go
- testscommon/shardedDataCacheNotifierMock.go
- testscommon/shardedDataStub.go
- txcache/crossTxCache.go
- txcache/crossTxCache_test.go
- txcache/disabledCache.go
- txcache/disabledCache_test.go
- txcache/selectionTracker.go
- txcache/txCache.go
- We have to integrate the TxPool notifications callbacks into the consensus and processing components.
- Before that, though, we've done some preparations (adjusted interfaces, added wrappers, did small refactoring).
- See delta and comments.
- Standard testing.
> Supernova TxPool integration: preparatory refactoring, preparatory integration steps

- factory/processing/blockProcessorCreator.go
- genesis/process/metaGenesisBlockCreator.go
- genesis/process/shardGenesisBlockCreator.go
- integrationTests/testProcessorNode.go
- process/block/baseProcess_test.go
- process/common.go
- process/common_test.go
- process/coordinator/blockDataRequest.go
- process/coordinator/blockDataRequest_test.go
- process/coordinator/process.go
- process/coordinator/process_test.go
- process/errors.go
- process/factory/containers/preProcessorsContainer_test.go
- process/interface.go
- testscommon/preprocMocks/preProcessorContainerMock.go
- testscommon/preprocMocks/preprocessorMock.go
- This PR refactors the transaction coordinator by extracting block data requesting logic into a separate component called BlockDataRequester. 
- The main purpose is to isolate data requesting functionality so it can be reused in different contexts, particularly for proposal processing and validation.
- Create a new BlockDataRequester component that handles all data requesting logic
- Integrate the new component into the existing TransactionCoordinator to maintain backward compatibility
- Move utility functions to a common location for shared use
- check that sync and consensus processes work as before
- 
Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the …
> Tx coordinator requests

- process/coordinator/blockDataRequest_test.go
- testscommon/headerHandlerStub.go
- Added comprehensive unit test coverage for the BlockDataRequest component to improve code quality and maintainability.
- New test for RequestBlockTransactions: Covers nil/empty body handling, different block types, missing preprocessors, and concurrent request scenarios
- New test for RequestMiniBlocksAndTransactions: Tests scheduled mini blocks flag behavior, cross-shard mini block processing, and header validation
- New test for NewBlockDataRequester constructor: Validates all nil dependency checks and successful initialization
- New test for IsDataPreparedForProcessing: Tests transaction preparation verification, error handling, and concurrent processing
- New test for receivedMiniBlock: Covers mini block reception handling, type validation, and preprocessor integration
Based on the …
> Unit tests block data request

- factory/processing/txSimulatorProcessComponents.go
- integrationTests/chainSimulator/simulate/simulate_test.go
> Merge master into rc supernova 2025.09.09

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build_and_run_chain_simulator_and_execute_system_test.yml
- factory/processing/txSimulatorProcessComponents.go
- integrationTests/chainSimulator/simulate/simulate_test.go
> Merge rc supernova into feat/sub second round 2025.09.09

- node/external/transactionAPI/apiTransactionProcessor_test.go
- node/external/transactionAPI/gasUsedAndFeeProcessor_test.go
- outport/process/transactionsfee/transactionsFeeProcessor_test.go
- process/coordinator/transactionType_test.go
- process/transaction/interceptedTransaction_test.go
- increase coverage
- increase coverage
- tests only
> Extra tests for disabled relayed

- process/block/executionResultsVerifier_test.go
- process/common_test.go
- some tests needs fixes + code should be moved to the new package
- fix tests and add more
- tests only
> fix executionResultsVerifier_test and improve coverage on process/common.go

- integrationTests/testProcessorNode.go
- integrationTests/testProcessorNodeWithTestWebServer.go
Failing integration test in integrationTests/api caused by not updating the arguments of TestProcessorNode.
Fix.
> Supernova TxPool: Fixed Failing Integration Test

- process/block/gasConsumption.go
- process/block/gasConsumption_test.go
- process/block/shardblockProposal.go
- process/block/shardblockProposal_test.go
> fix for verifyGasLimit: it should not check for pending mini blocks after CheckIncomingMiniBlocks
